import { Injectable } from '@angular/core';
import { AuthService } from './auth.service';
import { map, switchMap } from 'rxjs/operators';
import { throwError, of, iif } from 'rxjs';
import { OrgSettings } from '../models/org-settings.model';
import { ReportAllowedActions } from '../models/allowed-actions.model';

@Injectable({
  providedIn: 'root',
})
export class PermissionsService {
  // can check roleActionMap[role]['company']['view'] for whether he is allowed company view.
  roleActionMap: Record<string, Record<string, Record<string, boolean>>> = {
    owner: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: true,
        bill_verification: true,
        remind: true,
        split: false,
        delete: false,
        report: true,
        assign: true,
        edit: false,
        super_edit: true,
        verify: true,
        export: true,
        audit: false,
      },
      reports: {
        delete: false,
        resubmit: false,
        create: false,
        view: true,
        approve: false,
        super_approve: true,
        send_back: true,
        remind: true,
        verify: true,
        payment_queue: true,
        remove_payment_queue: true,
        export: true,
        export_accounting: true,
        share: false,
        add_approver: true,
        audit: false,
        review: true,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: true,
        approve: false,
        super_approve: true,
        send_back: true,
        process_request: true,
        issue: true,
        export: true,
        export_accounting: true,
        refund: true,
        add_approver: true,
        audit: false,
        view_requests: true,
      },
      ccc: {
        upload: true,
        match: true,
        assign: true,
        export: true,
        delete: true,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: false,
        company: true,
      },
      mis_reporting: {
        view: true,
      },
      analytics: {
        view: true,
      },
      employees: {
        view: true,
        add: true,
        edit: true,
        disable: true,
        export: true,
        invite: true,
      },
      settings: {
        view: true,
        edit: true,
        create_org: true,
        policy_rules: true,
        accounting: true,
      },
      accounting: {
        exports: true,
      },
      integration_exports: {
        exports: true,
      },
      payments: {
        view: true,
        start_processing: true,
        remove_payment_queue: true,
        mark_paid: true,
        remove_processing: true,
        export: true,
        export_accounting: true,
        audit: false,
        view_advances: true,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: true,
        cost_center: true,
      },
      recurrences: {
        view: false,
      },
    },
    admin: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: true,
        bill_verification: true,
        remind: true,
        split: false,
        delete: false,
        report: true,
        assign: true,
        edit: false,
        super_edit: true,
        verify: true,
        export: true,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: true,
        beta_view: true,
        approve: false,
        super_approve: true,
        send_back: true,
        remind: true,
        verify: true,
        payment_queue: true,
        remove_payment_queue: true,
        export: true,
        export_accounting: true,
        share: false,
        round_off_amount: true,
        add_approver: true,
        audit: false,
        review: true,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: true,
        approve: false,
        super_approve: true,
        send_back: true,
        process_request: true,
        issue: true,
        export: true,
        export_accounting: true,
        refund: true,
        add_approver: true,
        audit: false,
        view_requests: true,
      },
      ccc: {
        upload: true,
        match: true,
        assign: true,
        export: true,
        delete: true,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: false,
        company: true,
      },
      mis_reporting: {
        view: true,
      },
      analytics: {
        view: true,
      },
      employees: {
        view: true,
        add: true,
        edit: true,
        disable: true,
        export: true,
        invite: true,
      },
      settings: {
        view: true,
        edit: true,
        create_org: true,
        policy_rules: true,
        accounting: true,
      },
      accounting: {
        exports: true,
      },
      integration_exports: {
        exports: true,
      },
      payments: {
        view: true,
        start_processing: true,
        remove_payment_queue: true,
        mark_paid: true,
        remove_processing: true,
        export: true,
        export_accounting: true,
        audit: false,
        view_advances: true,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: true,
        cost_center: true,
      },
      recurrences: {
        view: false,
      },
    },
    finance: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: true,
        bill_verification: true,
        remind: true,
        split: false,
        delete: false,
        report: true,
        assign: true,
        edit: false,
        super_edit: true,
        verify: true,
        export: true,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: true,
        beta_view: true,
        approve: false,
        super_approve: true,
        send_back: true,
        remind: true,
        verify: true,
        payment_queue: true,
        remove_payment_queue: true,
        export: true,
        export_accounting: true,
        share: false,
        round_off_amount: true,
        add_approver: true,
        audit: false,
        review: true,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: true,
        approve: false,
        super_approve: true,
        send_back: true,
        process_request: true,
        issue: true,
        export: true,
        export_accounting: true,
        refund: true,
        add_approver: true,
        audit: false,
        view_requests: true,
      },
      ccc: {
        upload: true,
        match: true,
        assign: true,
        export: true,
        delete: true,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: false,
        company: true,
      },
      mis_reporting: {
        view: true,
      },
      analytics: {
        view: true,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: true,
        accounting: false,
      },
      accounting: {
        exports: true,
      },
      integration_exports: {
        exports: true,
      },
      payments: {
        view: true,
        start_processing: true,
        remove_payment_queue: true,
        mark_paid: true,
        remove_processing: true,
        export: true,
        export_accounting: true,
        audit: false,
        view_advances: true,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
    fyler: {
      expenses: {
        create: true,
        bulkCreate: true,
        view: true,
        flag: false,
        bill_verification: false,
        remind: false,
        split: true,
        delete: true,
        report: true,
        assign: false,
        edit: true,
        super_edit: false,
        verify: false,
        export: false,
        audit: false,
      },
      reports: {
        delete: true,
        edit: true,
        resubmit: true,
        create: true,
        view: true,
        beta_view: true,
        approve: false,
        super_approve: false,
        send_back: true,
        remind: false,
        verify: false,
        payment_queue: false,
        remove_payment_queue: false,
        export: true,
        export_accounting: false,
        share: true,
        round_off_amount: false,
        add_approver: true,
        audit: false,
        review: false,
      },
      advances: {
        request: true,
        delete: true,
        view: true,
        edit: true,
        super_edit: false,
        approve: false,
        super_approve: false,
        send_back: false,
        process_request: false,
        issue: false,
        export: false,
        export_accounting: false,
        refund: false,
        add_approver: true,
        audit: false,
        view_requests: true,
      },
      ccc: {
        upload: false,
        match: true,
        assign: false,
        export: true,
        delete: false,
      },
      receipts: {
        upload: true,
        match: true,
        delete: true,
      },
      summary: {
        team: false,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: true,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: true,
        start_processing: false,
        remove_payment_queue: false,
        mark_paid: false,
        remove_processing: false,
        export: false,
        export_accounting: false,
        audit: false,
        view_advances: false,
      },
      personal_cards: {
        view: true,
        upload: true,
        match: true,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: true,
      },
    },
    approver: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: false,
        bill_verification: false,
        remind: false,
        split: false,
        delete: false,
        report: false,
        assign: false,
        edit: false,
        super_edit: true,
        verify: false,
        export: false,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: true,
        beta_view: true,
        approve: true,
        super_approve: false,
        send_back: true,
        remind: false,
        verify: false,
        payment_queue: false,
        remove_payment_queue: false,
        export: true,
        export_accounting: true,
        share: false,
        round_off_amount: false,
        add_approver: true,
        audit: false,
        review: false,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: true,
        approve: true,
        super_approve: false,
        send_back: true,
        process_request: false,
        issue: false,
        export: false,
        export_accounting: false,
        refund: false,
        add_approver: true,
        audit: false,
        view_requests: true,
      },
      ccc: {
        upload: false,
        match: false,
        assign: false,
        export: false,
        delete: false,
      },
      receipts: {
        // approver
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: true,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
        team: true,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: true,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: false,
        start_processing: false,
        remove_payment_queue: false,
        mark_paid: false,
        remove_processing: false,
        export: false,
        export_accounting: false,
        audit: false,
        view_advances: false,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
    travel_admin: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: false,
        flag: false,
        bill_verification: false,
        remind: false,
        split: false,
        delete: false,
        report: false,
        assign: false,
        edit: false,
        super_edit: false,
        verify: false,
        export: false,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: false,
        beta_view: true,
        approve: false,
        super_approve: false,
        send_back: false,
        remind: false,
        verify: false,
        payment_queue: false,
        remove_payment_queue: false,
        export: false,
        export_accounting: false,
        share: false,
        round_off_amount: false,
        add_approver: false,
        audit: false,
        review: false,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: false,
        approve: false,
        super_approve: false,
        send_back: false,
        process_request: false,
        issue: false,
        export: false,
        export_accounting: false,
        refund: false,
        add_approver: false,
        audit: false,
        view_requests: false,
      },
      ccc: {
        upload: false,
        match: false,
        assign: false,
        export: false,
        delete: false,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: false,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: false,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: false,
        start_processing: false,
        remove_payment_queue: false,
        mark_paid: false,
        remove_processing: false,
        export: false,
        export_accounting: false,
        audit: false,
        view_advances: false,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
    travel_agent: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: false,
        flag: false,
        bill_verification: false,
        remind: false,
        split: false,
        delete: false,
        report: false,
        assign: false,
        edit: false,
        super_edit: false,
        verify: false,
        export: false,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: false,
        beta_view: true,
        approve: false,
        super_approve: false,
        send_back: false,
        remind: false,
        verify: false,
        payment_queue: false,
        remove_payment_queue: false,
        export: false,
        export_accounting: false,
        share: false,
        round_off_amount: false,
        add_approver: false,
        audit: false,
        review: false,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: false,
        approve: false,
        super_approve: false,
        send_back: false,
        process_request: false,
        issue: false,
        export: false,
        export_accounting: false,
        refund: false,
        add_approver: false,
        audit: false,
        view_requests: false,
      },
      ccc: {
        upload: false,
        match: false,
        assign: false,
        export: false,
        delete: false,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: false,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: false,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: false,
        start_processing: false,
        remove_payment_queue: false,
        mark_paid: false,
        remove_processing: false,
        export: false,
        export_accounting: false,
        audit: false,
        view_advances: false,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
    verifier: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: true,
        bill_verification: true,
        remind: false,
        split: false,
        delete: false,
        report: false,
        assign: false,
        edit: false,
        super_edit: true,
        verify: true,
        export: false,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: true,
        beta_view: true,
        approve: false,
        super_approve: false,
        send_back: true,
        remind: false,
        verify: true,
        payment_queue: false,
        remove_payment_queue: false,
        export: false,
        export_accounting: false,
        share: false,
        round_off_amount: true,
        add_approver: false,
        audit: false,
        review: true,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: false,
        approve: false,
        super_approve: false,
        send_back: false,
        process_request: false,
        issue: false,
        export: false,
        export_accounting: false,
        refund: false,
        add_approver: false,
        audit: false,
        view_requests: false,
      },
      ccc: {
        upload: false,
        match: false,
        assign: false,
        export: false,
        delete: false,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: false,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: false,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: false,
        start_processing: false,
        remove_payment_queue: false,
        mark_paid: false,
        remove_processing: false,
        export: false,
        export_accounting: false,
        audit: false,
        view_advances: false,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
    payment_processor: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: false,
        bill_verification: false,
        remind: false,
        split: false,
        delete: false,
        report: false,
        assign: false,
        edit: false,
        super_edit: false,
        verify: false,
        export: false,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: true,
        beta_view: true,
        approve: false,
        super_approve: false,
        send_back: false,
        remind: false,
        verify: false,
        payment_queue: true,
        remove_payment_queue: true,
        export: true,
        export_accounting: true,
        share: false,
        round_off_amount: true,
        add_approver: false,
        audit: false,
        review: true,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: true,
        approve: false,
        super_approve: true,
        send_back: true,
        process_request: true,
        issue: true,
        export: true,
        export_accounting: true,
        refund: true,
        add_approver: false,
        audit: false,
        view_requests: false,
      },
      ccc: {
        upload: false,
        match: false,
        assign: false,
        export: false,
        delete: false,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: false,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: false,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: true,
        start_processing: true,
        remove_payment_queue: true,
        mark_paid: true,
        remove_processing: true,
        export: true,
        export_accounting: true,
        audit: false,
        view_advances: true,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
    auditor: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: false,
        bill_verification: false,
        remind: false,
        split: false,
        delete: false,
        report: false,
        assign: false,
        edit: false,
        super_edit: false,
        verify: false,
        export: true,
        audit: true,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: true,
        beta_view: true,
        approve: false,
        super_approve: false,
        send_back: false,
        remind: false,
        verify: false,
        payment_queue: false,
        remove_payment_queue: false,
        export: true,
        export_accounting: false,
        share: false,
        round_off_amount: false,
        add_approver: false,
        audit: true,
        review: false,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: false,
        approve: false,
        super_approve: false,
        send_back: false,
        process_request: false,
        issue: false,
        export: true,
        export_accounting: false,
        refund: false,
        add_approver: false,
        audit: true,
        view_requests: false,
      },
      ccc: {
        upload: false,
        match: false,
        assign: false,
        export: false,
        delete: false,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: false,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: false,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: true,
        start_processing: false,
        remove_payment_queue: false,
        mark_paid: false,
        remove_processing: false,
        export: true,
        export_accounting: false,
        audit: true,
        view_advances: true,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
    hod: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: false,
        bill_verification: false,
        remind: false,
        split: false,
        delete: false,
        report: false,
        assign: false,
        edit: false,
        super_edit: true,
        verify: false,
        export: false,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: true,
        beta_view: true,
        approve: true,
        super_approve: false,
        send_back: true,
        remind: false,
        verify: false,
        payment_queue: false,
        remove_payment_queue: false,
        export: true,
        export_accounting: true,
        share: false,
        round_off_amount: false,
        add_approver: true,
        audit: false,
        review: false,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: true,
        approve: true,
        super_approve: false,
        send_back: true,
        process_request: false,
        issue: false,
        export: false,
        export_accounting: false,
        refund: false,
        add_approver: true,
        audit: false,
        view_requests: true,
      },
      ccc: {
        upload: false,
        match: false,
        assign: false,
        export: false,
        delete: false,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: true,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
        team: true,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: true,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: false,
        start_processing: false,
        remove_payment_queue: false,
        mark_paid: false,
        remove_processing: false,
        export: false,
        export_accounting: false,
        audit: false,
        view_advances: false,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
    hop: {
      expenses: {
        create: false,
        bulkCreate: false,
        view: true,
        flag: false,
        bill_verification: false,
        remind: false,
        split: false,
        delete: false,
        report: false,
        assign: false,
        edit: false,
        super_edit: true,
        verify: false,
        export: false,
        audit: false,
      },
      reports: {
        delete: false,
        edit: false,
        resubmit: false,
        create: false,
        view: true,
        beta_view: true,
        approve: true,
        super_approve: false,
        send_back: true,
        remind: false,
        verify: false,
        payment_queue: false,
        remove_payment_queue: false,
        export: true,
        export_accounting: true,
        share: false,
        round_off_amount: false,
        add_approver: true,
        audit: false,
        review: false,
      },
      advances: {
        request: false,
        delete: false,
        edit: false,
        super_edit: true,
        approve: true,
        super_approve: false,
        send_back: true,
        process_request: false,
        issue: false,
        export: false,
        export_accounting: false,
        refund: false,
        add_approver: true,
        audit: false,
        view_requests: true,
      },
      ccc: {
        upload: false,
        match: false,
        assign: false,
        export: false,
        delete: false,
      },
      receipts: {
        upload: false,
        match: false,
        delete: false,
      },
      summary: {
        team: true,
        company: false,
      },
      mis_reporting: {
        view: false,
      },
      analytics: {
        view: false,
        team: true,
      },
      employees: {
        view: false,
        add: false,
        edit: false,
        disable: false,
        export: false,
        invite: false,
      },
      settings: {
        view: false,
        edit: false,
        create_org: false,
        policy_rules: true,
        accounting: false,
      },
      accounting: {
        exports: false,
      },
      integration_exports: {
        exports: false,
      },
      payments: {
        view: false,
        start_processing: false,
        remove_payment_queue: false,
        mark_paid: false,
        remove_processing: false,
        export: false,
        export_accounting: false,
        audit: false,
        view_advances: false,
      },
      personal_cards: {
        view: false,
        upload: false,
        match: false,
      },
      vendors: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      bulk_upload: {
        category: false,
        cost_center: false,
      },
      recurrences: {
        view: false,
      },
    },
  };

  constructor(private authService: AuthService) {}

  allowedActions(resource: string, actions: string[], orgSettings: OrgSettings) {
    const roles$ = this.authService.getRoles();
    const allowedActions: Partial<ReportAllowedActions> = {
      allowedRouteAccess: false,
    };

    const filteredRoles$ = roles$.pipe(
      map((roles: string[]) => {
        if (roles.indexOf('SUPER_ADMIN') > -1) {
          roles.splice(roles.indexOf('SUPER_ADMIN'), 1);
        }

        return roles;
      })
    );

    const allowedActions$ = filteredRoles$.pipe(
      map((filteredRoles) => {
        if (this.allowedAccess(resource, orgSettings)) {
          for (const currentRole of filteredRoles) {
            const role = currentRole.toLowerCase();
            this.setAllowedActions(actions, allowedActions, role, resource);
          }
        }
        return allowedActions;
      }),
      switchMap((currentAllowedActions) => {
        if (currentAllowedActions.allowedRouteAccess) {
          return of(currentAllowedActions);
        } else {
          return throwError('no route access');
        }
      })
    );

    return filteredRoles$.pipe(
      switchMap((filteredRoles) => iif(() => filteredRoles.length > 0, allowedActions$, of(null)))
    );
  }

  setAllowedActions(actions: string[], allowedActions: Partial<ReportAllowedActions>, role: string, resource: string) {
    for (const action of actions) {
      if (!allowedActions.hasOwnProperty(action) || !allowedActions[action]) {
        allowedActions[action] = this.roleActionMap[role][resource][action];
        if (allowedActions[action]) {
          allowedActions.allowedRouteAccess = true;
        }
      }
    }
  }

  allowedAccess(resource: string, orgSettings: OrgSettings): boolean {
    let allowed = true;

    if (resource === 'advances') {
      allowed = orgSettings.advance_requests.enabled || orgSettings.advances.enabled;
    }

    return allowed;
  }
}
