import { provideAppInitializer, inject, EnvironmentProviders } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';

export function provideIcons(): EnvironmentProviders {
  return provideAppInitializer(() => {
    const matIconRegistry = inject(MatIconRegistry);
    const domSanitizer = inject(DomSanitizer);

    const path = '../../assets/svg';
    const svgImageArray = [
      'arrow-down.svg',
      'arrow-left.svg',
      'arrow-left.svg',
      'arrow-right.svg',
      'arrow-right.svg',
      'arrow-tail-left.svg',
      'arrow-tail-up.svg',
      'arrow-tail-up-down.svg',
      'arrow-long-tail-right.svg',
      'arrow-long-tail-left.svg',
      'arrow-with-bent.svg',
      'attachment-none.svg',
      'bell-fill.svg',
      'bell-outline.svg',
      'bin.svg',
      'bin.svg',
      'building.svg',
      'bus.svg',
      'calendar.svg',
      'camera.svg',
      'car.svg',
      'card.svg',
      'cash-slash.svg',
      'cash.svg',
      'check-square-fill.svg',
      'check.svg',
      'check-pad.svg',
      'chat.svg',
      'clear.svg',
      'clock.svg',
      'crop.svg',
      'cross.svg',
      'danger-fill.svg',
      'danger-outline.svg',
      'dashboard.svg',
      'duplicate.svg',
      'edit.svg',
      'envelope.svg',
      'fyle-logo-dark.svg',
      'success-toast-icon.svg',
      'failure-toast-icon.svg',
      'info-toast-icon.svg',
      'file-pdf.svg',
      'filter-applied.svg',
      'filter.svg',
      'flag-outline.svg',
      'flash-off.svg',
      'flash-on.svg',
      'folder.svg',
      'folder-fill.svg',
      'fuel.svg',
      'gear.svg',
      'hamburger-menu.svg',
      'house-fill.svg',
      'house-filled-arrow-clockwise.svg',
      'house-outline.svg',
      'hourglass.svg',
      'image.svg',
      'image.svg',
      'info-circle-fill.svg',
      'info-gradient.svg',
      'info-circle-white.svg',
      'list-plus.svg',
      'list.svg',
      'list-new.svg',
      'list-fill.svg',
      'location.svg',
      'logo-google.svg',
      'loader.svg',
      'mileage.svg',
      'notch.svg',
      'open-in-new-tab.svg',
      'phone.svg',
      'plus-minus.svg',
      'plus-square.svg',
      'plus.svg',
      'power.svg',
      'question-square-outline.svg',
      'question-square-fill.svg',
      'radio-circle-fill.svg',
      'radio-circle-outline.svg',
      'rectangle.svg',
      'scooter.svg',
      'search.svg',
      'send-back.svg',
      'send-fill.svg',
      'share.svg',
      'single-mode.svg',
      'split.svg',
      'square-outline.svg',
      'scooter.svg',
      'tag.svg',
      'tax.svg',
      'toll-charge.svg',
      'train.svg',
      'user-one.svg',
      'user-one.svg',
      'user-three.svg',
      'user-two.svg',
      'vertical-dots-menu.svg',
      'wallet.svg',
      'warning-fill.svg',
      'warning-outline.svg',
      'warning.svg',
      'arrow-up.svg',
      'check-circle-outline.svg',
      'question-square-outline.svg',
      'ai-auto-coded.svg',
      'ai-icon.svg',
      'arrow-tail-right.svg',
    ];

    svgImageArray.forEach((imageName) => {
      matIconRegistry.addSvgIcon(
        imageName.replace('.svg', ''),
        domSanitizer.bypassSecurityTrustResourceUrl(`${path}/${imageName}`),
      );
    });
  });
}
