import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule, MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@NgModule({
  declarations: [],
  imports: [CommonModule, MatIconModule],
  exports: [MatIconModule],
  providers: [MatIconRegistry],
})
export class IconModule {
  path = '../../assets/svg';

  svgImageArray = [
    'arrow-tail-left.svg',
    'arrow-up.svg',
    'attachment.svg',
    'building.svg',
    'bus.svg',
    'car.svg',
    'card.svg',
    'chat.svg',
    'chevron-right.svg',
    'check-square-fill.svg',
    'crop.svg',
    'close.svg',
    'dashboard.svg',
    'duplicate.svg',
    'file-lightning-indicator.svg',
    'error.svg',
    'edit.svg',
    'filter.svg',
    'filter-applied.svg',
    'flash-off.svg',
    'flash-on.svg',
    'fy-arrow-down.svg',
    'fy-calendar.svg',
    'camera.svg',
    'fy-close.svg',
    'fy-delete.svg',
    'fy-done.svg',
    'envelope.svg',
    'fy-expense.svg',
    'flag-fill.svg',
    'flag-outline.svg',
    'fy-info.svg',
    'fy-info-gradient.svg',
    'image.svg',
    'mileage.svg',
    'fy-matched.svg',
    'fy-notification-solid.svg',
    'fy-notification.svg',
    'fy-non-reimbursable.svg',
    'fy-receipt-attached.svg',
    'fy-receipt-not-attached.svg',
    'fy-receipts-new.svg',
    'fy-receipts.svg',
    'fy-recently-used.svg',
    'bell-fill.svg',
    'bell-outline.svg',
    'cash-slash.svg',
    'fy-receipt.svg',
    'clock.svg',
    'fy-rectangle.svg',
    'folder.svg',
    'cash.svg',
    'gear.svg',
    'loader.svg',
    'fy-search.svg',
    'fy-clear.svg',
    'fy-unmatched.svg',
    'location.svg',
    'hamburger-menu.svg',
    'house-outline.svg',
    'house-fill.svg',
    'info-circle-fill.svg',
    'image.svg',
    'fyle-logo-light.svg',
    'fyle-logo-dark.svg',
    'logo-google.svg',
    'list.svg',
    'navigate-left.svg',
    'navigate-right.svg',
    'attachment-none.svg',
    'open-in-new-tab.svg',
    'phone.svg',
    'power.svg',
    'plus-square.svg',
    'plus-minus.svg',
    'user-one.svg',
    'radio-circle-outline.svg',
    'radio-circle-fill.svg',
    'rectangle.svg',
    'house-filled-arrow-clockwise.svg',
    'search.svg',
    'send-fill.svg',
    'send-back.svg',
    'success-tick.svg',
    'search-not-found.svg',
    'share.svg',
    'single-mode.svg',
    'tag.svg',
    'tax.svg',
    'tick-circle-outline-white.svg',
    'toll-charge.svg',
    'tick-square-filled.svg',
    'train.svg',
    'warning.svg',
    'warning-fill.svg',
    'warning-outline.svg',
    'fy-merge.svg',
    'split.svg',
    'square-outline.svg',
    'list-plus.svg',
    'question-square-outline.svg',
    'user-one.svg',
    'user-two.svg',
    'user-three.svg',
    'vertical-dots-menu.svg',
    'wallet.svg',
    'scooter.svg',
  ];

  constructor(private domSanitizer: DomSanitizer, private matIconRegistry: MatIconRegistry) {
    this.svgImageArray.forEach((imageName) => {
      this.matIconRegistry.addSvgIcon(imageName.replace('.svg', ''), this.setPath(`${this.path}/${imageName}`));
    });
  }

  private setPath(url: string): SafeResourceUrl {
    return this.domSanitizer.bypassSecurityTrustResourceUrl(url);
  }
}
