import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule, MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@NgModule({
  declarations: [],
  imports: [CommonModule, MatIconModule],
  exports: [MatIconModule],
  providers: [MatIconRegistry],
})
export class IconModule {
  path = '../../assets/svg';

  svgImageArray = [
    'arrow-prev.svg',
    'arrow-next.svg',
    'arrow-up',
    'attachment.svg',
    'building.svg',
    'bus.svg',
    'car.svg',
    'card.svg',
    'chevron-right.svg',
    'close.svg',
    'danger.svg',
    'duplicate.svg',
    'expense.svg',
    'expense-rule.svg',
    'error.svg',
    'edit.svg',
    'error-filled.svg',
    'flash-off.svg',
    'flash-on.svg',
    'fy-add-new-expense.svg',
    'fy-advances-new.svg',
    'fy-arrow-down.svg',
    'fy-attachment.svg',
    'fy-bot.svg',
    'fy-calendar.svg',
    'fy-camera.svg',
    'fy-car-mini.svg',
    'fy-car.svg',
    'fy-chat.svg',
    'fy-classify-ccc.svg',
    'fy-close.svg',
    'fy-dashboard-new.svg',
    'fy-delete.svg',
    'fy-dismiss.svg',
    'fy-done.svg',
    'fy-email.svg',
    'fy-expense.svg',
    'fy-expenses-new.svg',
    'fy-filter.svg',
    'flag-fill.svg',
    'fy-help-new.svg',
    'fy-home-solid.svg',
    'fy-home.svg',
    'fy-individual.svg',
    'fy-iphone.svg',
    'fy-info.svg',
    'fy-info-gradient.svg',
    'fy-gallery.svg',
    'fy-matched-no.svg',
    'fy-matched-yes.svg',
    'fy-mileage.svg',
    'fy-matched.svg',
    'fy-notification-solid.svg',
    'fy-notification.svg',
    'fy-non-reimbursable.svg',
    'fy-plus.svg',
    'fy-receipt-attached.svg',
    'fy-receipt-not-attached.svg',
    'fy-receipt.svg',
    'fy-receipts-new.svg',
    'fy-receipts.svg',
    'fy-recently-used.svg',
    'fy-rectangle.svg',
    'fy-reports-new.svg',
    'fy-reports.svg',
    'fy-report.svg',
    'fy-reimbursable.svg',
    'fy-settings.svg',
    'fy-sort-ascending.svg',
    'fy-sort-descending.svg',
    'fy-spinner-circle.svg',
    'fy-switch-new.svg',
    'fy-switch.svg',
    'fy-team-advances-new.svg',
    'fy-team-reports-new.svg',
    'fy-search.svg',
    'fy-clear.svg',
    'fy-unmatched.svg',
    'fy-location.svg',
    'gallery.svg',
    'ionic-log-out-outline.svg',
    'information.svg',
    'logo-icon-white.svg',
    'logo-white.svg',
    'list.svg',
    'navigate-left.svg',
    'navigate-right.svg',
    'no-attachment.svg',
    'phone.svg',
    'professional-service.svg',
    'plus.svg',
    'plus-minus.svg',
    'profile.svg',
    'radio-circle-outline.svg',
    'rectangle.svg',
    'return-home.svg',
    'search.svg',
    'settings.svg',
    'single.svg',
    'split-expense.svg',
    'send.svg',
    'send-back.svg',
    'success-tick.svg',
    'search-not-found.svg',
    'share.svg',
    'single-mode.svg',
    'tag.svg',
    'tax.svg',
    'tick-circle-outline-white.svg',
    'toll-charge.svg',
    'tick-square-filled.svg',
    'train.svg',
    'warning-inverted.svg',
    'warning.svg',
    'fy-merge.svg',
    'split-evenly.svg',
    'split-new.svg',
    'list-plus.svg',
    'user-two.svg',
    'vertical-dots-menu.svg',
    'wallet.svg',
    'scooter.svg',
  ];

  constructor(private domSanitizer: DomSanitizer, private matIconRegistry: MatIconRegistry) {
    this.svgImageArray.forEach((imageName) => {
      this.matIconRegistry.addSvgIcon(imageName.replace('.svg', ''), this.setPath(`${this.path}/${imageName}`));
    });
  }

  private setPath(url: string): SafeResourceUrl {
    return this.domSanitizer.bypassSecurityTrustResourceUrl(url);
  }
}
