export enum CustomFieldTypes {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  SELECT = 'SELECT',
  BOOLEAN = 'BOOLEAN',
  MULTI_SELECT = 'MULTI_SELECT',
  LOCATION = 'LOCATION',
  USER_LIST = 'USER_LIST',
  DATE = 'DATE',
  DEPENDENT_SELECT = 'DEPENDENT_SELECT',
}
