export enum DataFeedSource {
  STATEMENT_UPLOAD = 'STATEMENT_UPLOAD',
  YODLEE = 'YODLEE',
  SPECTRE = 'SPECTRE',
  MASTERCARD_RTF = 'MASTERCARD_RTF',
  VISA_RTF = 'VISA_RTF',
  CAPITALONE_RTF = 'CAPITALONE_RTF',
  BANK_FEED_AMEX = 'BANK FEED - AMEX',
  BANK_FEED_CDF = 'BANK FEED - CDF',
  BANK_FEED_VCF = 'BANK FEED - VCF',
  BANK_FEED_S3DF = 'BANK FEED - S3DF',
  BANK_FEED_HAPPAY = 'BANK FEED - HAPPAY',
}
