export enum AllowedPaymentModes {
  PERSONAL_CASH_ACCOUNT = 'PERSONAL_CASH_ACCOUNT',
  PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT = 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
  PERSONAL_ADVANCE_ACCOUNT = 'PERSONAL_ADVANCE_ACCOUNT',
  COMPANY_ACCOUNT = 'COMPANY_ACCOUNT',
}
