export enum ExpenseSource {
  MOBILE = 'MOBILE',
  MOBILE_CAMERA = 'MOBILE_CAMERA',
  MOBILE_CAMERA_OFFLINE = 'MOBILE_CAMERA_OFFLINE',
  MOBILE_DASHCAM_BULK = 'MOBILE_DASHCAM_BULK',
  MOBILE_DASHCAM_GALLERY = 'MOBILE_DASHCAM_GALLERY',
  MOBILE_DASHCAM_SINGLE = 'MOBILE_DASHCAM_SINGLE',
  MOBILE_DASHCAM_SINGLE_OFFLINE = 'MOBILE_DASHCAM_SINGLE_OFFLINE',
  MOBILE_FILE = 'MOBILE_FILE',
  MOBILE_OFFLINE = 'MOBILE_OFFLINE',
}
