import { CustomField } from './custom_field.model';

export interface OrgUser {
  id: string;
  created_at?: Date;
  org_id: string;
  user_id?: string;
  employee_id?: number | string;
  location: string;
  level?: number | string | null;
  level_id?: string;
  band?: string | null;
  business_unit?: string | null;
  department_id?: string | null;
  department?: string | null;
  sub_department?: string | null;
  roles?: string[];
  approver1_id?: string;
  approver2_id?: string | null;
  approver3_id?: string | null;
  delegatee_id?: string | null;
  delegation_start_at?: Date | null;
  delegation_end_at?: Date | null;
  title?: string;
  status: string;
  branch_ifsc?: string;
  branch_account?: string;
  mobile: string;
  mobile_verified?: boolean;
  mobile_verified_at?: Date;
  is_primary?: boolean;
  owner?: boolean | null;
  joining_dt?: Date | null;
  special_email?: string;
  custom_field_values?: CustomField[];
  org_name: string;
  settings_id?: string;
  default_cost_center_id?: number;
  default_cost_center_name?: string;
  default_cost_center_code?: string;
  rank?: number | null;
  cost_center_ids?: number[];
  mobile_verification_attempts_left?: number;
}
