export enum PaymentModeType {
  COMPANY_ACCOUNT = 'COMPANY_ACCOUNT',
  PERSONAL_ACCOUNT = 'PERSONAL_ACCOUNT',
  PERSONAL_ADVANCE_ACCOUNT = 'PERSONAL_ADVANCE_ACCOUNT',
  PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT = 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
}
