export enum PerDiemRedirectedFrom {
  SAVE_PER_DIEM = 'SAVE_PER_DIEM',
  SAVE_AND_NEXT_PER_DIEM = 'SAVE_AND_NEXT_PERDIEM',
  SAVE_AND_PREV_PER_DIEM = 'SAVE_AND_PREV_PERDIEM',
  SAVE_AND_NEW_PER_DIEM = 'SAVE_AND_NEW_PER_DIEM',
}
