export enum ReportState {
  APPROVED = 'APPROVED',
  APPROVER_INQUIRY = 'APPROVER_INQUIRY',
  APPROVER_PENDING = 'APPROVER_PENDING',
  DRAFT = 'DRAFT',
  PAID = 'PAID',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
}
