export enum TransactionState {
  DRAFT = 'DRAFT',
  COMPLETE = 'COMPLETE',
  APPROVER_PENDING = 'APPROVER_PENDING',
  APPROVED = 'APPROVED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAID = 'PAID',
}
