import { Expense } from 'src/app/core/models/expense.model';

export interface exepensesV2Response {
  count: number,
  data: Expense[],
  limit: number,
  offset: number,
  url: string
}

// export const dummyExepensesV2Response: exepensesV2Response = {
//   count: 1, 
//   data: [
//     {
//       "_search_document": "'10':1 'abhishek':5 'ajain@fyle.in':6 'complete':3 'e/2021/02/t/129':4 'food':7,8,9 'inr':2", 
//       external_expense_id: null, 
//       "external_expense_source": null, 
//       "matched_by": null, 
//       "ou_band": null, 
//       "ou_business_unit": null, 
//       "ou_department": null, 
//       "ou_department_id": null, 
//       "ou_employee_id": null, 
//       "ou_id": "ouBFD8SkJTpy", 
//       "ou_joining_dt": null, 
//       "ou_level": null, 
//       "ou_location": null, 
//       "ou_mobile": "", 
//       "ou_org_id": "orgf9gwgXwrK", 
//       "ou_org_name": "Mobile app Test org", 
//       "ou_rank": null, 
//       "ou_sub_department": null, 
//       "ou_title": null, 
//       "ou_user_id": "usvKA4X8Ugcr", 
//       "rp_approved_at": null, 
//       "rp_claim_number": null, 
//       "rp_purpose": null, 
//       "rp_reimbursed_at": null, 
//       "source_account_id": "acc9dJiO1479s", 
//       "source_account_type": "PERSONAL_ACCOUNT", 
//       "transaction_approvals": null, 
//       "tx_activity_details": null, 
//       "tx_activity_policy_pending": null, 
//       "tx_admin_amount": null, 
//       "tx_amount": 10, 
//       "tx_billable": false, 
//       "tx_boolean_column1": null, 
//       "tx_boolean_column10": null, 
//       "tx_boolean_column2": null, 
//       "tx_boolean_column3": null, 
//       "tx_boolean_column4": null, 
//       "tx_boolean_column5": null, 
//       "tx_boolean_column6": null, 
//       "tx_boolean_column7": null, 
//       "tx_boolean_column8": null, 
//       "tx_boolean_column9": null, 
//       "tx_bus_travel_class": null, "tx_category": null, "tx_corporate_credit_card_expense_group_id": null, "tx_cost_center_code": null, "tx_cost_center_id": null, "tx_cost_center_name": null, "tx_created_at": "2021-02-17T05:58:24.972791", "tx_creator_id": "ouBFD8SkJTpy", "tx_currency": "INR", "tx_custom_properties": [{"name": "Food Text", "value": null}], "tx_decimal_column1": null, "tx_decimal_column10": null, "tx_decimal_column2": null, "tx_decimal_column3": null, "tx_decimal_column4": null, "tx_decimal_column5": null, "tx_decimal_column6": null, "tx_decimal_column7": null, "tx_decimal_column8": null, "tx_decimal_column9": null, "tx_distance": null, "tx_distance_unit": null, "tx_expense_number": "E/2021/02/T/129", "tx_external_id": null, "tx_extracted_data": null, "tx_file_ids": ["figSOLpbhmka"], "tx_flight_journey_travel_class": null, "tx_flight_return_travel_class": null, "tx_from_dt": null, "tx_fyle_category": "Food", "tx_hotel_is_breakfast_provided": null, "tx_id": "txU7B5XSmwhp", "tx_invoice_number": null, "tx_is_duplicate_expense": null, "tx_is_holiday_expense": null, "tx_location_column1": null, "tx_location_column10": null, "tx_location_column2": null, "tx_location_column3": null, "tx_location_column4": null, "tx_location_column5": null, "tx_location_column6": null, "tx_location_column7": null, "tx_location_column8": null, "tx_location_column9": null, "tx_locations": [], "tx_mandatory_fields_present": true, "tx_manual_flag": false, "tx_mileage_calculated_amount": null, "tx_mileage_calculated_distance": null, "tx_mileage_is_round_trip": null, "tx_mileage_rate": null, "tx_mileage_vehicle_type": null, "tx_num_days": null, "tx_num_files": 1, "tx_org_category": "Food", "tx_org_category_code": null, "tx_org_category_id": 122112, "tx_org_user_id": "ouBFD8SkJTpy", "tx_orig_amount": null, "tx_orig_currency": null, "tx_payment_id": "pay9EAuVqGxlD", "tx_per_diem_rate_id": null, "tx_physical_bill": false, "tx_physical_bill_at": null, "tx_policy_amount": null, "tx_policy_flag": false, "tx_policy_state": null, "tx_project_code": null, "tx_project_id": null, "tx_project_name": null, "tx_purpose": null, "tx_receipt_required": false, "tx_report_id": null, "tx_reported_at": null, "tx_risk_state": null, "tx_skip_reimbursement": false, "tx_source": "MOBILE", "tx_source_account_id": "acc9dJiO1479s", "tx_split_group_id": "txU7B5XSmwhp", "tx_split_group_user_amount": 20, "tx_state": "COMPLETE", "tx_sub_category": "Food", "tx_tax": null, "tx_text_array_column1": null, "tx_text_array_column10": null, "tx_text_array_column2": null, "tx_text_array_column3": null, "tx_text_array_column4": null, "tx_text_array_column5": null, "tx_text_array_column6": null, "tx_text_array_column7": null, "tx_text_array_column8": null, "tx_text_array_column9": null, "tx_text_column1": null, "tx_text_column10": null, "tx_text_column11": null, "tx_text_column12": null, "tx_text_column13": null, "tx_text_column14": null, "tx_text_column15": null, "tx_text_column2": null, "tx_text_column3": null, "tx_text_column4": null, "tx_text_column5": null, "tx_text_column6": null, "tx_text_column7": null, "tx_text_column8": null, "tx_text_column9": null, "tx_timestamp_column1": null, "tx_timestamp_column10": null, "tx_timestamp_column2": null, "tx_timestamp_column3": null, "tx_timestamp_column4": null, "tx_timestamp_column5": null, "tx_timestamp_column6": null, "tx_timestamp_column7": null, "tx_timestamp_column8": null, "tx_timestamp_column9": null, "tx_to_dt": null, "tx_train_travel_class": null, "tx_transcribed_data": null, "tx_transcription_state": null, "tx_txn_dt": "2021-02-17T06:30:00", "tx_updated_at": "2021-02-17T05:58:59.167656", "tx_user_amount": 10, "tx_user_can_delete": true, "tx_user_reason_for_duplicate_expenses": null, "tx_user_review_needed": null, "tx_vendor": null, "tx_vendor_id": null, "tx_verification_state": null, "us_email": "ajain@fyle.in", "us_full_name": "Abhishek"}], 
//     "limit": 1, 
//     "offset": 0, 
//     "url": "/v2/expenses"
// }

export const dummyExepensesV2Response1: exepensesV2Response = {
  count: 1, 
  data: [{
    external_expense_id: null,
    external_expense_source: null,
    matched_by: null,
    ou_band: null,
    ou_business_unit: null,
    ou_department: null,
    ou_department_id: null,
    ou_employee_id: null,
    ou_id: "",
    ou_joining_dt: null,
    ou_level: null,
    ou_location: null,
    ou_mobile: "",
    ou_org_id: "",
    ou_org_name: "",
    ou_rank: null,
    ou_sub_department: null,
    ou_title: null,
    ou_user_id: "",
    rp_approved_at: null,
    rp_claim_number: null,
    rp_purpose: null,
    rp_reimbursed_at: null,
    source_account_id: "",
    source_account_type: "",
    transaction_approvals: null,
    tx_activity_details: null,
    tx_activity_policy_pending: null,
    tx_admin_amount: null,
    tx_amount: 10,
    tx_billable: false,
    tx_boolean_column1: null,
    tx_boolean_column2: null,
    tx_boolean_column3: null,
    tx_boolean_column4: null,
    tx_boolean_column5: null,
    tx_boolean_column6: null,
    tx_boolean_column7: null,
    tx_boolean_column8: null,
    tx_boolean_column9: null,
    tx_boolean_column10: null,
    tx_bus_travel_class: null,
    tx_category: null,
    tx_corporate_credit_card_expense_group_id: null,
    tx_cost_center_code: null,
    tx_cost_center_id: null,
    tx_cost_center_name: null,
    tx_created_at: new Date(),
    tx_creator_id: "",
    tx_currency: "",
    tx_custom_properties: [],
    tx_decimal_column1: null,
    tx_decimal_column2: null,
    tx_decimal_column3: null,
    tx_decimal_column4: null,
    tx_decimal_column5: null,
    tx_decimal_column6: null,
    tx_decimal_column7: null,
    tx_decimal_column8: null,
    tx_decimal_column9: null,
    tx_decimal_column10: null,
    tx_distance: null,
    tx_distance_unit: null,
    tx_expense_number: "",
    tx_external_id: null,
    tx_extracted_data: null,
    tx_file_ids: ["a", "b"],
    tx_flight_journey_travel_class: null,
    tx_flight_return_travel_class: null,
    tx_from_dt: null,
    tx_fyle_category: "",
    tx_hotel_is_breakfast_provided: null,
    tx_id: "",
    tx_invoice_number: null,
    tx_is_duplicate_expense: null,
    tx_is_holiday_expense: null,
    tx_location_column1: null,
    tx_location_column2: null,
    tx_location_column3: null,
    tx_location_column4: null,
    tx_location_column5: null,
    tx_location_column6: null,
    tx_location_column7: null,
    tx_location_column8: null,
    tx_location_column9: null,
    tx_location_column10: null,
    tx_locations: [],
    tx_mandatory_fields_present: true,
    tx_manual_flag: false,
    tx_mileage_calculated_amount: null,
    tx_mileage_calculated_distance: null,
    tx_mileage_is_round_trip: null,
    tx_mileage_rate: null,
    tx_mileage_vehicle_type: null,
    tx_num_days: null,
    tx_num_files: 1,
    tx_org_category: "",
    tx_org_category_code: null,
    tx_org_category_id: 122112,
    tx_org_user_id: "",
    tx_orig_amount: null,
    tx_orig_currency: null,
    tx_payment_id: "",
    tx_per_diem_rate_id: null,
    tx_physical_bill: false,
    tx_physical_bill_at: null,
    tx_policy_amount: null,
    tx_policy_flag: false,
    tx_policy_state: null,
    tx_project_code: null,
    tx_project_id: null,
    tx_project_name: null,
    tx_purpose: null,
    tx_receipt_required: false,
    tx_report_id: null,
    tx_reported_at: null,
    tx_risk_state: null,
    tx_skip_reimbursement: false,
    tx_source: "",
    tx_source_account_id: "",
    tx_split_group_id: "",
    tx_split_group_user_amount: 0,
    tx_state: "",
    tx_sub_category: "",
    tx_tax: null,
    tx_text_array_column1: null,
    tx_text_array_column2: null,
    tx_text_array_column3: null,
    tx_text_array_column4: null,
    tx_text_array_column5: null,
    tx_text_array_column6: null,
    tx_text_array_column7: null,
    tx_text_array_column8: null,
    tx_text_array_column9: null,
    tx_text_array_column10: null,
    tx_text_column1: null,
    tx_text_column2: null,
    tx_text_column3: null,
    tx_text_column4: null,
    tx_text_column5: null,
    tx_text_column6: null,
    tx_text_column7: null,
    tx_text_column8: null,
    tx_text_column9: null,
    tx_text_column10: null,
    tx_text_column11: null,
    tx_text_column12: null,
    tx_text_column13: null,
    tx_text_column14: null,
    tx_text_column15: null,
    tx_timestamp_column1: null,
    tx_timestamp_column2: null,
    tx_timestamp_column3: null,
    tx_timestamp_column4: null,
    tx_timestamp_column5: null,
    tx_timestamp_column6: null,
    tx_timestamp_column7: null,
    tx_timestamp_column8: null,
    tx_timestamp_column9: null,
    tx_timestamp_column10: null,
    tx_to_dt: null,
    tx_train_travel_class: null,
    tx_transcribed_data: null,
    tx_transcription_state: null,
    tx_txn_dt: new Date(),
    tx_updated_at: new Date(),
    tx_user_amount: 0,
    tx_user_can_delete: true,
    tx_user_reason_for_duplicate_expenses: null,
    tx_user_review_needed: null,
    tx_vendor: null,
    tx_vendor_id: null,
    tx_verification_state: null,
    us_email: "",
    us_full_name: "",
    _search_document: "",
    tx_categoryDisplayName: ""
  }],
  "limit": 1, 
  "offset": 0, 
  "url": "/v2/expenses"
}


export function getDummyExpenses() : exepensesV2Response[] {
  return dummyExepensesV2Response1 as unknown as exepensesV2Response[];
}