export enum ReportStates {
  OPEN = 'OPEN',
  APPROVER_PENDING = 'APPROVER_PENDING',
  APPROVED = 'APPROVED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  UNAPPROVED_TEAM_REPORTS = 'UNAPPROVED_TEAM_REPORTS',
}
