import { ExpenseState } from '../../expense-state.enum';
import { Location } from '../../location.model';
import { ParsedResponse } from '../../parsed_response.model';
import { PlatformCategory } from '../platform-category.model';
import { PlatformCostCenter } from '../platform-cost-center.model';
import { File } from './file.model';
import { MileageUnitEnum, PlatformMileageRates } from '../platform-mileage-rates.model';
import { Project } from './project.model';
import { PlatformTaxGroup } from '../platform-tax-group.model';
import { User } from './user.model';
import { ReportApprovals } from '../report-approvals.model';
import { PlatformPerDiemRates } from '../platform-per-diem-rates.model';
import { Account } from './account.model';
import { CustomFields } from '../custom-fields.model';
import { CustomInput } from '../../custom-input.model';
import { CommuteDetails } from './commute-details.model';
import { CommuteDeduction } from 'src/app/core/enums/commute-deduction.enum';
import { MatchedCorporateCardTransaction } from './matched-corpporate-card-transaction.model';
import { ExpenseMissingMandatoryFields } from './expense-missing-mandatory-fields.model';
import { PolicyChecks } from './policy-checks.model';
import { ExpenseRuleData } from './expense-rule-data.model';
import { AccountingExportSummary } from './accounting-export-summary.model';
import { ExpenseReport } from './expense-report.model';
import { ExpenseEmployee } from 'src/app/core/mock-data/platform/v1/expense-employee.model';
import { AutoApprovalState } from '../auto-approval-state.enum';

export interface Expense {
  // `activity_details` is not added on purpose
  accounting_export_summary: {} | AccountingExportSummary;
  report_auto_approval_state: AutoApprovalState | null;
  is_exported: boolean;
  last_exported_at: Date;
  added_to_report_at: Date;
  admin_amount: number;
  approvals: ReportApprovals[];
  amount: number;
  approver_comments: string[];
  category: Pick<PlatformCategory, 'code' | 'id' | 'display_name' | 'name' | 'sub_category' | 'system_category'>;
  category_id: number;
  claim_amount: number;
  code: string;
  cost_center_id: number;
  cost_center: Pick<PlatformCostCenter, 'id' | 'name' | 'code'>;
  created_at: Date;
  creator_user_id: string;
  currency: string;
  custom_fields: CustomFields[] | Partial<CustomInput>[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  custom_fields_flattened: Record<string, any>;
  distance: number;
  distance_unit: MileageUnitEnum;
  employee: ExpenseEmployee;
  employee_id: string;
  ended_at: Date;
  expense_rule_data: ExpenseRuleData;
  expense_rule_id: string;
  extracted_data: ParsedResponse;
  file_ids: string[];
  files: Pick<File, 'id' | 'name' | 'content_type' | 'type'>[];
  foreign_amount: number;
  foreign_currency: string;
  hotel_is_breakfast_provided: boolean;
  id: string;
  invoice_number?: string;
  is_billable: boolean;
  is_corporate_card_transaction_auto_matched: boolean;
  is_policy_flagged: boolean;
  is_receipt_mandatory: boolean;
  is_reimbursable: boolean;
  is_split: boolean;
  is_verified: boolean;
  is_duplicate_present?: boolean;
  last_settled_at: Date;
  last_verified_at: Date;
  locations: Location[];
  matched_corporate_card_transaction_ids: string[];
  matched_corporate_card_transactions: MatchedCorporateCardTransaction[];
  merchant: string;
  mileage_calculated_amount: number;
  mileage_calculated_distance: number;
  mileage_is_round_trip: boolean;
  mileage_rate: Partial<PlatformMileageRates>;
  mileage_rate_id: number;
  missing_mandatory_fields: ExpenseMissingMandatoryFields;
  org_id: string;
  per_diem_num_days: number;
  per_diem_rate: Pick<PlatformPerDiemRates, 'id' | 'code' | 'name'>;
  per_diem_rate_id: number;
  policy_checks: PolicyChecks;
  policy_amount: number;
  project_id: number;
  project: Pick<Project, 'id' | 'name' | 'sub_project' | 'code' | 'display_name'>;
  purpose: string;
  report: ExpenseReport;
  report_id: string;
  seq_num: string;
  source: string;
  source_account: Pick<Account, 'id' | 'type'>;
  source_account_id: string;
  advance_wallet_id?: string;
  spent_at: Date;
  split_group_amount: number;
  split_group_id: string;
  started_at: Date;
  state: ExpenseState;
  state_display_name: string;
  tax_amount: number;
  tax_group: Pick<PlatformTaxGroup, 'name' | 'percentage'>;
  tax_group_id: string;
  travel_classes: string[];
  updated_at: Date;
  unreportable: boolean;
  user: User;
  user_id: string;
  verifications?: string[];
  verifier_comments: string[];
  report_last_paid_at: Date;
  report_last_approved_at: Date;
  commute_deduction?: CommuteDeduction;
  commute_details?: CommuteDetails;
  commute_details_id?: number;
  is_reconciled?: boolean;
}
