import { AdvanceRequestFile } from '../models/advance-request-file.model';

export const advRequestFile: AdvanceRequestFile = {
  files: [
    {
      id: 'fi1w2IE6JeqS',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-02-23T13:59:29.526Z'),
      name: '000.jpeg',
      s3url: '2023-02-23/orNVthTo2Zyo/receipts/fi1w2IE6JeqS.000.jpeg',
      transaction_id: null,
      invoice_id: null,
      advance_request_id: 'areqMP09oaYXBf',
      purpose: 'ORIGINAL',
      password: null,
      receipt_coordinates: null,
      email_meta_data: null,
      fyle_sub_url: '/api/files/fi1w2IE6JeqS/download',
    },
  ],
  advanceReq: {
    id: 'areqMP09oaYXBf',
    created_at: new Date('2023-02-23T16:24:01.335Z'),
    approved_at: null,
    purpose: 'some',
    notes: null,
    state: 'DRAFT',
    currency: 'USD',
    amount: 150,
    org_user_id: 'ouX8dwsbLCLv',
    advance_id: null,
    policy_amount: null,
    policy_flag: null,
    policy_state: 'SUCCESS',
    project_id: null,
    custom_field_values: [
      {
        id: 111,
        name: 'Test Number',
        value: 1,
      },
      {
        id: 112,
        name: 'Test Select',
        value: null,
      },
      {
        id: 113,
        name: 'test bool',
        value: false,
      },
      {
        id: 114,
        name: 'test multi',
        value: null,
      },
      {
        id: 115,
        name: 'test date',
        value: null,
      },
      {
        id: 134,
        name: 'Project Name',
        value: null,
      },
      {
        id: 136,
        name: '231',
        value: false,
      },
      {
        id: 150,
        name: 'checking',
        value: false,
      },
      {
        id: 151,
        name: '123',
        value: null,
      },
      {
        id: 152,
        name: 'Okay?',
        value: false,
      },
    ],
    updated_at: new Date('2023-02-23T11:46:17.569Z'),
    source: 'MOBILE',
    advance_request_number: 'AR/2023/02/R/3',
    updated_by: null,
    is_sent_back: false,
    is_pulled_back: true,
  },
};

export const advRequestFile2: AdvanceRequestFile = {
  files: [
    {
      id: 'fiK7c69UDJNb',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-02-24T12:03:57.680Z'),
      name: '000.jpeg',
      s3url: '2023-02-24/orNVthTo2Zyo/receipts/fiK7c69UDJNb.000.jpeg',
      transaction_id: null,
      invoice_id: null,
      advance_request_id: 'areq99bN9mZgu1',
      purpose: 'ORIGINAL',
      password: null,
      receipt_coordinates: null,
      email_meta_data: null,
      fyle_sub_url: '/api/files/fiK7c69UDJNb/download',
    },
  ],
  advanceReq: {
    id: 'areq99bN9mZgu1',
    created_at: new Date('2023-02-23T16:24:01.335Z'),
    approved_at: null,
    purpose: 'some',
    notes: null,
    state: 'DRAFT',
    currency: 'USD',
    amount: 150,
    org_user_id: 'ouX8dwsbLCLv',
    advance_id: null,
    policy_amount: null,
    policy_flag: null,
    policy_state: 'SUCCESS',
    project_id: null,
    custom_field_values: [
      {
        id: 111,
        name: 'Test Number',
        value: 1,
      },
      {
        id: 112,
        name: 'Test Select',
        value: null,
      },
      {
        id: 113,
        name: 'test bool',
        value: false,
      },
      {
        id: 114,
        name: 'test multi',
        value: null,
      },
      {
        id: 115,
        name: 'test date',
        value: null,
      },
      {
        id: 134,
        name: 'Project Name',
        value: null,
      },
      {
        id: 136,
        name: '231',
        value: false,
      },
      {
        id: 150,
        name: 'checking',
        value: false,
      },
      {
        id: 151,
        name: '123',
        value: null,
      },
      {
        id: 152,
        name: 'Okay?',
        value: false,
      },
    ],
    updated_at: new Date('2023-02-23T11:46:17.569Z'),
    source: 'MOBILE',
    advance_request_number: 'AR/2023/02/R/3',
    updated_by: null,
    is_sent_back: false,
    is_pulled_back: true,
  },
};
