import { ApiV2Reports } from '../models/api-reports.model';

export const apiReportRes: ApiV2Reports = {
  count: 4,
  data: [
    {
      _search_document:
        "'0':5 '2023':3 '5':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/11':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: null,
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: null,
      rp_amount: 0,
      rp_approval_state: null,
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/11',
      rp_created_at: new Date('2023-01-17T06:35:06.814556'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpFE5X1Pqi9P',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 0,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#5:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'MOBILE',
      rp_state: 'DRAFT',
      rp_submitted_at: null,
      rp_tax: null,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: false,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'2023':3 '4':1 '9400':5 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/10':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: ['ouX8dwsbLCLv'],
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: {
        ouX8dwsbLCLv: {
          rank: 99,
          state: 'APPROVAL_PENDING',
        },
      },
      rp_amount: 9400,
      rp_approval_state: 'APPROVAL_PENDING',
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/10',
      rp_created_at: new Date('2023-01-17T06:34:58.398683'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpSGcIEwzxDd',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 4,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: true,
      rp_purpose: '#4:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WEBAPP',
      rp_state: 'APPROVER_INQUIRY',
      rp_submitted_at: '2023-01-17T06:34:59.523',
      rp_tax: 1152.3,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: true,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'2023':3 '324':5 '4':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/9':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: ['ouX8dwsbLCLv'],
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: {
        ouX8dwsbLCLv: {
          rank: 99,
          state: 'APPROVAL_DONE',
        },
      },
      rp_amount: 324,
      rp_approval_state: 'APPROVAL_DONE',
      rp_approved_at: '2023-01-17T06:33:29.049',
      rp_claim_number: 'C/2023/01/R/9',
      rp_created_at: new Date('2023-01-13T07:29:00.963045'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpGpzBpAxtSn',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 1,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#4:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WORKFLOWS',
      rp_state: 'APPROVED',
      rp_submitted_at: '2023-01-13T07:29:01.135',
      rp_tax: 49.42,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: false,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'10121.24':5 '2022':3 '24':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2022/12/r/34':6 'dec':2 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: ['ouX8dwsbLCLv'],
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: {
        ouX8dwsbLCLv: {
          rank: 99,
          state: 'APPROVAL_PENDING',
        },
      },
      rp_amount: 10121.24,
      rp_approval_state: 'APPROVAL_PENDING',
      rp_approved_at: null,
      rp_claim_number: 'C/2022/12/R/34',
      rp_created_at: new Date('2022-12-26T07:29:00.734031'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpFkJ6jUJOyg',
      rp_locations: [],
      rp_manual_flag: true,
      rp_num_transactions: 3,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#24:  Dec 2022',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WORKFLOWS',
      rp_state: 'APPROVER_PENDING',
      rp_submitted_at: '2022-12-26T07:29:01.743',
      rp_tax: 305.08,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: true,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
  ],
  limit: 4,
  offset: 0,
  url: '/v2/reports',
};

export const apiReportRes1: ApiV2Reports = {
  count: 4,
  data: [
    {
      _search_document:
        "'2023':3 '4652':5 '7':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/15':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: null,
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: null,
      rp_amount: 4652,
      rp_approval_state: null,
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/15',
      rp_created_at: new Date('2023-01-18T07:29:00.749098'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpLMyvYSXgJy',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 3,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#7:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WORKFLOWS',
      rp_state: 'APPROVER_PENDING',
      rp_submitted_at: '2023-01-18T07:29:04.487',
      rp_tax: 695.5,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: false,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'2023':3 '347.45800399999996':5 '6':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/12':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: null,
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: null,
      rp_amount: 347.45800399999996,
      rp_approval_state: null,
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/12',
      rp_created_at: new Date('2023-01-17T07:29:00.800733'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpxtbiLXQZUm',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 1,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#6:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WORKFLOWS',
      rp_state: 'APPROVER_PENDING',
      rp_submitted_at: '2023-01-17T07:29:01.751',
      rp_tax: 53,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: false,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
  ],
  limit: 4,
  offset: 0,
  url: '/v2/reports',
};

export const apiReportRes2: ApiV2Reports = {
  count: 4,
  data: [
    {
      _search_document:
        "'0':5 '2023':3 '5':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/11':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: null,
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: null,
      rp_amount: 0,
      rp_approval_state: null,
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/11',
      rp_created_at: new Date('2023-01-17T06:35:06.814556'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpFE5X1Pqi9P',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 0,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#5:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'MOBILE',
      rp_state: 'DRAFT',
      rp_submitted_at: null,
      rp_tax: null,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: false,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'2023':3 '4':1 '9400':5 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/10':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: ['ouX8dwsbLCLv'],
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: {
        ouX8dwsbLCLv: {
          rank: 99,
          state: 'APPROVAL_PENDING',
        },
      },
      rp_amount: 9400,
      rp_approval_state: 'APPROVAL_PENDING',
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/10',
      rp_created_at: new Date('2023-01-17T06:34:58.398683'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpSGcIEwzxDd',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 4,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: true,
      rp_purpose: '#4:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WEBAPP',
      rp_state: 'APPROVER_INQUIRY',
      rp_submitted_at: '2023-01-17T06:34:59.523',
      rp_tax: 1152.3,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: true,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
  ],
  limit: 4,
  offset: 2,
  url: '/v2/reports',
};

export const expectedReports: ApiV2Reports = {
  count: 4,
  data: [
    {
      _search_document:
        "'0':5 '2023':3 '5':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/11':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: null,
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: null,
      rp_amount: 0,
      rp_approval_state: null,
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/11',
      rp_created_at: new Date('2023-01-17T06:35:06.814556'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpFE5X1Pqi9P',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 0,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#5:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'MOBILE',
      rp_state: 'DRAFT',
      rp_submitted_at: null,
      rp_tax: null,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: false,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'2023':3 '4':1 '9400':5 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/10':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: ['ouX8dwsbLCLv'],
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: {
        ouX8dwsbLCLv: {
          rank: 99,
          state: 'APPROVAL_PENDING',
        },
      },
      rp_amount: 9400,
      rp_approval_state: 'APPROVAL_PENDING',
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/10',
      rp_created_at: new Date('2023-01-17T06:34:58.398683'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpSGcIEwzxDd',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 4,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: true,
      rp_purpose: '#4:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WEBAPP',
      rp_state: 'APPROVER_INQUIRY',
      rp_submitted_at: '2023-01-17T06:34:59.523',
      rp_tax: 1152.3,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: true,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'2023':3 '324':5 '4':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/9':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: ['ouX8dwsbLCLv'],
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: {
        ouX8dwsbLCLv: {
          rank: 99,
          state: 'APPROVAL_DONE',
        },
      },
      rp_amount: 324,
      rp_approval_state: 'APPROVAL_DONE',
      rp_approved_at: '2023-01-17T06:33:29.049',
      rp_claim_number: 'C/2023/01/R/9',
      rp_created_at: new Date('2023-01-13T07:29:00.963045'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpGpzBpAxtSn',
      rp_locations: [],
      rp_manual_flag: false,
      rp_num_transactions: 1,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#4:  Jan 2023',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WORKFLOWS',
      rp_state: 'APPROVED',
      rp_submitted_at: '2023-01-13T07:29:01.135',
      rp_tax: 49.42,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: false,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'10121.24':5 '2022':3 '24':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2022/12/r/34':6 'dec':2 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
      approved_by: ['ouX8dwsbLCLv'],
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_level: '123',
      ou_level_id: 'lvlPtroPaClQy',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_status: '"ACTIVE"',
      ou_sub_department: null,
      ou_title: 'director',
      report_approvals: {
        ouX8dwsbLCLv: {
          rank: 99,
          state: 'APPROVAL_PENDING',
        },
      },
      rp_amount: 10121.24,
      rp_approval_state: 'APPROVAL_PENDING',
      rp_approved_at: null,
      rp_claim_number: 'C/2022/12/R/34',
      rp_created_at: new Date('2022-12-26T07:29:00.734031'),
      rp_currency: 'USD',
      rp_exported: false,
      rp_from_dt: null,
      rp_id: 'rpFkJ6jUJOyg',
      rp_locations: [],
      rp_manual_flag: true,
      rp_num_transactions: 3,
      rp_org_user_id: 'ouX8dwsbLCLv',
      rp_physical_bill: false,
      rp_physical_bill_at: null,
      rp_policy_flag: false,
      rp_purpose: '#24:  Dec 2022',
      rp_reimbursed_at: null,
      rp_risk_state: null,
      rp_risk_state_expense_count: null,
      rp_settlement_id: null,
      rp_source: 'WORKFLOWS',
      rp_state: 'APPROVER_PENDING',
      rp_submitted_at: '2022-12-26T07:29:01.743',
      rp_tax: 305.08,
      rp_to_dt: null,
      rp_trip_request_id: null,
      rp_type: 'EXPENSE',
      rp_verification_state: null,
      rp_verified: false,
      sequential_approval_turn: true,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
  ],
  limit: 4,
  offset: 0,
  url: '/v2/reports',
};
