export const dataErtpTransformed = {
  '': {
    search_document:
      "'46040':4 'a':8,14,20,26 'abhishek':32 'ajain@fyle.in':34 'business':11,17,23,29 'c/2022/10/r/37':5 'director':6 'indeed':13,19,25,31 'inr':3 'jain':33 'long':10,16,22,28 'mumbai':7 'report':2 'testing':1 'unit':12,18,24,30 'very':9,15,21,27",
  },
  approved: {
    by: null,
  },
  ou: {
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    department_id: 'deptpmQ0SsMO0S',
    employee_id: '',
    id: 'ouX8dwsbLCLv',
    level: 123,
    level_id: 'lvlPtroPaClQy',
    location: 'Mumbai',
    mobile: '123456',
    org_id: 'orNVthTo2Zyo',
    org_name: 'Staging Loaded',
    status: '"ACTIVE"',
    sub_department: null,
    title: 'director',
  },
  report: {
    approvals: null,
  },
  rp: {
    amount: 46040,
    approval_state: null,
    approved_at: null,
    claim_number: 'C/2022/10/R/37',
    created_at: new Date('2022-10-31T13:54:46.317Z'),
    currency: 'USD',
    exported: false,
    from_dt: null,
    id: 'rptkwzhsieIY',
    locations: [],
    manual_flag: false,
    num_transactions: 4,
    org_user_id: 'ouX8dwsbLCLv',
    physical_bill: false,
    physical_bill_at: null,
    policy_flag: false,
    purpose: 'My Testing Report',
    state: 'APPROVAL_PENDING',
    reimbursed_at: null,
    risk_state: null,
    risk_state_expense_count: null,
    settlement_id: null,
    to_dt: null,
    trip_request_id: null,
    type: 'EXPENSE',
    verification_state: null,
    verified: false,
  },
  sequential: {
    approval_turn: false,
  },
  us: {
    email: 'ajain@fyle.in',
    full_name: 'Abhishek Jain',
  },
};

export const apiErptReporDataParam = {
  '': {
    search_document:
      "'46040':4 'a':8,14,20,26 'abhishek':32 'ajain@fyle.in':34 'business':11,17,23,29 'c/2022/10/r/37':5 'director':6 'indeed':13,19,25,31 'inr':3 'jain':33 'long':10,16,22,28 'mumbai':7 'report':2 'testing':1 'unit':12,18,24,30 'very':9,15,21,27",
  },
  approved: {
    by: null,
  },
  ou: {
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    department_id: 'deptpmQ0SsMO0S',
    employee_id: '',
    id: 'ouX8dwsbLCLv',
    level: 123,
    level_id: 'lvlPtroPaClQy',
    location: 'Mumbai',
    mobile: '123456',
    org_id: 'orNVthTo2Zyo',
    org_name: 'Staging Loaded',
    status: '"ACTIVE"',
    sub_department: null,
    title: 'director',
  },
  report: {
    approvals: null,
  },
  rp: {
    amount: 46040,
    approval_state: null,
    approved_at: null,
    claim_number: 'C/2022/10/R/37',
    created_at: new Date('2022-10-31T13:54:46.317208'),
    currency: 'USD',
    exported: false,
    from_dt: null,
    id: 'rptkwzhsieIY',
    locations: [],
    manual_flag: false,
    num_transactions: 4,
    org_user_id: 'ouX8dwsbLCLv',
    physical_bill: false,
    physical_bill_at: null,
    policy_flag: false,
    purpose: 'My Testing Report',
    state: 'APPROVAL_PENDING',
    reimbursed_at: null,
    risk_state: null,
    risk_state_expense_count: null,
    settlement_id: null,
    to_dt: null,
    trip_request_id: null,
    type: 'EXPENSE',
    verification_state: null,
    verified: false,
  },
  sequential: {
    approval_turn: false,
  },
  us: {
    email: 'ajain@fyle.in',
    full_name: 'Abhishek Jain',
  },
};
