import deepFreeze from 'deep-freeze-strict';
import { DwollaCustomer } from '../models/dwolla-customer.model';

export const suspendedDwollaCustomer: DwollaCustomer = deepFreeze({
  id: 'test-id',
  org_id: 'orga123',
  created_at: new Date('2023-01-01T00:00:00.000Z'),
  updated_at: new Date('2023-01-02T00:00:00.000Z'),
  customer_id: 'test-customer-id',
  customer_email: 'test@test.com',
  customer_added_by: 'test-user',
  is_customer_verified: true,
  is_beneficial_owner_added: true,
  is_beneficial_owner_verified: true,
  is_bank_account_added: true,
  is_bank_account_verified: true,
  bank_account_added_by: 'test-user',
  is_customer_document_needed: false,
  is_beneficial_owner_document_needed: false,
  is_customer_retry: false,
  is_customer_suspended: true,
  micro_deposit_verification_status: 'verified',
  micro_deposit_verification_attempts: 0,
  is_beneficial_owner_retry: false,
});

export const activeDwollaCustomer: DwollaCustomer = deepFreeze({
  id: 'test-id',
  org_id: 'orga123',
  created_at: new Date('2023-01-01T00:00:00.000Z'),
  updated_at: new Date('2023-01-02T00:00:00.000Z'),
  customer_id: 'test-customer-id',
  customer_email: 'test@test.com',
  customer_added_by: 'test-user',
  is_customer_verified: true,
  is_beneficial_owner_added: true,
  is_beneficial_owner_verified: true,
  is_bank_account_added: true,
  is_bank_account_verified: true,
  bank_account_added_by: 'test-user',
  is_customer_document_needed: false,
  is_beneficial_owner_document_needed: false,
  is_customer_retry: false,
  is_customer_suspended: false,
  micro_deposit_verification_status: 'verified',
  micro_deposit_verification_attempts: 0,
  is_beneficial_owner_retry: false,
});
