import { UnflattenedAdvanceRequest } from '../models/unflattened-advance-request.model';

export const eadvances: UnflattenedAdvanceRequest = {
  areq_id: 'areqflAACl1G5B',
  areq_created_at: '2024-04-03T04:21:09.256Z',
  areq_approved_at: null,
  areq_purpose: 'rest',
  areq_notes: null,
  areq_state: 'SUBMITTED',
  areq_currency: 'INR',
  areq_amount: 154,
  areq_org_user_id: 'ouX8dwsbLCLv',
  areq_advance_id: null,
  areq_policy_amount: null,
  areq_policy_flag: true,
  areq_policy_state: 'SUCCESS',
  areq_project_id: null,
  areq_custom_field_values: [
    {
      name: '123',
      value: null,
      type: 'TEXT',
    },
    {
      id: 134,
      name: 'Project Name',
      value: null,
      type: 'TEXT',
    },
    {
      id: 112,
      name: 'Test Select',
      value: '',
      type: 'SELECT',
    },
    {
      id: 111,
      name: 'Test Number',
      value: 90,
      type: 'NUMBER',
    },
    {
      id: 114,
      name: 'test multi',
      value: '',
      type: 'MULTI_SELECT',
    },
    {
      id: 115,
      name: 'test date',
      value: null,
      type: 'DATE',
    },
    {
      id: 150,
      name: 'checking',
      value: false,
      type: 'BOOLEAN',
    },
    {
      id: 152,
      name: 'Okay?',
      value: false,
      type: 'BOOLEAN',
    },
    {
      id: 113,
      name: 'test bool',
      value: false,
      type: 'BOOLEAN',
    },
    {
      id: 136,
      name: '231',
      value: false,
      type: 'BOOLEAN',
    },
  ],
  areq_updated_at: '2024-04-03T04:58:17.896Z',
  areq_source: 'WEBAPP',
  areq_advance_request_number: 'AR/2024/04/R/9',
  areq_updated_by: null,
  areq_is_sent_back: false,
  areq_is_pulled_back: false,
  ou_id: 'ouX8dwsbLCLv',
  ou_org_id: 'orNVthTo2Zyo',
  ou_org_name: 'Staging Loaded',
  ou_employee_id: '1223',
  ou_location: 'Mumbai',
  ou_level: '123',
  ou_business_unit:
    'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
  ou_department: 'mileage dept',
  ou_title: 'sfkj',
  ou_mobile: '+919352529834',
  ou_sub_department: 'arun',
  ou_department_id: 'dept62zPkMskdX',
  us_full_name: 'Abhishek Jain test',
  us_email: 'ajain@fyle.in',
  project_code: null,
  project_name: null,
  advance_id: null,
  us_name: 'Abhishek Jain test',
  policy_amount: null,
  policy_flag: true,
  policy_state: 'SUCCESS',
  new_state: 'APPROVAL_PENDING',
};
