import { ExpensesInfo } from '../services/expenses-info.model';

export const expensesInfo: ExpensesInfo = {
  isReportedAndAbove: false,
  isAdvancePresent: true,
  defaultExpenses: [
    {
      _search_document:
        "'00':42,43 '1':1,7 '1.00':2 '3234':46 '98.41':9 'a':15,21,27,33 'abhishek':39 'ajain@fyle.in':41 'angular':45 'business':18,24,30,36 'complete':4 'director':13 'e/2023/03/t/110':8 'entertainment':44 'indeed':20,26,32,38 'USD':3,10 'jain':40 'long':17,23,29,35 'mumbai':14 'professional':11 'services':12 'term':6 'test':5 'unit':19,25,31,37 'very':16,22,28,34",
      corporate_credit_card_account_number: null,
      credit: false,
      custom_fields: {
        category2: null,
        select_all_2: null,
        test: null,
        test_112: null,
        text1: '54',
        user_list: [],
        userlist: [],
      },
      debit: false,
      duplicates: null,
      external_expense_id: null,
      matched_by: null,
      ou_band:
        'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_joining_dt: '2017-07-25',
      ou_level: '123',
      ou_location: 'Mumbai',
      ou_mobile: '+12025559975',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_rank: 1121212121,
      ou_sub_department: null,
      ou_title: 'director',
      ou_user_id: 'usvKA4X8Ugcr',
      rp_approved_at: null,
      rp_claim_number: null,
      rp_purpose: null,
      rp_reimbursed_at: null,
      source_account_id: 'accXURAJqqWcM',
      source_account_type: 'PERSONAL_ADVANCE_ACCOUNT',
      tg_name: 'cgst',
      tg_percentage: 0.18,
      tx_activity_details: null,
      tx_activity_policy_pending: null,
      tx_admin_amount: null,
      tx_amount: 1,
      tx_billable: false,
      tx_boolean_column1: null,
      tx_boolean_column10: null,
      tx_boolean_column2: null,
      tx_boolean_column3: null,
      tx_boolean_column4: null,
      tx_boolean_column5: null,
      tx_boolean_column6: null,
      tx_boolean_column7: null,
      tx_boolean_column8: null,
      tx_boolean_column9: null,
      tx_bus_travel_class: null,
      tx_category: null,
      tx_corporate_credit_card_expense_group_id: null,
      tx_cost_center_code: '12',
      tx_cost_center_id: 13793,
      tx_cost_center_name: '14',
      tx_created_at: new Date('2023-03-06T07:39:36.266905'),
      tx_creator_id: 'ouX8dwsbLCLv',
      tx_currency: 'USD',
      tx_custom_properties: [
        {
          id: 200227,
          name: 'userlist',
          value: [],
        },
        {
          id: 210649,
          name: 'User List',
          value: [],
        },
        {
          id: 215526,
          name: 'text1',
          value: '54',
        },
        {
          id: 210281,
          name: 'test',
          value: null,
        },
        {
          id: 212819,
          name: 'category2',
          value: null,
        },
        {
          id: 211321,
          name: 'test 112',
          value: null,
        },
        {
          id: 206198,
          name: '2232323',
          value: null,
        },
        {
          id: 211326,
          name: 'select all 2',
          value: null,
        },
      ],
      tx_decimal_column1: null,
      tx_decimal_column10: null,
      tx_decimal_column2: null,
      tx_decimal_column3: null,
      tx_decimal_column4: null,
      tx_decimal_column5: null,
      tx_decimal_column6: null,
      tx_decimal_column7: null,
      tx_decimal_column8: null,
      tx_decimal_column9: null,
      tx_distance: null,
      tx_distance_unit: null,
      tx_expense_number: 'E/2023/03/T/110',
      tx_external_id: null,
      tx_extracted_data: {
        amount: 98.41,
        category: 'Professional Services',
        currency: 'USD',
        date: null,
        invoice_dt: null,
        vendor: null,
      },
      tx_file_ids: ['fiNKwy0NukIW', 'fiNKwy0NukIW'],
      tx_flight_journey_travel_class: null,
      tx_flight_return_travel_class: null,
      tx_from_dt: null,
      tx_fyle_category: 'Entertainment',
      tx_hotel_is_breakfast_provided: null,
      tx_id: 'txLgXPnTDOGf',
      tx_invoice_number: null,
      tx_is_duplicate_expense: null,
      tx_is_holiday_expense: null,
      tx_is_implicit_merge_blocked: false,
      tx_is_split_expense: true,
      tx_location_column1: null,
      tx_location_column10: null,
      tx_location_column2: null,
      tx_location_column3: null,
      tx_location_column4: null,
      tx_location_column5: null,
      tx_location_column6: null,
      tx_location_column7: null,
      tx_location_column8: null,
      tx_location_column9: null,
      tx_locations: [],
      tx_mandatory_fields_present: true,
      tx_manual_flag: false,
      tx_mileage_calculated_amount: null,
      tx_mileage_calculated_distance: null,
      tx_mileage_is_round_trip: null,
      tx_mileage_rate: null,
      tx_mileage_vehicle_type: null,
      tx_num_days: null,
      tx_num_files: 2,
      tx_org_category: '00',
      tx_org_category_code: null,
      tx_org_category_id: 110351,
      tx_org_user_id: 'ouX8dwsbLCLv',
      tx_orig_amount: null,
      tx_orig_currency: null,
      tx_payment_id: 'pay1kbic4xI9e',
      tx_per_diem_rate_id: null,
      tx_physical_bill: false,
      tx_physical_bill_at: null,
      tx_policy_amount: null,
      tx_policy_flag: false,
      tx_policy_state: null,
      tx_project_code: 'CPM usr 1 test',
      tx_project_id: 3744,
      tx_project_name: '3234',
      tx_purpose: 'test_term (1)',
      tx_receipt_required: false,
      tx_report_id: null,
      tx_reported_at: null,
      tx_risk_state: null,
      tx_skip_reimbursement: true,
      tx_source: 'MOBILE_CAMERA',
      tx_source_account_id: 'accXURAJqqWcM',
      tx_split_group_id: 'txB1rVZJ4Pxl',
      tx_split_group_user_amount: 28600.775349999996,
      tx_state: 'COMPLETE',
      tx_sub_category: '00',
      tx_tax: 0.15,
      tx_tax_amount: 0.15,
      tx_tax_group_id: 'tg3iWuqWhfzB',
      tx_text_array_column1: null,
      tx_text_array_column10: null,
      tx_text_array_column2: null,
      tx_text_array_column3: null,
      tx_text_array_column4: null,
      tx_text_array_column5: null,
      tx_text_array_column6: null,
      tx_text_array_column7: null,
      tx_text_array_column8: null,
      tx_text_array_column9: null,
      tx_text_column1: null,
      tx_text_column10: null,
      tx_text_column11: null,
      tx_text_column12: null,
      tx_text_column13: null,
      tx_text_column14: null,
      tx_text_column15: null,
      tx_text_column2: null,
      tx_text_column3: null,
      tx_text_column4: null,
      tx_text_column5: null,
      tx_text_column6: null,
      tx_text_column7: '54',
      tx_text_column8: null,
      tx_text_column9: null,
      tx_timestamp_column1: null,
      tx_timestamp_column10: null,
      tx_timestamp_column2: null,
      tx_timestamp_column3: null,
      tx_timestamp_column4: null,
      tx_timestamp_column5: null,
      tx_timestamp_column6: null,
      tx_timestamp_column7: null,
      tx_timestamp_column8: null,
      tx_timestamp_column9: null,
      tx_to_dt: null,
      tx_train_travel_class: null,
      tx_transcribed_data: null,
      tx_transcription_state: null,
      tx_txn_dt: new Date('2023-03-06T11:30:00.000Z'),
      tx_updated_at: new Date('2023-03-06T15:28:47.498545'),
      tx_user_amount: 1,
      tx_user_can_delete: true,
      tx_user_reason_for_duplicate_expenses: null,
      tx_user_review_needed: null,
      tx_vendor: 'Angular',
      tx_vendor_id: 41372,
      tx_verification_state: null,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
      isDraft: false,
      isPolicyViolated: false,
      isCriticalPolicyViolated: false,
      vendorDetails: 'Angular',
    },
  ],
};

export const expenseInfoWithoutDefaultExpense: ExpensesInfo = {
  isReportedAndAbove: false,
  isAdvancePresent: false,
  defaultExpenses: null,
};

export const expensesInfoWithReportedExpense: ExpensesInfo = {
  isReportedAndAbove: true,
  isAdvancePresent: true,
  defaultExpenses: [
    {
      tx_state: 'APPROVER_PENDING',
      ...expensesInfo.defaultExpenses[0],
    },
  ],
};

export const expensesInfoWithMultipleAdvanceExpenses: ExpensesInfo = {
  isReportedAndAbove: false,
  isAdvancePresent: true,
  defaultExpenses: [
    {
      _search_document:
        "'00':42,43 '1':1,7 '1.00':2 '3234':46 '98.41':9 'a':15,21,27,33 'abhishek':39 'ajain@fyle.in':41 'angular':45 'business':18,24,30,36 'complete':4 'director':13 'e/2023/03/t/110':8 'entertainment':44 'indeed':20,26,32,38 'inr':3,10 'jain':40 'long':17,23,29,35 'mumbai':14 'professional':11 'services':12 'term':6 'test':5 'unit':19,25,31,37 'very':16,22,28,34",
      corporate_credit_card_account_number: null,
      credit: false,
      custom_fields: {
        category2: null,
        select_all_2: null,
        test: null,
        test_112: null,
        text1: '54',
        user_list: [],
        userlist: [],
      },
      debit: false,
      duplicates: null,
      external_expense_id: null,
      matched_by: null,
      ou_band:
        'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_joining_dt: '2017-07-25',
      ou_level: '123',
      ou_location: 'Mumbai',
      ou_mobile: '+12025559975',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_rank: 1121212121,
      ou_sub_department: null,
      ou_title: 'director',
      ou_user_id: 'usvKA4X8Ugcr',
      rp_approved_at: null,
      rp_claim_number: null,
      rp_purpose: null,
      rp_reimbursed_at: null,
      source_account_id: 'accXURAJqqWcM',
      source_account_type: 'PERSONAL_ADVANCE_ACCOUNT',
      tg_name: 'cgst',
      tg_percentage: 0.18,
      tx_activity_details: null,
      tx_activity_policy_pending: null,
      tx_admin_amount: null,
      tx_amount: 1,
      tx_billable: false,
      tx_boolean_column1: null,
      tx_boolean_column10: null,
      tx_boolean_column2: null,
      tx_boolean_column3: null,
      tx_boolean_column4: null,
      tx_boolean_column5: null,
      tx_boolean_column6: null,
      tx_boolean_column7: null,
      tx_boolean_column8: null,
      tx_boolean_column9: null,
      tx_bus_travel_class: null,
      tx_category: null,
      tx_corporate_credit_card_expense_group_id: null,
      tx_cost_center_code: '12',
      tx_cost_center_id: 13793,
      tx_cost_center_name: '14',
      tx_created_at: new Date('2023-03-06T07:39:36.266905'),
      tx_creator_id: 'ouX8dwsbLCLv',
      tx_currency: 'INR',
      tx_custom_properties: [
        {
          id: 200227,
          name: 'userlist',
          value: [],
        },
        {
          id: 210649,
          name: 'User List',
          value: [],
        },
        {
          id: 215526,
          name: 'text1',
          value: '54',
        },
        {
          id: 210281,
          name: 'test',
          value: null,
        },
        {
          id: 212819,
          name: 'category2',
          value: null,
        },
        {
          id: 211321,
          name: 'test 112',
          value: null,
        },
        {
          id: 206198,
          name: '2232323',
          value: null,
        },
        {
          id: 211326,
          name: 'select all 2',
          value: null,
        },
      ],
      tx_decimal_column1: null,
      tx_decimal_column10: null,
      tx_decimal_column2: null,
      tx_decimal_column3: null,
      tx_decimal_column4: null,
      tx_decimal_column5: null,
      tx_decimal_column6: null,
      tx_decimal_column7: null,
      tx_decimal_column8: null,
      tx_decimal_column9: null,
      tx_distance: null,
      tx_distance_unit: null,
      tx_expense_number: 'E/2023/03/T/110',
      tx_external_id: null,
      tx_extracted_data: {
        amount: 98.41,
        category: 'Professional Services',
        currency: 'INR',
        date: null,
        invoice_dt: null,
        vendor: null,
      },
      tx_file_ids: ['fiNKwy0NukIW', 'fiNKwy0NukIW'],
      tx_flight_journey_travel_class: null,
      tx_flight_return_travel_class: null,
      tx_from_dt: null,
      tx_fyle_category: 'Entertainment',
      tx_hotel_is_breakfast_provided: null,
      tx_id: 'txLgXPnTDOGf',
      tx_invoice_number: null,
      tx_is_duplicate_expense: null,
      tx_is_holiday_expense: null,
      tx_is_implicit_merge_blocked: false,
      tx_is_split_expense: true,
      tx_location_column1: null,
      tx_location_column10: null,
      tx_location_column2: null,
      tx_location_column3: null,
      tx_location_column4: null,
      tx_location_column5: null,
      tx_location_column6: null,
      tx_location_column7: null,
      tx_location_column8: null,
      tx_location_column9: null,
      tx_locations: [],
      tx_mandatory_fields_present: true,
      tx_manual_flag: false,
      tx_mileage_calculated_amount: null,
      tx_mileage_calculated_distance: null,
      tx_mileage_is_round_trip: null,
      tx_mileage_rate: null,
      tx_mileage_vehicle_type: null,
      tx_num_days: null,
      tx_num_files: 2,
      tx_org_category: '00',
      tx_org_category_code: null,
      tx_org_category_id: 110351,
      tx_org_user_id: 'ouX8dwsbLCLv',
      tx_orig_amount: null,
      tx_orig_currency: null,
      tx_payment_id: 'pay1kbic4xI9e',
      tx_per_diem_rate_id: null,
      tx_physical_bill: false,
      tx_physical_bill_at: null,
      tx_policy_amount: null,
      tx_policy_flag: false,
      tx_policy_state: null,
      tx_project_code: 'CPM usr 1 test',
      tx_project_id: 3744,
      tx_project_name: '3234',
      tx_purpose: 'test_term (1)',
      tx_receipt_required: false,
      tx_report_id: null,
      tx_reported_at: null,
      tx_risk_state: null,
      tx_skip_reimbursement: true,
      tx_source: 'MOBILE_CAMERA',
      tx_source_account_id: 'accXURAJqqWcM',
      tx_split_group_id: 'txB1rVZJ4Pxl',
      tx_split_group_user_amount: 28600.775349999996,
      tx_state: 'COMPLETE',
      tx_sub_category: '00',
      tx_tax: 0.15,
      tx_tax_amount: 0.15,
      tx_tax_group_id: 'tg3iWuqWhfzB',
      tx_text_array_column1: null,
      tx_text_array_column10: null,
      tx_text_array_column2: null,
      tx_text_array_column3: null,
      tx_text_array_column4: null,
      tx_text_array_column5: null,
      tx_text_array_column6: null,
      tx_text_array_column7: null,
      tx_text_array_column8: null,
      tx_text_array_column9: null,
      tx_text_column1: null,
      tx_text_column10: null,
      tx_text_column11: null,
      tx_text_column12: null,
      tx_text_column13: null,
      tx_text_column14: null,
      tx_text_column15: null,
      tx_text_column2: null,
      tx_text_column3: null,
      tx_text_column4: null,
      tx_text_column5: null,
      tx_text_column6: null,
      tx_text_column7: '54',
      tx_text_column8: null,
      tx_text_column9: null,
      tx_timestamp_column1: null,
      tx_timestamp_column10: null,
      tx_timestamp_column2: null,
      tx_timestamp_column3: null,
      tx_timestamp_column4: null,
      tx_timestamp_column5: null,
      tx_timestamp_column6: null,
      tx_timestamp_column7: null,
      tx_timestamp_column8: null,
      tx_timestamp_column9: null,
      tx_to_dt: null,
      tx_train_travel_class: null,
      tx_transcribed_data: null,
      tx_transcription_state: null,
      tx_txn_dt: new Date('2023-03-06T11:30:00.000Z'),
      tx_updated_at: new Date('2023-03-06T15:28:47.498545'),
      tx_user_amount: 1,
      tx_user_can_delete: true,
      tx_user_reason_for_duplicate_expenses: null,
      tx_user_review_needed: null,
      tx_vendor: 'Angular',
      tx_vendor_id: 41372,
      tx_verification_state: null,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
      isDraft: false,
      isPolicyViolated: false,
      isCriticalPolicyViolated: false,
      vendorDetails: 'Angular',
    },
  ],
};
