import { Expense } from '../models/expense.model';
import { ApiV2Response } from '../models/v2/api-v2-response.model';

export const expenseData1: Expense = {
  tx_categoryDisplayName: 'Groceries',
  tx_risk_state: null,
  tx_is_duplicate_expense: null,
  tx_duplicates: null,
  ou_org_name: 'Fyle Staging',
  tx_id: 'tx5fBcPBAxLv',
  tx_org_user_id: 'oucL6lSdrjiw',
  tx_created_at: new Date('2022-11-30T17:31:52.261Z'),
  tx_receipt_required: false,
  tx_user_can_delete: true,
  tx_txn_dt: new Date('2022-11-30T06:30:00.000Z'),
  tx_category: null,
  tx_amount: 956,
  tx_user_amount: 956,
  tx_policy_amount: null,
  tx_admin_amount: null,
  tx_tax: 78.94,
  tx_tax_amount: 78.94,
  tx_tax_group_id: 'tgia4INHcDWs',
  tg_name: 'kk',
  tg_percentage: 0.09,
  tx_currency: 'USD',
  tx_report_id: 'rpT7x1BFlLOi',
  tx_reported_at: '2022-11-30T17:31:53.719Z',
  tx_state: 'DRAFT',
  tx_num_files: 0,
  tx_invoice_number: null,
  tx_purpose: null,
  tx_source: 'MOBILE',
  tx_billable: null,
  tx_orig_amount: null,
  tx_orig_currency: null,
  tx_project_id: 305682,
  tx_project_name: 'PROJECT TEST 3 / TEST 1',
  tx_project_code: 'FF-032',
  tx_skip_reimbursement: false,
  tx_creator_id: 'oucL6lSdrjiw',
  tx_user_reason_for_duplicate_expenses: null,
  tx_external_id: null,
  tx_cost_center_name: 'Alain Henderson',
  tx_cost_center_code: null,
  tx_cost_center_id: 11743,
  tx_source_account_id: 'accQg5d75oAe9',
  tx_transcription_state: null,
  tx_verification_state: null,
  tx_physical_bill: null,
  tx_physical_bill_at: null,
  tx_policy_state: null,
  tx_manual_flag: false,
  tx_policy_flag: null,
  rp_purpose: 'teat2',
  rp_approved_at: null,
  rp_reimbursed_at: null,
  rp_claim_number: 'C/2022/02/R/8',
  ou_id: 'oucL6lSdrjiw',
  ou_org_id: 'orrjqbDbeP9p',
  ou_user_id: 'usrGrejHhlcy',
  ou_employee_id: 'testEmployeeUID',
  ou_location: 'India',
  ou_level: null,
  ou_band: null,
  ou_rank: null,
  ou_business_unit: null,
  ou_department_id: null,
  ou_department: null,
  ou_title: null,
  ou_mobile: '8080913866',
  ou_sub_department: null,
  ou_joining_dt: null,
  us_full_name: 'YAsh',
  us_email: 'yash.s@fyle.in',
  tx_vendor: 'asd',
  tx_vendor_id: 834,
  tx_platform_vendor: null,
  tx_platform_vendor_id: null,
  source_account_type: 'PERSONAL_ACCOUNT',
  source_account_id: 'accQg5d75oAe9',
  tx_org_category: 'Groceries',
  tx_sub_category: 'Groceries',
  tx_fyle_category: 'Groceries',
  tx_org_category_code: null,
  tx_org_category_id: 215481,
  external_expense_id: null,
  tx_expense_number: 'E/2022/11/T/62',
  tx_corporate_credit_card_expense_group_id: null,
  tx_split_group_id: 'tx5fBcPBAxLv',
  tx_split_group_user_amount: 956,
  tx_extracted_data: null,
  tx_transcribed_data: null,
  tx_user_review_needed: null,
  tx_mandatory_fields_present: true,
  is_test_call: null,
  tx_distance: null,
  tx_distance_unit: null,
  tx_from_dt: new Date('2022-11-30T17:31:52.261Z'),
  tx_to_dt: new Date('2022-11-30T06:30:00.000Z'),
  tx_updated_at: new Date('2022-11-30T17:31:52.261Z'),
  tx_num_days: null,
  tx_mileage_calculated_distance: null,
  tx_mileage_calculated_amount: null,
  tx_mileage_vehicle_type: null,
  tx_mileage_rate: null,
  tx_mileage_is_round_trip: null,
  tx_hotel_is_breakfast_provided: null,
  tx_flight_journey_travel_class: null,
  tx_flight_return_travel_class: null,
  tx_train_travel_class: null,
  tx_bus_travel_class: null,
  tx_taxi_travel_class: null,
  tx_per_diem_rate_id: null,
  tx_activity_policy_pending: null,
  tx_activity_details: null,
  tx_locations: [],
  tx_custom_properties: [
    {
      name: 'Multi Type',
      value: ['Multi 1'],
    },
    {
      name: 'name',
      value: null,
    },
  ],
  tx_is_implicit_merge_blocked: false,
};

export const expenseData2: Expense = {
  tx_risk_state: null,
  tx_is_duplicate_expense: null,
  tx_duplicates: null,
  ou_org_name: 'Fyle Staging',
  tx_id: 'tx5fBcPBAxLv',
  tx_org_user_id: 'oucL6lSdrjiw',
  tx_created_at: new Date('2022-11-30T17:31:52.261Z'),
  tx_receipt_required: false,
  tx_user_can_delete: true,
  tx_txn_dt: new Date('2022-11-30T06:30:00.000Z'),
  tx_category: null,
  tx_amount: 956,
  tx_user_amount: 956,
  tx_policy_amount: 0.00009,
  tx_admin_amount: null,
  tx_tax: 78.94,
  tx_tax_amount: 78.94,
  tx_tax_group_id: 'tgia4INHcDWs',
  tg_name: 'kk',
  tg_percentage: 0.09,
  tx_currency: 'USD',
  tx_report_id: 'rpT7x1BFlLOi',
  tx_reported_at: '2022-11-30T17:31:53.719Z',
  tx_state: 'APPROVER_PENDING',
  tx_num_files: 0,
  tx_invoice_number: null,
  tx_purpose: null,
  tx_source: 'MOBILE',
  tx_billable: null,
  tx_orig_amount: null,
  tx_orig_currency: null,
  tx_project_id: 305682,
  tx_project_name: 'PROJECT TEST 3 / TEST 1',
  tx_project_code: 'FF-032',
  tx_skip_reimbursement: false,
  tx_creator_id: 'oucL6lSdrjiw',
  tx_user_reason_for_duplicate_expenses: null,
  tx_external_id: null,
  tx_cost_center_name: 'Alain Henderson',
  tx_cost_center_code: null,
  tx_cost_center_id: 11743,
  tx_source_account_id: 'accQg5d75oAe9',
  tx_transcription_state: null,
  tx_verification_state: null,
  tx_physical_bill: null,
  tx_physical_bill_at: null,
  tx_policy_state: null,
  tx_manual_flag: true,
  tx_policy_flag: null,
  rp_purpose: 'teat2',
  rp_approved_at: null,
  rp_reimbursed_at: null,
  rp_claim_number: 'C/2022/02/R/8',
  ou_id: 'oucL6lSdrjiw',
  ou_org_id: 'orrjqbDbeP9p',
  ou_user_id: 'usrGrejHhlcy',
  ou_employee_id: 'testEmployeeUID',
  ou_location: 'India',
  ou_level: null,
  ou_band: null,
  ou_rank: null,
  ou_business_unit: null,
  ou_department_id: null,
  ou_department: null,
  ou_title: null,
  ou_mobile: '8080913866',
  ou_sub_department: null,
  ou_joining_dt: null,
  us_full_name: 'YAsh',
  us_email: 'yash.s@fyle.in',
  tx_vendor: 'asd',
  tx_vendor_id: 834,
  tx_platform_vendor: null,
  tx_platform_vendor_id: null,
  source_account_type: 'PERSONAL_ACCOUNT',
  source_account_id: 'accQg5d75oAe9',
  tx_org_category: 'Groceries',
  tx_sub_category: 'Groceries',
  tx_fyle_category: 'Groceries',
  tx_org_category_code: null,
  tx_org_category_id: 215481,
  external_expense_id: null,
  tx_expense_number: 'E/2022/11/T/62',
  tx_corporate_credit_card_expense_group_id: null,
  tx_split_group_id: 'tx5fBcPBAxLv',
  tx_split_group_user_amount: 956,
  tx_extracted_data: null,
  tx_transcribed_data: null,
  tx_user_review_needed: null,
  tx_mandatory_fields_present: true,
  is_test_call: null,
  tx_distance: null,
  tx_distance_unit: null,
  tx_from_dt: null,
  tx_to_dt: null,
  tx_num_days: null,
  tx_mileage_calculated_distance: null,
  tx_mileage_calculated_amount: null,
  tx_mileage_vehicle_type: null,
  tx_mileage_rate: null,
  tx_mileage_is_round_trip: null,
  tx_hotel_is_breakfast_provided: null,
  tx_flight_journey_travel_class: null,
  tx_flight_return_travel_class: null,
  tx_train_travel_class: null,
  tx_bus_travel_class: null,
  tx_taxi_travel_class: null,
  tx_per_diem_rate_id: null,
  tx_activity_policy_pending: null,
  tx_activity_details: null,
  tx_locations: [],
  tx_custom_properties: [
    {
      name: 'Multi Type',
      value: ['Multi 1'],
    },
    {
      name: 'name',
      value: null,
    },
  ],
  tx_is_implicit_merge_blocked: false,
};

export const etxncData: ApiV2Response<Expense> = {
  limit: 1,
  offset: 0,
  count: 1,
  url: '/v2/expenses',
  data: [
    {
      _search_document:
        "'-102717':57 '1':42 '111':9 '20210809':56 '5':53 '899':1 '899.00':2 'a':15,21,27,33 'abcdfeiapcalp':43,44,45,46,47 'abhishek':39 'ajain@fyle.in':41 'ana':12 'approver':4 'aus':55 'board':50 'business':18,24,30,36 'director':13 'e/2023/01/t/89':8 'equalization':52 'honecomb':54 'indeed':20,26,32,38 'inr':3,10 'jain':40 'long':17,23,29,35 'mumbai':14 'of':51 'others':11,48 'pending':5 'project':59 'staging':58 'state':49 'term':7 'test':6 'unit':19,25,31,37 'very':16,22,28,34",
      corporate_credit_card_account_number: null,
      credit: false,
      debit: false,
      duplicates: null,
      external_expense_id: null,
      matched_by: null,
      ou_band:
        'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_joining_dt: '2017-07-25',
      ou_level: '123',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_rank: 1121212121,
      ou_sub_department: null,
      ou_title: 'director',
      ou_user_id: 'usvKA4X8Ugcr',
      rp_approved_at: null,
      rp_claim_number: 'C/2023/01/R/20',
      rp_purpose: '#8:  Jan 2023',
      rp_reimbursed_at: null,
      source_account_id: 'acc5APeygFjRd',
      source_account_type: 'PERSONAL_ACCOUNT',
      tg_name: 'GST',
      tg_percentage: 0.05,
      transaction_approvals: null,
      tx_activity_details: null,
      tx_activity_policy_pending: null,
      tx_admin_amount: null,
      tx_amount: 899,
      tx_billable: true,
      tx_boolean_column1: null,
      tx_boolean_column10: null,
      tx_boolean_column2: null,
      tx_boolean_column3: null,
      tx_boolean_column4: null,
      tx_boolean_column5: null,
      tx_boolean_column6: null,
      tx_boolean_column7: null,
      tx_boolean_column8: null,
      tx_boolean_column9: null,
      tx_bus_travel_class: null,
      tx_category: null,
      tx_corporate_credit_card_expense_group_id: null,
      tx_cost_center_code: null,
      tx_cost_center_id: 13795,
      tx_cost_center_name: '01test2',
      tx_created_at: new Date('2023-01-23T05:15:03.797599'),
      tx_creator_id: 'ouX8dwsbLCLv',
      tx_currency: 'USD',
      tx_custom_properties: [
        {
          name: 'userlist',
          value: [],
        },
        {
          name: 'User List',
          value: [],
        },
      ],
      tx_decimal_column1: null,
      tx_decimal_column10: null,
      tx_decimal_column2: null,
      tx_decimal_column3: null,
      tx_decimal_column4: null,
      tx_decimal_column5: null,
      tx_decimal_column6: null,
      tx_decimal_column7: null,
      tx_decimal_column8: null,
      tx_decimal_column9: null,
      tx_distance: null,
      tx_distance_unit: null,
      tx_expense_number: 'E/2023/01/T/89',
      tx_external_id: null,
      tx_extracted_data: {
        amount: 111,
        category: 'Others',
        currency: 'INR',
        date: null,
        invoice_dt: null,
        vendor: 'ANA',
      },
      tx_file_ids: ['fiGLwwPtYD8X'],
      tx_flight_journey_travel_class: null,
      tx_flight_return_travel_class: null,
      tx_from_dt: null,
      tx_fyle_category: 'Others',
      tx_hotel_is_breakfast_provided: false,
      tx_id: 'txOJVaaPxo9O',
      tx_invoice_number: null,
      tx_is_duplicate_expense: null,
      tx_is_holiday_expense: null,
      tx_is_implicit_merge_blocked: false,
      tx_is_split_expense: false,
      tx_location_column1: null,
      tx_location_column10: null,
      tx_location_column2: null,
      tx_location_column3: null,
      tx_location_column4: null,
      tx_location_column5: null,
      tx_location_column6: null,
      tx_location_column7: null,
      tx_location_column8: null,
      tx_location_column9: null,
      tx_locations: [],
      tx_mandatory_fields_present: true,
      tx_manual_flag: false,
      tx_mileage_calculated_amount: null,
      tx_mileage_calculated_distance: null,
      tx_mileage_is_round_trip: null,
      tx_mileage_rate: null,
      tx_mileage_vehicle_type: null,
      tx_num_days: null,
      tx_num_files: 1,
      tx_org_category: '1',
      tx_org_category_code: null,
      tx_org_category_id: 89550,
      tx_org_user_id: 'ouX8dwsbLCLv',
      tx_orig_amount: null,
      tx_orig_currency: null,
      tx_payment_id: 'payYS8l37XIwY',
      tx_per_diem_rate_id: null,
      tx_physical_bill: false,
      tx_physical_bill_at: null,
      tx_policy_amount: null,
      tx_policy_flag: false,
      tx_policy_state: null,
      tx_project_code: null,
      tx_project_id: 3943,
      tx_project_name: 'Staging Project',
      tx_purpose: 'test_term',
      tx_receipt_required: null,
      tx_report_id: 'rpFvmTgyeBjN',
      tx_reported_at: '2023-01-23T07:29:01.37166',
      tx_risk_state: null,
      tx_skip_reimbursement: false,
      tx_source: 'WEBAPP',
      tx_source_account_id: 'acc5APeygFjRd',
      tx_split_group_id: 'txOJVaaPxo9O',
      tx_split_group_user_amount: 899,
      tx_state: 'APPROVER_PENDING',
      tx_sub_category: 'ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP',
      tx_tax: 42.81,
      tx_tax_amount: 42.81,
      tx_tax_group_id: 'tgwotEwriRB5',
      tx_text_array_column1: null,
      tx_text_array_column10: null,
      tx_text_array_column2: null,
      tx_text_array_column3: null,
      tx_text_array_column4: null,
      tx_text_array_column5: null,
      tx_text_array_column6: null,
      tx_text_array_column7: null,
      tx_text_array_column8: null,
      tx_text_array_column9: null,
      tx_text_column1: null,
      tx_text_column10: null,
      tx_text_column11: null,
      tx_text_column12: null,
      tx_text_column13: null,
      tx_text_column14: null,
      tx_text_column15: null,
      tx_text_column2: null,
      tx_text_column3: null,
      tx_text_column4: null,
      tx_text_column5: null,
      tx_text_column6: null,
      tx_text_column7: null,
      tx_text_column8: null,
      tx_text_column9: null,
      tx_timestamp_column1: null,
      tx_timestamp_column10: null,
      tx_timestamp_column2: null,
      tx_timestamp_column3: null,
      tx_timestamp_column4: null,
      tx_timestamp_column5: null,
      tx_timestamp_column6: null,
      tx_timestamp_column7: null,
      tx_timestamp_column8: null,
      tx_timestamp_column9: null,
      tx_to_dt: null,
      tx_train_travel_class: null,
      tx_transcribed_data: null,
      tx_transcription_state: null,
      tx_txn_dt: new Date('2023-01-23T17:00:00'),
      tx_updated_at: new Date('2023-01-23T07:29:01.808297'),
      tx_user_amount: 899,
      tx_user_can_delete: true,
      tx_user_reason_for_duplicate_expenses: null,
      tx_user_review_needed: null,
      tx_vendor: 'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
      tx_vendor_id: 28922,
      tx_verification_state: null,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
  ],
};

export const expenseDataWithDateString = {
  tx_categoryDisplayName: 'Groceries',
  tx_risk_state: null,
  tx_is_duplicate_expense: null,
  tx_duplicates: null,
  ou_org_name: 'Fyle Staging',
  tx_id: 'tx5fBcPBAxLv',
  tx_org_user_id: 'oucL6lSdrjiw',
  tx_created_at: '2022-11-30T17:31:52.261Z',
  tx_receipt_required: false,
  tx_user_can_delete: true,
  tx_txn_dt: '2022-11-30T06:30:00.000Z',
  tx_category: null,
  tx_amount: 956,
  tx_user_amount: 956,
  tx_policy_amount: null,
  tx_admin_amount: null,
  tx_tax: 78.94,
  tx_tax_amount: 78.94,
  tx_tax_group_id: 'tgia4INHcDWs',
  tg_name: 'kk',
  tg_percentage: 0.09,
  tx_currency: 'USD',
  tx_report_id: 'rpT7x1BFlLOi',
  tx_reported_at: '2022-11-30T17:31:53.719Z',
  tx_state: 'DRAFT',
  tx_num_files: 0,
  tx_invoice_number: null,
  tx_purpose: null,
  tx_source: 'MOBILE',
  tx_billable: null,
  tx_orig_amount: null,
  tx_orig_currency: null,
  tx_project_id: 305682,
  tx_project_name: 'PROJECT TEST 3 / TEST 1',
  tx_project_code: 'FF-032',
  tx_skip_reimbursement: false,
  tx_creator_id: 'oucL6lSdrjiw',
  tx_user_reason_for_duplicate_expenses: null,
  tx_external_id: null,
  tx_cost_center_name: 'Alain Henderson',
  tx_cost_center_code: null,
  tx_cost_center_id: 11743,
  tx_source_account_id: 'accQg5d75oAe9',
  tx_transcription_state: null,
  tx_verification_state: null,
  tx_physical_bill: null,
  tx_physical_bill_at: null,
  tx_policy_state: null,
  tx_manual_flag: false,
  tx_policy_flag: null,
  rp_purpose: 'teat2',
  rp_approved_at: null,
  rp_reimbursed_at: null,
  rp_claim_number: 'C/2022/02/R/8',
  ou_id: 'oucL6lSdrjiw',
  ou_org_id: 'orrjqbDbeP9p',
  ou_user_id: 'usrGrejHhlcy',
  ou_employee_id: 'testEmployeeUID',
  ou_location: 'India',
  ou_level: null,
  ou_band: null,
  ou_rank: null,
  ou_business_unit: null,
  ou_department_id: null,
  ou_department: null,
  ou_title: null,
  ou_mobile: '8080913866',
  ou_sub_department: null,
  ou_joining_dt: null,
  us_full_name: 'YAsh',
  us_email: 'yash.s@fyle.in',
  tx_vendor: 'asd',
  tx_vendor_id: 834,
  tx_platform_vendor: null,
  tx_platform_vendor_id: null,
  source_account_type: 'PERSONAL_ACCOUNT',
  source_account_id: 'accQg5d75oAe9',
  tx_org_category: 'Groceries',
  tx_sub_category: 'Groceries',
  tx_fyle_category: 'Groceries',
  tx_org_category_code: null,
  tx_org_category_id: 215481,
  external_expense_id: null,
  tx_expense_number: 'E/2022/11/T/62',
  tx_corporate_credit_card_expense_group_id: null,
  tx_split_group_id: 'tx5fBcPBAxLv',
  tx_split_group_user_amount: 956,
  tx_extracted_data: null,
  tx_transcribed_data: null,
  tx_user_review_needed: null,
  tx_mandatory_fields_present: true,
  is_test_call: null,
  tx_distance: null,
  tx_distance_unit: null,
  tx_from_dt: '2022-11-30T17:31:52.261Z',
  tx_to_dt: '2022-11-30T06:30:00.000Z',
  tx_num_days: null,
  tx_mileage_calculated_distance: null,
  tx_mileage_calculated_amount: null,
  tx_mileage_vehicle_type: null,
  tx_mileage_rate: null,
  tx_mileage_is_round_trip: null,
  tx_hotel_is_breakfast_provided: null,
  tx_flight_journey_travel_class: null,
  tx_flight_return_travel_class: null,
  tx_train_travel_class: null,
  tx_bus_travel_class: null,
  tx_taxi_travel_class: null,
  tx_per_diem_rate_id: null,
  tx_activity_policy_pending: null,
  tx_activity_details: null,
  tx_locations: [],
  tx_updated_at: '2022-11-30T17:31:52.261Z',
  tx_custom_properties: [
    {
      name: 'Multi Type',
      value: ['Multi 1'],
    },
    {
      name: 'name',
      value: null,
    },
  ],
  tx_is_implicit_merge_blocked: false,
};

export const etxnData: Expense = {
  tx_risk_state: null,
  tx_is_duplicate_expense: null,
  tx_duplicates: [
    {
      transaction_id: 'txPYUtSXQdkO',
      reason: '(Accuracy rate: 33%) The amount, currency, date of spend of this expense match with another expense.',
      percent: 33,
      fields: ['amount', 'currency', 'txn_dt'],
    },
  ],
  ou_org_name: 'Staging Loaded',
  tx_id: 'txCBp2jIK6G3',
  tx_org_user_id: 'ouX8dwsbLCLv',
  tx_created_at: new Date('2023-01-13T07:25:23.047Z'),
  tx_receipt_required: false,
  tx_user_can_delete: true,
  tx_txn_dt: new Date('2023-01-13T11:30:00.000Z'),
  tx_category: null,
  tx_amount: 324,
  tx_user_amount: 324,
  tx_policy_amount: null,
  tx_admin_amount: null,
  tx_tax: 49.42,
  tx_tax_amount: 49.42,
  tx_tax_group_id: 'tg3iWuqWhfzB',
  tg_name: 'cgst',
  tg_percentage: 0.18,
  tx_currency: 'INR',
  tx_report_id: 'rpGpzBpAxtSn',
  tx_reported_at: '2023-01-13T07:29:01.010Z',
  tx_state: 'APPROVED',
  tx_num_files: 0,
  tx_invoice_number: null,
  tx_purpose: 'test_term',
  tx_source: 'MOBILE',
  tx_billable: null,
  tx_orig_amount: null,
  tx_orig_currency: null,
  tx_project_id: 3943,
  tx_project_name: 'Staging Project',
  tx_project_code: null,
  tx_skip_reimbursement: false,
  tx_creator_id: 'ouX8dwsbLCLv',
  tx_user_reason_for_duplicate_expenses: null,
  tx_external_id: null,
  tx_cost_center_name: '01test2',
  tx_cost_center_code: null,
  tx_cost_center_id: 13795,
  tx_source_account_id: 'acc5APeygFjRd',
  tx_transcription_state: null,
  tx_verification_state: null,
  tx_physical_bill: null,
  tx_physical_bill_at: null,
  tx_policy_state: null,
  tx_manual_flag: null,
  tx_policy_flag: null,
  rp_purpose: '#4:  Jan 2023',
  rp_approved_at: '2023-01-17T06:33:29.049Z',
  rp_reimbursed_at: null,
  rp_claim_number: 'C/2023/01/R/9',
  ou_id: 'ouX8dwsbLCLv',
  ou_org_id: 'orNVthTo2Zyo',
  ou_user_id: 'usvKA4X8Ugcr',
  ou_employee_id: '',
  ou_location: 'Mumbai',
  ou_level: '123',
  ou_band:
    'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
  ou_rank: 1121212121,
  ou_business_unit:
    'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
  ou_department_id: 'deptpmQ0SsMO0S',
  ou_department: '0000000',
  ou_title: 'director',
  ou_mobile: '123456',
  ou_sub_department: null,
  ou_joining_dt: '2017-07-25T00:00:00.000+0000',
  us_full_name: 'Abhishek Jain',
  us_email: 'ajain@fyle.in',
  tx_vendor: 'New new new',
  tx_vendor_id: 28828,
  tx_platform_vendor: null,
  tx_platform_vendor_id: null,
  source_account_type: 'PERSONAL_ACCOUNT',
  source_account_id: 'acc5APeygFjRd',
  tx_org_category: 'Ani test 1',
  tx_sub_category: 'sub1',
  tx_fyle_category: null,
  tx_org_category_code: null,
  tx_org_category_id: 212527,
  external_expense_id: null,
  tx_expense_number: 'E/2023/01/T/55',
  tx_corporate_credit_card_expense_group_id: null,
  tx_split_group_id: 'txCBp2jIK6G3',
  tx_split_group_user_amount: 324,
  tx_extracted_data: null,
  tx_transcribed_data: null,
  tx_user_review_needed: null,
  tx_mandatory_fields_present: true,
  is_test_call: null,
  tx_distance: null,
  tx_distance_unit: null,
  tx_from_dt: null,
  tx_to_dt: null,
  tx_num_days: null,
  tx_mileage_calculated_distance: null,
  tx_mileage_calculated_amount: null,
  tx_mileage_vehicle_type: null,
  tx_mileage_rate: null,
  tx_mileage_is_round_trip: null,
  tx_hotel_is_breakfast_provided: null,
  tx_flight_journey_travel_class: null,
  tx_flight_return_travel_class: null,
  tx_train_travel_class: null,
  tx_bus_travel_class: null,
  tx_taxi_travel_class: null,
  tx_per_diem_rate_id: null,
  tx_activity_policy_pending: null,
  tx_activity_details: null,
  tx_locations: [],
  tx_custom_properties: [
    {
      name: 'userlist',
      value: [],
      type: 'USER_LIST',
      mandatory: false,
      options: [],
    },
    {
      name: 'User List',
      value: [],
      type: 'USER_LIST',
      mandatory: false,
      options: [],
    },
  ],
  tx_is_implicit_merge_blocked: false,
  tx_categoryDisplayName: 'Ani test 1 / sub1',
};

export const expenseList: Expense[] = [
  {
    _search_document:
      "'1024.0':1 '1024.00':2 'a':13,19,25,31 'abhishek':37 'ajain@fyle.in':39 'ani':40,42 'business':16,22,28,34 'card':8 'complete':4 'description':5 'director':11 'e/2022/02/t/874':10 'indeed':18,24,30,36 'inr':3 'is':6 'j3duuf':45 'jain':38 'long':15,21,27,33 'mumbai':12 'project':47 'staging':46 'test':41,43 'transaction':9 'unit':17,23,29,35 'vendor':44 'very':14,20,26,32 'yuv3hw':7",
    corporate_credit_card_account_number: '8698',
    credit: false,
    debit: true,
    duplicates: null,
    external_expense_id: null,
    matched_by: 'SYSTEM',
    ou_band:
      'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_department_id: 'deptpmQ0SsMO0S',
    ou_employee_id: '',
    ou_id: 'ouX8dwsbLCLv',
    ou_joining_dt: '2017-07-25',
    ou_level: '123',
    ou_location: 'Mumbai',
    ou_mobile: '123456',
    ou_org_id: 'orNVthTo2Zyo',
    ou_org_name: 'Staging Loaded',
    ou_rank: 1121212121,
    ou_sub_department: null,
    ou_title: 'director',
    ou_user_id: 'usvKA4X8Ugcr',
    rp_approved_at: null,
    rp_claim_number: null,
    rp_purpose: null,
    rp_reimbursed_at: null,
    source_account_id: 'accZ1IWjhjLv4',
    source_account_type: 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
    tg_name: 'cgst',
    tg_percentage: 0.18,
    transaction_approvals: null,
    tx_activity_details: null,
    tx_activity_policy_pending: null,
    tx_admin_amount: null,
    tx_amount: 1024,
    tx_billable: false,
    tx_boolean_column1: null,
    tx_boolean_column10: null,
    tx_boolean_column2: null,
    tx_boolean_column3: null,
    tx_boolean_column4: null,
    tx_boolean_column5: null,
    tx_boolean_column6: null,
    tx_boolean_column7: null,
    tx_boolean_column8: null,
    tx_boolean_column9: null,
    tx_bus_travel_class: null,
    tx_category: null,
    tx_corporate_credit_card_expense_group_id: 'cccet1B17R8gWZ',
    tx_cost_center_code: null,
    tx_cost_center_id: 13795,
    tx_cost_center_name: '01test2',
    tx_created_at: new Date('2022-02-17T14:13:13.947712'),
    tx_creator_id: 'SYSTEM_CORPORATE_CARD',
    tx_currency: 'INR',
    tx_custom_properties: [
      {
        name: 'userlist',
        value: null,
      },
      {
        name: 'User List',
        value: null,
      },
      {
        name: 'test',
        value: null,
      },
      {
        name: 'category2',
        value: null,
      },
      {
        name: 'pub create hola 1',
        value: null,
      },
      {
        name: 'test 112',
        value: null,
      },
      {
        name: '2232323',
        value: null,
      },
      {
        name: 'select all 2',
        value: null,
      },
    ],
    tx_decimal_column1: null,
    tx_decimal_column10: null,
    tx_decimal_column2: null,
    tx_decimal_column3: null,
    tx_decimal_column4: null,
    tx_decimal_column5: null,
    tx_decimal_column6: null,
    tx_decimal_column7: null,
    tx_decimal_column8: null,
    tx_decimal_column9: null,
    tx_distance: null,
    tx_distance_unit: null,
    tx_expense_number: 'E/2022/02/T/874',
    tx_external_id: null,
    tx_extracted_data: null,
    tx_file_ids: null,
    tx_flight_journey_travel_class: null,
    tx_flight_return_travel_class: null,
    tx_from_dt: null,
    tx_fyle_category: null,
    tx_hotel_is_breakfast_provided: null,
    tx_id: 'txBphgnCHHeO',
    tx_invoice_number: null,
    tx_is_duplicate_expense: null,
    tx_is_holiday_expense: null,
    tx_is_implicit_merge_blocked: false,
    tx_is_split_expense: false,
    tx_location_column1: null,
    tx_location_column10: null,
    tx_location_column2: null,
    tx_location_column3: null,
    tx_location_column4: null,
    tx_location_column5: null,
    tx_location_column6: null,
    tx_location_column7: null,
    tx_location_column8: null,
    tx_location_column9: null,
    tx_locations: [],
    tx_mandatory_fields_present: true,
    tx_manual_flag: false,
    tx_mileage_calculated_amount: null,
    tx_mileage_calculated_distance: null,
    tx_mileage_is_round_trip: null,
    tx_mileage_rate: null,
    tx_mileage_vehicle_type: null,
    tx_num_days: null,
    tx_num_files: 0,
    tx_org_category: 'ani test',
    tx_org_category_code: null,
    tx_org_category_id: 212690,
    tx_org_user_id: 'ouX8dwsbLCLv',
    tx_orig_amount: null,
    tx_orig_currency: null,
    tx_payment_id: 'pay4ystoS87BR',
    tx_per_diem_rate_id: null,
    tx_physical_bill: false,
    tx_physical_bill_at: null,
    tx_policy_amount: null,
    tx_policy_flag: false,
    tx_policy_state: null,
    tx_project_code: null,
    tx_project_id: 3943,
    tx_project_name: 'Staging Project',
    tx_purpose: 'description is yuv3hw (Card Transaction)',
    tx_receipt_required: null,
    tx_report_id: null,
    tx_reported_at: null,
    tx_risk_state: null,
    tx_skip_reimbursement: true,
    tx_source: 'CORPORATE_CARD',
    tx_source_account_id: 'accZ1IWjhjLv4',
    tx_split_group_id: 'txBphgnCHHeO',
    tx_split_group_user_amount: 1024,
    tx_state: 'COMPLETE',
    tx_sub_category: 'ani test',
    tx_tax: null,
    tx_tax_amount: null,
    tx_tax_group_id: 'tg3iWuqWhfzB',
    tx_text_array_column1: null,
    tx_text_array_column10: null,
    tx_text_array_column2: null,
    tx_text_array_column3: null,
    tx_text_array_column4: null,
    tx_text_array_column5: null,
    tx_text_array_column6: null,
    tx_text_array_column7: null,
    tx_text_array_column8: null,
    tx_text_array_column9: null,
    tx_text_column1: null,
    tx_text_column10: null,
    tx_text_column11: null,
    tx_text_column12: null,
    tx_text_column13: null,
    tx_text_column14: null,
    tx_text_column15: null,
    tx_text_column2: null,
    tx_text_column3: null,
    tx_text_column4: null,
    tx_text_column5: null,
    tx_text_column6: null,
    tx_text_column7: null,
    tx_text_column8: null,
    tx_text_column9: null,
    tx_timestamp_column1: null,
    tx_timestamp_column10: null,
    tx_timestamp_column2: null,
    tx_timestamp_column3: null,
    tx_timestamp_column4: null,
    tx_timestamp_column5: null,
    tx_timestamp_column6: null,
    tx_timestamp_column7: null,
    tx_timestamp_column8: null,
    tx_timestamp_column9: null,
    tx_to_dt: null,
    tx_train_travel_class: null,
    tx_transcribed_data: null,
    tx_transcription_state: null,
    tx_txn_dt: new Date('2008-12-27T17:00:00'),
    tx_updated_at: new Date('2023-01-17T06:34:32.50466'),
    tx_user_amount: 1024,
    tx_user_can_delete: true,
    tx_user_reason_for_duplicate_expenses: null,
    tx_user_review_needed: null,
    tx_vendor: 'vendor_j3duuf',
    tx_vendor_id: 26050,
    tx_verification_state: null,
    us_email: 'ajain@fyle.in',
    us_full_name: 'Abhishek Jain',
  },
];
