import { ExpenseFieldsMap } from '../models/v1/expense-fields-map.model';

export const txnFieldsData: Partial<ExpenseFieldsMap> = {
  purpose: {
    id: 22,
    created_at: new Date(new Date('2018-01-31T23:50:27.221Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'purpose',
    field_name: 'Purpose_display_name',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'E.g. Client Meetin',
    default_value: 'test_term',
    options: ['test_term', 'purpose test', 'lala lala la', 'test again'],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN', 'FYLER'],
    field: 'purpose',
  },
  txn_dt: {
    id: 29,
    created_at: new Date(new Date('2018-01-31T23:50:27.221Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'txn_dt',
    field_name: 'Date of Spenrt',
    seq: 1,
    type: 'DATE',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    placeholder: 'Select dt',
    default_value: null,
    options: [],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'VERIFIER'],
    field: 'txn_dt',
  },
  vendor_id: {
    id: 31,
    created_at: new Date(new Date('2018-01-31T23:50:27.221Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'vendor_id',
    field_name: 'Merchant',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'E.g. Uber',
    default_value: '',
    options: [
      'Australian Taxation Office',
      'expensify@thatharmansingh.com - HoneComb Aus',
      'Nilesh As Vendor',
      'Nilesh Aus Vendor',
      'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
      'Uber',
      'Uber BV',
      'YEHUDAHALEVI16',
      'New new new',
    ],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    field: 'vendor_id',
  },
  cost_center_id: {
    id: 3,
    created_at: new Date(new Date('2018-01-31T23:50:27.221Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'cost_center_id',
    field_name: 'Cost Center',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    placeholder: 'Select Cost Center',
    default_value: null,
    options: [],
    org_category_ids: [
      16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
    ],
    code: null,
    roles_editable: [
      'TRAVEL_ADMIN',
      'PAYMENT_PROCESSOR',
      'VERIFIER',
      'FINANCE',
      'ADMIN',
      'FYLER',
      'APPROVER',
      'TRAVEL_AGENT',
    ],
    field: 'cost_center_id',
  },
  project_id: {
    id: 184692,
    created_at: new Date(new Date('2021-07-28T08:48:55.152Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'project_id',
    field_name: 'Project xyZ',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    placeholder: 'Select Projjjjj',
    default_value: null,
    options: [],
    org_category_ids: [],
    code: null,
    roles_editable: [
      'FYLER',
      'APPROVER',
      'TRAVEL_ADMIN',
      'VERIFIER',
      'PAYMENT_PROCESSOR',
      'FINANCE',
      'ADMIN',
      'TRAVEL_AGENT',
      'OWNER',
      'AUDITOR',
    ],
    field: 'project_id',
  },
  billable: {
    id: 188990,
    created_at: new Date(new Date('2021-07-29T11:05:38.811Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'billable',
    field_name: 'Billable',
    seq: 1,
    type: 'BOOLEAN',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    placeholder: 'Billable',
    default_value: false,
    options: [],
    org_category_ids: [],
    code: null,
    roles_editable: [
      'FYLER',
      'APPROVER',
      'TRAVEL_ADMIN',
      'VERIFIER',
      'PAYMENT_PROCESSOR',
      'FINANCE',
      'ADMIN',
      'TRAVEL_AGENT',
      'OWNER',
      'AUDITOR',
    ],
    field: 'billable',
  },
  tax_group_id: {
    id: 193510,
    created_at: new Date(new Date('2021-08-17T04:48:57.792Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'tax_group_id',
    field_name: 's',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 's',
    default_value: 'GST',
    options: [
      '23',
      'cgst',
      'Exempt Sales @0.0%',
      'GST',
      'MB - GST/RST on Purchases @12.0%',
      'MB - GST/RST on Sales @12.0%',
      'Sales Tax on Imports @0.0%',
      'sdds',
      'sdds1',
      'Services Standard Purchase',
      'Tax Exempt @0.0%',
      'Tax on Consulting @8.25%',
      'Tax on Goods @8.75%',
      'Tax on Purchases @8.25%',
    ],
    org_category_ids: [
      16558, 16559, 16560, 16561, 16562, 16563, 16564, 16566, 16568, 16569, 16570, 16571, 16572, 16573, 16574, 16575,
    ],
    code: null,
    roles_editable: ['OWNER', 'AUDITOR'],
    field: 'tax_group_id',
  },
  org_category_id: {
    id: 203055,
    created_at: new Date(new Date('2022-03-08T11:37:18.493Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'org_category_id',
    field_name: 'Category',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Select Category',
    default_value: null,
    options: [],
    org_category_ids: [],
    code: null,
    roles_editable: [
      'FYLER',
      'APPROVER',
      'TRAVEL_ADMIN',
      'VERIFIER',
      'PAYMENT_PROCESSOR',
      'FINANCE',
      'ADMIN',
      'TRAVEL_AGENT',
      'OWNER',
      'AUDITOR',
    ],
    field: 'org_category_id',
  },
};

export const expenseFieldsMapResponse: Partial<ExpenseFieldsMap> = {
  bus_travel_class: [
    {
      id: 2,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'bus_travel_class',
      field_name: 'Bus travel Class\\/',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'TEST',
      default_value: null,
      options: ['eco', 'business', 'jhgjg'],
      org_category_ids: [
        17283, 49621, 83060, 87409, 87441, 101148, 101149, 101151, 102676, 102757, 105705, 106574, 110168, 110597,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  cost_center_id: [
    {
      id: 3,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'cost_center_id',
      field_name: 'Cost Center',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select Cost Center',
      default_value: null,
      options: [],
      org_category_ids: [
        16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
      ],
      code: null,
      roles_editable: [
        'TRAVEL_ADMIN',
        'PAYMENT_PROCESSOR',
        'VERIFIER',
        'FINANCE',
        'ADMIN',
        'FYLER',
        'APPROVER',
        'TRAVEL_AGENT',
      ],
      field: 'cost_center_id',
    },
  ],
  distance: [
    {
      id: 6,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'distance',
      field_name: 'Distance',
      seq: 1,
      type: 'NUMBER',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Enter Distance',
      default_value: null,
      options: [],
      org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 7,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'distance',
      field_name: 'Distance',
      seq: 2,
      type: 'NUMBER',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'Enter Distance',
      default_value: null,
      options: [],
      org_category_ids: [16570, 201959],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  distance_unit: [
    {
      id: 8,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'distance_unit',
      field_name: 'Unit',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'test unit 2',
      default_value: 'KM',
      options: ['KM', 'MILES'],
      org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 9,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'distance_unit',
      field_name: 'Unit',
      seq: 2,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'Unit',
      default_value: 'MILES',
      options: ['KM', 'MILES'],
      org_category_ids: [16570, 201959],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  flight_journey_travel_class: [
    {
      id: 10,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'flight_journey_travel_class',
      field_name: 'Onward Travel Class',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select travel class',
      default_value: null,
      options: ['BUSINESS'],
      org_category_ids: [
        16576, 54536, 54537, 54660, 56081, 83032, 83033, 89470, 102758, 126680, 174487, 201940, 201941, 201942, 201943,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  flight_return_travel_class: [
    {
      id: 11,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'flight_return_travel_class',
      field_name: 'Return Travel Class',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select travel class',
      default_value: null,
      options: ['BUSINESS', 'ECONOMY', 'FIRST_CLASS'],
      org_category_ids: [
        16576, 54536, 54537, 54660, 56081, 83032, 83033, 89470, 102758, 126680, 174487, 201940, 201941, 201942, 201943,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  from_dt: [
    {
      id: 12,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'from_dt',
      field_name: 'From',
      seq: 1,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'Select Date',
      default_value: null,
      options: [],
      org_category_ids: [16567, 52524, 115520, 115521, 115972, 116010],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 13,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'from_dt',
      field_name: 'Onward Date',
      seq: 2,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select Date',
      default_value: null,
      options: [],
      org_category_ids: [
        16558, 16576, 17283, 49621, 54536, 54537, 54660, 54661, 56081, 83032, 83033, 83060, 87409, 87441, 89470, 101148,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 14,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'from_dt',
      field_name: 'Check-in Date',
      seq: 3,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'Date',
      default_value: null,
      options: [],
      org_category_ids: [16572, 93333, 123035, 201953, 201954, 201955, 201957, 201958, 212529],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  location1: [
    {
      id: 15,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'location1',
      field_name: 'From',
      seq: 1,
      type: 'LOCATION',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select a Cityyyyyyyyy',
      default_value: null,
      options: [],
      org_category_ids: [
        16565, 16576, 17283, 49621, 54536, 54537, 54660, 54661, 56081, 87409, 89470, 123039, 126680, 135129, 161125,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 16,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'location1',
      field_name: 'City',
      seq: 2,
      type: 'LOCATION',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select a City',
      default_value: null,
      options: [],
      org_category_ids: [16572, 51725, 93332, 93333, 123035, 201953, 201954, 201955, 201957, 201958, 212529],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 17,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'location1',
      field_name: 'From',
      seq: 3,
      type: 'LOCATION',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Choose Location - Search for Place or Area',
      default_value: null,
      options: [],
      org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  location2: [
    {
      id: 18,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'location2',
      field_name: 'To',
      seq: 1,
      type: 'LOCATION',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select a City',
      default_value: null,
      options: [],
      org_category_ids: [
        16565, 17283, 49621, 54536, 54537, 54660, 54661, 56081, 87409, 89470, 123039, 126680, 161125, 174059, 174487,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 19,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'location2',
      field_name: 'To',
      seq: 2,
      type: 'LOCATION',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Choose Location - Search for Place or Area',
      default_value: null,
      options: [],
      org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  num_days: [
    {
      id: 21,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'num_days',
      field_name: 'No. of Days',
      seq: 1,
      type: 'NUMBER',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'XYZ',
      default_value: null,
      options: [],
      org_category_ids: [52524, 115520, 115521, 115972, 116010],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  purpose: [
    {
      id: 22,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'purpose',
      field_name: 'Purpose_display_name',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'E.g. Client Meetin',
      default_value: 'test_term',
      options: ['test_term', 'purpose test', 'lala lala la', 'test again'],
      org_category_ids: [
        16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
      ],
      code: null,
      roles_editable: ['APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN', 'FYLER'],
      field: 'purpose',
    },
  ],
  to_dt: [
    {
      id: 25,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'to_dt',
      field_name: 'To',
      seq: 1,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'Select Date',
      default_value: null,
      options: [],
      org_category_ids: [16567, 52524, 115520, 115521, 115972, 116010],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 26,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'to_dt',
      field_name: 'Return Date',
      seq: 2,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select Date',
      default_value: null,
      options: [],
      org_category_ids: [
        16558, 16576, 17283, 49621, 54536, 54537, 54660, 54661, 56081, 83032, 83033, 83060, 87409, 87441, 89470, 101148,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 27,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'to_dt',
      field_name: 'Check-out Date',
      seq: 3,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Hotel Details',
      default_value: null,
      options: [],
      org_category_ids: [16572, 51725, 93332, 93333, 123035, 201953, 201954, 201955, 201957, 201958, 212529],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  train_travel_class: [
    {
      id: 28,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'train_travel_class',
      field_name: 'Travel class',
      seq: 1,
      type: 'TEXT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Enter class of travel',
      default_value: null,
      options: [],
      org_category_ids: [16558, 54661, 114806, 123037, 201946, 201947, 201948, 201949, 201950, 201951],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  txn_dt: [
    {
      id: 29,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'txn_dt',
      field_name: 'Date of Spenrt',
      seq: 1,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select dt',
      default_value: null,
      options: [],
      org_category_ids: [
        16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'VERIFIER'],
      field: 'txn_dt',
    },
    {
      id: 30,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'txn_dt',
      field_name: 'Start Date',
      seq: 2,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select Date',
      default_value: null,
      options: [],
      org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
      code: null,
      roles_editable: ['APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN', 'FYLER'],
    },
  ],
  vendor_id: [
    {
      id: 31,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'vendor_id',
      field_name: 'Merchant',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'E.g. Uber',
      default_value: '',
      options: [
        'Australian Taxation Office',
        'expensify@thatharmansingh.com - HoneComb Aus',
        'Nilesh As Vendor',
        'Nilesh Aus Vendor',
        'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
        'Uber',
        'Uber BV',
        'YEHUDAHALEVI16',
        'New new new',
      ],
      org_category_ids: [
        16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
      field: 'vendor_id',
    },
  ],
  project_id: [
    {
      id: 184692,
      created_at: new Date('2021-07-28T08:48:55.152Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'project_id',
      field_name: 'Project xyZ',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select Projjjjj',
      default_value: null,
      options: [],
      org_category_ids: [],
      code: null,
      roles_editable: [
        'FYLER',
        'APPROVER',
        'TRAVEL_ADMIN',
        'VERIFIER',
        'PAYMENT_PROCESSOR',
        'FINANCE',
        'ADMIN',
        'TRAVEL_AGENT',
        'OWNER',
        'AUDITOR',
      ],
      field: 'project_id',
    },
  ],
  billable: [
    {
      id: 188990,
      created_at: new Date('2021-07-29T11:05:38.811Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'billable',
      field_name: 'Billable',
      seq: 1,
      type: 'BOOLEAN',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Billable',
      default_value: false,
      options: [],
      org_category_ids: [],
      code: null,
      roles_editable: [
        'FYLER',
        'APPROVER',
        'TRAVEL_ADMIN',
        'VERIFIER',
        'PAYMENT_PROCESSOR',
        'FINANCE',
        'ADMIN',
        'TRAVEL_AGENT',
        'OWNER',
        'AUDITOR',
      ],
      field: 'billable',
    },
  ],
  tax_group_id: [
    {
      id: 193510,
      created_at: new Date('2021-08-17T04:48:57.792Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'tax_group_id',
      field_name: 's',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 's',
      default_value: 'GST',
      options: [
        '23',
        'cgst',
        'Exempt Sales @0.0%',
        'GST',
        'MB - GST/RST on Purchases @12.0%',
        'MB - GST/RST on Sales @12.0%',
        'Sales Tax on Imports @0.0%',
        'sdds',
        'sdds1',
        'Services Standard Purchase',
        'Tax Exempt @0.0%',
        'Tax on Consulting @8.25%',
        'Tax on Goods @8.75%',
        'Tax on Purchases @8.25%',
      ],
      org_category_ids: [
        16558, 16559, 16560, 16561, 16562, 16563, 16564, 16566, 16568, 16569, 16570, 16571, 16572, 16573, 16574, 16575,
      ],
      code: null,
      roles_editable: ['OWNER', 'AUDITOR'],
      field: 'tax_group_id',
    },
  ],
  org_category_id: [
    {
      id: 203055,
      created_at: new Date('2022-03-08T11:37:18.493Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'org_category_id',
      field_name: 'Category',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'Select Category',
      default_value: null,
      options: [],
      org_category_ids: [],
      code: null,
      roles_editable: [
        'FYLER',
        'APPROVER',
        'TRAVEL_ADMIN',
        'VERIFIER',
        'PAYMENT_PROCESSOR',
        'FINANCE',
        'ADMIN',
        'TRAVEL_AGENT',
        'OWNER',
        'AUDITOR',
      ],
      field: 'org_category_id',
    },
  ],
};
