import { Expense } from '../models/expense.model';
import { ApiV2Response } from '../models/v2/api-v2-response.model';

export const expenseV2Data: ApiV2Response<Expense> = {
  count: 1145,
  data: [
    {
      _search_document: null,
      corporate_credit_card_account_number: null,
      credit: false,
      debit: false,
      duplicates: null,
      external_expense_id: null,
      matched_by: null,
      ou_band:
        'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_joining_dt: '2017-07-25',
      ou_level: '123',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_rank: 1121212121,
      ou_sub_department: null,
      ou_title: 'director',
      ou_user_id: 'usvKA4X8Ugcr',
      rp_approved_at: null,
      rp_claim_number: null,
      rp_purpose: null,
      rp_reimbursed_at: null,
      source_account_id: 'acc5APeygFjRd',
      source_account_type: 'PERSONAL_ACCOUNT',
      tg_name: null,
      tg_percentage: null,
      transaction_approvals: null,
      tx_activity_details: null,
      tx_activity_policy_pending: null,
      tx_admin_amount: null,
      tx_amount: null,
      tx_billable: true,
      tx_boolean_column1: null,
      tx_boolean_column10: null,
      tx_boolean_column2: null,
      tx_boolean_column3: null,
      tx_boolean_column4: null,
      tx_boolean_column5: null,
      tx_boolean_column6: null,
      tx_boolean_column7: null,
      tx_boolean_column8: null,
      tx_boolean_column9: null,
      tx_bus_travel_class: null,
      tx_category: null,
      tx_corporate_credit_card_expense_group_id: null,
      tx_cost_center_code: null,
      tx_cost_center_id: 13795,
      tx_cost_center_name: '01test2',
      tx_created_at: new Date('2023-01-24T14:50:29.732687'),
      tx_creator_id: 'ouX8dwsbLCLv',
      tx_currency: null,
      tx_custom_properties: [
        {
          name: 'userlist',
          value: [],
        },
        {
          name: 'User List',
          value: [],
        },
      ],
      tx_decimal_column1: null,
      tx_decimal_column10: null,
      tx_decimal_column2: null,
      tx_decimal_column3: null,
      tx_decimal_column4: null,
      tx_decimal_column5: null,
      tx_decimal_column6: null,
      tx_decimal_column7: null,
      tx_decimal_column8: null,
      tx_decimal_column9: null,
      tx_distance: null,
      tx_distance_unit: 'KM',
      tx_expense_number: 'E/2023/01/T/111',
      tx_external_id: null,
      tx_extracted_data: null,
      tx_file_ids: null,
      tx_flight_journey_travel_class: null,
      tx_flight_return_travel_class: null,
      tx_from_dt: null,
      tx_fyle_category: 'Mileage',
      tx_hotel_is_breakfast_provided: null,
      tx_id: 'txEpXa1cd6oq',
      tx_invoice_number: null,
      tx_is_duplicate_expense: null,
      tx_is_implicit_merge_blocked: false,
      tx_is_split_expense: false,
      tx_location_column1: null,
      tx_location_column10: null,
      tx_location_column2: null,
      tx_location_column3: null,
      tx_location_column4: null,
      tx_location_column5: null,
      tx_location_column6: null,
      tx_location_column7: null,
      tx_location_column8: null,
      tx_location_column9: null,
      tx_locations: [],
      tx_mandatory_fields_present: true,
      tx_manual_flag: false,
      tx_mileage_calculated_amount: null,
      tx_mileage_calculated_distance: null,
      tx_mileage_is_round_trip: null,
      tx_mileage_rate: 10,
      tx_mileage_vehicle_type: 'new policy test',
      tx_num_days: null,
      tx_num_files: 0,
      tx_org_category: 'Mileage',
      tx_org_category_code: null,
      tx_org_category_id: 58348,
      tx_org_user_id: 'ouX8dwsbLCLv',
      tx_orig_amount: null,
      tx_orig_currency: null,
      tx_payment_id: null,
      tx_per_diem_rate_id: null,
      tx_physical_bill: false,
      tx_physical_bill_at: null,
      tx_policy_amount: null,
      tx_policy_flag: false,
      tx_policy_state: null,
      tx_project_code: null,
      tx_project_id: 3943,
      tx_project_name: 'Staging Project',
      tx_purpose: 'test_term',
      tx_receipt_required: null,
      tx_report_id: null,
      tx_reported_at: null,
      tx_risk_state: null,
      tx_skip_reimbursement: false,
      tx_source: 'WEBAPP',
      tx_source_account_id: 'acc5APeygFjRd',
      tx_split_group_id: 'txEpXa1cd6oq',
      tx_split_group_user_amount: null,
      tx_state: 'DRAFT',
      tx_sub_category: '123',
      tx_tax: null,
      tx_tax_amount: null,
      tx_tax_group_id: null,
      tx_text_array_column1: null,
      tx_text_array_column10: null,
      tx_text_array_column2: null,
      tx_text_array_column3: null,
      tx_text_array_column4: null,
      tx_text_array_column5: null,
      tx_text_array_column6: null,
      tx_text_array_column7: null,
      tx_text_array_column8: null,
      tx_text_array_column9: null,
      tx_text_column1: null,
      tx_text_column10: null,
      tx_text_column11: null,
      tx_text_column12: null,
      tx_text_column13: null,
      tx_text_column14: null,
      tx_text_column15: null,
      tx_text_column2: null,
      tx_text_column3: null,
      tx_text_column4: null,
      tx_text_column5: null,
      tx_text_column6: null,
      tx_text_column7: null,
      tx_text_column8: null,
      tx_text_column9: null,
      tx_timestamp_column1: null,
      tx_timestamp_column10: null,
      tx_timestamp_column2: null,
      tx_timestamp_column3: null,
      tx_timestamp_column4: null,
      tx_timestamp_column5: null,
      tx_timestamp_column6: null,
      tx_timestamp_column7: null,
      tx_timestamp_column8: null,
      tx_timestamp_column9: null,
      tx_to_dt: null,
      tx_train_travel_class: null,
      tx_transcribed_data: null,
      tx_transcription_state: null,
      tx_txn_dt: new Date('2023-01-24T11:30:00.000Z'),
      tx_updated_at: new Date('2023-01-24T14:50:29.732687'),
      tx_user_amount: null,
      tx_user_can_delete: true,
      tx_user_reason_for_duplicate_expenses: null,
      tx_user_review_needed: null,
      tx_vendor: null,
      tx_vendor_id: null,
      tx_verification_state: null,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
  ],
  limit: 1,
  offset: 0,
  url: '/v2/expenses',
};

export const expenseV2DataMultiple: ApiV2Response<Expense> = {
  count: 2,
  data: [
    {
      _search_document:
        "'1':45 '344':1 '344.00':2 'a':12,18,24,30 'abhishek':36 'ajain@fyle.in':38 'asdfg':46 'australian':41 'business':15,21,27,33 'complete':4 'director':10 'e/2023/01/t/99':7 'indeed':17,23,29,35 'inr':3,8 'jain':37 'long':14,20,26,32 'mumbai':11 'office':43 'project':44 'software':9,39,40 'taxation':42 'term':6 'test':5 'unit':16,22,28,34 'very':13,19,25,31",
      corporate_credit_card_account_number: null,
      credit: false,
      debit: false,
      duplicates: null,
      external_expense_id: null,
      matched_by: null,
      ou_band:
        'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_joining_dt: '2017-07-25',
      ou_level: '123',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_rank: 1121212121,
      ou_sub_department: null,
      ou_title: 'director',
      ou_user_id: 'usvKA4X8Ugcr',
      rp_approved_at: null,
      rp_claim_number: null,
      rp_purpose: null,
      rp_reimbursed_at: null,
      source_account_id: 'acc5APeygFjRd',
      source_account_type: 'PERSONAL_ACCOUNT',
      tg_name: 'cgst',
      tg_percentage: 0.18,
      transaction_approvals: null,
      tx_activity_details: null,
      tx_activity_policy_pending: null,
      tx_admin_amount: null,
      tx_amount: 344,
      tx_billable: false,
      tx_boolean_column1: null,
      tx_boolean_column10: null,
      tx_boolean_column2: null,
      tx_boolean_column3: null,
      tx_boolean_column4: null,
      tx_boolean_column5: null,
      tx_boolean_column6: null,
      tx_boolean_column7: null,
      tx_boolean_column8: null,
      tx_boolean_column9: null,
      tx_bus_travel_class: null,
      tx_category: null,
      tx_corporate_credit_card_expense_group_id: null,
      tx_cost_center_code: null,
      tx_cost_center_id: 13795,
      tx_cost_center_name: '01test2',
      tx_created_at: new Date('2023-01-24T09:54:24.186607'),
      tx_creator_id: 'ouX8dwsbLCLv',
      tx_currency: 'INR',
      tx_custom_properties: [
        {
          name: 'userlist',
          value: null,
        },
        {
          name: 'User List',
          value: null,
        },
      ],
      tx_decimal_column1: null,
      tx_decimal_column10: null,
      tx_decimal_column2: null,
      tx_decimal_column3: null,
      tx_decimal_column4: null,
      tx_decimal_column5: null,
      tx_decimal_column6: null,
      tx_decimal_column7: null,
      tx_decimal_column8: null,
      tx_decimal_column9: null,
      tx_distance: null,
      tx_distance_unit: null,
      tx_expense_number: 'E/2023/01/T/99',
      tx_external_id: null,
      tx_extracted_data: {
        amount: null,
        category: 'Software',
        currency: 'INR',
        date: null,
        invoice_dt: null,
        vendor: null,
      },
      tx_file_ids: ['fiM5z7LzzjJy', 'fiM5z7LzzjJy'],
      tx_flight_journey_travel_class: null,
      tx_flight_return_travel_class: null,
      tx_from_dt: null,
      tx_fyle_category: null,
      tx_hotel_is_breakfast_provided: null,
      tx_id: 'tx3qHxFNgRcZ',
      tx_invoice_number: null,
      tx_is_duplicate_expense: null,
      tx_is_implicit_merge_blocked: false,
      tx_is_split_expense: false,
      tx_location_column1: null,
      tx_location_column10: null,
      tx_location_column2: null,
      tx_location_column3: null,
      tx_location_column4: null,
      tx_location_column5: null,
      tx_location_column6: null,
      tx_location_column7: null,
      tx_location_column8: null,
      tx_location_column9: null,
      tx_locations: [],
      tx_mandatory_fields_present: true,
      tx_manual_flag: false,
      tx_mileage_calculated_amount: null,
      tx_mileage_calculated_distance: null,
      tx_mileage_is_round_trip: null,
      tx_mileage_rate: null,
      tx_mileage_vehicle_type: null,
      tx_num_days: null,
      tx_num_files: 1,
      tx_org_category: 'Software',
      tx_org_category_code: '117',
      tx_org_category_id: 16577,
      tx_org_user_id: 'ouX8dwsbLCLv',
      tx_orig_amount: null,
      tx_orig_currency: null,
      tx_payment_id: 'pay43PWwwA2gV',
      tx_per_diem_rate_id: null,
      tx_physical_bill: false,
      tx_physical_bill_at: null,
      tx_policy_amount: null,
      tx_policy_flag: false,
      tx_policy_state: null,
      tx_project_code: null,
      tx_project_id: 316443,
      tx_project_name: 'Project 1 / asdfg',
      tx_purpose: 'test_term',
      tx_receipt_required: null,
      tx_report_id: null,
      tx_reported_at: null,
      tx_risk_state: null,
      tx_skip_reimbursement: false,
      tx_source: 'MOBILE_DASHCAM_SINGLE',
      tx_source_account_id: 'acc5APeygFjRd',
      tx_split_group_id: 'tx3qHxFNgRcZ',
      tx_split_group_user_amount: 344,
      tx_state: 'COMPLETE',
      tx_sub_category: 'Software',
      tx_tax: 52.47,
      tx_tax_amount: 52.47,
      tx_tax_group_id: 'tg3iWuqWhfzB',
      tx_text_array_column1: null,
      tx_text_array_column10: null,
      tx_text_array_column2: null,
      tx_text_array_column3: null,
      tx_text_array_column4: null,
      tx_text_array_column5: null,
      tx_text_array_column6: null,
      tx_text_array_column7: null,
      tx_text_array_column8: null,
      tx_text_array_column9: null,
      tx_text_column1: null,
      tx_text_column10: null,
      tx_text_column11: null,
      tx_text_column12: null,
      tx_text_column13: null,
      tx_text_column14: null,
      tx_text_column15: null,
      tx_text_column2: null,
      tx_text_column3: null,
      tx_text_column4: null,
      tx_text_column5: null,
      tx_text_column6: null,
      tx_text_column7: null,
      tx_text_column8: null,
      tx_text_column9: null,
      tx_timestamp_column1: null,
      tx_timestamp_column10: null,
      tx_timestamp_column2: null,
      tx_timestamp_column3: null,
      tx_timestamp_column4: null,
      tx_timestamp_column5: null,
      tx_timestamp_column6: null,
      tx_timestamp_column7: null,
      tx_timestamp_column8: null,
      tx_timestamp_column9: null,
      tx_to_dt: null,
      tx_train_travel_class: null,
      tx_transcribed_data: null,
      tx_transcription_state: null,
      tx_txn_dt: new Date('2023-01-24T17:00:00'),
      tx_updated_at: new Date('2023-01-30T09:08:35.810575'),
      tx_user_amount: 344,
      tx_user_can_delete: true,
      tx_user_reason_for_duplicate_expenses: null,
      tx_user_review_needed: null,
      tx_vendor: 'Australian Taxation Office',
      tx_vendor_id: 28860,
      tx_verification_state: null,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
    {
      _search_document:
        "'1':1,8 '1.00':2 'a':13,19,25,31 'abhishek':37 'ajain@fyle.in':39 'business':16,22,28,34 'complete':4 'director':11 'e/2023/01/t/90':7 'indeed':18,24,30,36 'inr':3,9 'jain':38 'long':15,21,27,33 'mumbai':12 'new':42,43,44 'others':10,40,41 'project':46 'staging':45 'term':6 'test':5 'unit':17,23,29,35 'very':14,20,26,32",
      corporate_credit_card_account_number: null,
      credit: false,
      debit: false,
      duplicates: null,
      external_expense_id: null,
      matched_by: null,
      ou_band:
        'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
      ou_business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      ou_department: '0000000',
      ou_department_id: 'deptpmQ0SsMO0S',
      ou_employee_id: '',
      ou_id: 'ouX8dwsbLCLv',
      ou_joining_dt: '2017-07-25',
      ou_level: '123',
      ou_location: 'Mumbai',
      ou_mobile: '123456',
      ou_org_id: 'orNVthTo2Zyo',
      ou_org_name: 'Staging Loaded',
      ou_rank: 1121212121,
      ou_sub_department: null,
      ou_title: 'director',
      ou_user_id: 'usvKA4X8Ugcr',
      rp_approved_at: null,
      rp_claim_number: null,
      rp_purpose: null,
      rp_reimbursed_at: null,
      source_account_id: 'acc5APeygFjRd',
      source_account_type: 'PERSONAL_ACCOUNT',
      tg_name: 'cgst',
      tg_percentage: 0.18,
      transaction_approvals: null,
      tx_activity_details: null,
      tx_activity_policy_pending: null,
      tx_admin_amount: null,
      tx_amount: 1,
      tx_billable: false,
      tx_boolean_column1: null,
      tx_boolean_column10: null,
      tx_boolean_column2: null,
      tx_boolean_column3: null,
      tx_boolean_column4: null,
      tx_boolean_column5: null,
      tx_boolean_column6: null,
      tx_boolean_column7: null,
      tx_boolean_column8: null,
      tx_boolean_column9: null,
      tx_bus_travel_class: null,
      tx_category: null,
      tx_corporate_credit_card_expense_group_id: null,
      tx_cost_center_code: null,
      tx_cost_center_id: 13795,
      tx_cost_center_name: '01test2',
      tx_created_at: new Date('2023-01-23T08:43:12.290706'),
      tx_creator_id: 'ouX8dwsbLCLv',
      tx_currency: 'INR',
      tx_custom_properties: [
        {
          name: 'userlist',
          value: null,
        },
        {
          name: 'User List',
          value: null,
        },
      ],
      tx_decimal_column1: null,
      tx_decimal_column10: null,
      tx_decimal_column2: null,
      tx_decimal_column3: null,
      tx_decimal_column4: null,
      tx_decimal_column5: null,
      tx_decimal_column6: null,
      tx_decimal_column7: null,
      tx_decimal_column8: null,
      tx_decimal_column9: null,
      tx_distance: null,
      tx_distance_unit: null,
      tx_expense_number: 'E/2023/01/T/90',
      tx_external_id: null,
      tx_extracted_data: {
        amount: 1,
        category: 'Others',
        currency: 'INR',
        date: null,
        invoice_dt: null,
        vendor: null,
      },
      tx_file_ids: ['fiy1ZupY0Sl0', 'fiy1ZupY0Sl0'],
      tx_flight_journey_travel_class: null,
      tx_flight_return_travel_class: null,
      tx_from_dt: null,
      tx_fyle_category: null,
      tx_hotel_is_breakfast_provided: null,
      tx_id: 'txWphhAUZbq7',
      tx_invoice_number: null,
      tx_is_duplicate_expense: null,
      tx_is_implicit_merge_blocked: false,
      tx_is_split_expense: false,
      tx_location_column1: null,
      tx_location_column10: null,
      tx_location_column2: null,
      tx_location_column3: null,
      tx_location_column4: null,
      tx_location_column5: null,
      tx_location_column6: null,
      tx_location_column7: null,
      tx_location_column8: null,
      tx_location_column9: null,
      tx_locations: [],
      tx_mandatory_fields_present: true,
      tx_manual_flag: false,
      tx_mileage_calculated_amount: null,
      tx_mileage_calculated_distance: null,
      tx_mileage_is_round_trip: null,
      tx_mileage_rate: null,
      tx_mileage_vehicle_type: null,
      tx_num_days: null,
      tx_num_files: 1,
      tx_org_category: 'Others',
      tx_org_category_code: '7028 Ministry Expense · Conference · Freedom Income · Freedom Book',
      tx_org_category_id: 16564,
      tx_org_user_id: 'ouX8dwsbLCLv',
      tx_orig_amount: null,
      tx_orig_currency: null,
      tx_payment_id: 'payPUt2DnqLZT',
      tx_per_diem_rate_id: null,
      tx_physical_bill: false,
      tx_physical_bill_at: null,
      tx_policy_amount: null,
      tx_policy_flag: false,
      tx_policy_state: null,
      tx_project_code: null,
      tx_project_id: 3943,
      tx_project_name: 'Staging Project',
      tx_purpose: 'test_term',
      tx_receipt_required: null,
      tx_report_id: null,
      tx_reported_at: null,
      tx_risk_state: null,
      tx_skip_reimbursement: false,
      tx_source: 'MOBILE_DASHCAM_SINGLE',
      tx_source_account_id: 'acc5APeygFjRd',
      tx_split_group_id: 'txWphhAUZbq7',
      tx_split_group_user_amount: 1,
      tx_state: 'COMPLETE',
      tx_sub_category: 'Others',
      tx_tax: null,
      tx_tax_amount: null,
      tx_tax_group_id: 'tg3iWuqWhfzB',
      tx_text_array_column1: null,
      tx_text_array_column10: null,
      tx_text_array_column2: null,
      tx_text_array_column3: null,
      tx_text_array_column4: null,
      tx_text_array_column5: null,
      tx_text_array_column6: null,
      tx_text_array_column7: null,
      tx_text_array_column8: null,
      tx_text_array_column9: null,
      tx_text_column1: null,
      tx_text_column10: null,
      tx_text_column11: null,
      tx_text_column12: null,
      tx_text_column13: null,
      tx_text_column14: null,
      tx_text_column15: null,
      tx_text_column2: null,
      tx_text_column3: null,
      tx_text_column4: null,
      tx_text_column5: null,
      tx_text_column6: null,
      tx_text_column7: null,
      tx_text_column8: null,
      tx_text_column9: null,
      tx_timestamp_column1: null,
      tx_timestamp_column10: null,
      tx_timestamp_column2: null,
      tx_timestamp_column3: null,
      tx_timestamp_column4: null,
      tx_timestamp_column5: null,
      tx_timestamp_column6: null,
      tx_timestamp_column7: null,
      tx_timestamp_column8: null,
      tx_timestamp_column9: null,
      tx_to_dt: null,
      tx_train_travel_class: null,
      tx_transcribed_data: null,
      tx_transcription_state: null,
      tx_txn_dt: new Date('2023-01-23T17:00:00'),
      tx_updated_at: new Date('2023-01-30T09:09:03.961227'),
      tx_user_amount: 1,
      tx_user_can_delete: true,
      tx_user_reason_for_duplicate_expenses: null,
      tx_user_review_needed: null,
      tx_vendor: 'New new new',
      tx_vendor_id: 28828,
      tx_verification_state: null,
      us_email: 'ajain@fyle.in',
      us_full_name: 'Abhishek Jain',
    },
  ],
  limit: 2,
  offset: 0,
  url: '/v2/expenses',
};
