import { Expense } from '../models/expense.model';

export const apiExpenseRes: Expense[] = [
  {
    tx_risk_state: null,
    tx_is_duplicate_expense: null,
    tx_duplicates: null,
    ou_org_name: 'Fyle Staging',
    tx_id: 'tx3nHShG60zq',
    tx_org_user_id: 'ousFT9HJe1yW',
    tx_created_at: new Date('2021-07-29T11:45:30.513Z'),
    tx_receipt_required: false,
    tx_user_can_delete: true,
    tx_txn_dt: new Date('2021-07-29T06:30:00.000Z'),
    tx_category: null,
    tx_amount: 3,
    tx_user_amount: 3,
    tx_policy_amount: null,
    tx_admin_amount: null,
    tx_tax: 0.32,
    tx_tax_amount: 0.32,
    tx_tax_group_id: 'tgFDWBpJL3vy',
    tg_name: 'bnb',
    tg_percentage: 0.12,
    tx_currency: 'INR',
    tx_report_id: 'rp1xCiq5WA1R',
    tx_reported_at: '2022-10-19T08:25:13.993Z',
    tx_state: 'APPROVED',
    tx_num_files: 0,
    tx_invoice_number: null,
    tx_purpose: 'Others',
    tx_source: 'WEBAPP',
    tx_billable: false,
    tx_orig_amount: null,
    tx_orig_currency: null,
    tx_project_id: 3812,
    tx_project_name: '1212',
    tx_project_code: null,
    tx_skip_reimbursement: false,
    tx_creator_id: 'ousFT9HJe1yW',
    tx_user_reason_for_duplicate_expenses: null,
    tx_external_id: null,
    tx_cost_center_name: '213',
    tx_cost_center_code: 'q2e3',
    tx_cost_center_id: 12488,
    tx_source_account_id: 'accDDeaVIs6p6',
    tx_transcription_state: null,
    tx_verification_state: 'VERIFIED',
    tx_physical_bill: null,
    tx_physical_bill_at: null,
    tx_policy_state: null,
    tx_manual_flag: null,
    tx_policy_flag: false,
    rp_purpose: '#1:  Jul 2021',
    rp_approved_at: '2022-11-03T05:47:51.678Z',
    rp_reimbursed_at: null,
    rp_claim_number: 'C/2022/10/R/6',
    ou_id: 'ousFT9HJe1yW',
    ou_org_id: 'orrjqbDbeP9p',
    ou_user_id: 'usrEwaK89uND',
    ou_employee_id: null,
    ou_location: 'thane',
    ou_level: null,
    ou_band: null,
    ou_rank: null,
    ou_business_unit: null,
    ou_department_id: null,
    ou_department: null,
    ou_title: 'Miss',
    ou_mobile: null,
    ou_sub_department: null,
    ou_joining_dt: '2022-08-04T00:00:00.000+0000',
    us_full_name: 'Fyler Vaishnavi',
    us_email: 'vaishnavi.mohan+fyler@fyle.in',
    tx_vendor: 'ramdev baba',
    tx_vendor_id: 26665,
    tx_platform_vendor: null,
    tx_platform_vendor_id: null,
    source_account_type: 'PERSONAL_ACCOUNT',
    source_account_id: 'accDDeaVIs6p6',
    tx_org_category: '0 aniruddha test cat',
    tx_sub_category: '0 aniruddha test cat',
    tx_fyle_category: null,
    tx_org_category_code: '13',
    tx_org_category_id: 207484,
    external_expense_id: null,
    tx_expense_number: 'E/2021/07/T/115',
    tx_corporate_credit_card_expense_group_id: null,
    tx_split_group_id: 'tx3nHShG60zq',
    tx_split_group_user_amount: 31,
    tx_extracted_data: null,
    tx_transcribed_data: null,
    tx_user_review_needed: null,
    tx_mandatory_fields_present: true,
    is_test_call: null,
    tx_distance: null,
    tx_distance_unit: null,
    tx_from_dt: null,
    tx_to_dt: null,
    tx_num_days: null,
    tx_mileage_calculated_distance: null,
    tx_mileage_calculated_amount: null,
    tx_mileage_vehicle_type: null,
    tx_mileage_rate: null,
    tx_mileage_is_round_trip: null,
    tx_hotel_is_breakfast_provided: false,
    tx_flight_journey_travel_class: null,
    tx_flight_return_travel_class: null,
    tx_train_travel_class: null,
    tx_bus_travel_class: null,
    tx_taxi_travel_class: null,
    tx_per_diem_rate_id: null,
    tx_activity_policy_pending: null,
    tx_activity_details: null,
    tx_locations: [],
    tx_custom_properties: [
      {
        name: 'status',
        value: '',
      },
      {
        name: 'Multi Type',
        value: ['Multi 1'],
      },
      {
        name: 'name',
        value: null,
      },
    ],
    tx_is_implicit_merge_blocked: false,
  },
];
