import { ExpenseFieldsMap } from '../models/v1/expense-fields-map.model';
import { ExpenseFieldsObj } from '../models/v1/expense-fields-obj.model';

export const txnFieldsData: Partial<ExpenseFieldsObj> = {
  purpose: {
    id: 22,
    created_at: new Date(new Date('2018-01-31T23:50:27.221Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'purpose',
    field_name: 'Purpose_display_name',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'E.g. Client Meetin',
    default_value: 'test_term',
    options: ['test_term', 'purpose test', 'lala lala la', 'test again'],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN', 'FYLER'],
    field: 'purpose',
  },
  txn_dt: {
    id: 29,
    created_at: new Date(new Date('2018-01-31T23:50:27.221Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'txn_dt',
    field_name: 'Date of Spenrt',
    seq: 1,
    type: 'DATE',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    placeholder: 'Select dt',
    default_value: null,
    options: [],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'VERIFIER'],
    field: 'txn_dt',
  },
  tax_group_id: {
    id: 193510,
    created_at: new Date(new Date('2021-08-17T04:48:57.792Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'tax_group_id',
    field_name: 's',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 's',
    default_value: 'GST',
    options: [
      '23',
      'cgst',
      'Exempt Sales @0.0%',
      'GST',
      'MB - GST/RST on Purchases @12.0%',
      'MB - GST/RST on Sales @12.0%',
      'Sales Tax on Imports @0.0%',
      'sdds',
      'sdds1',
      'Services Standard Purchase',
      'Tax Exempt @0.0%',
      'Tax on Consulting @8.25%',
      'Tax on Goods @8.75%',
      'Tax on Purchases @8.25%',
    ],
    org_category_ids: [
      16558, 16559, 16560, 16561, 16562, 16563, 16564, 16566, 16568, 16569, 16570, 16571, 16572, 16573, 16574, 16575,
    ],
    code: null,
    roles_editable: ['OWNER', 'AUDITOR'],
    field: 'tax_group_id',
  },
  org_category_id: {
    id: 203055,
    created_at: new Date(new Date('2022-03-08T11:37:18.493Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'org_category_id',
    field_name: 'Category',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Select Category',
    default_value: null,
    options: [],
    org_category_ids: [],
    code: null,
    roles_editable: [
      'FYLER',
      'APPROVER',
      'TRAVEL_ADMIN',
      'VERIFIER',
      'PAYMENT_PROCESSOR',
      'FINANCE',
      'ADMIN',
      'TRAVEL_AGENT',
      'OWNER',
      'AUDITOR',
    ],
    field: 'org_category_id',
  },
};

export const txnFieldsData2: Partial<ExpenseFieldsObj> = {
  ...txnFieldsData,
  vendor_id: {
    code: '1234',
    column_name: 'vendor_id',
    created_at: new Date(new Date('2022-03-08T11:37:18.493Z')),
    default_value: null,
    is_custom: false,
    is_mandatory: true,
    is_enabled: false,
    org_category_ids: [],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'Select Vendor',
    seq: 0,
    type: 'SELECT',
    updated_at: new Date(new Date('2022-03-08T11:37:18.493Z')),
    options: ['vendor_1', 'vendor_2'],
  },
  project_id: {
    code: '4567',
    column_name: 'project_id',
    created_at: undefined,
    default_value: '',
    is_custom: false,
    is_mandatory: true,
    is_enabled: false,
    org_category_ids: [],
    org_id: '',
    placeholder: '',
    seq: 0,
    type: '',
    updated_at: undefined,
  },
  bus_travel_class: {
    id: 2,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'bus_travel_class',
    field_name: 'Bus travel Class\\/',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'TEST',
    default_value: null,
    options: ['eco', 'business', 'jhgjg'],
    org_category_ids: [
      17283, 49621, 83060, 87409, 87441, 101148, 101149, 101151, 102676, 102757, 105705, 106574, 110168, 110597, 114563,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
  },
  txn_dt: {
    id: 29,
    created_at: new Date(new Date('2018-01-31T23:50:27.221Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'txn_dt',
    field_name: 'Date of Spenrt',
    seq: 1,
    type: 'DATE',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Select dt',
    default_value: null,
    options: [],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'VERIFIER'],
    field: 'txn_dt',
  },
  distance: {
    id: 6,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'distance',
    field_name: 'Distance',
    seq: 1,
    type: 'NUMBER',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Enter Distance',
    default_value: null,
    options: [],
    org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
  },
};

export const txnFieldsData3: Partial<ExpenseFieldsObj> = {
  ...txnFieldsData2,
  cost_center_id: {
    id: 3,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'cost_center_id',
    field_name: 'Cost Center',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Select Cost Center',
    default_value: null,
    options: [],
    org_category_ids: [
      16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
    ],
    code: null,
    roles_editable: [
      'TRAVEL_ADMIN',
      'PAYMENT_PROCESSOR',
      'VERIFIER',
      'FINANCE',
      'ADMIN',
      'FYLER',
      'APPROVER',
      'TRAVEL_AGENT',
    ],
    field: 'cost_center_id',
  },
};

export const expenseFieldsMapResponse: Partial<ExpenseFieldsMap> = {
  purpose: [
    {
      id: 22,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'purpose',
      field_name: 'Purpose_display_name',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'E.g. Client Meetin',
      default_value: 'test_term',
      options: ['test_term', 'purpose test', 'lala lala la', 'test again'],
      org_category_ids: [
        16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
      ],
      code: null,
      roles_editable: ['APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN', 'FYLER'],
      field: 'purpose',
    },
  ],
  txn_dt: [
    {
      id: 29,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'txn_dt',
      field_name: 'Date of Spenrt',
      seq: 1,
      type: 'DATE',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select dt',
      default_value: null,
      options: [],
      org_category_ids: [
        16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'VERIFIER'],
      field: 'txn_dt',
    },
  ],
  vendor_id: [
    {
      id: 31,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'vendor_id',
      field_name: 'Merchant',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'E.g. Uber',
      default_value: '',
      options: [
        'Australian Taxation Office',
        'expensify@thatharmansingh.com - HoneComb Aus',
        'Nilesh As Vendor',
        'Nilesh Aus Vendor',
        'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
        'Uber',
        'Uber BV',
        'YEHUDAHALEVI16',
        'New new new',
      ],
      org_category_ids: [
        16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
      field: 'vendor_id',
    },
  ],
  org_category_id: [
    {
      id: 203055,
      created_at: new Date('2022-03-08T11:37:18.493Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'org_category_id',
      field_name: 'Category',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'Select Category',
      default_value: null,
      options: [],
      org_category_ids: [],
      code: null,
      roles_editable: [
        'FYLER',
        'APPROVER',
        'TRAVEL_ADMIN',
        'VERIFIER',
        'PAYMENT_PROCESSOR',
        'FINANCE',
        'ADMIN',
        'TRAVEL_AGENT',
        'OWNER',
        'AUDITOR',
      ],
      field: 'org_category_id',
    },
  ],
};

export const expenseFieldsMapResponse2: Partial<ExpenseFieldsMap> = {
  bus_travel_class: [
    {
      id: 2,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'bus_travel_class',
      field_name: 'Bus travel Class\\/',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'TEST',
      default_value: null,
      options: ['eco', 'business', 'jhgjg'],
      org_category_ids: [
        17283, 49621, 83060, 87409, 87441, 101148, 101149, 101151, 102676, 102757, 105705, 106574, 110168, 110597,
        114563,
      ],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
  cost_center_id: [
    {
      id: 3,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'cost_center_id',
      field_name: 'Cost Center',
      seq: 1,
      type: 'SELECT',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Select Cost Center',
      default_value: null,
      options: [],
      org_category_ids: [
        16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
      ],
      code: null,
      roles_editable: [
        'TRAVEL_ADMIN',
        'PAYMENT_PROCESSOR',
        'VERIFIER',
        'FINANCE',
        'ADMIN',
        'FYLER',
        'APPROVER',
        'TRAVEL_AGENT',
      ],
      field: 'cost_center_id',
    },
  ],
  distance: [
    {
      id: 6,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'distance',
      field_name: 'Distance',
      seq: 1,
      type: 'NUMBER',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Enter Distance',
      default_value: null,
      options: [],
      org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
    {
      id: 7,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'distance',
      field_name: 'Distance 2',
      seq: 2,
      type: 'NUMBER',
      is_custom: false,
      is_enabled: true,
      is_mandatory: false,
      placeholder: 'Enter Distance',
      default_value: null,
      options: [],
      org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
};

export const expenseFieldsMapResponse3 = {
  distance: [
    {
      id: 6,
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      created_by: {
        user_id: 'SYSTEM',
        org_user_id: null,
        org_id: null,
        roles: [],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: null,
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: null,
      },
      updated_at: new Date('2023-01-13T11:45:00.655Z'),
      updated_by: {
        user_id: 'usEyHSLj6aHw',
        org_user_id: 'ou9KVQTZWIFk',
        org_id: 'orNVthTo2Zyo',
        roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
        scopes: [],
        allowed_cidrs: [],
        cluster_domain: '"https://staging.fyle.tech"',
        proxy_org_user_id: null,
        tpa_id: null,
        tpa_name: null,
        name: 'ou9KVQTZWIFk',
      },
      org_id: 'orNVthTo2Zyo',
      column_name: 'distance',
      field_name: 'Distance',
      seq: 1,
      type: 'NUMBER',
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      placeholder: 'Enter Distance',
      default_value: null,
      options: [],
      org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
      code: null,
      roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    },
  ],
};

export const expenseFieldsMapResponse4 = {
  ...expenseFieldsMapResponse,
  ...expenseFieldsMapResponse2,
  project_id: [
    {
      code: 'PID001',
      column_name: 'project_id',
      created_at: new Date('2018-01-31T23:50:27.221Z'),
      default_value: 'Default Value',
      field_name: 'Project ID',
      id: 1,
      is_custom: false,
      is_enabled: true,
      is_mandatory: true,
      options: ['Option 1', 'Option 2', 'Option 3'],
      org_category_ids: [1, 2, 3],
      org_id: 'ORG001',
      placeholder: 'Enter Project ID',
      roles_editable: ['Role 1', 'Role 2'],
      seq: 1,
      type: 'text',
      updated_at: new Date(),
      parent_field_id: 123,
      field: 'Project',
      input_type: 'input',
    },
  ],
};

export const txnFieldsMap2: Partial<ExpenseFieldsObj> = {
  purpose: {
    id: 22,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'purpose',
    field_name: 'Purpose_display_name',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'E.g. Client Meetin',
    default_value: 'test_term',
    options: ['test_term', 'purpose test', 'lala lala la', 'test again'],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN', 'FYLER'],
    field: 'purpose',
  },
  txn_dt: {
    id: 29,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'txn_dt',
    field_name: 'Date of Spenrt',
    seq: 1,
    type: 'DATE',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    placeholder: 'Select dt',
    default_value: null,
    options: [],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'VERIFIER'],
    field: 'txn_dt',
  },
  vendor_id: {
    id: 31,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'vendor_id',
    field_name: 'Merchant',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'E.g. Uber',
    default_value: '',
    options: [
      'Australian Taxation Office',
      'expensify@thatharmansingh.com - HoneComb Aus',
      'Nilesh As Vendor',
      'Nilesh Aus Vendor',
      'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
      'Uber',
      'Uber BV',
      'YEHUDAHALEVI16',
      'New new new',
    ],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    field: 'vendor_id',
  },
  org_category_id: {
    id: 203055,
    created_at: new Date('2022-03-08T11:37:18.493Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'org_category_id',
    field_name: 'Category',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Select Category',
    default_value: null,
    options: [],
    org_category_ids: [],
    code: null,
    roles_editable: [
      'FYLER',
      'APPROVER',
      'TRAVEL_ADMIN',
      'VERIFIER',
      'PAYMENT_PROCESSOR',
      'FINANCE',
      'ADMIN',
      'TRAVEL_AGENT',
      'OWNER',
      'AUDITOR',
    ],
    field: 'org_category_id',
  },
};

export const txnFieldsFlightData: Partial<ExpenseFieldsObj> = {
  ...txnFieldsData,
  vendor_id: {
    code: '1234',
    column_name: 'vendor_id',
    created_at: new Date(new Date('2022-03-08T11:37:18.493Z')),
    default_value: null,
    is_custom: false,
    is_mandatory: true,
    is_enabled: false,
    org_category_ids: [],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'Select Vendor',
    seq: 0,
    type: 'SELECT',
    updated_at: new Date(new Date('2022-03-08T11:37:18.493Z')),
    options: ['vendor_1', 'vendor_2'],
  },
  project_id: {
    code: '4567',
    column_name: 'project_id',
    created_at: undefined,
    default_value: '',
    is_custom: false,
    is_mandatory: true,
    is_enabled: false,
    org_category_ids: [],
    org_id: '',
    placeholder: '',
    seq: 0,
    type: '',
    updated_at: undefined,
  },
  bus_travel_class: {
    id: 2,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'bus_travel_class',
    field_name: 'Bus travel Class\\/',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'TEST',
    default_value: null,
    options: ['eco', 'business', 'jhgjg'],
    org_category_ids: [
      17283, 49621, 83060, 87409, 87441, 101148, 101149, 101151, 102676, 102757, 105705, 106574, 110168, 110597, 114563,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
  },
  txn_dt: {
    id: 29,
    created_at: new Date(new Date('2018-01-31T23:50:27.221Z')),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date(new Date('2023-01-13T11:45:00.655Z')),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'txn_dt',
    field_name: 'Date of Spenrt',
    seq: 1,
    type: 'DATE',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Select dt',
    default_value: null,
    options: [],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'VERIFIER'],
    field: 'txn_dt',
  },
  distance: {
    id: 6,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'distance',
    field_name: 'Distance',
    seq: 1,
    type: 'NUMBER',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Enter Distance',
    default_value: null,
    options: [],
    org_category_ids: [16565, 52525, 58348, 58349, 115914, 115970, 117013, 123032, 197625],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
  },
  flight_journey_travel_class: {
    id: 2,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'flight_journey_travel_class',
    field_name: 'Flight Travel Class\\/',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'TEST',
    default_value: null,
    options: ['economy', 'business'],
    org_category_ids: [
      17283, 49621, 83060, 87409, 87441, 101148, 101149, 101151, 102676, 102757, 105705, 106574, 110168, 110597, 114563,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
  },
};
