import { ExpenseFieldsObj } from '../models/v1/expense-fields-obj.model';

export const expenseFieldObjData: Partial<ExpenseFieldsObj> = {
  purpose: {
    id: 22,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'purpose',
    field_name: 'Purpose_display_name',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'E.g. Client Meetin',
    default_value: 'test_term',
    options: ['test_term', 'purpose test', 'lala lala la', 'test again'],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN', 'FYLER'],
    field: 'purpose',
  },
  txn_dt: {
    id: 29,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'txn_dt',
    field_name: 'Date of Spenrt',
    seq: 1,
    type: 'DATE',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    placeholder: 'Select dt',
    default_value: null,
    options: [],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16565, 16566, 16567, 16568, 16569, 16570, 16571, 16572,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'VERIFIER'],
    field: 'txn_dt',
  },
  vendor_id: {
    id: 31,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'vendor_id',
    field_name: 'Merchant',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'E.g. Uber',
    default_value: '',
    options: [
      'Australian Taxation Office',
      'expensify@thatharmansingh.com - HoneComb Aus',
      'Nilesh As Vendor',
      'Nilesh Aus Vendor',
      'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
      'Uber',
      'Uber BV',
      'YEHUDAHALEVI16',
      'New new new',
    ],
    org_category_ids: [
      16557, 16558, 16559, 16560, 16561, 16562, 16563, 16564, 16566, 16567, 16568, 16569, 16570, 16571, 16572, 16573,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
    field: 'vendor_id',
  },
  org_category_id: {
    id: 203055,
    created_at: new Date('2022-03-08T11:37:18.493Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'org_category_id',
    field_name: 'Category',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    placeholder: 'Select Category',
    default_value: null,
    options: [],
    org_category_ids: [],
    code: null,
    roles_editable: [
      'FYLER',
      'APPROVER',
      'TRAVEL_ADMIN',
      'VERIFIER',
      'PAYMENT_PROCESSOR',
      'FINANCE',
      'ADMIN',
      'TRAVEL_AGENT',
      'OWNER',
      'AUDITOR',
    ],
    field: 'org_category_id',
  },
};

export const txnFieldData: Partial<ExpenseFieldsObj> = {
  purpose: {
    id: 22,
    code: null,
    column_name: 'purpose',
    created_at: new Date('2018-01-31T23:50:27.221000+00:00'),
    default_value: 'test_term',
    field_name: 'Purpose_display_name',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    options: [],
    org_category_ids: [16557, 16558, 16559, 16560, 16561],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'E.g. Client Meetin',
    seq: 1,
    type: 'SELECT',
    updated_at: new Date('2023-05-25T12:09:02.814657+00:00'),
    parent_field_id: null,
    field: 'purpose',
  },
  txn_dt: {
    id: 29,
    code: null,
    column_name: 'txn_dt',
    created_at: new Date('2018-01-31T23:50:27.221000+00:00'),
    default_value: null,
    field_name: 'something',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    options: [],
    org_category_ids: [16557, 16558, 16559, 16560, 16561],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'something',
    seq: 1,
    type: 'DATE',
    updated_at: new Date('2023-06-13T10:58:05.362134+00:00'),
    parent_field_id: null,
    field: 'txn_dt',
  },
  vendor_id: {
    id: 31,
    code: null,
    column_name: 'vendor_id',
    created_at: new Date('2018-01-31T23:50:27.221000+00:00'),
    default_value: '',
    field_name: 'Merchant',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    options: [],
    org_category_ids: [],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'E.g. Uber',
    seq: 1,
    type: 'SELECT',
    updated_at: new Date('2023-05-25T12:09:02.814657+00:00'),
    parent_field_id: null,
    field: 'vendor_id',
  },
  cost_center_id: {
    id: 3,
    code: null,
    column_name: 'cost_center_id',
    created_at: new Date('2018-01-31T23:50:27.221000+00:00'),
    default_value: null,
    field_name: 'Location',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    options: [],
    org_category_ids: [16557, 16558, 16559, 16560, 16561],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'Select Cost Center',
    seq: 1,
    type: 'SELECT',
    updated_at: new Date('2023-05-25T12:09:02.814657+00:00'),
    parent_field_id: null,
    field: 'cost_center_id',
  },
  project_id: {
    id: 184692,
    code: null,
    column_name: 'project_id',
    created_at: new Date('2021-07-28T08:48:55.152191+00:00'),
    default_value: null,
    field_name: 'Project',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    options: [],
    org_category_ids: [16557, 16558, 16559, 16560, 16561],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'Select Aircraft No',
    seq: 1,
    type: 'SELECT',
    updated_at: new Date('2023-05-29T19:18:08.730586+00:00'),
    parent_field_id: null,
    field: 'project_id',
  },
  billable: {
    id: 188990,
    code: null,
    column_name: 'billable',
    created_at: new Date('2021-07-29T11:05:38.811564+00:00'),
    default_value: false,
    field_name: 'Billable',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    options: [],
    org_category_ids: [16557, 16558, 16559, 16560, 16561],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'Billable',
    seq: 1,
    type: 'BOOLEAN',
    updated_at: new Date('2023-05-25T12:09:02.814657+00:00'),
    parent_field_id: null,
    field: 'billable',
  },
  tax_group_id: {
    id: 193510,
    code: null,
    column_name: 'tax_group_id',
    created_at: new Date('2021-08-17T04:48:57.792695+00:00'),
    default_value: 'Tax on Goods @8.75%',
    field_name: 's',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    options: [],
    org_category_ids: [16557, 16558, 16559, 16560, 16561],
    org_id: 'orNVthTo2Zyo',
    placeholder: 's',
    seq: 1,
    type: 'SELECT',
    updated_at: new Date('2023-05-25T12:09:02.814657+00:00'),
    parent_field_id: null,
    field: 'tax_group_id',
  },
  org_category_id: {
    id: 203055,
    code: null,
    column_name: 'org_category_id',
    created_at: new Date('2022-03-08T11:37:18.493620+00:00'),
    default_value: null,
    field_name: 'Category',
    is_custom: false,
    is_enabled: true,
    is_mandatory: true,
    options: [],
    org_category_ids: [16557, 16558, 16559, 16560, 16561],
    org_id: 'orNVthTo2Zyo',
    placeholder: 'Select Category',
    seq: 1,
    type: 'SELECT',
    updated_at: new Date('2023-05-25T12:09:02.814657+00:00'),
    parent_field_id: null,
    field: 'org_category_id',
  },
};

export const txnFieldsData2: Partial<ExpenseFieldsObj> = {
  flight_journey_travel_class: {
    id: 2,
    created_at: new Date('2018-01-31T23:50:27.221Z'),
    created_by: {
      user_id: 'SYSTEM',
      org_user_id: null,
      org_id: null,
      roles: [],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: null,
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: null,
    },
    updated_at: new Date('2023-01-13T11:45:00.655Z'),
    updated_by: {
      user_id: 'usEyHSLj6aHw',
      org_user_id: 'ou9KVQTZWIFk',
      org_id: 'orNVthTo2Zyo',
      roles: ['FYLER', 'ADMIN', 'APPROVER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'SUPER_ADMIN', 'HOP'],
      scopes: [],
      allowed_cidrs: [],
      cluster_domain: '"https://staging.fyle.tech"',
      proxy_org_user_id: null,
      tpa_id: null,
      tpa_name: null,
      name: 'ou9KVQTZWIFk',
    },
    org_id: 'orNVthTo2Zyo',
    column_name: 'bus_travel_class',
    field_name: 'Bus travel Class\\/',
    seq: 1,
    type: 'SELECT',
    is_custom: false,
    is_enabled: true,
    is_mandatory: false,
    placeholder: 'TEST',
    default_value: null,
    options: ['eco', 'business', 'jhgjg'],
    org_category_ids: [
      17283, 49621, 83060, 87409, 87441, 101148, 101149, 101151, 102676, 102757, 105705, 106574, 110168, 110597, 114563,
    ],
    code: null,
    roles_editable: ['FYLER', 'APPROVER', 'TRAVEL_ADMIN', 'VERIFIER', 'PAYMENT_PROCESSOR', 'FINANCE', 'ADMIN'],
  },
};
