import { ExtendedOrgUser } from '../models/extended-org-user.model';

export const apiEouRes: ExtendedOrgUser = {
  ou: {
    id: 'ouX8dwsbLCLv',
    created_at: new Date('2018-02-01T02:32:25.267Z'),
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    level_id: 'lvlPtroPaClQy',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'deptpmQ0SsMO0S',
    department: '0000000',
    sub_department: null,
    roles: ['FINANCE', 'ADMIN', 'APPROVER', 'FYLER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'AUDITOR', 'HOP', 'HOD', 'OWNER'],
    approver1_id: null,
    approver2_id: 'oubQzXeZbwbS',
    approver3_id: null,
    delegatee_id: null,
    delegation_start_at: null,
    delegation_end_at: null,
    title: 'director',
    status: 'ACTIVE',
    branch_ifsc: 'ICIC0002322',
    branch_account: null,
    mobile: '123456',
    mobile_verified: false,
    mobile_verified_at: null,
    is_primary: true,
    owner: false,
    joining_dt: new Date('2017-07-25T00:00:00.000+0000'),
    special_email: 'receipts+ajain_6@fyle.ai',
    custom_field_values: [
      {
        id: 415,
        name: 'nj',
        value: 2222,
      },
      {
        id: 790,
        name: 'nj1233',
        value: 'hvgv',
      },
      {
        id: 792,
        name: 'nj12331',
        value: 'asdf',
      },
      {
        id: 793,
        name: 'nj123312',
        value: 'asd',
      },
    ],
    org_name: 'Staging Loaded',
    settings_id: 'ousS9MgDNQ6NB',
    default_cost_center_id: null,
    default_cost_center_name: null,
    default_cost_center_code: null,
    cost_center_ids: [13792, 13793, 13794, 14018, 13795, 13995, 9493, 9494, 13785, 13787, 13788, 13789, 13790, 13791],
  },
  org: {
    domain: 'fyle.in',
    currency: 'INR',
  },
  us: {
    id: 'usvKA4X8Ugcr',
    created_at: new Date('2016-06-13T12:21:16.803Z'),
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
    email_verified_at: new Date('2022-09-06T05:26:19.898Z'),
    onboarded: true,
  },
  ap1: {
    full_name: null,
    email: null,
  },
  ap2: {
    full_name: 'AA23',
    email: 'ajain+12+12+1@fyle.in',
  },
  ap3: {
    full_name: null,
    email: null,
  },
  bb: {
    bank_name: 'ICICI BANK LIMITED',
  },
  dwolla: {
    customer_id: 'dwcJzfwZCgwkdfG',
    bank_account_added: true,
  },
};

export const eouRes2: ExtendedOrgUser = {
  ou: {
    id: 'ouX8dwsbLCLv',
    created_at: new Date('2018-02-01T02:32:25.267Z'),
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    level_id: 'lvlPtroPaClQy',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'deptpmQ0SsMO0S',
    department: '0000000',
    sub_department: null,
    roles: ['FINANCE', 'ADMIN', 'APPROVER', 'FYLER', 'VERIFIER', 'PAYMENT_PROCESSOR', 'AUDITOR', 'HOP', 'HOD', 'OWNER'],
    approver1_id: null,
    approver2_id: 'oubQzXeZbwbS',
    approver3_id: null,
    delegatee_id: null,
    delegation_start_at: null,
    delegation_end_at: null,
    title: 'director',
    status: 'ACTIVE',
    branch_ifsc: 'ICIC0002322',
    branch_account: null,
    mobile: '123456',
    mobile_verified: false,
    mobile_verified_at: null,
    is_primary: true,
    owner: false,
    joining_dt: '2017-07-25T00:00:00.000+0000',
    special_email: 'receipts+ajain_6@fyle.ai',
    custom_field_values: [
      {
        id: 415,
        name: 'nj',
        value: 2222,
      },
    ],
    org_name: 'Staging Loaded',
    settings_id: 'ousS9MgDNQ6NB',
    default_cost_center_id: null,
    default_cost_center_name: null,
    default_cost_center_code: null,
    cost_center_ids: [13792, 13793, 13794, 14018, 13795, 13995, 9493, 9494, 13785, 13787, 13788, 13789, 13790, 13791],
  },
  org: {
    domain: 'fyle.in',
    currency: 'INR',
  },
  us: {
    id: 'usvKA4X8Ugcr',
    created_at: new Date('2016-06-13T12:21:16.803Z'),
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
    email_verified_at: new Date('2022-09-06T05:26:19.898Z'),
    onboarded: true,
  },
  ap1: {
    full_name: null,
    email: null,
  },
  ap2: {
    full_name: 'AA23',
    email: 'ajain+12+12+1@fyle.in',
  },
  ap3: {
    full_name: null,
    email: null,
  },
  bb: {
    bank_name: 'ICICI BANK LIMITED',
  },
  dwolla: {
    customer_id: 'dwcJzfwZCgwkdfG',
    bank_account_added: true,
  },
};
