export const projects = [
  {
    ap1_email: null,
    ap1_full_name: null,
    ap2_email: null,
    ap2_full_name: null,
    project_active: true,
    project_approver1_id: null,
    project_approver2_id: null,
    project_code: '1184',
    project_created_at: new Date('2021-05-12T04:58:40.834Z'),
    project_description: 'Sage Intacct Project - Customer Mapped Project, Id - 1184',
    project_id: 257528,
    project_name: 'Customer Mapped Project',
    project_org_category_ids: [122269, 122270, 122271, null],
    project_org_id: 'orFdTTTNcyye',
    project_updated_at: new Date('2021-07-08T04:58:27.686Z'),
    projectv2_name: 'Customer Mapped Project',
    sub_project_name: null,
  },
  {
    ap1_email: 'john.d@fyle.in',
    ap1_full_name: 'John Doe',
    ap2_email: 'james.d@fyle.in',
    ap2_full_name: 'James Doe',
    project_active: true,
    project_approver1_id: null,
    project_approver2_id: null,
    project_code: '67',
    project_created_at: new Date('2021-03-11T00:12:31.322Z'),
    project_description: 'Quickbooks Online Customer / Project - Abercrombie International Group, Id - 67',
    project_id: 168826,
    project_name: 'Abercrombie International Group',
    project_org_category_ids: [16557, 16558, 16559, 16560, 16561],
    project_org_id: 'orNVthTo2Zyo',
    project_updated_at: new Date('2023-02-22T04:58:55.727Z'),
    projectv2_name: 'Abercrombie International Group',
    sub_project_name: null,
  },
];

export const singleProjects1 = {
  ap1_email: 'john.d@fyle.in',
  ap1_full_name: 'John Doe',
  ap2_email: 'james.d@fyle.in',
  ap2_full_name: 'James Doe',
  project_active: true,
  project_approver1_id: null,
  project_approver2_id: null,
  project_code: '67',
  project_created_at: new Date('2021-03-11T00:12:31.322Z'),
  project_description: 'Quickbooks Online Customer / Project - Abercrombie International Group, Id - 67',
  project_id: 168826,
  project_name: 'Abercrombie International Group',
  project_org_category_ids: [16557, 16558, 16559, 16560, 16561],
  project_org_id: 'orNVthTo2Zyo',
  project_updated_at: new Date('2023-02-22T04:58:55.727Z'),
  projectv2_name: 'Abercrombie International Group',
  sub_project_name: null,
};

export const singleProject2 = {
  ap1_email: null,
  ap1_full_name: null,
  ap2_email: null,
  ap2_full_name: null,
  project_active: true,
  project_approver1_id: null,
  project_approver2_id: null,
  project_code: '1184',
  project_created_at: new Date('2021-05-12T10:28:40.834844'),
  project_description: 'Sage Intacct Project - Customer Mapped Project, Id - 1184',
  project_id: 257528,
  project_name: 'Customer Mapped Project',
  project_org_category_ids: [122269, 122270, 122271, null],
  project_org_id: 'orFdTTTNcyye',
  project_updated_at: new Date('2021-07-08T10:28:27.686886'),
  projectv2_name: 'Customer Mapped Project',
  sub_project_name: null,
};

export const expectedProjects = [
  {
    label: 'None',
    value: null,
  },
  {
    label: 'Customer Mapped Project',
    value: {
      ap1_email: null,
      ap1_full_name: null,
      ap2_email: null,
      ap2_full_name: null,
      project_active: true,
      project_approver1_id: null,
      project_approver2_id: null,
      project_code: '1184',
      project_created_at: new Date('2021-05-12T04:58:40.834Z'),
      project_description: 'Sage Intacct Project - Customer Mapped Project, Id - 1184',
      project_id: 257528,
      project_name: 'Customer Mapped Project',
      project_org_category_ids: [122269, 122270, 122271, null],
      project_org_id: 'orFdTTTNcyye',
      project_updated_at: new Date('2021-07-08T04:58:27.686Z'),
      projectv2_name: 'Customer Mapped Project',
      sub_project_name: null,
    },
  },
  {
    label: 'Abercrombie International Group',
    value: {
      ap1_email: 'john.d@fyle.in',
      ap1_full_name: 'John Doe',
      ap2_email: 'james.d@fyle.in',
      ap2_full_name: 'James Doe',
      project_active: true,
      project_approver1_id: null,
      project_approver2_id: null,
      project_code: '67',
      project_created_at: new Date('2021-03-11T00:12:31.322Z'),
      project_description: 'Quickbooks Online Customer / Project - Abercrombie International Group, Id - 67',
      project_id: 168826,
      project_name: 'Abercrombie International Group',
      project_org_category_ids: [16557, 16558, 16559, 16560, 16561],
      project_org_id: 'orNVthTo2Zyo',
      project_updated_at: new Date('2023-02-22T04:58:55.727Z'),
      projectv2_name: 'Abercrombie International Group',
      sub_project_name: null,
    },
  },
];

export const expectedProjects2 = [
  {
    label: 'None',
    value: null,
  },
  {
    label: undefined,
    value: [
      {
        ap1_email: null,
        ap1_full_name: null,
        ap2_email: null,
        ap2_full_name: null,
        project_active: true,
        project_approver1_id: null,
        project_approver2_id: null,
        project_code: null,
        project_created_at: new Date('2020-06-26T05:32:00.174Z'),
        project_description: null,
        project_id: 3943,
        project_name: 'Staging Project',
        project_org_category_ids: [16560, 224734, 201949],
        project_org_id: 'orNVthTo2Zyo',
        project_updated_at: new Date('2022-11-23T08:55:29.400Z'),
        projectv2_name: 'Staging Project',
        sub_project_name: null,
      },
    ],
  },
  {
    label: 'Customer Mapped Project',
    value: {
      ap1_email: null,
      ap1_full_name: null,
      ap2_email: null,
      ap2_full_name: null,
      project_active: true,
      project_approver1_id: null,
      project_approver2_id: null,
      project_code: '1184',
      project_created_at: new Date('2021-05-12T04:58:40.834Z'),
      project_description: 'Sage Intacct Project - Customer Mapped Project, Id - 1184',
      project_id: 257528,
      project_name: 'Customer Mapped Project',
      project_org_category_ids: [122269, 122270, 122271, null],
      project_org_id: 'orFdTTTNcyye',
      project_updated_at: new Date('2021-07-08T04:58:27.686Z'),
      projectv2_name: 'Customer Mapped Project',
      sub_project_name: null,
    },
  },
  {
    label: 'Abercrombie International Group',
    value: {
      ap1_email: 'john.d@fyle.in',
      ap1_full_name: 'John Doe',
      ap2_email: 'james.d@fyle.in',
      ap2_full_name: 'James Doe',
      project_active: true,
      project_approver1_id: null,
      project_approver2_id: null,
      project_code: '67',
      project_created_at: new Date('2021-03-11T00:12:31.322Z'),
      project_description: 'Quickbooks Online Customer / Project - Abercrombie International Group, Id - 67',
      project_id: 168826,
      project_name: 'Abercrombie International Group',
      project_org_category_ids: [16557, 16558, 16559, 16560, 16561],
      project_org_id: 'orNVthTo2Zyo',
      project_updated_at: new Date('2023-02-22T04:58:55.727Z'),
      projectv2_name: 'Abercrombie International Group',
      sub_project_name: null,
    },
  },
];

export const expectedProjects3 = [
  {
    label: 'None',
    value: null,
  },
  {
    label: 'Customer Mapped Project',
    value: {
      ap1_email: null,
      ap1_full_name: null,
      ap2_email: null,
      ap2_full_name: null,
      project_active: true,
      project_approver1_id: null,
      project_approver2_id: null,
      project_code: '1184',
      project_created_at: new Date('2021-05-12T04:58:40.834Z'),
      project_description: 'Sage Intacct Project - Customer Mapped Project, Id - 1184',
      project_id: 257528,
      project_name: 'Customer Mapped Project',
      project_org_category_ids: [122269, 122270, 122271, null],
      project_org_id: 'orFdTTTNcyye',
      project_updated_at: new Date('2021-07-08T04:58:27.686Z'),
      projectv2_name: 'Customer Mapped Project',
      sub_project_name: null,
    },
    selected: true,
  },
  {
    label: 'Abercrombie International Group',
    value: {
      ap1_email: 'john.d@fyle.in',
      ap1_full_name: 'John Doe',
      ap2_email: 'james.d@fyle.in',
      ap2_full_name: 'James Doe',
      project_active: true,
      project_approver1_id: null,
      project_approver2_id: null,
      project_code: '67',
      project_created_at: new Date('2021-03-11T00:12:31.322Z'),
      project_description: 'Quickbooks Online Customer / Project - Abercrombie International Group, Id - 67',
      project_id: 168826,
      project_name: 'Abercrombie International Group',
      project_org_category_ids: [16557, 16558, 16559, 16560, 16561],
      project_org_id: 'orNVthTo2Zyo',
      project_updated_at: new Date('2023-02-22T04:58:55.727Z'),
      projectv2_name: 'Abercrombie International Group',
      sub_project_name: null,
    },
  },
];

export const expectedProjects4 = [
  {
    label: 'project1',
    value: {
      ap1_email: null,
      ap1_full_name: null,
      ap2_email: null,
      ap2_full_name: null,
      project_active: true,
      project_approver1_id: null,
      project_approver2_id: null,
      project_code: null,
      project_created_at: new Date('2020-06-26T05:32:00.174Z'),
      project_description: null,
      project_id: 3943,
      project_name: 'Staging Project',
      project_org_category_ids: [16560, 224734, 201949],
      project_org_id: 'orNVthTo2Zyo',
      project_updated_at: new Date('2022-11-23T08:55:29.400Z'),
      projectv2_name: 'Staging Project',
      sub_project_name: null,
    },
  },
];
