import { FileTransaction } from '../models/file-txn.model';

export const fileTxns: FileTransaction = {
  txns: [
    {
      created_at: new Date('2023-03-02T14:13:16.734Z'),
      updated_at: new Date('2023-03-02T14:13:16.734Z'),
      id: 'txB9uUczgwgO',
      source: 'MOBILE',
      org_user_id: 'ouX8dwsbLCLv',
      creator_id: 'ouX8dwsbLCLv',
      txn_dt: new Date('2023-03-02T17:00:00.000Z'),
      status_id: null,
      vendor: null,
      platform_vendor: null,
      category: null,
      amount: 120,
      currency: 'INR',
      admin_amount: null,
      user_amount: 120,
      orig_amount: null,
      orig_currency: null,
      tax: 18.304799999999997,
      tax_amount: 18.304799999999997,
      tax_group_id: 'tg3iWuqWhfzB',
      report_id: null,
      reported_at: null,
      num_files: 0,
      invoice_number: null,
      purpose: 'test_term (2) (1)',
      vendor_id: 28828,
      platform_vendor_id: null,
      project_id: 3943,
      billable: null,
      skip_reimbursement: true,
      state: 'DRAFT',
      external_id: null,
      cost_center_id: 13793,
      payment_id: null,
      source_account_id: 'acc5APeygFjRd',
      org_category_id: 110351,
      physical_bill: null,
      policy_state: null,
      manual_flag: null,
      policy_flag: false,
      expense_number: 'E/2023/03/T/34',
      split_group_id: 'txxkBruL0EO9',
      split_group_user_amount: 500,
      extracted_data: null,
      proposed_exchange_rate: null,
      exchange_rate: null,
      exchange_rate_diff_percentage: null,
      mandatory_fields_present: false,
      user_reason_for_duplicate_expenses: null,
      distance: null,
      distance_unit: null,
      from_dt: null,
      to_dt: null,
      num_days: null,
      fyle_category: 'Entertainment',
      mileage_calculated_distance: null,
      mileage_calculated_amount: null,
      mileage_vehicle_type: null,
      mileage_rate: null,
      mileage_is_round_trip: null,
      hotel_is_breakfast_provided: null,
      flight_journey_travel_class: null,
      flight_return_travel_class: null,
      train_travel_class: null,
      bus_travel_class: null,
      taxi_travel_class: null,
      per_diem_rate_id: null,
      activity_policy_pending: null,
      activity_details: null,
      custom_properties: [
        {
          name: 'userlist',
          value: [],
        },
        {
          name: 'User List',
          value: [],
        },
        {
          name: 'test',
          value: null,
        },
        {
          name: 'category2',
          value: null,
        },
        {
          name: 'pub create hola 1',
          value: null,
        },
        {
          name: 'test 112',
          value: null,
        },
        {
          name: '2232323',
          value: null,
        },
        {
          name: 'select all 2',
          value: null,
        },
      ],
      physical_bill_at: null,
      policy_amount: null,
      locations: [],
    },
    {
      created_at: new Date('2023-03-02T14:13:16.811Z'),
      updated_at: new Date('2023-03-02T14:13:16.811Z'),
      id: 'txnumQykfO9h',
      source: 'MOBILE',
      org_user_id: 'ouX8dwsbLCLv',
      creator_id: 'ouX8dwsbLCLv',
      txn_dt: new Date('2023-03-02T17:00:00.000Z'),
      status_id: null,
      vendor: null,
      platform_vendor: null,
      category: null,
      amount: 80,
      currency: 'INR',
      admin_amount: null,
      user_amount: 80,
      orig_amount: null,
      orig_currency: null,
      tax: 12.203199999999997,
      tax_amount: 12.203199999999997,
      tax_group_id: 'tg3iWuqWhfzB',
      report_id: null,
      reported_at: null,
      num_files: 0,
      invoice_number: null,
      purpose: 'test_term (2) (2)',
      vendor_id: 28828,
      platform_vendor_id: null,
      project_id: 3943,
      billable: null,
      skip_reimbursement: true,
      state: 'DRAFT',
      external_id: null,
      cost_center_id: 13793,
      payment_id: null,
      source_account_id: 'acc5APeygFjRd',
      org_category_id: 110351,
      physical_bill: null,
      policy_state: null,
      manual_flag: null,
      policy_flag: false,
      expense_number: 'E/2023/03/T/35',
      split_group_id: 'txxkBruL0EO9',
      split_group_user_amount: 500,
      extracted_data: null,
      proposed_exchange_rate: null,
      exchange_rate: null,
      exchange_rate_diff_percentage: null,
      mandatory_fields_present: false,
      user_reason_for_duplicate_expenses: null,
      distance: null,
      distance_unit: null,
      from_dt: null,
      to_dt: null,
      num_days: null,
      fyle_category: 'Entertainment',
      mileage_calculated_distance: null,
      mileage_calculated_amount: null,
      mileage_vehicle_type: null,
      mileage_rate: null,
      mileage_is_round_trip: null,
      hotel_is_breakfast_provided: null,
      flight_journey_travel_class: null,
      flight_return_travel_class: null,
      train_travel_class: null,
      bus_travel_class: null,
      taxi_travel_class: null,
      per_diem_rate_id: null,
      activity_policy_pending: null,
      activity_details: null,
      custom_properties: [
        {
          name: 'userlist',
          value: [],
        },
        {
          name: 'User List',
          value: [],
        },
        {
          name: 'test',
          value: null,
        },
        {
          name: 'category2',
          value: null,
        },
        {
          name: 'pub create hola 1',
          value: null,
        },
        {
          name: 'test 112',
          value: null,
        },
        {
          name: '2232323',
          value: null,
        },
        {
          name: 'select all 2',
          value: null,
        },
      ],
      physical_bill_at: null,
      policy_amount: null,
      locations: [],
    },
  ],
  files: [
    {
      id: 'fic2q7DLgysQ',
      name: '000.jpeg',
      content: 'some content here',
    },
  ],
};
