// import { Option } from '../models/option.model';

// export const optionData1: Option[] = [
//   {
//     label: 'report 1',
//     value: {
//       rp: {
//         id: 'rp5eUkeNm9wB',
//         org_user_id: 'ouCI4UQ2G0K1',
//         created_at: new Date('2023-01-21T07:45:18.869Z'),
//         purpose: '#7:  Jan 2023',
//         currency: 'USD',
//         amount: 1348.09332,
//         tax: 1277.14,
//         state: 'APPROVER_PENDING',
//         source: 'MOBILE',
//         num_transactions: 1,
//         settlement_id: null,
//         approved_at: null,
//         reimbursed_at: null,
//         submitted_at: new Date('2023-01-21T07:45:23.282Z'),
//         verification_state: null,
//         trip_request_id: null,
//         physical_bill: false,
//         physical_bill_at: null,
//         exported: null,
//         manual_flag: false,
//         policy_flag: false,
//         claim_number: 'C/2023/01/R/42',
//         from_dt: null,
//         to_dt: null,
//         location1: null,
//         location2: null,
//         location3: null,
//         location4: null,
//         location5: null,
//         type: 'EXPENSE',
//         locations: [],
//         risk_state_expense_count: null,
//         risk_state: null,
//       },
//       ou: {
//         id: 'ouCI4UQ2G0K1',
//         org_id: 'orrjqbDbeP9p',
//         location: 'bangalore',
//         business_unit: null,
//         department: 'Primary Sales',
//         sub_department: 'Primary Sales',
//         mobile: null,
//         title: 'lion',
//         employee_id: 'A',
//         level: 123,
//         status: 'ACTIVE',
//         org_name: 'Fyle Staging',
//         department_id: 'deptSdAUA5Urej',
//       },
//       us: {
//         full_name: 'Abhishek Jain',
//         email: 'ajain@fyle.in',
//       },
//     },
//     selected: true,
//   },
//   {
//     label: 'report 2',
//     value: {
//       rp: {
//         id: 'rp72SaHM7Fbz',
//         org_user_id: 'ouCI4UQ2G0K1',
//         created_at: new Date('2023-01-21T07:45:18.858Z'),
//         purpose: '#7:  Jan 2023',
//         currency: 'USD',
//         amount: 0,
//         tax: 0,
//         state: 'APPROVER_PENDING',
//         source: 'MOBILE',
//         num_transactions: 0,
//         settlement_id: null,
//         approved_at: null,
//         reimbursed_at: null,
//         submitted_at: new Date('2023-01-21T07:45:21.515Z'),
//         verification_state: null,
//         trip_request_id: null,
//         physical_bill: true,
//         physical_bill_at: new Date('2023-01-21T07:45:21.173Z'),
//         exported: null,
//         manual_flag: false,
//         policy_flag: false,
//         claim_number: 'C/2023/01/R/41',
//         from_dt: null,
//         to_dt: null,
//         location1: null,
//         location2: null,
//         location3: null,
//         location4: null,
//         location5: null,
//         type: 'EXPENSE',
//         locations: [],
//         risk_state_expense_count: null,
//         risk_state: null,
//       },
//       ou: {
//         id: 'ouCI4UQ2G0K1',
//         org_id: 'orrjqbDbeP9p',
//         location: 'bangalore',
//         business_unit: null,
//         department: 'Primary Sales',
//         sub_department: 'Primary Sales',
//         mobile: null,
//         title: 'lion',
//         employee_id: 'A',
//         level: 123,
//         status: 'ACTIVE',
//         org_name: 'Fyle Staging',
//         department_id: 'deptSdAUA5Urej',
//       },
//       us: {
//         full_name: 'Abhishek Jain',
//         email: 'ajain@fyle.in',
//       },
//     },
//   },
// ];
