import { Expense } from '../models/platform/v1/expense.model';
import { ApprovalState } from '../models/platform/report-approvals.model';
import { MileageUnitEnum } from '../models/platform/platform-mileage-rates.model';
import { AccountType } from '../models/platform/v1/account.model';
import { ExpenseState } from '../models/expense-state.enum';
import { ReportState } from '../models/platform/platform-report.model';

export const platformExpenseData: Expense = {
  accounting_export_summary: {},
  added_to_report_at: null,
  admin_amount: null,
  amount: 2263.68,
  approvals: [
    {
      approver_user: {
        email: 'suyash.p+3@fyle.in',
        full_name: 'Suyash 3',
        id: 'usyg6aRkXnl8',
      },
      approver_user_id: 'usyg6aRkXnl8',
      state: ApprovalState.APPROVAL_DISABLED,
    },
  ],
  approver_comments: [],
  category: {
    code: null,
    display_name: 'Mileage',
    id: 256620,
    name: 'Mileage',
    sub_category: null,
    system_category: 'Mileage',
  },
  category_id: 256620,
  claim_amount: 2263.68,
  code: null,
  cost_center: null,
  cost_center_id: null,
  created_at: new Date('2023-12-05T22:50:43.158Z'),
  creator_user_id: 'usvMoPfCC9Xw',
  currency: 'USD',
  custom_fields: [
    {
      is_enabled: true,
      name: 'ASDF',
      type: 'TEXT',
      value: null,
    },
  ],
  custom_fields_flattened: {
    asdf: null,
  },
  distance: 3456,
  distance_unit: MileageUnitEnum.MILES,
  employee: {
    business_unit: null,
    code: null,
    custom_fields: [],
    department: null,
    department_id: null,
    flattened_custom_field: {},
    has_accepted_invite: true,
    id: 'ou6cE4dCLH8d',
    is_enabled: true,
    joined_at: null,
    level: {
      band: null,
      id: 'lvlqaReubGuJl',
      name: 'Entry level',
    },
    location: null,
    mobile: null,
    org_id: 'orNbIQloYtfa',
    org_name: 'Advance-test',
    title: null,
    user: {
      email: 'devendra.r@fyle.in',
      full_name: 'devendra',
      id: 'usvMoPfCC9Xw',
    },
    user_id: 'usvMoPfCC9Xw',
  },
  employee_id: 'ou6cE4dCLH8d',
  ended_at: null,
  expense_rule_data: null,
  expense_rule_id: null,
  extracted_data: null,
  file_ids: [],
  files: [],
  foreign_amount: null,
  foreign_currency: null,
  hotel_is_breakfast_provided: null,
  id: 'txvslh8aQMbu',
  is_billable: null,
  is_corporate_card_transaction_auto_matched: false,
  is_exported: null,
  is_manually_flagged: null,
  is_physical_bill_submitted: null,
  is_policy_flagged: false,
  is_receipt_mandatory: null,
  is_reimbursable: true,
  is_split: false,
  is_verified: false,
  is_weekend_spend: false,
  last_exported_at: null,
  last_settled_at: null,
  last_verified_at: null,
  locations: [],
  matched_corporate_card_transaction_ids: [],
  matched_corporate_card_transactions: [],
  merchant: null,
  mileage_calculated_amount: null,
  mileage_calculated_distance: null,
  mileage_is_round_trip: null,
  mileage_rate: {
    code: null,
    id: 332872,
    rate: 0.655,
    vehicle_type: 'IRS Rate',
  },
  mileage_rate_id: 332872,
  missing_mandatory_fields: {
    amount: false,
    currency: false,
    expense_field_ids: [],
    receipt: false,
  },
  org_id: 'orNbIQloYtfa',
  per_diem_num_days: null,
  per_diem_rate: null,
  per_diem_rate_id: null,
  physical_bill_submitted_at: null,
  policy_amount: null,
  policy_checks: {
    are_approvers_added: false,
    is_amount_limit_applied: false,
    is_flagged_ever: false,
    violations: null,
  },
  project: null,
  project_id: null,
  purpose: null,
  report: null,
  report_id: null,
  report_last_approved_at: null,
  report_last_paid_at: null,
  report_settlement_id: null,
  seq_num: 'E/2023/12/T/8',
  source: 'WEBAPP',
  source_account: {
    id: 'accO6abI7gZ6T',
    type: AccountType.PERSONAL_CASH_ACCOUNT,
  },
  source_account_id: 'accO6abI7gZ6T',
  spent_at: new Date('2023-12-06T11:30:00.000Z'),
  split_group_amount: null,
  split_group_id: 'txvslh8aQMbu',
  started_at: null,
  state: ExpenseState.DRAFT,
  state_display_name: 'Incomplete',
  tax_amount: null,
  tax_group: null,
  tax_group_id: null,
  travel_classes: [],
  updated_at: new Date('2024-01-22T07:17:05.949Z'),
  user: {
    email: 'devendra.r@fyle.in',
    full_name: 'devendra',
    id: 'usvMoPfCC9Xw',
  },
  user_id: 'usvMoPfCC9Xw',
  verifier_comments: ['Amount changed due to following reason(s) : No policy violation explanation provided'],
};

export const platformExpenseDataWithSubCategory: Expense = {
  accounting_export_summary: {},
  added_to_report_at: null,
  id: 'txD5hIQgLuR5',
  created_at: new Date('2024-02-09T06:50:13.098Z'),
  admin_amount: null,
  amount: 32,
  approvals: [],
  approver_comments: [],
  category: {
    code: null,
    display_name: 'Food / Burger',
    id: 290006,
    name: 'Food',
    sub_category: 'Burger',
    system_category: 'Food',
  },
  category_id: 290006,
  claim_amount: 32,
  code: null,
  // commute_deduction: null,
  // commute_details: {
  //     distance: null,
  //     distance_unit: null,
  //     home_location: null,
  //     id: null,
  //     work_location: null
  // },
  // commute_details_id: null,
  cost_center: {
    code: null,
    id: 20423,
    name: 'Cost Center',
  },
  cost_center_id: 20423,
  creator_user_id: 'usvMoPfCC9Xw',
  currency: 'USD',
  custom_fields: [
    {
      is_enabled: true,
      name: 'location desc',
      type: 'TEXT',
      value: 'Noida',
    },
    {
      is_enabled: true,
      name: 'PP1 where',
      type: 'DEPENDENT_SELECT',
      value: null,
    },
    {
      is_enabled: true,
      name: 'PP 1',
      type: 'DEPENDENT_SELECT',
      value: null,
    },
    {
      is_enabled: true,
      name: 'CC 1',
      type: 'DEPENDENT_SELECT',
      value: null,
    },
  ],
  custom_fields_flattened: {
    cc_1: null,
    location_desc: 'Noida',
    pp1_where: null,
    pp_1: null,
  },
  distance: null,
  distance_unit: null,
  employee: {
    business_unit: null,
    code: null,
    custom_fields: [],
    department: null,
    department_id: null,
    flattened_custom_field: {},
    has_accepted_invite: true,
    id: 'ou6cE4dCLH8d',
    is_enabled: true,
    joined_at: null,
    level: {
      band: null,
      id: 'lvlqaReubGuJl',
      name: 'Entry level',
    },
    location: null,
    mobile: null,
    org_id: 'orNbIQloYtfa',
    org_name: 'Advance-test',
    title: null,
    user: {
      email: 'devendra.r@fyle.in',
      full_name: 'Devendra Singh Rana',
      id: 'usvMoPfCC9Xw',
    },
    user_id: 'usvMoPfCC9Xw',
  },
  employee_id: 'ou6cE4dCLH8d',
  ended_at: null,
  expense_rule_data: null,
  expense_rule_id: null,
  extracted_data: null,
  file_ids: [],
  files: [],
  foreign_amount: null,
  foreign_currency: null,
  hotel_is_breakfast_provided: null,
  invoice_number: null,
  is_billable: null,
  is_corporate_card_transaction_auto_matched: false,
  is_exported: null,
  is_manually_flagged: null,
  is_physical_bill_submitted: null,
  is_policy_flagged: null,
  is_receipt_mandatory: null,
  is_reimbursable: true,
  is_split: false,
  is_verified: false,
  is_weekend_spend: false,
  last_exported_at: null,
  last_settled_at: null,
  last_verified_at: null,
  locations: [],
  matched_corporate_card_transaction_ids: [],
  matched_corporate_card_transactions: [],
  merchant: 'test-1',
  mileage_calculated_amount: null,
  mileage_calculated_distance: null,
  mileage_is_round_trip: null,
  mileage_rate: null,
  mileage_rate_id: null,
  missing_mandatory_fields: {
    amount: false,
    currency: false,
    expense_field_ids: [],
    receipt: false,
  },
  org_id: 'orNbIQloYtfa',
  per_diem_num_days: null,
  per_diem_rate: null,
  per_diem_rate_id: null,
  physical_bill_submitted_at: null,
  policy_amount: null,
  policy_checks: {
    are_approvers_added: false,
    is_amount_limit_applied: false,
    is_flagged_ever: false,
    violations: null,
  },
  project: {
    code: null,
    display_name: 'Project 1',
    id: 325126,
    name: 'Project 1',
    sub_project: null,
  },
  project_id: 325126,
  purpose: 'Client Meeting',
  report: {
    amount: 12983.793345,
    approvals: [
      {
        approver_user: {
          email: 'aniruddha.s@fyle.in',
          full_name: 'Annii Dept head',
          id: 'us2zNEhtHp8d',
        },
        approver_user_id: 'us2zNEhtHp8d',
        state: ApprovalState.APPROVAL_PENDING,
      },
      {
        approver_user: {
          email: 'suyash.p+3@fyle.in',
          full_name: 'Suyash 3',
          id: 'usyg6aRkXnl8',
        },
        approver_user_id: 'usyg6aRkXnl8',
        state: ApprovalState.APPROVAL_DISABLED,
      },
    ],
    id: null,
    last_approved_at: null,
    last_paid_at: null,
    last_submitted_at: new Date('2023-12-05T22:56:09.428Z'),
    last_verified_at: null,
    reimbursement_id: null,
    reimbursement_seq_num: null,
    seq_num: 'C/2023/12/R/2',
    settlement_id: null,
    state: ReportState.APPROVER_PENDING,
    title: '#1:  Dec 2023',
  },
  report_id: null,
  report_last_approved_at: null,
  report_last_paid_at: null,
  report_settlement_id: null,
  seq_num: 'E/2024/02/T/137',
  source: 'MOBILE',
  source_account: {
    id: 'accO6abI7gZ6T',
    type: AccountType.PERSONAL_CASH_ACCOUNT,
  },
  source_account_id: 'accO6abI7gZ6T',
  spent_at: new Date('2024-02-09T11:30:00.000Z'),
  split_group_amount: null,
  split_group_id: 'txD5hIQgLuR5',
  started_at: null,
  state: ExpenseState.APPROVER_PENDING,
  state_display_name: 'Reported',
  tax_amount: 3.43,
  tax_group: {
    name: 'testing tax',
    percentage: 0.12,
  },
  tax_group_id: 'tgyvHlipn1sF',
  travel_classes: [],
  updated_at: new Date('2024-02-09T08:04:59.324Z'),
  user: {
    email: 'devendra.r@fyle.in',
    full_name: 'Devendra Singh Rana',
    id: 'usvMoPfCC9Xw',
  },
  user_id: 'usvMoPfCC9Xw',
  verifications: [],
  verifier_comments: [],
};

export const platformExpenseDataWithReportId: Expense = {
  ...platformExpenseDataWithSubCategory,
  report_id: 'rpbNc3kn5baq',
};
