import { PlatformPolicyExpense } from '../models/platform/platform-policy-expense.model';

export const platformPolicyExpenseData: PlatformPolicyExpense = {
  spent_at: new Date('2023-02-07T17:00:00.000Z'),
  started_at: new Date('2023-02-04T17:00:00.000Z'),
  ended_at: new Date('2023-02-05T17:00:00.000Z'),
  merchant: 'Australian Taxation Office',
  foreign_currency: null,
  foreign_amount: null,
  claim_amount: 54,
  purpose: 'test_term',
  cost_center_id: 13795,
  category_id: 89550,
  project_id: 290054,
  source_account_id: 'acc5APeygFjRd',
  tax_amount: 8.24,
  tax_group_id: 'tg3iWuqWhfzB',
  is_reimbursable: true,
  locations: [],
  custom_fields: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210281,
      mandatory: false,
      name: 'test',
      options: [
        {
          label: 'asd',
          value: 'asd',
        },
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdff',
          value: 'asdff',
        },
      ],
      placeholder: '123test',
      prefix: '',
      type: 'MULTI_SELECT',
      value: '',
    },
    {
      id: 212819,
      mandatory: false,
      name: 'category2',
      options: [
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdfa',
          value: 'asdfa',
        },
      ],
      placeholder: 'category2',
      prefix: '',
      type: 'MULTI_SELECT',
      value: '',
    },
    {
      id: 206206,
      mandatory: false,
      name: 'pub create hola 1',
      options: [],
      placeholder: 'pub create hola 1',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 211321,
      mandatory: false,
      name: 'test 112',
      options: [],
      placeholder: 'placeholder',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 206198,
      mandatory: false,
      name: '2232323',
      options: [],
      placeholder: 'adsf',
      prefix: '',
      type: 'DATE',
      value: null,
    },
    {
      id: 211326,
      mandatory: false,
      name: 'select all 2',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: null,
    },
  ],
  num_files: 0,
  is_matching_ccc: false,
  travel_classes: [],
};
