import { AccountType } from '../enums/account-type.enum';
import { ExpenseState } from '../models/expense-state.enum';
import { PlatformExpense } from '../models/platform/platform-expense.model';

export const platformExpense1: PlatformExpense = {
  added_to_report_at: new Date('2023-01-23T07:29:01.371000+00:00'),
  admin_amount: null,
  amount: 899,
  approvals: [
    {
      approver_user: {
        email: 'aditya.g@fyle.in',
        full_name: 'Aditya Gupta',
        id: 'usvJ3MB64C7k',
      },
      approver_user_id: 'usvJ3MB64C7k',
      state: 'APPROVAL_DONE',
    },
  ],
  approver_comments: [],
  category: {
    code: null,
    display_name: 'Mileage / LOL',
    id: 89550,
    name: 'Mileage',
    sub_category: 'LOL',
    system_category: 'Mileage',
  },
  category_id: 89550,
  claim_amount: 899,
  code: null,
  cost_center: {
    code: null,
    id: 13795,
    name: '01test2',
  },
  cost_center_id: 13795,
  created_at: new Date('2023-01-23T05:15:03.797599+00:00'),
  creator_user_id: 'usvKA4X8Ugcr',
  currency: 'USD',
  custom_fields: [
    {
      name: 'userlist',
      value: [],
    },
    {
      name: 'User List',
      value: [],
    },
    {
      name: 'test',
      value: '',
    },
    {
      name: 'category2',
      value: '',
    },
    {
      name: 'pub create hola 1',
      value: null,
    },
    {
      name: 'test 112',
      value: null,
    },
    {
      name: '2232323',
      value: null,
    },
    {
      name: 'select all 2',
      value: null,
    },
  ],
  custom_fields_flattened: {
    2232323: null,
    category2: '',
    pub_create_hola_1: null,
    select_all_2: null,
    test: '',
    test_112: null,
    user_list: [],
    userlist: [],
  },
  distance: null,
  distance_unit: null,
  employee: {
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    code: '1223',
    custom_fields: [
      {
        name: 'mm',
        value: null,
      },
      {
        name: 'nmm',
        value: null,
      },
      {
        name: 'mbbm',
        value: null,
      },
      {
        name: 'mmnnm',
        value: null,
      },
      {
        name: 'mnjb',
        value: null,
      },
      {
        name: 'tesdufjshadf',
        value: null,
      },
      {
        name: 'new',
        value: null,
      },
      {
        name: 'Test Field',
        value: null,
      },
      {
        name: 'feni type 2',
        value: 'cashew',
      },
      {
        name: 'feni type',
        value: ['coconut'],
      },
      {
        name: 'nndm',
        value: null,
      },
      {
        name: 'test boolean',
        value: false,
      },
    ],
    department: {
      code: null,
      display_name: 'mileage dept / arun',
      id: 'dept62zPkMskdX',
      name: 'mileage dept',
      sub_department: 'arun',
    },
    department_id: 'dept62zPkMskdX',
    flattened_custom_field: {
      feni_type: ['coconut'],
      feni_type_2: 'cashew',
      mbbm: null,
      mm: null,
      mmnnm: null,
      mnjb: null,
      new: null,
      nmm: null,
      nndm: null,
      tesdufjshadf: null,
      test_boolean: false,
      test_field: null,
    },
    has_accepted_invite: true,
    id: 'ouX8dwsbLCLv',
    is_enabled: true,
    level: {
      band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
      id: 'lvlPtroPaClQy',
      name: '123',
    },
    location: 'Mumbai',
    org_id: 'orNVthTo2Zyo',
    org_name: 'Staging Loaded',
    title: 'director',
    user: {
      email: 'ajain@fyle.in',
      full_name: 'Abhishek Jain',
      id: 'usvKA4X8Ugcr',
    },
    user_id: 'usvKA4X8Ugcr',
  },
  employee_id: 'ouX8dwsbLCLv',
  ended_at: null,
  expense_rule_data: null,
  expense_rule_id: null,
  extracted_data: {
    amount: 111,
    category: 'Others',
    currency: 'USD',
    date: null,
    invoice_dt: null,
    vendor_name: 'ANA',
  },
  file_ids: ['fiGLwwPtYD8X'],
  files: [
    {
      content_type: 'application/pdf',
      id: 'fiGLwwPtYD8X',
      name: 'Receipt01 1 1 1.pdf',
      type: 'RECEIPT',
    },
  ],
  foreign_amount: null,
  foreign_currency: null,
  hotel_is_breakfast_provided: false,
  id: 'txOJVaaPxo9O',
  is_billable: true,
  is_corporate_card_transaction_auto_matched: false,
  is_exported: null,
  is_manually_flagged: null,
  is_physical_bill_submitted: null,
  is_policy_flagged: null,
  is_receipt_mandatory: null,
  is_reimbursable: true,
  is_split: false,
  is_verified: false,
  is_weekend_spend: false,
  last_exported_at: null,
  last_settled_at: null,
  last_verified_at: null,
  locations: [],
  matched_corporate_card_transaction_ids: [],
  matched_corporate_card_transactions: [],
  merchant: 'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
  mileage_calculated_amount: null,
  mileage_calculated_distance: null,
  mileage_is_round_trip: null,
  mileage_rate: {
    id: 57035,
    code: null,
    vehicle_type: 'bicycle',
  },
  mileage_rate_id: 57035,
  missing_mandatory_fields: {
    amount: false,
    currency: false,
    expense_field_ids: [],
  },
  org_id: 'orNVthTo2Zyo',
  per_diem_num_days: null,
  per_diem_rate: null,
  per_diem_rate_id: null,
  physical_bill_submitted_at: null,
  policy_amount: null,
  policy_checks: {
    are_approvers_added: false,
    is_amount_limit_applied: false,
    is_flagged_ever: false,
    violations: [],
  },
  project: {
    code: null,
    display_name: 'Staging Project',
    id: 3943,
    name: 'Staging Project',
    sub_project: null,
  },
  project_id: 3943,
  purpose: 'test_term',
  report: {
    amount: 899,
    approvals: [
      {
        approver_user: {
          email: 'aditya.g@fyle.in',
          full_name: 'Aditya Gupta',
          id: 'usvJ3MB64C7k',
        },
        approver_user_id: 'usvJ3MB64C7k',
        state: 'APPROVAL_DONE',
      },
    ],
    id: 'rpFvmTgyeBjN',
    last_approved_at: new Date('2023-03-01T10:35:05.479+00:00'),
    last_paid_at: null,
    last_submitted_at: new Date('2023-01-23T07:29:01.856+00:00'),
    last_verified_at: null,
    reimbursement_id: null,
    reimbursement_seq_num: null,
    seq_num: 'C/2023/01/R/20',
    settlement_id: null,
    state: 'APPROVED',
    title: '#8:  Jan 2023',
  },
  report_id: 'rpFvmTgyeBjN',
  report_settlement_id: null,
  seq_num: 'E/2023/01/T/89',
  source: 'WEBAPP',
  source_account: {
    id: 'acc5APeygFjRd',
    type: AccountType.PERSONAL,
  },
  source_account_id: 'acc5APeygFjRd',
  spent_at: new Date('2023-01-23T17:00:00+00:00'),
  split_group_amount: null,
  split_group_id: 'txOJVaaPxo9O',
  started_at: null,
  state: ExpenseState.APPROVED,
  state_display_name: 'Approved',
  tax_amount: 42.81,
  tax_group: {
    name: 'GST',
    percentage: 0.05,
  },
  tax_group_id: 'tgwotEwriRB5',
  travel_classes: [],
  updated_at: new Date('2023-03-01T10:35:05.358546+00:00'),
  user: {
    email: 'ajain@fyle.in',
    full_name: 'Abhishek Jain',
    id: 'usvKA4X8Ugcr',
  },
  user_id: 'usvKA4X8Ugcr',
  verifier_comments: [],
};
