import { expectedUnflattendedTxnData3 } from '../mock-data/unflattened-txn.data';
import { ExpensePolicy } from '../models/platform/platform-expense-policy.model';
import { PolicyViolation } from '../models/policy-violation.model';
import { PublicPolicyExpense } from '../models/public-policy-expense.model';

export const publicPolicyExpenseData1: PublicPolicyExpense = {
  skip_reimbursement: false,
  source: 'MOBILE',
  state: 'COMPLETE',
  txn_dt: new Date('2023-02-21T06:30:00.000Z'),
  org_category_id: 113717,
  currency: 'INR',
  amount: 20453.73,
  distance: 619.81,
  mileage_calculated_amount: 20453.73,
  mileage_calculated_distance: 619.81,
  policy_amount: null,
  mileage_vehicle_type: 'bicycle',
  mileage_rate: 33,
  distance_unit: 'MILES',
  mileage_is_round_trip: false,
  fyle_category: 'flight',
  org_user_id: 'ouH8VvkHBg9H',
  locations: [
    {
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      formatted_address:
        'Shop No:8, Sahar Cargo, Andheri Victor Mati Lane, Sahar Rd, Tank View, Sahar Village, Andheri East, Mumbai, Maharashtra 400099, India',
      latitude: 19.098039,
      longitude: 72.867626,
      display_name:
        'Bangalore Airport Terminal Services Private Limited, Sahar Road, Tank View, Sahar Village, Andheri East, Mumbai, Maharashtra, India',
    },
  ],
  custom_properties: [
    {
      id: 174083,
      mandatory: false,
      name: 'userlist test',
      options: [],
      placeholder: 'userlist test',
      prefix: '',
      type: 'USER_LIST',
      value: null,
    },
    {
      id: 218778,
      mandatory: false,
      name: 'select type field',
      options: [
        {
          label: 'select-1',
          value: 'select-1',
        },
        {
          label: 'select-2',
          value: 'select-2',
        },
      ],
      placeholder: 'select custom field',
      prefix: '',
      type: 'SELECT',
      value: 'select-1',
    },
  ],
  source_account_id: 'acc1Wy9lM0dHV',
  orig_currency: null,
  orig_amount: null,
  project_id: 3898,
  purpose: 'Test',
  category: null,
  cost_center_id: 4736,
  mileage_rate_id: 24329,
  activity_details: '',
  activity_policy_pending: false,
  admin_amount: 0,
  billable: false,
  bus_travel_class: 'luxury',
  created_at: undefined,
  creator_id: '',
  exchange_rate: 0,
  exchange_rate_diff_percentage: 0,
  expense_number: '',
  external_id: '',
  extracted_data: undefined,
  flight_journey_travel_class: 'economy',
  flight_return_travel_class: 'business',
  from_dt: undefined,
  hotel_is_breakfast_provided: false,
  id: '1234',
  is_matching_ccc_expense: false,
  invoice_number: 0,
  mandatory_fields_present: false,
  manual_flag: false,
  num_days: 0,
  num_files: 0,
  payment_id: '',
  per_diem_rate_id: 0,
  physical_bill: false,
  physical_bill_at: undefined,
  platform_vendor: '',
  platform_vendor_id: '',
  policy_flag: false,
  policy_state: '',
  proposed_exchange_rate: 0,
  report_id: '',
  reported_at: undefined,
  split_group_id: '',
  split_group_user_amount: 0,
  status_id: '',
  tax: '',
  tax_amount: 0,
  tax_group_id: 'txid1',
  taxi_travel_class: '',
  to_dt: undefined,
  train_travel_class: 'first-class',
  updated_at: undefined,
  user_amount: 0,
  user_reason_for_duplicate_expenses: '',
  vendor: 'Uber',
  vendor_id: 0,
};

export const publicPolicyExpenseData2: PublicPolicyExpense = {
  ...publicPolicyExpenseData1,
  fyle_category: 'airlines',
};

export const publicPolicyExpenseData3: PublicPolicyExpense = {
  ...publicPolicyExpenseData1,
  fyle_category: 'bus',
};

export const publicPolicyExpenseData4: PublicPolicyExpense = {
  ...publicPolicyExpenseData1,
  fyle_category: 'train',
};

export const publicPolicyExpenseData5: PublicPolicyExpense = {
  ...publicPolicyExpenseData1,
  skip_reimbursement: null,
};

export const publicPolicyExpenseData6: PublicPolicyExpense = {
  ...publicPolicyExpenseData1,
  locations: null,
};

export const publicPolicyExpenseData7: PublicPolicyExpense = {
  ...publicPolicyExpenseData1,
  fyle_category: null,
};

export const expensePolicyData: ExpensePolicy = {
  data: {
    final_desired_state: {
      add_approver_user_ids: [],
      amount: null,
      flag: true,
      is_receipt_mandatory: false,
      remove_employee_approver1: false,
      run_status: 'SUCCESS',
      run_summary: ['expense will be flagged for verification and approval'],
    },
    individual_desired_states: [
      {
        add_approver_user_ids: [],
        amount: 0.00005,
        expense_policy_rule: {
          action_show_warning: true,
          description:
            'The expense will be flagged when the total amount of all expenses in category Others in a month exceeds: INR 3000.',
          id: 'tprlDUfXa0idO',
        },
        expense_policy_rule_id: 'tprlDUfXa0idO',
        expenses_query_object_params: {
          limit_end_date: '2023-03-01',
          limit_start_date: '2023-02-01',
          params: {
            category_id: 'in.(1630)',
            employee_id: 'eq.ouWmQvnfr9x0',
            cost_center_id: 'CostCentId1',
            currency: 'INR',
            mileage_rate_id: 'MilRatId1',
            project_id: 'ProId1',
          },
        },
        run_result: ['expense will be flagged for verification and approval'],
        run_status: 'VIOLATED_ACTION_SUCCESS',
      },
    ],
  },
};

export const policyViolationData: PolicyViolation = {
  data: {
    individual_desired_states: [
      {
        expense_id: 'txGNXsC1bmIo',
        add_approver_user_ids: [],
        amount: 0.00005,
        expense_policy_rule: {
          action_show_warning: true,
          description:
            'The expense will be flagged when the total amount of all expenses in category Others in a month exceeds: INR 3000.',
          id: 'tprlDUfXa0idO',
        },
        expense_policy_rule_id: 'tprlDUfXa0idO',
        expenses_query_object_params: {
          limit_end_date: '2023-03-01',
          limit_start_date: '2023-02-01',
          params: {
            category_id: 'in.(1630)',
            employee_id: 'eq.ouWmQvnfr9x0',
            cost_center_id: 'CostCentId1',
            currency: 'INR',
            mileage_rate_id: 'MilRatId1',
            project_id: 'ProId1',
          },
        },
        run_result: ['expense will be flagged for verification and approval'],
        run_status: 'VIOLATED_ACTION_SUCCESS',
      },
    ],
    final_desired_state: {
      add_approver_user_ids: [],
      amount: null,
      flag: true,
      is_receipt_mandatory: false,
      remove_employee_approver1: false,
      run_status: 'SUCCESS',
      run_summary: ['expense will be flagged for verification and approval'],
    },
  },
  amount: 100,
  currency: 'INR',
  name: 'Policy Violation 1',
  type: 'Expense Policy',
};

export const violations: { [id: string]: PolicyViolation } = {
  txVTmNOp5JEa: policyViolationData,
};

export const splitPolicyExp: PublicPolicyExpense = {
  ...publicPolicyExpenseData1,
  id: 'txqhb1IwrujH',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-03-03T06:50:11.644Z'),
  txn_dt: new Date('2023-02-15T06:30:00.000Z'),
  amount: 20.4,
  user_amount: 20.4,
};

export const splitTransactionData1: PublicPolicyExpense = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txUQZ7xKSbDw',
  org_user_id: 'ourw7Hi4mmpO',
  created_at: new Date('2023-01-21T13:55:38.496Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-01-21T18:30:00.000Z'),
  category: null,
  amount: 2211.2650000000003,
  user_amount: 2211.2650000000003,
  policy_amount: null,
  admin_amount: null,
  tax: '337.31',
  tax_amount: 337.31,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'DRAFT',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term',
  source: 'MOBILE_DASHCAM_SINGLE',
  billable: null,
  orig_amount: 5000,
  orig_currency: 'ARS',
  project_id: 168826,
  project_name: 'Abercrombie International Group',
  project_code: '67',
  skip_reimbursement: false,
  creator_id: 'ourw7Hi4mmpO',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: 'A very long cost center name A very long cost center name A very long cost center name',
  cost_center_code: 'A very long cost center code A very long cost center code A very long cost center code',
  cost_center_id: 6725,
  source_account_id: 'acct0vTdfNQrT',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor: 'Uber',
  vendor_id: null,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Accm.Depr. Furniture & Fixtures',
  sub_category: 'Accm.Depr. Furniture & Fixtures',
  fyle_category: null,
  org_category_code: '15510',
  org_category_id: 129111,
  expense_number: 'E/2023/01/T/88',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txUQZ7xKSbDw',
  split_group_user_amount: 2211.2650000000003,
  extracted_data: {
    amount: null,
    currency: 'INR',
    category: 'Others',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: false,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Accm.Depr. Furniture & Fixtures',
  exchange_rate: 0,
  exchange_rate_diff_percentage: 0,
  is_matching_ccc_expense: false,
  mileage_rate_id: 0,
  payment_id: '',
  proposed_exchange_rate: 0,
  status_id: '',
  updated_at: undefined,
};

export const publicPolicyExpenseDataFromTxn: PublicPolicyExpense = {
  ...expectedUnflattendedTxnData3.tx,
  tax: '',
  locations: null,
  exchange_rate: 0,
  exchange_rate_diff_percentage: 0,
  is_matching_ccc_expense: false,
  mileage_rate_id: 0,
  payment_id: '',
  proposed_exchange_rate: 0,
  status_id: '',
  updated_at: undefined,
  user_review_needed: null,
};
