import { ExtendedReport } from '../models/report.model';

export const expectedReportSingleResponse: ExtendedReport = {
  _search_document:
    "'145':5 'a':8 'abhishek':10 'ajain@fyle.in':12 'bangalore':9 'c/2023/01/r/31':6 'columns':3 'inr':4 'jain':11 'lion':7 'manage':2 'test':1",
  approved_by: ['out3t2X258rd'],
  ou_business_unit: null,
  ou_department: 'Primary Sales',
  ou_department_id: 'deptSdAUA5Urej',
  ou_employee_id: 'A',
  ou_id: 'ouCI4UQ2G0K1',
  ou_level: '123wqe',
  ou_level_id: 'lvlEtPwKjAF6U',
  ou_location: 'bangalore',
  ou_mobile: null,
  ou_org_id: 'orrjqbDbeP9p',
  ou_org_name: 'Fyle Staging',
  ou_status: '"ACTIVE"',
  ou_sub_department: 'Primary Sales',
  ou_title: 'lion',
  report_approvals: {
    out3t2X258rd: {
      rank: 0,
      state: 'APPROVAL_PENDING',
    },
  },
  rp_amount: 145,
  rp_approval_state: null,
  rp_approved_at: null,
  rp_claim_number: 'C/2023/01/R/31',
  rp_created_at: new Date('2023-01-19T07:27:33.235573'),
  rp_currency: 'USD',
  rp_exported: false,
  rp_from_dt: null,
  rp_id: 'rpfClhA1lglE',
  rp_locations: [],
  rp_manual_flag: false,
  rp_num_transactions: 3,
  rp_org_user_id: 'ouCI4UQ2G0K1',
  rp_physical_bill: false,
  rp_physical_bill_at: null,
  rp_policy_flag: false,
  rp_purpose: 'test_manage_columns',
  rp_reimbursed_at: null,
  rp_risk_state: null,
  rp_risk_state_expense_count: null,
  rp_settlement_id: null,
  rp_source: 'WEBAPP',
  rp_state: 'APPROVER_PENDING',
  rp_submitted_at: '2023-01-19T07:27:36.879',
  rp_tax: 15.54,
  rp_to_dt: null,
  rp_trip_request_id: null,
  rp_type: 'EXPENSE',
  rp_verification_state: null,
  rp_verified: false,
  sequential_approval_turn: false,
  us_email: 'ajain@fyle.in',
  us_full_name: 'Abhishek Jain',
};

export const apiErptcReportsRes: ExtendedReport[] = [
  {
    rp_id: 'rpfClhA1lglE',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2023-01-19T07:27:33.235Z'),
    rp_purpose: 'test_manage_columns',
    rp_currency: 'USD',
    rp_amount: 145,
    rp_tax: 15.54,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WEBAPP',
    rp_num_transactions: 3,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-19T07:27:36.879Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/31',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: '123wqe',
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpG0qW1oL4DX',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2023-01-04T00:00:13.630Z'),
    rp_purpose: '#1: October 2022',
    rp_currency: 'USD',
    rp_amount: 121124.70000000001,
    rp_tax: 0,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'TPA',
    rp_num_transactions: 2,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-04T00:00:13.630Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: false,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/11',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: '123wqe',
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpqzKD4bPXpW',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2022-04-10T04:35:09.284Z'),
    rp_purpose: '#21:  Apr 2022',
    rp_currency: 'USD',
    rp_amount: 818958.934675,
    rp_tax: 71.52,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WEBAPP',
    rp_num_transactions: 32,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-04T00:00:13.630Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: false,
    rp_manual_flag: true,
    rp_policy_flag: true,
    rp_claim_number: 'C/2022/04/R/70',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: '123wqe',
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpRmtgbN7P3F',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2022-04-10T04:33:59.667Z'),
    rp_purpose: '#17:  Apr 2022',
    rp_currency: 'USD',
    rp_amount: 0,
    rp_tax: null,
    rp_state: 'DRAFT',
    rp_source: 'WEBAPP',
    rp_num_transactions: 0,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: null,
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: null,
    rp_policy_flag: null,
    rp_claim_number: 'C/2022/04/R/69',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: '123wqe',
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
];
