import { UnflattenedReport } from '../models/report-unflattened.model';

export const expectedErpt: UnflattenedReport[] = [
  {
    rp: {
      id: 'rprAfNrce73O',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-21T07:29:01.958Z'),
      purpose: '#8:  Jan 2023',
      currency: 'USD',
      amount: 116.9,
      tax: 17.83,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 1,
      approvals: null,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:29:03.656Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/16',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpLMyvYSXgJy',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-18T07:29:00.749Z'),
      purpose: '#7:  Jan 2023',
      currency: 'USD',
      amount: 4652,
      tax: 695.5,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 3,
      approvals: null,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-18T07:29:04.487Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/15',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpxtbiLXQZUm',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-17T07:29:00.800Z'),
      purpose: '#6:  Jan 2023',
      currency: 'USD',
      amount: 347.45800399999996,
      tax: 53,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 1,
      approvals: null,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-17T07:29:01.751Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/12',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpSGcIEwzxDd',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-17T06:34:58.398Z'),
      purpose: '#4:  Jan 2023',
      currency: 'USD',
      amount: 9400,
      tax: 1152.3,
      state: 'APPROVER_INQUIRY',
      source: 'WEBAPP',
      num_transactions: 4,
      approvals: null,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-17T06:34:59.523Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: true,
      claim_number: 'C/2023/01/R/10',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
];

export const expectedSingleErpt: UnflattenedReport = {
  rp: {
    id: 'rprAfNrce73O',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-21T07:29:01.958Z'),
    purpose: '#8:  Jan 2023',
    currency: 'USD',
    amount: 116.9,
    tax: 17.83,
    state: 'APPROVER_PENDING',
    source: 'WORKFLOWS',
    num_transactions: 1,
    approvals: null,
    settlement_id: null,
    approved_at: null,
    reimbursed_at: null,
    submitted_at: new Date('2023-01-21T07:29:03.656Z'),
    verification_state: null,
    trip_request_id: null,
    physical_bill: false,
    physical_bill_at: null,
    exported: null,
    manual_flag: false,
    policy_flag: false,
    claim_number: 'C/2023/01/R/16',
    from_dt: null,
    to_dt: null,
    location1: null,
    location2: null,
    location3: null,
    location4: null,
    location5: null,
    type: 'EXPENSE',
    locations: [],
    risk_state_expense_count: null,
    risk_state: null,
  },
  ou: {
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    location: 'Mumbai',
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    sub_department: null,
    mobile: '123456',
    title: 'director',
    employee_id: '',
    level: 123,
    status: 'ACTIVE',
    org_name: 'Staging Loaded',
    department_id: 'deptpmQ0SsMO0S',
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
};

export const extendedReportParam: UnflattenedReport[] = [
  {
    rp: {
      id: 'rp5eUkeNm9wB',
      org_user_id: 'ouCI4UQ2G0K1',
      created_at: new Date('2023-01-21T07:45:18.869Z'),
      purpose: '#7:  Jan 2023',
      currency: 'USD',
      amount: 1348.09332,
      tax: 1277.14,
      state: 'APPROVER_PENDING',
      source: 'MOBILE',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:45:23.282Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/42',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouCI4UQ2G0K1',
      org_id: 'orrjqbDbeP9p',
      location: 'bangalore',
      business_unit: null,
      department: 'Primary Sales',
      sub_department: 'Primary Sales',
      mobile: null,
      title: 'lion',
      employee_id: 'A',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Fyle Staging',
      department_id: 'deptSdAUA5Urej',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rp72SaHM7Fbz',
      org_user_id: 'ouCI4UQ2G0K1',
      created_at: new Date('2023-01-21T07:45:18.858Z'),
      purpose: '#7:  Jan 2023',
      currency: 'USD',
      amount: 0,
      tax: 0,
      state: 'APPROVER_PENDING',
      source: 'MOBILE',
      num_transactions: 0,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:45:21.515Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: true,
      physical_bill_at: new Date('2023-01-21T07:45:21.173Z'),
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/41',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouCI4UQ2G0K1',
      org_id: 'orrjqbDbeP9p',
      location: 'bangalore',
      business_unit: null,
      department: 'Primary Sales',
      sub_department: 'Primary Sales',
      mobile: null,
      title: 'lion',
      employee_id: 'A',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Fyle Staging',
      department_id: 'deptSdAUA5Urej',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpvcIMRMyM3A',
      org_user_id: 'ouCI4UQ2G0K1',
      created_at: new Date('2023-01-21T07:42:58.367Z'),
      purpose: '#5:  Jan 2023',
      currency: 'USD',
      amount: 250,
      tax: 26.79,
      state: 'APPROVER_PENDING',
      source: 'MOBILE',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:43:01.261Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/40',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouCI4UQ2G0K1',
      org_id: 'orrjqbDbeP9p',
      location: 'bangalore',
      business_unit: null,
      department: 'Primary Sales',
      sub_department: 'Primary Sales',
      mobile: null,
      title: 'lion',
      employee_id: 'A',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Fyle Staging',
      department_id: 'deptSdAUA5Urej',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpvwqzb9Jqq0',
      org_user_id: 'ouCI4UQ2G0K1',
      created_at: new Date('2023-01-21T07:34:02.610Z'),
      purpose: 'A new report',
      currency: 'USD',
      amount: 150,
      tax: 12.39,
      state: 'APPROVER_PENDING',
      source: 'MOBILE',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:34:04.686Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/39',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouCI4UQ2G0K1',
      org_id: 'orrjqbDbeP9p',
      location: 'bangalore',
      business_unit: null,
      department: 'Primary Sales',
      sub_department: 'Primary Sales',
      mobile: null,
      title: 'lion',
      employee_id: 'A',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Fyle Staging',
      department_id: 'deptSdAUA5Urej',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
];

export const expectedUnflattenedReports: UnflattenedReport[] = [
  {
    rp: {
      id: 'rp5eUkeNm9wB',
      org_user_id: 'ouCI4UQ2G0K1',
      created_at: new Date('2023-01-21T07:45:18.869Z'),
      purpose: '#7:  Jan 2023',
      currency: 'USD',
      amount: 1348.09332,
      tax: 1277.14,
      state: 'APPROVER_PENDING',
      source: 'MOBILE',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:45:23.282Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/42',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouCI4UQ2G0K1',
      org_id: 'orrjqbDbeP9p',
      location: 'bangalore',
      business_unit: null,
      department: 'Primary Sales',
      sub_department: 'Primary Sales',
      mobile: null,
      title: 'lion',
      employee_id: 'A',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Fyle Staging',
      department_id: 'deptSdAUA5Urej',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rp72SaHM7Fbz',
      org_user_id: 'ouCI4UQ2G0K1',
      created_at: new Date('2023-01-21T07:45:18.858Z'),
      purpose: '#7:  Jan 2023',
      currency: 'USD',
      amount: 0,
      tax: 0,
      state: 'APPROVER_PENDING',
      source: 'MOBILE',
      num_transactions: 0,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:45:21.515Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: true,
      physical_bill_at: new Date('2023-01-21T07:45:21.173Z'),
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/41',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouCI4UQ2G0K1',
      org_id: 'orrjqbDbeP9p',
      location: 'bangalore',
      business_unit: null,
      department: 'Primary Sales',
      sub_department: 'Primary Sales',
      mobile: null,
      title: 'lion',
      employee_id: 'A',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Fyle Staging',
      department_id: 'deptSdAUA5Urej',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpvcIMRMyM3A',
      org_user_id: 'ouCI4UQ2G0K1',
      created_at: new Date('2023-01-21T07:42:58.367Z'),
      purpose: '#5:  Jan 2023',
      currency: 'USD',
      amount: 250,
      tax: 26.79,
      state: 'APPROVER_PENDING',
      source: 'MOBILE',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:43:01.261Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/40',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouCI4UQ2G0K1',
      org_id: 'orrjqbDbeP9p',
      location: 'bangalore',
      business_unit: null,
      department: 'Primary Sales',
      sub_department: 'Primary Sales',
      mobile: null,
      title: 'lion',
      employee_id: 'A',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Fyle Staging',
      department_id: 'deptSdAUA5Urej',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpvwqzb9Jqq0',
      org_user_id: 'ouCI4UQ2G0K1',
      created_at: new Date('2023-01-21T07:34:02.610Z'),
      purpose: 'A new report',
      currency: 'USD',
      amount: 150,
      tax: 12.39,
      state: 'APPROVER_PENDING',
      source: 'MOBILE',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:34:04.686Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/39',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouCI4UQ2G0K1',
      org_id: 'orrjqbDbeP9p',
      location: 'bangalore',
      business_unit: null,
      department: 'Primary Sales',
      sub_department: 'Primary Sales',
      mobile: null,
      title: 'lion',
      employee_id: 'A',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Fyle Staging',
      department_id: 'deptSdAUA5Urej',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
];

export const expectedPendingReports: UnflattenedReport[] = [
  {
    rp: {
      id: 'rprAfNrce73O',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-21T07:29:01.958Z'),
      purpose: '#8:  Jan 2023',
      currency: 'USD',
      amount: 116.9,
      tax: 17.83,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:29:03.656Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/16',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpLMyvYSXgJy',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-18T07:29:00.749Z'),
      purpose: '#7:  Jan 2023',
      currency: 'USD',
      amount: 4652,
      tax: 695.5,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 3,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-18T07:29:04.487Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/15',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpxtbiLXQZUm',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-17T07:29:00.800Z'),
      purpose: '#6:  Jan 2023',
      currency: 'USD',
      amount: 347.45800399999996,
      tax: 53,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-17T07:29:01.751Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/12',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpSGcIEwzxDd',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-17T06:34:58.398Z'),
      purpose: '#4:  Jan 2023',
      currency: 'USD',
      amount: 9400,
      tax: 1152.3,
      state: 'APPROVER_INQUIRY',
      source: 'WEBAPP',
      num_transactions: 4,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-17T06:34:59.523Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: true,
      claim_number: 'C/2023/01/R/10',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
];

export const addedApproversReports: UnflattenedReport[] = [
  {
    rp: {
      id: 'rprAfNrce73O',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-21T07:29:01.958Z'),
      purpose: '#8:  Jan 2023',
      currency: 'USD',
      amount: 116.9,
      tax: 17.83,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-21T07:29:03.656Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/16',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpLMyvYSXgJy',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-18T07:29:00.749Z'),
      purpose: '#7:  Jan 2023',
      currency: 'USD',
      amount: 4652,
      tax: 695.5,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 3,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-18T07:29:04.487Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/15',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpxtbiLXQZUm',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-17T07:29:00.800Z'),
      purpose: '#6:  Jan 2023',
      currency: 'USD',
      amount: 347.45800399999996,
      tax: 53,
      state: 'APPROVER_PENDING',
      source: 'WORKFLOWS',
      num_transactions: 1,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-17T07:29:01.751Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: false,
      claim_number: 'C/2023/01/R/12',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
  {
    rp: {
      id: 'rpSGcIEwzxDd',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-01-17T06:34:58.398Z'),
      purpose: '#4:  Jan 2023',
      currency: 'USD',
      amount: 9400,
      tax: 1152.3,
      state: 'APPROVER_INQUIRY',
      source: 'WEBAPP',
      num_transactions: 4,
      settlement_id: null,
      approved_at: null,
      reimbursed_at: null,
      submitted_at: new Date('2023-01-17T06:34:59.523Z'),
      verification_state: null,
      trip_request_id: null,
      physical_bill: false,
      physical_bill_at: null,
      exported: null,
      manual_flag: false,
      policy_flag: true,
      claim_number: 'C/2023/01/R/10',
      from_dt: null,
      to_dt: null,
      location1: null,
      location2: null,
      location3: null,
      location4: null,
      location5: null,
      type: 'EXPENSE',
      locations: [],
      risk_state_expense_count: null,
      risk_state: null,
    },
    ou: {
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      location: 'Mumbai',
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department: '0000000',
      sub_department: null,
      mobile: '123456',
      title: 'director',
      employee_id: '',
      level: 123,
      status: 'ACTIVE',
      org_name: 'Staging Loaded',
      department_id: 'deptpmQ0SsMO0S',
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
  },
];

export const unflattenedErptc: UnflattenedReport = {
  rp: {
    id: 'rprAfNrce73O',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-21T07:29:01.958Z'),
    purpose: '#8:  Jan 2023',
    currency: 'USD',
    amount: 116.9,
    tax: 17.83,
    state: 'APPROVER_PENDING',
    source: 'WORKFLOWS',
    num_transactions: 1,
    approvals: null,
    settlement_id: null,
    approved_at: null,
    reimbursed_at: null,
    submitted_at: new Date('2023-01-21T07:29:03.656Z'),
    verification_state: null,
    trip_request_id: null,
    physical_bill: false,
    physical_bill_at: null,
    exported: null,
    manual_flag: false,
    policy_flag: false,
    claim_number: 'C/2023/01/R/16',
    from_dt: null,
    to_dt: null,
    location1: null,
    location2: null,
    location3: null,
    location4: null,
    location5: null,
    type: 'EXPENSE',
    locations: [],
    risk_state_expense_count: null,
    risk_state: null,
  },
  ou: {
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    location: 'Mumbai',
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    sub_department: null,
    mobile: '123456',
    title: 'director',
    employee_id: '',
    level: 123,
    status: 'ACTIVE',
    org_name: 'Staging Loaded',
    department_id: 'deptpmQ0SsMO0S',
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
};

export const unflattenedErptcArrayItem1: UnflattenedReport = {
  rp: {
    id: 'rprAfNrce73O',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-21T07:29:01.958Z'),
    purpose: '#8:  Jan 2023',
    currency: 'USD',
    amount: 116.9,
    tax: 17.83,
    state: 'APPROVER_PENDING',
    source: 'WORKFLOWS',
    num_transactions: 1,
    approvals: null,
    settlement_id: null,
    approved_at: null,
    reimbursed_at: null,
    submitted_at: new Date('2023-01-21T07:29:03.656Z'),
    verification_state: null,
    trip_request_id: null,
    physical_bill: false,
    physical_bill_at: null,
    exported: null,
    manual_flag: false,
    policy_flag: false,
    claim_number: 'C/2023/01/R/16',
    from_dt: null,
    to_dt: null,
    location1: null,
    location2: null,
    location3: null,
    location4: null,
    location5: null,
    type: 'EXPENSE',
    locations: [],
    risk_state_expense_count: null,
    risk_state: null,
  },
  ou: {
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    location: 'Mumbai',
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    sub_department: null,
    mobile: '123456',
    title: 'director',
    employee_id: '',
    level: 123,
    status: 'ACTIVE',
    org_name: 'Staging Loaded',
    department_id: 'deptpmQ0SsMO0S',
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
};

export const unflattenedErptcArrayItem2: UnflattenedReport = {
  rp: {
    id: 'rpLMyvYSXgJy',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-18T07:29:00.749Z'),
    purpose: '#7:  Jan 2023',
    currency: 'USD',
    amount: 4652,
    tax: 695.5,
    state: 'APPROVER_PENDING',
    source: 'WORKFLOWS',
    num_transactions: 3,
    approvals: null,
    settlement_id: null,
    approved_at: null,
    reimbursed_at: null,
    submitted_at: new Date('2023-01-18T07:29:04.487Z'),
    verification_state: null,
    trip_request_id: null,
    physical_bill: false,
    physical_bill_at: null,
    exported: null,
    manual_flag: false,
    policy_flag: false,
    claim_number: 'C/2023/01/R/15',
    from_dt: null,
    to_dt: null,
    location1: null,
    location2: null,
    location3: null,
    location4: null,
    location5: null,
    type: 'EXPENSE',
    locations: [],
    risk_state_expense_count: null,
    risk_state: null,
  },
  ou: {
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    location: 'Mumbai',
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    sub_department: null,
    mobile: '123456',
    title: 'director',
    employee_id: '',
    level: 123,
    status: 'ACTIVE',
    org_name: 'Staging Loaded',
    department_id: 'deptpmQ0SsMO0S',
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
};

export const unflattenedErptcArrayItem3: UnflattenedReport = {
  rp: {
    id: 'rpxtbiLXQZUm',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-17T07:29:00.800Z'),
    purpose: '#6:  Jan 2023',
    currency: 'USD',
    amount: 347.45800399999996,
    tax: 53,
    state: 'APPROVER_PENDING',
    source: 'WORKFLOWS',
    num_transactions: 1,
    approvals: null,
    settlement_id: null,
    approved_at: null,
    reimbursed_at: null,
    submitted_at: new Date('2023-01-17T07:29:01.751Z'),
    verification_state: null,
    trip_request_id: null,
    physical_bill: false,
    physical_bill_at: null,
    exported: null,
    manual_flag: false,
    policy_flag: false,
    claim_number: 'C/2023/01/R/12',
    from_dt: null,
    to_dt: null,
    location1: null,
    location2: null,
    location3: null,
    location4: null,
    location5: null,
    type: 'EXPENSE',
    locations: [],
    risk_state_expense_count: null,
    risk_state: null,
  },
  ou: {
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    location: 'Mumbai',
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    sub_department: null,
    mobile: '123456',
    title: 'director',
    employee_id: '',
    level: 123,
    status: 'ACTIVE',
    org_name: 'Staging Loaded',
    department_id: 'deptpmQ0SsMO0S',
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
};

export const unflattenedErptcArrayItem4: UnflattenedReport = {
  rp: {
    id: 'rpSGcIEwzxDd',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-17T06:34:58.398Z'),
    purpose: '#4:  Jan 2023',
    currency: 'USD',
    amount: 9400,
    tax: 1152.3,
    state: 'APPROVER_INQUIRY',
    source: 'WEBAPP',
    num_transactions: 4,
    approvals: null,
    settlement_id: null,
    approved_at: null,
    reimbursed_at: null,
    submitted_at: new Date('2023-01-17T06:34:59.523Z'),
    verification_state: null,
    trip_request_id: null,
    physical_bill: false,
    physical_bill_at: null,
    exported: null,
    manual_flag: false,
    policy_flag: true,
    claim_number: 'C/2023/01/R/10',
    from_dt: null,
    to_dt: null,
    location1: null,
    location2: null,
    location3: null,
    location4: null,
    location5: null,
    type: 'EXPENSE',
    locations: [],
    risk_state_expense_count: null,
    risk_state: null,
  },
  ou: {
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    location: 'Mumbai',
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    sub_department: null,
    mobile: '123456',
    title: 'director',
    employee_id: '',
    level: 123,
    status: 'ACTIVE',
    org_name: 'Staging Loaded',
    department_id: 'deptpmQ0SsMO0S',
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
};

export const singleERptcFixDatesMock: UnflattenedReport = {
  rp: {
    id: 'rprAfNrce73O',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-21T07:29:01.958Z'),
    purpose: '#8:  Jan 2023',
    currency: 'USD',
    amount: 116.9,
    tax: 17.83,
    state: 'APPROVER_PENDING',
    source: 'WORKFLOWS',
    num_transactions: 1,
    approvals: null,
    settlement_id: null,
    approved_at: null,
    reimbursed_at: null,
    submitted_at: new Date('2023-01-21T07:29:03.656Z'),
    verification_state: null,
    trip_request_id: null,
    physical_bill: false,
    physical_bill_at: null,
    exported: null,
    manual_flag: false,
    policy_flag: false,
    claim_number: 'C/2023/01/R/16',
    from_dt: null,
    to_dt: null,
    location1: null,
    location2: null,
    location3: null,
    location4: null,
    location5: null,
    type: 'EXPENSE',
    locations: [],
    risk_state_expense_count: null,
    risk_state: null,
  },
  ou: {
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    location: 'Mumbai',
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    sub_department: null,
    mobile: '123456',
    title: 'director',
    employee_id: '',
    level: 123,
    status: 'ACTIVE',
    org_name: 'Staging Loaded',
    department_id: 'deptpmQ0SsMO0S',
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
};

export const singleERptcLocalFixedMock: UnflattenedReport = {
  rp: {
    id: 'rprAfNrce73O',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-21T07:29:01.958Z'),
    purpose: '#8:  Jan 2023',
    currency: 'USD',
    amount: 116.9,
    tax: 17.83,
    state: 'APPROVER_PENDING',
    source: 'WORKFLOWS',
    num_transactions: 1,
    approvals: null,
    settlement_id: null,
    approved_at: null,
    reimbursed_at: null,
    submitted_at: new Date('2023-01-21T07:29:03.656Z'),
    verification_state: null,
    trip_request_id: null,
    physical_bill: false,
    physical_bill_at: null,
    exported: null,
    manual_flag: false,
    policy_flag: false,
    claim_number: 'C/2023/01/R/16',
    from_dt: null,
    to_dt: null,
    location1: null,
    location2: null,
    location3: null,
    location4: null,
    location5: null,
    type: 'EXPENSE',
    locations: [],
    risk_state_expense_count: null,
    risk_state: null,
  },
  ou: {
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    location: 'Mumbai',
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department: '0000000',
    sub_department: null,
    mobile: '123456',
    title: 'director',
    employee_id: '',
    level: 123,
    status: 'ACTIVE',
    org_name: 'Staging Loaded',
    department_id: 'deptpmQ0SsMO0S',
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
};
