export const apiErptcReportsRes = [
  {
    rp_id: 'rpfClhA1lglE',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2023-01-19T07:27:33.235Z'),
    rp_purpose: 'test_manage_columns',
    rp_currency: 'INR',
    rp_amount: 145,
    rp_tax: 15.54,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WEBAPP',
    rp_num_transactions: 3,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-19T07:27:36.879Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/31',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: '123wqe',
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpG0qW1oL4DX',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2023-01-04T00:00:13.630Z'),
    rp_purpose: '#1: October 2022',
    rp_currency: 'INR',
    rp_amount: 121124.70000000001,
    rp_tax: 0,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'TPA',
    rp_num_transactions: 2,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-04T00:00:13.630Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: false,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/11',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: '123wqe',
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpqzKD4bPXpW',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2022-04-10T04:35:09.284Z'),
    rp_purpose: '#21:  Apr 2022',
    rp_currency: 'INR',
    rp_amount: 818958.934675,
    rp_tax: 71.52,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WEBAPP',
    rp_num_transactions: 32,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-04T00:00:13.630Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: false,
    rp_manual_flag: true,
    rp_policy_flag: true,
    rp_claim_number: 'C/2022/04/R/70',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: '123wqe',
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpRmtgbN7P3F',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2022-04-10T04:33:59.667Z'),
    rp_purpose: '#17:  Apr 2022',
    rp_currency: 'INR',
    rp_amount: 0,
    rp_tax: null,
    rp_state: 'DRAFT',
    rp_source: 'WEBAPP',
    rp_num_transactions: 0,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: null,
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: null,
    rp_policy_flag: null,
    rp_claim_number: 'C/2022/04/R/69',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: '123wqe',
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
];

export const apiCreateDraftRes = {
  created_at: '2023-01-19T16:25:46.804Z',
  updated_at: '2023-01-19T16:25:46.804Z',
  last_updated_by: {
    user_id: 'usvKA4X8Ugcr',
    org_user_id: 'ouCI4UQ2G0K1',
    org_id: 'orrjqbDbeP9p',
    roles: ['APPROVER', 'ADMIN', 'FYLER', 'HOP', 'FINANCE', 'PAYMENT_PROCESSOR', 'VERIFIER', 'AUDITOR', 'OWNER'],
    scopes: [],
    allowed_CIDRs: [],
    cluster_domain: '"https://staging.fyle.tech"',
    proxy_org_user_id: null,
    tpa_id: null,
    tpa_name: null,
    name: 'ouCI4UQ2G0K1',
  },
  id: 'rp6LK3ghVatB',
  org_user_id: 'ouCI4UQ2G0K1',
  purpose: '#6:  Jan 2023',
  currency: 'INR',
  creator_id: 'ouCI4UQ2G0K1',
  amount: 0,
  tax: null,
  status_id: null,
  num_transactions: 0,
  tally_export_id: null,
  state: 'DRAFT',
  source: 'MOBILE',
  reimbursement_id: null,
  approved_at: null,
  reimbursed_at: null,
  submitted_at: null,
  settlement_id: null,
  verification_state: null,
  trip_request_id: null,
  physical_bill: false,
  exported: null,
  manual_flag: null,
  policy_flag: null,
  claim_number: 'C/2023/01/R/35',
  physical_bill_at: null,
  from_dt: null,
  to_dt: null,
  location1: null,
  location2: null,
  location3: null,
  location4: null,
  location5: null,
  type: 'EXPENSE',
};
