import { ExtendedReport } from '../models/report.model';

export const apiExtendedReportRes = [
  {
    rp_id: 'rprAfNrce73O',
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_created_at: '2023-01-21T07:29:01.958Z',
    rp_purpose: '#8:  Jan 2023',
    rp_currency: 'INR',
    rp_amount: 116.9,
    rp_tax: 17.83,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WORKFLOWS',
    rp_num_transactions: 1,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-21T07:29:03.656Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/16',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouX8dwsbLCLv',
    ou_org_id: 'orNVthTo2Zyo',
    ou_location: 'Mumbai',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_sub_department: null,
    ou_mobile: '123456',
    ou_title: 'director',
    ou_employee_id: '',
    ou_level: '123',
    ou_status: 'ACTIVE',
    ou_org_name: 'Staging Loaded',
    ou_department_id: 'deptpmQ0SsMO0S',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpLMyvYSXgJy',
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_created_at: '2023-01-18T07:29:00.749Z',
    rp_purpose: '#7:  Jan 2023',
    rp_currency: 'INR',
    rp_amount: 4652,
    rp_tax: 695.5,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WORKFLOWS',
    rp_num_transactions: 3,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-18T07:29:04.487Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/15',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouX8dwsbLCLv',
    ou_org_id: 'orNVthTo2Zyo',
    ou_location: 'Mumbai',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_sub_department: null,
    ou_mobile: '123456',
    ou_title: 'director',
    ou_employee_id: '',
    ou_level: '123',
    ou_status: 'ACTIVE',
    ou_org_name: 'Staging Loaded',
    ou_department_id: 'deptpmQ0SsMO0S',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpxtbiLXQZUm',
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_created_at: '2023-01-17T07:29:00.800Z',
    rp_purpose: '#6:  Jan 2023',
    rp_currency: 'INR',
    rp_amount: 347.45800399999996,
    rp_tax: 53,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WORKFLOWS',
    rp_num_transactions: 1,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-17T07:29:01.751Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/12',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouX8dwsbLCLv',
    ou_org_id: 'orNVthTo2Zyo',
    ou_location: 'Mumbai',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_sub_department: null,
    ou_mobile: '123456',
    ou_title: 'director',
    ou_employee_id: '',
    ou_level: '123',
    ou_status: 'ACTIVE',
    ou_org_name: 'Staging Loaded',
    ou_department_id: 'deptpmQ0SsMO0S',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpSGcIEwzxDd',
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_created_at: '2023-01-17T06:34:58.398Z',
    rp_purpose: '#4:  Jan 2023',
    rp_currency: 'INR',
    rp_amount: 9400,
    rp_tax: 1152.3,
    rp_state: 'APPROVER_INQUIRY',
    rp_source: 'WEBAPP',
    rp_num_transactions: 4,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: '2023-01-17T06:34:59.523Z',
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: true,
    rp_claim_number: 'C/2023/01/R/10',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouX8dwsbLCLv',
    ou_org_id: 'orNVthTo2Zyo',
    ou_location: 'Mumbai',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_sub_department: null,
    ou_mobile: '123456',
    ou_title: 'director',
    ou_employee_id: '',
    ou_level: '123',
    ou_status: 'ACTIVE',
    ou_org_name: 'Staging Loaded',
    ou_department_id: 'deptpmQ0SsMO0S',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
];

export const reportParam = {
  _search_document:
    "'46040':4 'a':8,14,20,26 'abhishek':32 'ajain@fyle.in':34 'business':11,17,23,29 'c/2022/10/r/37':5 'director':6 'indeed':13,19,25,31 'inr':3 'jain':33 'long':10,16,22,28 'mumbai':7 'report':2 'testing':1 'unit':12,18,24,30 'very':9,15,21,27",
  approved_by: null,
  ou_business_unit:
    'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
  ou_department: '0000000',
  ou_department_id: 'deptpmQ0SsMO0S',
  ou_employee_id: '',
  ou_id: 'ouX8dwsbLCLv',
  ou_level: '123',
  ou_level_id: 'lvlPtroPaClQy',
  ou_location: 'Mumbai',
  ou_mobile: '123456',
  ou_org_id: 'orNVthTo2Zyo',
  ou_org_name: 'Staging Loaded',
  ou_status: '"ACTIVE"',
  ou_sub_department: null,
  ou_title: 'director',
  report_approvals: null,
  rp_amount: 46040,
  rp_approval_state: null,
  rp_approved_at: null,
  rp_claim_number: 'C/2022/10/R/37',
  rp_created_at: new Date('2022-10-31T13:54:46.317208'),
  rp_currency: 'INR',
  rp_exported: false,
  rp_from_dt: null,
  rp_id: 'rptkwzhsieIY',
  rp_locations: [],
  rp_manual_flag: false,
  rp_num_transactions: 4,
  rp_org_user_id: 'ouX8dwsbLCLv',
  rp_physical_bill: false,
  rp_physical_bill_at: null,
  rp_policy_flag: false,
  rp_purpose: 'My Testing Report',
  rp_reimbursed_at: null,
  rp_risk_state: null,
  rp_risk_state_expense_count: null,
  rp_settlement_id: null,
  rp_source: 'MOBILE',
  rp_state: 'DRAFT',
  rp_submitted_at: null,
  rp_tax: 101.29,
  rp_to_dt: null,
  rp_trip_request_id: null,
  rp_type: 'EXPENSE',
  rp_verification_state: null,
  rp_verified: false,
  sequential_approval_turn: false,
  us_email: 'ajain@fyle.in',
  us_full_name: 'Abhishek Jain',
};
