import { ExtendedReport } from '../models/report.model';

export const apiExtendedReportRes: ExtendedReport[] = [
  {
    rp_id: 'rprAfNrce73O',
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_created_at: new Date('2023-01-21T07:29:01.958Z'),
    rp_purpose: '#8:  Jan 2023',
    rp_currency: 'USD',
    rp_amount: 116.9,
    rp_tax: 17.83,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WORKFLOWS',
    rp_num_transactions: 1,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: new Date('2023-01-21T07:29:03.656Z'),
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/16',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouX8dwsbLCLv',
    ou_org_id: 'orNVthTo2Zyo',
    ou_location: 'Mumbai',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_sub_department: null,
    ou_mobile: '123456',
    ou_title: 'director',
    ou_employee_id: '',
    ou_level: 123,
    ou_status: 'ACTIVE',
    ou_org_name: 'Staging Loaded',
    ou_department_id: 'deptpmQ0SsMO0S',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpLMyvYSXgJy',
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_created_at: new Date('2023-01-18T07:29:00.749Z'),
    rp_purpose: '#7:  Jan 2023',
    rp_currency: 'USD',
    rp_amount: 4652,
    rp_tax: 695.5,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WORKFLOWS',
    rp_num_transactions: 3,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: new Date('2023-01-18T07:29:04.487Z'),
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/15',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouX8dwsbLCLv',
    ou_org_id: 'orNVthTo2Zyo',
    ou_location: 'Mumbai',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_sub_department: null,
    ou_mobile: '123456',
    ou_title: 'director',
    ou_employee_id: '',
    ou_level: 123,
    ou_status: 'ACTIVE',
    ou_org_name: 'Staging Loaded',
    ou_department_id: 'deptpmQ0SsMO0S',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpxtbiLXQZUm',
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_created_at: new Date('2023-01-17T07:29:00.800Z'),
    rp_purpose: '#6:  Jan 2023',
    rp_currency: 'USD',
    rp_amount: 347.45800399999996,
    rp_tax: 53,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WORKFLOWS',
    rp_num_transactions: 1,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: new Date('2023-01-17T07:29:01.751Z'),
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/12',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouX8dwsbLCLv',
    ou_org_id: 'orNVthTo2Zyo',
    ou_location: 'Mumbai',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_sub_department: null,
    ou_mobile: '123456',
    ou_title: 'director',
    ou_employee_id: '',
    ou_level: 123,
    ou_status: 'ACTIVE',
    ou_org_name: 'Staging Loaded',
    ou_department_id: 'deptpmQ0SsMO0S',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpSGcIEwzxDd',
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_created_at: new Date('2023-01-17T06:34:58.398Z'),
    rp_purpose: '#4:  Jan 2023',
    rp_currency: 'USD',
    rp_amount: 9400,
    rp_tax: 1152.3,
    rp_state: 'APPROVER_INQUIRY',
    rp_source: 'WEBAPP',
    rp_num_transactions: 4,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: new Date('2023-01-17T06:34:59.523Z'),
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: true,
    rp_claim_number: 'C/2023/01/R/10',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouX8dwsbLCLv',
    ou_org_id: 'orNVthTo2Zyo',
    ou_location: 'Mumbai',
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_sub_department: null,
    ou_mobile: '123456',
    ou_title: 'director',
    ou_employee_id: '',
    ou_level: 123,
    ou_status: 'ACTIVE',
    ou_org_name: 'Staging Loaded',
    ou_department_id: 'deptpmQ0SsMO0S',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
];

export const expectedAllReports: ExtendedReport[] = [
  {
    _search_document:
      "'0':5 '2023':3 '4':1 'a':8 'abhishek':10 'ajain@fyle.in':12 'bangalore':9 'c/2023/02/r/5':6 'feb':2 'inr':4 'jain':11 'lion':7",
    approved_by: null,
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_department_id: 'deptSdAUA5Urej',
    ou_employee_id: 'A',
    ou_id: 'ouCI4UQ2G0K1',
    ou_level: 123,
    ou_level_id: 'lvlEtPwKjAF6U',
    ou_location: 'bangalore',
    ou_mobile: null,
    ou_org_id: 'orrjqbDbeP9p',
    ou_org_name: 'Fyle Staging',
    ou_status: '"ACTIVE"',
    ou_sub_department: 'Primary Sales',
    ou_title: 'lion',
    report_approvals: null,
    rp_amount: 0,
    rp_approval_state: null,
    rp_approved_at: null,
    rp_claim_number: 'C/2023/02/R/5',
    rp_created_at: new Date('2023-02-01T00:23:42.505Z'),
    rp_currency: 'USD',
    rp_exported: false,
    rp_from_dt: null,
    rp_id: 'rpkkdCNBFsJ2',
    rp_locations: [],
    rp_manual_flag: false,
    rp_num_transactions: 0,
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_physical_bill: true,
    rp_physical_bill_at: new Date('2023-02-01T00:23:45.938Z'),
    rp_policy_flag: false,
    rp_purpose: '#4:  Feb 2023',
    rp_reimbursed_at: null,
    rp_risk_state: null,
    rp_risk_state_expense_count: null,
    rp_settlement_id: null,
    rp_source: 'MOBILE',
    rp_state: 'APPROVER_PENDING',
    rp_submitted_at: new Date('2023-02-01T00:23:46.556Z'),
    rp_tax: 0,
    rp_to_dt: null,
    rp_trip_request_id: null,
    rp_type: 'EXPENSE',
    rp_verification_state: null,
    rp_verified: false,
    sequential_approval_turn: false,
    us_email: 'ajain@fyle.in',
    us_full_name: 'Abhishek Jain',
  },
  {
    _search_document:
      "'16370.8':5 '2023':3 '4':1 'a':8 'abhishek':10 'ajain@fyle.in':12 'bangalore':9 'c/2023/02/r/4':6 'feb':2 'inr':4 'jain':11 'lion':7",
    approved_by: null,
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_department_id: 'deptSdAUA5Urej',
    ou_employee_id: 'A',
    ou_id: 'ouCI4UQ2G0K1',
    ou_level: 123,
    ou_level_id: 'lvlEtPwKjAF6U',
    ou_location: 'bangalore',
    ou_mobile: null,
    ou_org_id: 'orrjqbDbeP9p',
    ou_org_name: 'Fyle Staging',
    ou_status: '"ACTIVE"',
    ou_sub_department: 'Primary Sales',
    ou_title: 'lion',
    report_approvals: null,
    rp_amount: 16370.8,
    rp_approval_state: null,
    rp_approved_at: null,
    rp_claim_number: 'C/2023/02/R/4',
    rp_created_at: new Date('2023-02-01T00:23:42.495Z'),
    rp_currency: 'USD',
    rp_exported: false,
    rp_from_dt: null,
    rp_id: 'rpNiAxUFhUlo',
    rp_locations: [],
    rp_manual_flag: false,
    rp_num_transactions: 1,
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_policy_flag: false,
    rp_purpose: '#4:  Feb 2023',
    rp_reimbursed_at: null,
    rp_risk_state: null,
    rp_risk_state_expense_count: null,
    rp_settlement_id: null,
    rp_source: 'MOBILE',
    rp_state: 'DRAFT',
    rp_submitted_at: null,
    rp_tax: 15509.18,
    rp_to_dt: null,
    rp_trip_request_id: null,
    rp_type: 'EXPENSE',
    rp_verification_state: null,
    rp_verified: false,
    sequential_approval_turn: false,
    us_email: 'ajain@fyle.in',
    us_full_name: 'Abhishek Jain',
  },
];

export const expectedPaginatedReports: ExtendedReport[] = [
  {
    _search_document:
      "'0':5 '2023':3 '4':1 'a':8 'abhishek':10 'ajain@fyle.in':12 'bangalore':9 'c/2023/02/r/5':6 'feb':2 'inr':4 'jain':11 'lion':7",
    approved_by: null,
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_department_id: 'deptSdAUA5Urej',
    ou_employee_id: 'A',
    ou_id: 'ouCI4UQ2G0K1',
    ou_level: 123,
    ou_level_id: 'lvlEtPwKjAF6U',
    ou_location: 'bangalore',
    ou_mobile: null,
    ou_org_id: 'orrjqbDbeP9p',
    ou_org_name: 'Fyle Staging',
    ou_status: '"ACTIVE"',
    ou_sub_department: 'Primary Sales',
    ou_title: 'lion',
    report_approvals: null,
    rp_amount: 0,
    rp_approval_state: null,
    rp_approved_at: null,
    rp_claim_number: 'C/2023/02/R/5',
    rp_created_at: new Date('2023-02-01T00:23:42.505Z'),
    rp_currency: 'USD',
    rp_exported: false,
    rp_from_dt: null,
    rp_id: 'rpkkdCNBFsJ2',
    rp_locations: [],
    rp_manual_flag: false,
    rp_num_transactions: 0,
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_physical_bill: true,
    rp_physical_bill_at: new Date('2023-02-01T00:23:45.938Z'),
    rp_policy_flag: false,
    rp_purpose: '#4:  Feb 2023',
    rp_reimbursed_at: null,
    rp_risk_state: null,
    rp_risk_state_expense_count: null,
    rp_settlement_id: null,
    rp_source: 'MOBILE',
    rp_state: 'APPROVER_PENDING',
    rp_submitted_at: new Date('2023-02-01T00:23:46.556Z'),
    rp_tax: 0,
    rp_to_dt: null,
    rp_trip_request_id: null,
    rp_type: 'EXPENSE',
    rp_verification_state: null,
    rp_verified: false,
    sequential_approval_turn: false,
    us_email: 'ajain@fyle.in',
    us_full_name: 'Abhishek Jain',
  },
  {
    _search_document:
      "'16370.8':5 '2023':3 '4':1 'a':8 'abhishek':10 'ajain@fyle.in':12 'bangalore':9 'c/2023/02/r/4':6 'feb':2 'inr':4 'jain':11 'lion':7",
    approved_by: null,
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_department_id: 'deptSdAUA5Urej',
    ou_employee_id: 'A',
    ou_id: 'ouCI4UQ2G0K1',
    ou_level: 123,
    ou_level_id: 'lvlEtPwKjAF6U',
    ou_location: 'bangalore',
    ou_mobile: null,
    ou_org_id: 'orrjqbDbeP9p',
    ou_org_name: 'Fyle Staging',
    ou_status: '"ACTIVE"',
    ou_sub_department: 'Primary Sales',
    ou_title: 'lion',
    report_approvals: null,
    rp_amount: 16370.8,
    rp_approval_state: null,
    rp_approved_at: null,
    rp_claim_number: 'C/2023/02/R/4',
    rp_created_at: new Date('2023-02-01T00:23:42.495Z'),
    rp_currency: 'USD',
    rp_exported: false,
    rp_from_dt: null,
    rp_id: 'rpNiAxUFhUlo',
    rp_locations: [],
    rp_manual_flag: false,
    rp_num_transactions: 1,
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_policy_flag: false,
    rp_purpose: '#4:  Feb 2023',
    rp_reimbursed_at: null,
    rp_risk_state: null,
    rp_risk_state_expense_count: null,
    rp_settlement_id: null,
    rp_source: 'MOBILE',
    rp_state: 'DRAFT',
    rp_submitted_at: null,
    rp_tax: 15509.18,
    rp_to_dt: null,
    rp_trip_request_id: null,
    rp_type: 'EXPENSE',
    rp_verification_state: null,
    rp_verified: false,
    sequential_approval_turn: false,
    us_email: 'ajain@fyle.in',
    us_full_name: 'Abhishek Jain',
  },
  {
    _search_document:
      "'0':5 '2023':3 '5':1 'a':9,15,21,27 'abhishek':33 'ajain@fyle.in':35 'business':12,18,24,30 'c/2023/01/r/11':6 'director':7 'indeed':14,20,26,32 'inr':4 'jain':34 'jan':2 'long':11,17,23,29 'mumbai':8 'unit':13,19,25,31 'very':10,16,22,28",
    approved_by: null,
    ou_business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    ou_department: '0000000',
    ou_department_id: 'deptpmQ0SsMO0S',
    ou_employee_id: '',
    ou_id: 'ouX8dwsbLCLv',
    ou_level: 123,
    ou_level_id: 'lvlPtroPaClQy',
    ou_location: 'Mumbai',
    ou_mobile: '123456',
    ou_org_id: 'orNVthTo2Zyo',
    ou_org_name: 'Staging Loaded',
    ou_status: '"ACTIVE"',
    ou_sub_department: null,
    ou_title: 'director',
    report_approvals: null,
    rp_amount: 0,
    rp_approval_state: null,
    rp_approved_at: null,
    rp_claim_number: 'C/2023/01/R/11',
    rp_created_at: new Date('2023-01-17T01:05:06.814Z'),
    rp_currency: 'USD',
    rp_exported: false,
    rp_from_dt: null,
    rp_id: 'rpFE5X1Pqi9P',
    rp_locations: [],
    rp_manual_flag: false,
    rp_num_transactions: 0,
    rp_org_user_id: 'ouX8dwsbLCLv',
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_policy_flag: false,
    rp_purpose: '#5:  Jan 2023',
    rp_reimbursed_at: null,
    rp_risk_state: null,
    rp_risk_state_expense_count: null,
    rp_settlement_id: null,
    rp_source: 'MOBILE',
    rp_state: 'DRAFT',
    rp_submitted_at: null,
    rp_tax: null,
    rp_to_dt: null,
    rp_trip_request_id: null,
    rp_type: 'EXPENSE',
    rp_verification_state: null,
    rp_verified: false,
    sequential_approval_turn: false,
    us_email: 'ajain@fyle.in',
    us_full_name: 'Abhishek Jain',
  },
];

export const reportParam: ExtendedReport = {
  _search_document:
    "'46040':4 'a':8,14,20,26 'abhishek':32 'ajain@fyle.in':34 'business':11,17,23,29 'c/2022/10/r/37':5 'director':6 'indeed':13,19,25,31 'inr':3 'jain':33 'long':10,16,22,28 'mumbai':7 'report':2 'testing':1 'unit':12,18,24,30 'very':9,15,21,27",
  approved_by: null,
  ou_business_unit:
    'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
  ou_department: '0000000',
  ou_department_id: 'deptpmQ0SsMO0S',
  ou_employee_id: '',
  ou_id: 'ouX8dwsbLCLv',
  ou_level: 123,
  ou_level_id: 'lvlPtroPaClQy',
  ou_location: 'Mumbai',
  ou_mobile: '123456',
  ou_org_id: 'orNVthTo2Zyo',
  ou_org_name: 'Staging Loaded',
  ou_status: '"ACTIVE"',
  ou_sub_department: null,
  ou_title: 'director',
  report_approvals: null,
  rp_amount: 46040,
  rp_approval_state: null,
  rp_approved_at: null,
  rp_claim_number: 'C/2022/10/R/37',
  rp_created_at: new Date('2022-10-31T13:54:46.317208'),
  rp_currency: 'USD',
  rp_exported: false,
  rp_from_dt: null,
  rp_id: 'rptkwzhsieIY',
  rp_locations: [],
  rp_manual_flag: false,
  rp_num_transactions: 4,
  rp_org_user_id: 'ouX8dwsbLCLv',
  rp_physical_bill: false,
  rp_physical_bill_at: null,
  rp_policy_flag: false,
  rp_purpose: 'My Testing Report',
  rp_state: 'APPROVAL_PENDING',
  rp_reimbursed_at: null,
  rp_risk_state: null,
  rp_risk_state_expense_count: null,
  rp_settlement_id: null,
  rp_to_dt: null,
  rp_trip_request_id: null,
  rp_type: 'EXPENSE',
  rp_verification_state: null,
  rp_verified: false,
  sequential_approval_turn: false,
  us_email: 'ajain@fyle.in',
  us_full_name: 'Abhishek Jain',
};

export const expectedReportSingleResponse: ExtendedReport = {
  _search_document:
    "'145':5 'a':8 'abhishek':10 'ajain@fyle.in':12 'bangalore':9 'c/2023/01/r/31':6 'columns':3 'inr':4 'jain':11 'lion':7 'manage':2 'test':1",
  approved_by: ['out3t2X258rd'],
  ou_business_unit: null,
  ou_department: 'Primary Sales',
  ou_department_id: 'deptSdAUA5Urej',
  ou_employee_id: 'A',
  ou_id: 'ouCI4UQ2G0K1',
  ou_level: 123,
  ou_level_id: 'lvlEtPwKjAF6U',
  ou_location: 'bangalore',
  ou_mobile: null,
  ou_org_id: 'orrjqbDbeP9p',
  ou_org_name: 'Fyle Staging',
  ou_status: '"ACTIVE"',
  ou_sub_department: 'Primary Sales',
  ou_title: 'lion',
  report_approvals: {
    out3t2X258rd: {
      rank: 0,
      state: 'APPROVAL_PENDING',
    },
  },
  rp_amount: 145,
  rp_approval_state: null,
  rp_approved_at: null,
  rp_claim_number: 'C/2023/01/R/31',
  rp_created_at: new Date('2023-01-19T07:27:33.235573'),
  rp_currency: 'USD',
  rp_exported: false,
  rp_from_dt: null,
  rp_id: 'rpfClhA1lglE',
  rp_locations: [],
  rp_manual_flag: false,
  rp_num_transactions: 3,
  rp_org_user_id: 'ouCI4UQ2G0K1',
  rp_physical_bill: false,
  rp_physical_bill_at: null,
  rp_policy_flag: false,
  rp_purpose: 'test_manage_columns',
  rp_reimbursed_at: null,
  rp_risk_state: null,
  rp_risk_state_expense_count: null,
  rp_settlement_id: null,
  rp_source: 'WEBAPP',
  rp_state: 'APPROVER_PENDING',
  rp_submitted_at: new Date('2023-01-19T07:27:36.879'),
  rp_tax: 15.54,
  rp_to_dt: null,
  rp_trip_request_id: null,
  rp_type: 'EXPENSE',
  rp_verification_state: null,
  rp_verified: false,
  sequential_approval_turn: false,
  us_email: 'ajain@fyle.in',
  us_full_name: 'Abhishek Jain',
};

export const apiErptcReportsRes: ExtendedReport[] = [
  {
    rp_id: 'rpfClhA1lglE',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2023-01-19T07:27:33.235Z'),
    rp_purpose: 'test_manage_columns',
    rp_currency: 'USD',
    rp_amount: 145,
    rp_tax: 15.54,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WEBAPP',
    rp_num_transactions: 3,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: new Date('2023-01-19T07:27:36.879Z'),
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/31',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: 123,
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpG0qW1oL4DX',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2023-01-04T00:00:13.630Z'),
    rp_purpose: '#1: October 2022',
    rp_currency: 'USD',
    rp_amount: 121124.70000000001,
    rp_tax: 0,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'TPA',
    rp_num_transactions: 2,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: new Date('2023-01-04T00:00:13.630Z'),
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: false,
    rp_manual_flag: false,
    rp_policy_flag: false,
    rp_claim_number: 'C/2023/01/R/11',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: 123,
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpqzKD4bPXpW',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2022-04-10T04:35:09.284Z'),
    rp_purpose: '#21:  Apr 2022',
    rp_currency: 'USD',
    rp_amount: 818958.934675,
    rp_tax: 71.52,
    rp_state: 'APPROVER_PENDING',
    rp_source: 'WEBAPP',
    rp_num_transactions: 32,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: new Date('2023-01-04T00:00:13.630Z'),
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: false,
    rp_manual_flag: true,
    rp_policy_flag: true,
    rp_claim_number: 'C/2022/04/R/70',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: 123,
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
  {
    rp_id: 'rpRmtgbN7P3F',
    rp_org_user_id: 'ouCI4UQ2G0K1',
    rp_created_at: new Date('2022-04-10T04:33:59.667Z'),
    rp_purpose: '#17:  Apr 2022',
    rp_currency: 'USD',
    rp_amount: 0,
    rp_tax: null,
    rp_state: 'DRAFT',
    rp_source: 'WEBAPP',
    rp_num_transactions: 0,
    rp_approvals: null,
    rp_settlement_id: null,
    rp_approved_at: null,
    rp_reimbursed_at: null,
    rp_submitted_at: null,
    rp_verification_state: null,
    rp_trip_request_id: null,
    rp_physical_bill: false,
    rp_physical_bill_at: null,
    rp_exported: null,
    rp_manual_flag: null,
    rp_policy_flag: null,
    rp_claim_number: 'C/2022/04/R/69',
    rp_from_dt: null,
    rp_to_dt: null,
    rp_location1: null,
    rp_location2: null,
    rp_location3: null,
    rp_location4: null,
    rp_location5: null,
    rp_type: 'EXPENSE',
    rp_locations: [],
    ou_id: 'ouCI4UQ2G0K1',
    ou_org_id: 'orrjqbDbeP9p',
    ou_location: 'bangalore',
    ou_business_unit: null,
    ou_department: 'Primary Sales',
    ou_sub_department: 'Primary Sales',
    ou_mobile: null,
    ou_title: 'lion',
    ou_employee_id: 'A',
    ou_level: 123,
    ou_status: 'ACTIVE',
    ou_org_name: 'Fyle Staging',
    ou_department_id: 'deptSdAUA5Urej',
    us_full_name: 'Abhishek Jain',
    us_email: 'ajain@fyle.in',
    rp_risk_state_expense_count: null,
    rp_risk_state: null,
  },
];

export const newReportParam = {
  _search_document:
    "'46040':4 'a':8,14,20,26 'abhishek':32 'ajain@fyle.in':34 'business':11,17,23,29 'c/2022/10/r/37':5 'director':6 'indeed':13,19,25,31 'inr':3 'jain':33 'long':10,16,22,28 'mumbai':7 'report':2 'testing':1 'unit':12,18,24,30 'very':9,15,21,27",
  approved_by: null,
  ou_business_unit:
    'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
  ou_department: '0000000',
  ou_department_id: 'deptpmQ0SsMO0S',
  ou_employee_id: '',
  ou_id: 'ouX8dwsbLCLv',
  ou_level: 123,
  ou_level_id: 'lvlPtroPaClQy',
  ou_location: 'Mumbai',
  ou_mobile: '123456',
  ou_org_id: 'orNVthTo2Zyo',
  ou_org_name: 'Staging Loaded',
  ou_status: '"ACTIVE"',
  ou_sub_department: null,
  ou_title: 'director',
  report_approvals: null,
  rp_amount: 46040,
  rp_approval_state: null,
  rp_approved_at: null,
  rp_claim_number: 'C/2022/10/R/37',
  rp_created_at: new Date('2022-10-31T13:54:46.317208'),
  rp_currency: 'USD',
  rp_exported: false,
  rp_from_dt: null,
  rp_id: 'rptkwzhsieIY',
  rp_locations: [],
  rp_manual_flag: false,
  rp_num_transactions: 4,
  rp_org_user_id: 'ouX8dwsbLCLv',
  rp_physical_bill: false,
  rp_physical_bill_at: null,
  rp_policy_flag: false,
  rp_purpose: 'A report',
  rp_state: 'APPROVAL_PENDING',
  rp_reimbursed_at: null,
  rp_risk_state: null,
  rp_risk_state_expense_count: null,
  rp_settlement_id: null,
  rp_to_dt: null,
  rp_trip_request_id: null,
  rp_type: 'EXPENSE',
  rp_verification_state: null,
  rp_verified: false,
  sequential_approval_turn: false,
  us_email: 'ajain@fyle.in',
  us_full_name: 'Abhishek Jain',
};

export const reportData1: ExtendedReport = {
  _search_document:
    "'0':7 '2023':3 '3':1 'a':11,17,23,29 'abhishek':35 'ajain@fyle.in':37 'business':14,20,26,32 'c/2023/07/r/17':8 'director':9 'expense':5 'indeed':16,22,28,34 'inr':6 'jain':36 'jul':2 'long':13,19,25,31 'mumbai':10 'office':4 'unit':15,21,27,33 'very':12,18,24,30",
  approved_by: null,
  ou_business_unit:
    'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
  ou_department: '0000000',
  ou_department_id: 'dept7HJ9C4wvtX',
  ou_employee_id: '',
  ou_id: 'ouX8dwsbLCLv',
  ou_level: 123,
  ou_level_id: 'lvlPtroPaClQy',
  ou_location: 'Mumbai',
  ou_mobile: null,
  ou_org_id: 'orNVthTo2Zyo',
  ou_org_name: 'Staging Loaded',
  ou_status: '"ACTIVE"',
  ou_sub_department: 'arun',
  ou_title: 'director',
  report_approvals: null,
  rp_amount: 0,
  rp_approval_state: null,
  rp_approved_at: null,
  rp_claim_number: 'C/2023/07/R/17',
  rp_created_at: new Date('2023-07-11T06:19:28.260142'),
  rp_currency: 'INR',
  rp_exported: false,
  rp_from_dt: null,
  rp_id: 'rpMvN0P10l6F',
  rp_locations: [],
  rp_manual_flag: false,
  rp_num_transactions: 0,
  rp_org_user_id: 'ouX8dwsbLCLv',
  rp_physical_bill: false,
  rp_physical_bill_at: null,
  rp_policy_flag: false,
  rp_purpose: '#3:  Jul 2023 - Office expense',
  rp_reimbursed_at: null,
  rp_risk_state: null,
  rp_risk_state_expense_count: null,
  rp_settlement_id: null,
  rp_source: 'WEBAPP',
  rp_state: 'DRAFT',
  rp_submitted_at: null,
  rp_tax: null,
  rp_to_dt: null,
  rp_trip_request_id: null,
  rp_type: 'EXPENSE',
  rp_verification_state: null,
  rp_verified: false,
  sequential_approval_turn: false,
  us_email: 'ajain@fyle.in',
  us_full_name: 'Abhishek Jain',
};
