import { ReportOptions } from '../models/report-options.model';
import { expectedErpt, expectedUnflattenedReports } from './report-unflattened.data';

export const reportOptionsData: ReportOptions[] = [
  {
    label: 'report1',
    value: expectedErpt[0],
  },
  {
    label: 'report2',
    value: expectedErpt[1],
  },
];

export const reportOptionsData2: ReportOptions[] = [
  {
    label: 'report1',
    value: {
      ...expectedErpt[0],
      rp: {
        ...expectedErpt[0].rp,
        state: 'DRAFT',
      },
    },
  },
];

export const reportOptionsData3: ReportOptions[] = [
  {
    label: '#8:  Jan 2023',
    value: {
      rp: {
        id: 'rprAfNrce73O',
        org_user_id: 'ouX8dwsbLCLv',
        created_at: new Date('2023-01-21T07:29:01.958Z'),
        purpose: '#8:  Jan 2023',
        currency: 'USD',
        amount: 116.9,
        tax: 17.83,
        state: 'APPROVER_PENDING',
        source: 'WORKFLOWS',
        num_transactions: 1,
        approvals: null,
        settlement_id: null,
        approved_at: null,
        reimbursed_at: null,
        submitted_at: new Date('2023-01-21T07:29:03.656Z'),
        verification_state: null,
        trip_request_id: null,
        physical_bill: false,
        physical_bill_at: null,
        exported: null,
        manual_flag: false,
        policy_flag: false,
        claim_number: 'C/2023/01/R/16',
        from_dt: null,
        to_dt: null,
        location1: null,
        location2: null,
        location3: null,
        location4: null,
        location5: null,
        type: 'EXPENSE',
        locations: [],
        risk_state_expense_count: null,
        risk_state: null,
      },
      ou: {
        id: 'ouX8dwsbLCLv',
        org_id: 'orNVthTo2Zyo',
        location: 'Mumbai',
        business_unit:
          'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
        department: '0000000',
        sub_department: null,
        mobile: '123456',
        title: 'director',
        employee_id: '',
        level: 123,
        status: 'ACTIVE',
        org_name: 'Staging Loaded',
        department_id: 'deptpmQ0SsMO0S',
      },
      us: {
        full_name: 'Abhishek Jain',
        email: 'ajain@fyle.in',
      },
    },
  },
  {
    label: '#7:  Jan 2023',
    value: {
      rp: {
        id: 'rpLMyvYSXgJy',
        org_user_id: 'ouX8dwsbLCLv',
        created_at: new Date('2023-01-18T07:29:00.749Z'),
        purpose: '#7:  Jan 2023',
        currency: 'USD',
        amount: 4652,
        tax: 695.5,
        state: 'APPROVER_PENDING',
        source: 'WORKFLOWS',
        num_transactions: 3,
        approvals: null,
        settlement_id: null,
        approved_at: null,
        reimbursed_at: null,
        submitted_at: new Date('2023-01-18T07:29:04.487Z'),
        verification_state: null,
        trip_request_id: null,
        physical_bill: false,
        physical_bill_at: null,
        exported: null,
        manual_flag: false,
        policy_flag: false,
        claim_number: 'C/2023/01/R/15',
        from_dt: null,
        to_dt: null,
        location1: null,
        location2: null,
        location3: null,
        location4: null,
        location5: null,
        type: 'EXPENSE',
        locations: [],
        risk_state_expense_count: null,
        risk_state: null,
      },
      ou: {
        id: 'ouX8dwsbLCLv',
        org_id: 'orNVthTo2Zyo',
        location: 'Mumbai',
        business_unit:
          'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
        department: '0000000',
        sub_department: null,
        mobile: '123456',
        title: 'director',
        employee_id: '',
        level: 123,
        status: 'ACTIVE',
        org_name: 'Staging Loaded',
        department_id: 'deptpmQ0SsMO0S',
      },
      us: {
        full_name: 'Abhishek Jain',
        email: 'ajain@fyle.in',
      },
    },
  },
  {
    label: '#6:  Jan 2023',
    value: {
      rp: {
        id: 'rpxtbiLXQZUm',
        org_user_id: 'ouX8dwsbLCLv',
        created_at: new Date('2023-01-17T07:29:00.800Z'),
        purpose: '#6:  Jan 2023',
        currency: 'USD',
        amount: 347.45800399999996,
        tax: 53,
        state: 'APPROVER_PENDING',
        source: 'WORKFLOWS',
        num_transactions: 1,
        approvals: null,
        settlement_id: null,
        approved_at: null,
        reimbursed_at: null,
        submitted_at: new Date('2023-01-17T07:29:01.751Z'),
        verification_state: null,
        trip_request_id: null,
        physical_bill: false,
        physical_bill_at: null,
        exported: null,
        manual_flag: false,
        policy_flag: false,
        claim_number: 'C/2023/01/R/12',
        from_dt: null,
        to_dt: null,
        location1: null,
        location2: null,
        location3: null,
        location4: null,
        location5: null,
        type: 'EXPENSE',
        locations: [],
        risk_state_expense_count: null,
        risk_state: null,
      },
      ou: {
        id: 'ouX8dwsbLCLv',
        org_id: 'orNVthTo2Zyo',
        location: 'Mumbai',
        business_unit:
          'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
        department: '0000000',
        sub_department: null,
        mobile: '123456',
        title: 'director',
        employee_id: '',
        level: 123,
        status: 'ACTIVE',
        org_name: 'Staging Loaded',
        department_id: 'deptpmQ0SsMO0S',
      },
      us: {
        full_name: 'Abhishek Jain',
        email: 'ajain@fyle.in',
      },
    },
  },
  {
    label: '#4:  Jan 2023',
    value: {
      rp: {
        id: 'rpSGcIEwzxDd',
        org_user_id: 'ouX8dwsbLCLv',
        created_at: new Date('2023-01-17T06:34:58.398Z'),
        purpose: '#4:  Jan 2023',
        currency: 'USD',
        amount: 9400,
        tax: 1152.3,
        state: 'APPROVER_INQUIRY',
        source: 'WEBAPP',
        num_transactions: 4,
        approvals: null,
        settlement_id: null,
        approved_at: null,
        reimbursed_at: null,
        submitted_at: new Date('2023-01-17T06:34:59.523Z'),
        verification_state: null,
        trip_request_id: null,
        physical_bill: false,
        physical_bill_at: null,
        exported: null,
        manual_flag: false,
        policy_flag: true,
        claim_number: 'C/2023/01/R/10',
        from_dt: null,
        to_dt: null,
        location1: null,
        location2: null,
        location3: null,
        location4: null,
        location5: null,
        type: 'EXPENSE',
        locations: [],
        risk_state_expense_count: null,
        risk_state: null,
      },
      ou: {
        id: 'ouX8dwsbLCLv',
        org_id: 'orNVthTo2Zyo',
        location: 'Mumbai',
        business_unit:
          'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
        department: '0000000',
        sub_department: null,
        mobile: '123456',
        title: 'director',
        employee_id: '',
        level: 123,
        status: 'ACTIVE',
        org_name: 'Staging Loaded',
        department_id: 'deptpmQ0SsMO0S',
      },
      us: {
        full_name: 'Abhishek Jain',
        email: 'ajain@fyle.in',
      },
    },
  },
];

export const reportOptionsData4: ReportOptions[] = [
  {
    label: '#8:  Jan 2023',
    value: {
      rp: {
        id: 'rprAfNrce73O',
        org_user_id: 'ouX8dwsbLCLv',
        created_at: new Date('2023-01-21T07:29:01.958Z'),
        purpose: '#8:  Jan 2023',
        currency: 'USD',
        amount: 116.9,
        tax: 17.83,
        state: 'APPROVER_PENDING',
        source: 'WORKFLOWS',
        num_transactions: 1,
        approvals: null,
        settlement_id: null,
        approved_at: null,
        reimbursed_at: null,
        submitted_at: new Date('2023-01-21T07:29:03.656Z'),
        verification_state: null,
        trip_request_id: null,
        physical_bill: false,
        physical_bill_at: null,
        exported: null,
        manual_flag: false,
        policy_flag: false,
        claim_number: 'C/2023/01/R/16',
        from_dt: null,
        to_dt: null,
        location1: null,
        location2: null,
        location3: null,
        location4: null,
        location5: null,
        type: 'EXPENSE',
        locations: [],
        risk_state_expense_count: null,
        risk_state: null,
      },
      ou: {
        id: 'ouX8dwsbLCLv',
        org_id: 'orNVthTo2Zyo',
        location: 'Mumbai',
        business_unit:
          'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
        department: '0000000',
        sub_department: null,
        mobile: '123456',
        title: 'director',
        employee_id: '',
        level: 123,
        status: 'ACTIVE',
        org_name: 'Staging Loaded',
        department_id: 'deptpmQ0SsMO0S',
      },
      us: {
        full_name: 'Abhishek Jain',
        email: 'ajain@fyle.in',
      },
    },
  },
  {
    label: '#7:  Jan 2023',
    value: {
      rp: {
        id: 'rpLMyvYSXgJy',
        org_user_id: 'ouX8dwsbLCLv',
        created_at: new Date('2023-01-18T07:29:00.749Z'),
        purpose: '#7:  Jan 2023',
        currency: 'USD',
        amount: 4652,
        tax: 695.5,
        state: 'APPROVER_PENDING',
        source: 'WORKFLOWS',
        num_transactions: 3,
        approvals: null,
        settlement_id: null,
        approved_at: null,
        reimbursed_at: null,
        submitted_at: new Date('2023-01-18T07:29:04.487Z'),
        verification_state: null,
        trip_request_id: null,
        physical_bill: false,
        physical_bill_at: null,
        exported: null,
        manual_flag: false,
        policy_flag: false,
        claim_number: 'C/2023/01/R/15',
        from_dt: null,
        to_dt: null,
        location1: null,
        location2: null,
        location3: null,
        location4: null,
        location5: null,
        type: 'EXPENSE',
        locations: [],
        risk_state_expense_count: null,
        risk_state: null,
      },
      ou: {
        id: 'ouX8dwsbLCLv',
        org_id: 'orNVthTo2Zyo',
        location: 'Mumbai',
        business_unit:
          'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
        department: '0000000',
        sub_department: null,
        mobile: '123456',
        title: 'director',
        employee_id: '',
        level: 123,
        status: 'ACTIVE',
        org_name: 'Staging Loaded',
        department_id: 'deptpmQ0SsMO0S',
      },
      us: {
        full_name: 'Abhishek Jain',
        email: 'ajain@fyle.in',
      },
    },
  },
  {
    label: '#6:  Jan 2023',
    value: {
      rp: {
        id: 'rpxtbiLXQZUm',
        org_user_id: 'ouX8dwsbLCLv',
        created_at: new Date('2023-01-17T07:29:00.800Z'),
        purpose: '#6:  Jan 2023',
        currency: 'USD',
        amount: 347.45800399999996,
        tax: 53,
        state: 'APPROVER_PENDING',
        source: 'WORKFLOWS',
        num_transactions: 1,
        approvals: null,
        settlement_id: null,
        approved_at: null,
        reimbursed_at: null,
        submitted_at: new Date('2023-01-17T07:29:01.751Z'),
        verification_state: null,
        trip_request_id: null,
        physical_bill: false,
        physical_bill_at: null,
        exported: null,
        manual_flag: false,
        policy_flag: false,
        claim_number: 'C/2023/01/R/12',
        from_dt: null,
        to_dt: null,
        location1: null,
        location2: null,
        location3: null,
        location4: null,
        location5: null,
        type: 'EXPENSE',
        locations: [],
        risk_state_expense_count: null,
        risk_state: null,
      },
      ou: {
        id: 'ouX8dwsbLCLv',
        org_id: 'orNVthTo2Zyo',
        location: 'Mumbai',
        business_unit:
          'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
        department: '0000000',
        sub_department: null,
        mobile: '123456',
        title: 'director',
        employee_id: '',
        level: 123,
        status: 'ACTIVE',
        org_name: 'Staging Loaded',
        department_id: 'deptpmQ0SsMO0S',
      },
      us: {
        full_name: 'Abhishek Jain',
        email: 'ajain@fyle.in',
      },
    },
  },
  {
    label: '#4:  Jan 2023',
    value: {
      rp: {
        id: 'rpSGcIEwzxDd',
        org_user_id: 'ouX8dwsbLCLv',
        created_at: new Date('2023-01-17T06:34:58.398Z'),
        purpose: '#4:  Jan 2023',
        currency: 'USD',
        amount: 9400,
        tax: 1152.3,
        state: 'APPROVER_INQUIRY',
        source: 'WEBAPP',
        num_transactions: 4,
        approvals: null,
        settlement_id: null,
        approved_at: null,
        reimbursed_at: null,
        submitted_at: new Date('2023-01-17T06:34:59.523Z'),
        verification_state: null,
        trip_request_id: null,
        physical_bill: false,
        physical_bill_at: null,
        exported: null,
        manual_flag: false,
        policy_flag: true,
        claim_number: 'C/2023/01/R/10',
        from_dt: null,
        to_dt: null,
        location1: null,
        location2: null,
        location3: null,
        location4: null,
        location5: null,
        type: 'EXPENSE',
        locations: [],
        risk_state_expense_count: null,
        risk_state: null,
      },
      ou: {
        id: 'ouX8dwsbLCLv',
        org_id: 'orNVthTo2Zyo',
        location: 'Mumbai',
        business_unit:
          'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
        department: '0000000',
        sub_department: null,
        mobile: '123456',
        title: 'director',
        employee_id: '',
        level: 123,
        status: 'ACTIVE',
        org_name: 'Staging Loaded',
        department_id: 'deptpmQ0SsMO0S',
      },
      us: {
        full_name: 'Abhishek Jain',
        email: 'ajain@fyle.in',
      },
    },
  },
];

export const reportOptionsData5: ReportOptions[] = [
  {
    label: '#7:  Jan 2023',
    value: expectedUnflattenedReports[0],
  },
  {
    label: '#7:  Jan 2023',
    value: expectedUnflattenedReports[1],
  },
  {
    label: '#5:  Jan 2023',
    value: expectedUnflattenedReports[2],
  },
  {
    label: 'A new report',
    value: expectedUnflattenedReports[3],
  },
];
