import { Transaction } from '../models/v1/transaction.model';

export const txnList: Transaction[] = [
  {
    created_at: new Date('2023-01-31T04:03:12.575Z'),
    updated_at: new Date('2023-01-31T04:03:12.575Z'),
    id: 'txAzvMhbD71q',
    source: 'WEBAPP',
    org_user_id: 'ouX8dwsbLCLv',
    creator_id: 'ouX8dwsbLCLv',
    txn_dt: new Date('2023-01-31T17:00:00.000Z'),
    status_id: null,
    vendor: null,
    platform_vendor: null,
    category: null,
    amount: null,
    currency: null,
    admin_amount: null,
    user_amount: null,
    orig_amount: null,
    orig_currency: null,
    tax: null,
    tax_amount: null,
    tax_group_id: null,
    report_id: null,
    reported_at: null,
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    vendor_id: null,
    platform_vendor_id: null,
    project_id: null,
    billable: false,
    skip_reimbursement: false,
    state: 'DRAFT',
    external_id: null,
    cost_center_id: null,
    payment_id: null,
    source_account_id: 'acc5APeygFjRd',
    org_category_id: 117013,
    physical_bill: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    expense_number: 'E/2023/01/T/135',
    split_group_id: 'txAzvMhbD71q',
    split_group_user_amount: null,
    extracted_data: null,
    proposed_exchange_rate: null,
    exchange_rate: null,
    exchange_rate_diff_percentage: null,
    mandatory_fields_present: true,
    user_reason_for_duplicate_expenses: null,
    distance: null,
    distance_unit: 'KM',
    from_dt: null,
    to_dt: null,
    num_days: null,
    fyle_category: 'Mileage',
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: 'new policy test',
    mileage_rate: 10,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    custom_properties: [
      {
        name: 'userlist',
        value: [],
      },
      {
        name: 'User List',
        value: [],
      },
    ],
    physical_bill_at: null,
    policy_amount: null,
    locations: [],
  },
  {
    created_at: new Date('2023-01-31T04:03:23.031Z'),
    updated_at: new Date('2023-01-31T04:03:23.031Z'),
    id: 'txzLsDY1IAAw',
    source: 'WEBAPP',
    org_user_id: 'ouX8dwsbLCLv',
    creator_id: 'ouX8dwsbLCLv',
    txn_dt: new Date('2023-01-31T17:00:00.000Z'),
    status_id: null,
    vendor: null,
    platform_vendor: null,
    category: null,
    amount: null,
    currency: null,
    admin_amount: null,
    user_amount: null,
    orig_amount: null,
    orig_currency: null,
    tax: null,
    tax_amount: null,
    tax_group_id: null,
    report_id: null,
    reported_at: null,
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    vendor_id: null,
    platform_vendor_id: null,
    project_id: null,
    billable: false,
    skip_reimbursement: false,
    state: 'DRAFT',
    external_id: null,
    cost_center_id: 13795,
    payment_id: null,
    source_account_id: 'acc5APeygFjRd',
    org_category_id: 123032,
    physical_bill: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    expense_number: 'E/2023/01/T/136',
    split_group_id: 'txzLsDY1IAAw',
    split_group_user_amount: null,
    extracted_data: null,
    proposed_exchange_rate: null,
    exchange_rate: null,
    exchange_rate_diff_percentage: null,
    mandatory_fields_present: true,
    user_reason_for_duplicate_expenses: null,
    distance: null,
    distance_unit: 'KM',
    from_dt: null,
    to_dt: null,
    num_days: null,
    fyle_category: 'Mileage',
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: 'new policy test',
    mileage_rate: 10,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    custom_properties: [
      {
        name: 'userlist',
        value: [],
      },
      {
        name: 'User List',
        value: [],
      },
    ],
    physical_bill_at: null,
    policy_amount: null,
    locations: [],
  },
];

export const txnData: Transaction = {
  source: 'MOBILE_DASHCAM_BULK',
  txn_dt: new Date('2023-02-08T17:00:00.000Z'),
  currency: 'INR',
  user_amount: null,
  admin_amount: null,
  policy_amount: null,
  custom_attributes: null,
  source_account_id: 'acc5APeygFjRd',
  skip_reimbursement: false,
};

export const txnData2: Transaction = {
  created_at: new Date('2023-02-08T06:47:48.414Z'),
  updated_at: new Date('2023-02-08T06:47:48.414Z'),
  id: 'txNVtsqF8Siq',
  source: 'MOBILE_DASHCAM_BULK',
  org_user_id: 'ouX8dwsbLCLv',
  creator_id: 'ouX8dwsbLCLv',
  txn_dt: new Date('2023-02-08T17:00:00.000Z'),
  status_id: null,
  vendor: null,
  platform_vendor: null,
  category: null,
  amount: null,
  currency: null,
  admin_amount: null,
  user_amount: null,
  orig_amount: null,
  orig_currency: null,
  tax: null,
  tax_amount: null,
  tax_group_id: null,
  report_id: null,
  reported_at: null,
  num_files: 0,
  invoice_number: null,
  purpose: null,
  vendor_id: null,
  platform_vendor_id: null,
  project_id: null,
  billable: null,
  skip_reimbursement: false,
  state: 'DRAFT',
  external_id: null,
  cost_center_id: null,
  payment_id: null,
  source_account_id: 'acc5APeygFjRd',
  org_category_id: 16582,
  physical_bill: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  expense_number: 'E/2023/02/T/51',
  split_group_id: 'txNVtsqF8Siq',
  split_group_user_amount: null,
  extracted_data: null,
  proposed_exchange_rate: null,
  exchange_rate: null,
  exchange_rate_diff_percentage: null,
  mandatory_fields_present: false,
  user_reason_for_duplicate_expenses: null,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  fyle_category: 'Unspecified',
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  custom_properties: null,
  physical_bill_at: null,
  policy_amount: null,
  locations: [],
};

export const upsertTxnParam: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE',
  txn_dt: new Date('2023-02-13T17:00:00.000Z'),
  from_dt: new Date('2023-02-13T17:00:00.000Z'),
  to_dt: new Date('2023-02-13T17:00:00.000Z'),
  tax: 10,
  currency: 'INR',
  amount: 122,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210281,
      mandatory: false,
      name: 'test',
      options: [
        {
          label: 'asd',
          value: 'asd',
        },
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdff',
          value: 'asdff',
        },
      ],
      placeholder: '123test',
      prefix: '',
      type: 'MULTI_SELECT',
      value: '',
    },
    {
      id: 212819,
      mandatory: false,
      name: 'category2',
      options: [
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdfa',
          value: 'asdfa',
        },
      ],
      placeholder: 'category2',
      prefix: '',
      type: 'MULTI_SELECT',
      value: '',
    },
    {
      id: 206206,
      mandatory: false,
      name: 'pub create hola 1',
      options: [],
      placeholder: 'pub create hola 1',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 211321,
      mandatory: false,
      name: 'test 112',
      options: [],
      placeholder: 'placeholder',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 206198,
      mandatory: false,
      name: '2232323',
      options: [],
      placeholder: 'adsf',
      prefix: '',
      type: 'DATE',
      value: null,
    },
    {
      id: 211326,
      mandatory: false,
      name: 'select all 2',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: '2023-02-13T17:00:00.000Z',
    },
  ],
  num_files: 0,
  org_user_id: 'ouX8dwsbLCLv',
  project_id: 3943,
  tax_amount: 18.61,
  tax_group_id: 'tg3iWuqWhfzB',
  org_category_id: 16564,
  fyle_category: null,
  vendor: 'Australian Taxation Office',
  purpose: 'test_term',
  cost_center_id: 13795,
  cost_center_name: '01test2',
  cost_center_code: null,
  user_amount: null,
  admin_amount: null,
  custom_attributes: null,
  id: 'txT5J30Rsnbd',
};

export const txnData4: Transaction = {
  created_at: new Date('2023-02-13T07:26:41.582Z'),
  updated_at: new Date('2023-02-13T07:26:44.188Z'),
  id: 'txT5J30Rsnbd',
  source: 'MOBILE',
  org_user_id: 'ouX8dwsbLCLv',
  creator_id: 'ouX8dwsbLCLv',
  txn_dt: new Date('2023-02-13T17:00:00.000Z'),
  from_dt: new Date('2023-02-13T17:00:00.000Z'),
  to_dt: new Date('2023-02-13T17:00:00.000Z'),
  status_id: null,
  vendor: null,
  platform_vendor: null,
  category: null,
  amount: 122,
  currency: 'INR',
  admin_amount: null,
  user_amount: 122,
  orig_amount: null,
  orig_currency: null,
  tax: 18.61,
  tax_amount: 18.61,
  tax_group_id: 'tg3iWuqWhfzB',
  report_id: null,
  reported_at: null,
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term',
  vendor_id: 28860,
  platform_vendor_id: null,
  project_id: 3943,
  billable: null,
  skip_reimbursement: false,
  state: 'COMPLETE',
  external_id: null,
  cost_center_id: 13795,
  payment_id: 'payxKczQQVvUj',
  source_account_id: 'acc5APeygFjRd',
  org_category_id: 16564,
  physical_bill: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  expense_number: 'E/2023/02/T/69',
  split_group_id: 'txT5J30Rsnbd',
  split_group_user_amount: 122,
  extracted_data: null,
  proposed_exchange_rate: null,
  exchange_rate: null,
  exchange_rate_diff_percentage: null,
  mandatory_fields_present: true,
  user_reason_for_duplicate_expenses: null,
  distance: null,
  distance_unit: null,
  num_days: null,
  fyle_category: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  custom_properties: [
    {
      name: 'userlist',
      value: [],
    },
    {
      name: 'User List',
      value: [],
    },
    {
      name: 'test',
      value: '',
    },
    {
      name: 'category2',
      value: '',
    },
    {
      name: 'pub create hola 1',
      value: null,
    },
    {
      name: 'test 112',
      value: null,
    },
    {
      name: '2232323',
      value: null,
    },
    {
      name: 'select all 2',
      value: '2023-02-13T17:00:00.000Z',
    },
  ],
  physical_bill_at: null,
  policy_amount: null,
  locations: [],
};

export const txnUtilityParam: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE',
  txn_dt: new Date('2023-02-13T17:00:00.000Z'),
  from_dt: new Date('2023-02-13T17:00:00.000Z'),
  to_dt: new Date('2023-02-13T17:00:00.000Z'),
  currency: 'INR',
  amount: 122,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210281,
      mandatory: false,
      name: 'test',
      options: [
        {
          label: 'asd',
          value: 'asd',
        },
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdff',
          value: 'asdff',
        },
      ],
      placeholder: '123test',
      prefix: '',
      type: 'MULTI_SELECT',
      value: '',
    },
    {
      id: 212819,
      mandatory: false,
      name: 'category2',
      options: [
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdfa',
          value: 'asdfa',
        },
      ],
      placeholder: 'category2',
      prefix: '',
      type: 'MULTI_SELECT',
      value: '',
    },
    {
      id: 206206,
      mandatory: false,
      name: 'pub create hola 1',
      options: [],
      placeholder: 'pub create hola 1',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 211321,
      mandatory: false,
      name: 'test 112',
      options: [],
      placeholder: 'placeholder',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 206198,
      mandatory: false,
      name: '2232323',
      options: [],
      placeholder: 'adsf',
      prefix: '',
      type: 'DATE',
      value: null,
    },
    {
      id: 211326,
      mandatory: false,
      name: 'select all 2',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: '2023-02-13T17:00:00.000Z',
    },
  ],
  num_files: 0,
  org_user_id: 'ouX8dwsbLCLv',
  project_id: 3943,
  source_account_id: 'acc5APeygFjRd',
  tax_amount: 18.61,
  tax_group_id: 'tg3iWuqWhfzB',
  org_category_id: 16564,
  fyle_category: null,
  vendor: 'Australian Taxation Office',
  purpose: 'test_term',
  cost_center_id: 13795,
  cost_center_name: '01test2',
  cost_center_code: null,
  user_amount: null,
  admin_amount: null,
  custom_attributes: null,
  id: 'txT5J30Rsnbd',
};

export const txnDataPayload: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE',
  txn_dt: new Date('2023-02-13T17:00:00.000Z'),
  from_dt: new Date('2023-02-13T17:00:00.000Z'),
  to_dt: new Date('2023-02-13T17:00:00.000Z'),
  currency: 'INR',
  amount: 122,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 211326,
      mandatory: false,
      name: 'custom date',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: '2023-02-13T17:00:00.000Z',
    },
  ],
  num_files: 0,
  org_user_id: 'ouX8dwsbLCLv',
  project_id: 3943,
  source_account_id: 'acc5APeygFjRd',
  tax_amount: 18.61,
  tax_group_id: 'tg3iWuqWhfzB',
  org_category_id: 16564,
  fyle_category: null,
  vendor: 'Australian Taxation Office',
  purpose: 'test_term',
  cost_center_id: 13795,
  cost_center_name: '01test2',
  cost_center_code: null,
  user_amount: null,
  admin_amount: null,
  custom_attributes: null,
};
