import { Transaction } from '../models/v1/transaction.model';

export const txnList: Transaction[] = [
  {
    created_at: new Date('2023-01-31T04:03:12.575Z'),
    updated_at: new Date('2023-01-31T04:03:12.575Z'),
    id: 'txAzvMhbD71q',
    source: 'WEBAPP',
    org_user_id: 'ouX8dwsbLCLv',
    creator_id: 'ouX8dwsbLCLv',
    txn_dt: new Date('2023-01-31T17:00:00.000Z'),
    status_id: null,
    vendor: null,
    platform_vendor: null,
    category: null,
    amount: null,
    currency: null,
    admin_amount: null,
    user_amount: null,
    orig_amount: null,
    orig_currency: null,
    tax: null,
    tax_amount: null,
    tax_group_id: null,
    report_id: null,
    reported_at: null,
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    vendor_id: null,
    platform_vendor_id: null,
    project_id: null,
    billable: false,
    skip_reimbursement: false,
    state: 'DRAFT',
    external_id: null,
    cost_center_id: null,
    payment_id: null,
    source_account_id: 'acc5APeygFjRd',
    org_category_id: 117013,
    physical_bill: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    expense_number: 'E/2023/01/T/135',
    split_group_id: 'txAzvMhbD71q',
    split_group_user_amount: null,
    extracted_data: null,
    proposed_exchange_rate: null,
    exchange_rate: null,
    exchange_rate_diff_percentage: null,
    mandatory_fields_present: true,
    user_reason_for_duplicate_expenses: null,
    distance: null,
    distance_unit: 'KM',
    from_dt: null,
    to_dt: null,
    num_days: null,
    fyle_category: 'Mileage',
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: 'new policy test',
    mileage_rate: 10,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    custom_properties: [
      {
        name: 'userlist',
        value: [],
      },
      {
        name: 'User List',
        value: [],
      },
    ],
    physical_bill_at: null,
    policy_amount: null,
    locations: [],
  },
  {
    created_at: new Date('2023-01-31T04:03:23.031Z'),
    updated_at: new Date('2023-01-31T04:03:23.031Z'),
    id: 'txzLsDY1IAAw',
    source: 'WEBAPP',
    org_user_id: 'ouX8dwsbLCLv',
    creator_id: 'ouX8dwsbLCLv',
    txn_dt: new Date('2023-01-31T17:00:00.000Z'),
    status_id: null,
    vendor: null,
    platform_vendor: null,
    category: null,
    amount: null,
    currency: null,
    admin_amount: null,
    user_amount: null,
    orig_amount: null,
    orig_currency: null,
    tax: null,
    tax_amount: null,
    tax_group_id: null,
    report_id: null,
    reported_at: null,
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    vendor_id: null,
    platform_vendor_id: null,
    project_id: null,
    billable: false,
    skip_reimbursement: false,
    state: 'DRAFT',
    external_id: null,
    cost_center_id: 13795,
    payment_id: null,
    source_account_id: 'acc5APeygFjRd',
    org_category_id: 123032,
    physical_bill: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    expense_number: 'E/2023/01/T/136',
    split_group_id: 'txzLsDY1IAAw',
    split_group_user_amount: null,
    extracted_data: null,
    proposed_exchange_rate: null,
    exchange_rate: null,
    exchange_rate_diff_percentage: null,
    mandatory_fields_present: true,
    user_reason_for_duplicate_expenses: null,
    distance: null,
    distance_unit: 'KM',
    from_dt: null,
    to_dt: null,
    num_days: null,
    fyle_category: 'Mileage',
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: 'new policy test',
    mileage_rate: 10,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    custom_properties: [
      {
        name: 'userlist',
        value: [],
      },
      {
        name: 'User List',
        value: [],
      },
    ],
    physical_bill_at: null,
    policy_amount: null,
    locations: [],
  },
];
