import { Transaction } from '../models/v1/transaction.model';
import { optionsData15, optionsData33 } from './merge-expenses-options-data.data';

export const txnList: Transaction[] = [
  {
    created_at: new Date('2023-01-31T04:03:12.575Z'),
    updated_at: new Date('2023-01-31T04:03:12.575Z'),
    id: 'txAzvMhbD71q',
    source: 'WEBAPP',
    org_user_id: 'ouX8dwsbLCLv',
    creator_id: 'ouX8dwsbLCLv',
    txn_dt: new Date('2023-01-31T17:00:00.000Z'),
    status_id: null,
    vendor: null,
    platform_vendor: null,
    category: null,
    amount: null,
    currency: null,
    admin_amount: null,
    user_amount: null,
    orig_amount: null,
    orig_currency: null,
    tax: null,
    tax_amount: null,
    tax_group_id: null,
    report_id: null,
    reported_at: null,
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    vendor_id: null,
    platform_vendor_id: null,
    project_id: null,
    billable: false,
    skip_reimbursement: false,
    state: 'DRAFT',
    external_id: null,
    cost_center_id: null,
    payment_id: null,
    source_account_id: 'acc5APeygFjRd',
    org_category_id: 117013,
    physical_bill: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    expense_number: 'E/2023/01/T/135',
    split_group_id: 'txAzvMhbD71q',
    split_group_user_amount: null,
    extracted_data: null,
    proposed_exchange_rate: null,
    exchange_rate: null,
    exchange_rate_diff_percentage: null,
    mandatory_fields_present: true,
    user_reason_for_duplicate_expenses: null,
    distance: null,
    distance_unit: 'KM',
    from_dt: null,
    to_dt: null,
    num_days: null,
    fyle_category: 'Mileage',
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: 'new policy test',
    mileage_rate: 10,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    custom_properties: [
      {
        name: 'userlist',
        value: [],
      },
      {
        name: 'User List',
        value: [],
      },
    ],
    physical_bill_at: null,
    policy_amount: null,
    locations: [],
  },
  {
    created_at: new Date('2023-01-31T04:03:23.031Z'),
    updated_at: new Date('2023-01-31T04:03:23.031Z'),
    id: 'txzLsDY1IAAw',
    source: 'WEBAPP',
    org_user_id: 'ouX8dwsbLCLv',
    creator_id: 'ouX8dwsbLCLv',
    txn_dt: new Date('2023-01-31T17:00:00.000Z'),
    status_id: null,
    vendor: null,
    platform_vendor: null,
    category: null,
    amount: null,
    currency: null,
    admin_amount: null,
    user_amount: null,
    orig_amount: null,
    orig_currency: null,
    tax: null,
    tax_amount: null,
    tax_group_id: null,
    report_id: null,
    reported_at: null,
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    vendor_id: null,
    platform_vendor_id: null,
    project_id: null,
    billable: false,
    skip_reimbursement: false,
    state: 'DRAFT',
    external_id: null,
    cost_center_id: 13795,
    payment_id: null,
    source_account_id: 'acc5APeygFjRd',
    org_category_id: 123032,
    physical_bill: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    expense_number: 'E/2023/01/T/136',
    split_group_id: 'txzLsDY1IAAw',
    split_group_user_amount: null,
    extracted_data: null,
    proposed_exchange_rate: null,
    exchange_rate: null,
    exchange_rate_diff_percentage: null,
    mandatory_fields_present: true,
    user_reason_for_duplicate_expenses: null,
    distance: null,
    distance_unit: 'KM',
    from_dt: null,
    to_dt: null,
    num_days: null,
    fyle_category: 'Mileage',
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: 'new policy test',
    mileage_rate: 10,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    custom_properties: [
      {
        name: 'userlist',
        value: [],
      },
      {
        name: 'User List',
        value: [],
      },
    ],
    physical_bill_at: null,
    policy_amount: null,
    locations: [],
  },
];

export const txnData: Transaction = {
  source: 'MOBILE_DASHCAM_BULK',
  txn_dt: new Date('2023-02-08T17:00:00.000Z'),
  currency: 'INR',
  user_amount: null,
  admin_amount: null,
  policy_amount: null,
  custom_attributes: null,
  source_account_id: 'acc5APeygFjRd',
  skip_reimbursement: false,
};

export const txnData2: Transaction = {
  created_at: new Date('2023-02-08T06:47:48.414Z'),
  updated_at: new Date('2023-02-08T06:47:48.414Z'),
  id: 'txNVtsqF8Siq',
  source: 'MOBILE_DASHCAM_BULK',
  org_user_id: 'ouX8dwsbLCLv',
  creator_id: 'ouX8dwsbLCLv',
  txn_dt: new Date('2023-02-08T17:00:00.000Z'),
  status_id: null,
  vendor: null,
  platform_vendor: null,
  category: null,
  amount: null,
  currency: null,
  admin_amount: null,
  user_amount: null,
  orig_amount: null,
  orig_currency: null,
  tax: null,
  tax_amount: null,
  tax_group_id: null,
  report_id: null,
  reported_at: null,
  num_files: 0,
  invoice_number: null,
  purpose: null,
  vendor_id: null,
  platform_vendor_id: null,
  project_id: null,
  billable: null,
  skip_reimbursement: false,
  state: 'DRAFT',
  external_id: null,
  cost_center_id: null,
  payment_id: null,
  source_account_id: 'acc5APeygFjRd',
  org_category_id: 16582,
  physical_bill: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  expense_number: 'E/2023/02/T/51',
  split_group_id: 'txNVtsqF8Siq',
  split_group_user_amount: null,
  extracted_data: null,
  proposed_exchange_rate: null,
  exchange_rate: null,
  exchange_rate_diff_percentage: null,
  mandatory_fields_present: false,
  user_reason_for_duplicate_expenses: null,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  fyle_category: 'Unspecified',
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  custom_properties: null,
  physical_bill_at: null,
  policy_amount: null,
  locations: [],
};

export const upsertTxnParam: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE',
  txn_dt: new Date('2023-02-13T17:00:00.000Z'),
  from_dt: new Date('2023-02-13T17:00:00.000Z'),
  to_dt: new Date('2023-02-13T17:00:00.000Z'),
  tax: 10,
  currency: 'INR',
  amount: 122,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210281,
      mandatory: false,
      name: 'test',
      options: [
        {
          label: 'asd',
          value: 'asd',
        },
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdff',
          value: 'asdff',
        },
      ],
      placeholder: '123test',
      prefix: '',
      type: 'MULTI_SELECT',
      value: '',
    },
    {
      id: 212819,
      mandatory: false,
      name: 'category2',
      options: [
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdfa',
          value: 'asdfa',
        },
      ],
      placeholder: 'category2',
      prefix: '',
      type: 'MULTI_SELECT',
      value: '',
    },
    {
      id: 206206,
      mandatory: false,
      name: 'pub create hola 1',
      options: [],
      placeholder: 'pub create hola 1',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 211321,
      mandatory: false,
      name: 'test 112',
      options: [],
      placeholder: 'placeholder',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 206198,
      mandatory: false,
      name: '2232323',
      options: [],
      placeholder: 'adsf',
      prefix: '',
      type: 'DATE',
      value: null,
    },
    {
      id: 211326,
      mandatory: false,
      name: 'select all 2',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: '2023-02-13T17:00:00.000Z',
    },
  ],
  num_files: 0,
  org_user_id: 'ouX8dwsbLCLv',
  project_id: 3943,
  tax_amount: 18.61,
  tax_group_id: 'tg3iWuqWhfzB',
  org_category_id: 16564,
  fyle_category: null,
  vendor: 'Australian Taxation Office',
  purpose: 'test_term',
  cost_center_id: 13795,
  cost_center_name: '01test2',
  cost_center_code: null,
  user_amount: null,
  admin_amount: null,
  custom_attributes: null,
  id: 'txT5J30Rsnbd',
};

export const txnData4: Transaction = {
  created_at: new Date('2023-02-13T07:26:41.582Z'),
  updated_at: new Date('2023-02-13T07:26:44.188Z'),
  id: 'txT5J30Rsnbd',
  source: 'MOBILE',
  org_user_id: 'ouX8dwsbLCLv',
  creator_id: 'ouX8dwsbLCLv',
  txn_dt: new Date('2023-02-13T17:00:00.000Z'),
  from_dt: new Date('2023-02-13T17:00:00.000Z'),
  to_dt: new Date('2023-02-13T17:00:00.000Z'),
  status_id: null,
  vendor: null,
  platform_vendor: null,
  category: null,
  amount: 122,
  currency: 'INR',
  admin_amount: null,
  user_amount: 122,
  orig_amount: null,
  orig_currency: null,
  tax: 18.61,
  tax_amount: 18.61,
  tax_group_id: 'tg3iWuqWhfzB',
  report_id: null,
  reported_at: null,
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term',
  vendor_id: 28860,
  platform_vendor_id: null,
  project_id: 3943,
  billable: null,
  skip_reimbursement: false,
  state: 'COMPLETE',
  external_id: null,
  cost_center_id: 13795,
  payment_id: 'payxKczQQVvUj',
  source_account_id: 'acc5APeygFjRd',
  org_category_id: 16564,
  physical_bill: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  expense_number: 'E/2023/02/T/69',
  split_group_id: 'txT5J30Rsnbd',
  split_group_user_amount: 122,
  extracted_data: null,
  proposed_exchange_rate: null,
  exchange_rate: null,
  exchange_rate_diff_percentage: null,
  mandatory_fields_present: true,
  user_reason_for_duplicate_expenses: null,
  distance: null,
  distance_unit: null,
  num_days: null,
  fyle_category: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  custom_properties: [
    {
      name: 'userlist',
      value: [],
    },
    {
      name: 'User List',
      value: [],
    },
    {
      name: 'test',
      value: '',
    },
    {
      name: 'category2',
      value: '',
    },
    {
      name: 'pub create hola 1',
      value: null,
    },
    {
      name: 'test 112',
      value: null,
    },
    {
      name: '2232323',
      value: null,
    },
    {
      name: 'select all 2',
      value: '2023-02-13T17:00:00.000Z',
    },
  ],
  physical_bill_at: null,
  policy_amount: null,
  locations: [],
};

export const txnDataPayload: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE',
  txn_dt: new Date('2023-02-13T17:00:00.000Z'),
  from_dt: new Date('2023-02-13T17:00:00.000Z'),
  to_dt: new Date('2023-02-13T17:00:00.000Z'),
  currency: 'INR',
  amount: 122,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 211326,
      mandatory: false,
      name: 'custom date',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: '2023-02-13T17:00:00.000Z',
    },
  ],
  num_files: 0,
  org_user_id: 'ouX8dwsbLCLv',
  project_id: 3943,
  source_account_id: 'acc5APeygFjRd',
  tax_amount: 18.61,
  tax_group_id: 'tg3iWuqWhfzB',
  org_category_id: 16564,
  fyle_category: null,
  vendor: 'Australian Taxation Office',
  purpose: 'test_term',
  cost_center_id: 13795,
  cost_center_name: '01test2',
  cost_center_code: null,
  user_amount: null,
  admin_amount: null,
  custom_attributes: null,
};

export const splitPurposeTxn: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: null,
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-02-13T04:23:45.902Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('1970-01-01T17:00:00.000Z'),
  category: null,
  amount: 105,
  user_amount: null,
  policy_amount: null,
  admin_amount: null,
  tax: null,
  tax_amount: null,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'DRAFT',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term (1)',
  source: 'WEBAPP',
  billable: null,
  orig_amount: null,
  orig_currency: null,
  project_id: 316443,
  project_name: null,
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '01test2',
  cost_center_code: null,
  cost_center_id: 13795,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: false,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: false,
  policy_flag: null,
  vendor: 'New new new',
  vendor_id: null,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Unspecified',
  sub_category: 'Unspecified',
  fyle_category: null,
  org_category_code: null,
  org_category_id: 110351,
  expense_number: 'E/2023/02/T/84',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txfwF576rExp',
  split_group_user_amount: 175,
  extracted_data: {
    amount: 175,
    currency: 'INR',
    category: 'Software',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: false,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: null,
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: null,
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Unspecified',
  custom_attributes: null,
};

export const sourceSplitTxn: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txf9U09amjaU',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-02-16T09:05:24.698Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-02-15T18:30:00.000Z'),
  category: null,
  amount: 348.34,
  user_amount: 348.34,
  policy_amount: null,
  admin_amount: null,
  tax: 16.59,
  tax_amount: 16.59,
  tax_group_id: 'tgwotEwriRB5',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term',
  source: 'WEBAPP',
  billable: true,
  orig_amount: 454,
  orig_currency: 'ALL',
  project_id: 3943,
  project_name: 'Staging Project',
  project_code: null,
  skip_reimbursement: true,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '01test2',
  cost_center_code: null,
  cost_center_id: 13795,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor: 'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
  vendor_id: 28922,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: '1',
  sub_category: 'ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP',
  fyle_category: 'Others',
  org_category_code: null,
  org_category_id: 89550,
  expense_number: 'E/2023/02/T/121',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txf9U09amjaU',
  split_group_user_amount: 348.34,
  extracted_data: null,
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: false,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: '1 / ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP',
};

export const splitTxn: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txf9U09amjaU',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-02-16T09:05:24.698Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-02-15T18:30:00.000Z'),
  category: null,
  amount: 272.4,
  user_amount: 348.34,
  policy_amount: null,
  admin_amount: null,
  tax: 16.59,
  tax_amount: 9.954,
  tax_group_id: 'tgwotEwriRB5',
  currency: 'ALL',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term',
  source: 'MOBILE',
  billable: true,
  orig_amount: 454,
  orig_currency: 'ALL',
  project_name: 'Staging Project',
  project_code: null,
  skip_reimbursement: true,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '01test2',
  cost_center_code: null,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor: 'State Board of Equalization (5 - HoneComb Aus) (20210809-102717)',
  vendor_id: 28922,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: '1',
  sub_category: 'ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP',
  fyle_category: 'Others',
  org_category_code: null,
  org_category_id: 110351,
  expense_number: 'E/2023/02/T/121',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txf9U09amjaU',
  split_group_user_amount: 348.34,
  extracted_data: null,
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: false,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: '1 / ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP ABCDFEIAPCALP',
};

export const sourceTxn2: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txxkBruL0EO9',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-03-02T06:42:12.938Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-03-01T18:30:00.000Z'),
  category: null,
  amount: 500,
  user_amount: 500,
  policy_amount: null,
  admin_amount: null,
  tax: 76.27,
  tax_amount: 76.27,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term',
  source: 'MOBILE',
  billable: null,
  orig_amount: null,
  orig_currency: null,
  project_id: 3943,
  project_name: 'Staging Project',
  project_code: null,
  skip_reimbursement: true,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '14',
  cost_center_code: '12',
  cost_center_id: 13793,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: false,
  vendor: 'New new new',
  vendor_id: 28828,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Others',
  sub_category: 'Others',
  fyle_category: null,
  org_category_code: '7028 Ministry Expense · Conference · Freedom Income · Freedom Book',
  org_category_id: 16564,
  expense_number: 'E/2023/03/T/29',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txxkBruL0EO9',
  split_group_user_amount: 500,
  extracted_data: null,
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Others',
};

export const splitTxns: Transaction[] = [
  {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: null,
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-03-02T06:42:12.938Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2023-03-01T18:30:00.000Z'),
    category: null,
    amount: 300,
    user_amount: 500,
    policy_amount: null,
    admin_amount: null,
    tax: 76.27,
    tax_amount: 45.762,
    tax_group_id: 'tg3iWuqWhfzB',
    currency: 'INR',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    source: 'MOBILE',
    billable: true,
    orig_amount: null,
    orig_currency: null,
    project_name: 'Staging Project',
    project_code: null,
    project_id: 3943,
    skip_reimbursement: true,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: '14',
    cost_center_code: '12',
    cost_center_id: 13793,
    source_account_id: 'acc5APeygFjRd',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: false,
    vendor: 'New new new',
    vendor_id: 28828,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'Others',
    sub_category: 'Others',
    fyle_category: null,
    org_category_code: '7028 Ministry Expense · Conference · Freedom Income · Freedom Book',
    expense_number: 'E/2023/03/T/29',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txxkBruL0EO9',
    split_group_user_amount: 500,
    extracted_data: null,
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 200227,
        mandatory: false,
        name: 'userlist',
        options: [],
        placeholder: 'userlist_custom_field',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
      {
        id: 210649,
        mandatory: false,
        name: 'User List',
        options: [],
        placeholder: 'User List',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Others',
  },
  {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: null,
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-03-02T06:42:12.938Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2023-03-01T18:30:00.000Z'),
    category: null,
    amount: 200,
    user_amount: 500,
    policy_amount: null,
    admin_amount: null,
    tax: 76.27,
    tax_amount: 30.507999999999996,
    tax_group_id: 'tg3iWuqWhfzB',
    currency: 'INR',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    source: 'MOBILE',
    billable: true,
    orig_amount: null,
    orig_currency: null,
    project_name: 'Staging Project',
    project_code: null,
    skip_reimbursement: true,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: '14',
    cost_center_code: '12',
    cost_center_id: 13793,
    source_account_id: 'acc5APeygFjRd',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: false,
    project_id: 3943,
    vendor: 'New new new',
    vendor_id: 28828,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'Others',
    sub_category: 'Others',
    fyle_category: null,
    org_category_code: '7028 Ministry Expense · Conference · Freedom Income · Freedom Book',
    expense_number: 'E/2023/03/T/29',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txxkBruL0EO9',
    split_group_user_amount: 500,
    extracted_data: null,
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 200227,
        mandatory: false,
        name: 'userlist',
        options: [],
        placeholder: 'userlist_custom_field',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
      {
        id: 210649,
        mandatory: false,
        name: 'User List',
        options: [],
        placeholder: 'User List',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Others',
  },
];

export const createSourceTxn: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'tx4QhcvNHpuh',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-03-03T02:30:03.710Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-03-02T18:30:00.000Z'),
  category: null,
  amount: 16428.56,
  user_amount: 16428.56,
  policy_amount: null,
  admin_amount: null,
  tax: 2506.052,
  tax_amount: 2506.052,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term (2)',
  source: 'MOBILE_CAMERA',
  billable: null,
  orig_amount: 200,
  orig_currency: 'USD',
  project_id: 3943,
  project_name: 'Staging Project',
  project_code: null,
  skip_reimbursement: true,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '14',
  cost_center_code: '12',
  cost_center_id: 13793,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: false,
  vendor: 'Nilesh As Vendor',
  vendor_id: 28923,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Food',
  sub_category: 'Travelling - Inland',
  fyle_category: 'Food',
  org_category_code: '4060344',
  org_category_id: 201952,
  expense_number: 'E/2023/03/T/45',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'tx0AGAoeQfQX',
  split_group_user_amount: 41071.4,
  extracted_data: {
    amount: 84.12,
    currency: 'USD',
    category: 'Professional Services',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210281,
      mandatory: false,
      name: 'test',
      options: [
        {
          label: 'asd',
          value: 'asd',
        },
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdff',
          value: 'asdff',
        },
      ],
      placeholder: '123test',
      prefix: '',
      type: 'MULTI_SELECT',
      value: null,
    },
    {
      id: 212819,
      mandatory: false,
      name: 'category2',
      options: [
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdfa',
          value: 'asdfa',
        },
      ],
      placeholder: 'category2',
      prefix: '',
      type: 'MULTI_SELECT',
      value: null,
    },
    {
      id: 211321,
      mandatory: false,
      name: 'test 112',
      options: [],
      placeholder: 'placeholder',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 206198,
      mandatory: false,
      name: '2232323',
      options: [],
      placeholder: 'adsf',
      prefix: '',
      type: 'DATE',
      value: null,
    },
    {
      id: 211326,
      mandatory: false,
      name: 'select all 2',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: null,
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Food / Travelling - Inland',
};

export const createSourceTxn2: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-03-03T02:30:03.710Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-03-02T18:30:00.000Z'),
  category: null,
  user_amount: 16428.56,
  policy_amount: null,
  admin_amount: null,
  tax: 2506.052,
  tax_amount: 2506.052,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term (2)',
  source: 'MOBILE_CAMERA',
  billable: null,
  orig_amount: 200,
  orig_currency: 'USD',
  project_id: 3943,
  project_name: 'Staging Project',
  project_code: null,
  skip_reimbursement: true,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '14',
  cost_center_code: '12',
  cost_center_id: 13793,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: false,
  vendor: 'Nilesh As Vendor',
  vendor_id: 28923,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Food',
  sub_category: 'Travelling - Inland',
  fyle_category: 'Food',
  org_category_code: '4060344',
  org_category_id: 201952,
  expense_number: 'E/2023/03/T/45',
  corporate_credit_card_expense_group_id: null,
  extracted_data: {
    amount: 84.12,
    currency: 'USD',
    category: 'Professional Services',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Food / Travelling - Inland',
};

export const splitTxn2: Transaction[] = [
  {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'tx4QhcvNHpuh',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-03-03T02:30:03.710Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2023-03-02T18:30:00.000Z'),
    category: null,
    amount: 120,
    user_amount: 16428.56,
    policy_amount: null,
    admin_amount: null,
    tax: 2506.052,
    tax_amount: 1503.6312,
    tax_group_id: 'tg3iWuqWhfzB',
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term (2)',
    source: 'MOBILE',
    billable: false,
    orig_amount: 200,
    orig_currency: 'USD',
    project_id: 3744,
    project_name: 'Staging Project',
    project_code: null,
    skip_reimbursement: true,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: '14',
    cost_center_code: '12',
    source_account_id: 'acc5APeygFjRd',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: false,
    vendor: 'Nilesh As Vendor',
    vendor_id: 28923,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'Food',
    sub_category: 'Travelling - Inland',
    fyle_category: 'Food',
    org_category_code: '4060344',
    expense_number: 'E/2023/03/T/45',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'tx0AGAoeQfQX',
    split_group_user_amount: 41071.4,
    extracted_data: {
      amount: 84.12,
      currency: 'USD',
      category: 'Professional Services',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 200227,
        mandatory: false,
        name: 'userlist',
        options: [],
        placeholder: 'userlist_custom_field',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
      {
        id: 210649,
        mandatory: false,
        name: 'User List',
        options: [],
        placeholder: 'User List',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
      {
        id: 210281,
        mandatory: false,
        name: 'test',
        options: [
          {
            label: 'asd',
            value: 'asd',
          },
          {
            label: 'asdf',
            value: 'asdf',
          },
          {
            label: 'asdff',
            value: 'asdff',
          },
        ],
        placeholder: '123test',
        prefix: '',
        type: 'MULTI_SELECT',
        value: null,
      },
      {
        id: 212819,
        mandatory: false,
        name: 'category2',
        options: [
          {
            label: 'asdf',
            value: 'asdf',
          },
          {
            label: 'asdfa',
            value: 'asdfa',
          },
        ],
        placeholder: 'category2',
        prefix: '',
        type: 'MULTI_SELECT',
        value: null,
      },
      {
        id: 211321,
        mandatory: false,
        name: 'test 112',
        options: [],
        placeholder: 'placeholder',
        prefix: '',
        type: 'LOCATION',
        value: null,
      },
      {
        id: 206198,
        mandatory: false,
        name: '2232323',
        options: [],
        placeholder: 'adsf',
        prefix: '',
        type: 'DATE',
        value: null,
      },
      {
        id: 211326,
        mandatory: false,
        name: 'select all 2',
        options: [],
        placeholder: 'helo date',
        prefix: '',
        type: 'DATE',
        value: null,
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Food / Travelling - Inland',
  },
  {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'tx4QhcvNHpuh',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-03-03T02:30:03.710Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2023-03-02T18:30:00.000Z'),
    category: null,
    amount: 80,
    user_amount: 16428.56,
    policy_amount: null,
    admin_amount: null,
    tax: 2506.052,
    tax_amount: 1002.4208,
    tax_group_id: 'tg3iWuqWhfzB',
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term (2)',
    source: 'MOBILE',
    billable: false,
    orig_amount: 200,
    orig_currency: 'USD',
    project_id: 3744,
    project_name: 'Staging Project',
    project_code: null,
    skip_reimbursement: true,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: '14',
    cost_center_code: '12',
    source_account_id: 'acc5APeygFjRd',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: false,
    vendor: 'Nilesh As Vendor',
    vendor_id: 28923,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'Food',
    sub_category: 'Travelling - Inland',
    fyle_category: 'Food',
    org_category_code: '4060344',
    expense_number: 'E/2023/03/T/45',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'tx0AGAoeQfQX',
    split_group_user_amount: 41071.4,
    extracted_data: {
      amount: 84.12,
      currency: 'USD',
      category: 'Professional Services',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 200227,
        mandatory: false,
        name: 'userlist',
        options: [],
        placeholder: 'userlist_custom_field',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
      {
        id: 210649,
        mandatory: false,
        name: 'User List',
        options: [],
        placeholder: 'User List',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
      {
        id: 210281,
        mandatory: false,
        name: 'test',
        options: [
          {
            label: 'asd',
            value: 'asd',
          },
          {
            label: 'asdf',
            value: 'asdf',
          },
          {
            label: 'asdff',
            value: 'asdff',
          },
        ],
        placeholder: '123test',
        prefix: '',
        type: 'MULTI_SELECT',
        value: null,
      },
      {
        id: 212819,
        mandatory: false,
        name: 'category2',
        options: [
          {
            label: 'asdf',
            value: 'asdf',
          },
          {
            label: 'asdfa',
            value: 'asdfa',
          },
        ],
        placeholder: 'category2',
        prefix: '',
        type: 'MULTI_SELECT',
        value: null,
      },
      {
        id: 211321,
        mandatory: false,
        name: 'test 112',
        options: [],
        placeholder: 'placeholder',
        prefix: '',
        type: 'LOCATION',
        value: null,
      },
      {
        id: 206198,
        mandatory: false,
        name: '2232323',
        options: [],
        placeholder: 'adsf',
        prefix: '',
        type: 'DATE',
        value: null,
      },
      {
        id: 211326,
        mandatory: false,
        name: 'select all 2',
        options: [],
        placeholder: 'helo date',
        prefix: '',
        type: 'DATE',
        value: null,
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Food / Travelling - Inland',
  },
];

export const txnParam1: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: null,
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-03-03T02:30:03.710Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-03-03T17:00:00.000Z'),
  category: null,
  amount: 9857.136,
  user_amount: null,
  policy_amount: null,
  admin_amount: null,
  tax_amount: 1503.6312,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term (2) (1)',
  source: 'MOBILE_CAMERA',
  billable: false,
  orig_amount: 120,
  orig_currency: 'USD',
  project_id: 3744,
  project_name: 'Staging Project',
  project_code: null,
  skip_reimbursement: true,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '14',
  cost_center_code: '12',
  cost_center_id: 13793,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: false,
  vendor: 'Nilesh As Vendor',
  vendor_id: 28923,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Food',
  sub_category: 'Travelling - Inland',
  fyle_category: 'Food',
  org_category_code: '4060344',
  org_category_id: 201952,
  expense_number: 'E/2023/03/T/45',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'tx0AGAoeQfQX',
  split_group_user_amount: 41071.4,
  extracted_data: {
    amount: 84.12,
    currency: 'USD',
    category: 'Professional Services',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210281,
      mandatory: false,
      name: 'test',
      options: [
        {
          label: 'asd',
          value: 'asd',
        },
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdff',
          value: 'asdff',
        },
      ],
      placeholder: '123test',
      prefix: '',
      type: 'MULTI_SELECT',
      value: null,
    },
    {
      id: 212819,
      mandatory: false,
      name: 'category2',
      options: [
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdfa',
          value: 'asdfa',
        },
      ],
      placeholder: 'category2',
      prefix: '',
      type: 'MULTI_SELECT',
      value: null,
    },
    {
      id: 211321,
      mandatory: false,
      name: 'test 112',
      options: [],
      placeholder: 'placeholder',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 206198,
      mandatory: false,
      name: '2232323',
      options: [],
      placeholder: 'adsf',
      prefix: '',
      type: 'DATE',
      value: null,
    },
    {
      id: 211326,
      mandatory: false,
      name: 'select all 2',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: null,
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Food / Travelling - Inland',
  custom_attributes: null,
};

export const txnParam2: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: null,
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-03-03T02:30:03.710Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-03-03T17:00:00.000Z'),
  category: null,
  amount: 6571.424000000001,
  user_amount: null,
  policy_amount: null,
  admin_amount: null,
  tax_amount: 1002.4208,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term (2) (2)',
  source: 'MOBILE_CAMERA',
  billable: false,
  orig_amount: 80,
  orig_currency: 'USD',
  project_id: 3744,
  project_name: 'Staging Project',
  project_code: null,
  skip_reimbursement: true,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '14',
  cost_center_code: '12',
  cost_center_id: 13793,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: false,
  vendor: 'Nilesh As Vendor',
  vendor_id: 28923,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Food',
  sub_category: 'Travelling - Inland',
  fyle_category: 'Food',
  org_category_code: '4060344',
  org_category_id: 201952,
  expense_number: 'E/2023/03/T/45',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'tx0AGAoeQfQX',
  split_group_user_amount: 41071.4,
  extracted_data: {
    amount: 84.12,
    currency: 'USD',
    category: 'Professional Services',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      id: 200227,
      mandatory: false,
      name: 'userlist',
      options: [],
      placeholder: 'userlist_custom_field',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210649,
      mandatory: false,
      name: 'User List',
      options: [],
      placeholder: 'User List',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210281,
      mandatory: false,
      name: 'test',
      options: [
        {
          label: 'asd',
          value: 'asd',
        },
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdff',
          value: 'asdff',
        },
      ],
      placeholder: '123test',
      prefix: '',
      type: 'MULTI_SELECT',
      value: null,
    },
    {
      id: 212819,
      mandatory: false,
      name: 'category2',
      options: [
        {
          label: 'asdf',
          value: 'asdf',
        },
        {
          label: 'asdfa',
          value: 'asdfa',
        },
      ],
      placeholder: 'category2',
      prefix: '',
      type: 'MULTI_SELECT',
      value: null,
    },
    {
      id: 211321,
      mandatory: false,
      name: 'test 112',
      options: [],
      placeholder: 'placeholder',
      prefix: '',
      type: 'LOCATION',
      value: null,
    },
    {
      id: 206198,
      mandatory: false,
      name: '2232323',
      options: [],
      placeholder: 'adsf',
      prefix: '',
      type: 'DATE',
      value: null,
    },
    {
      id: 211326,
      mandatory: false,
      name: 'select all 2',
      options: [],
      placeholder: 'helo date',
      prefix: '',
      type: 'DATE',
      value: null,
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Food / Travelling - Inland',
  custom_attributes: null,
};

export const txnData5: Transaction = {
  ...txnData,
  orig_currency: 'USD',
  orig_amount: 200,
  amount: 2000,
  split_group_id: 'txOJVaaPxo9O',
  split_group_user_amount: 100,
  id: null,
  source: 'MOBILE_DASHCAM_BULK',
  txn_dt: new Date('2023-01-31T17:00:00.000Z'),
  project_id: null,
  cost_center_id: null,
  org_category_id: 117013,
  billable: true,
  tax_amount: 45,
  custom_properties: [
    {
      name: 'userlist',
      value: [],
    },
    {
      name: 'User List',
      value: [],
    },
  ],
};

export const expectedTxnParams: Transaction = {
  ...txnData5,
  split_group_id: 'txOJVaaPxo9O',
  split_group_user_amount: 100,
  orig_amount: 100,
  amount: 1000,
};

export const expectedTxnParams2: Transaction = {
  ...txnData5,
  orig_amount: 100,
  amount: 1000,
  split_group_id: 'txOJVaaPxo9O',
  split_group_user_amount: 100,
  cost_center_id: 13795,
  org_category_id: 123032,
};

export const expectedTxnParams3: Transaction = {
  ...txnData5,
  orig_currency: undefined,
  split_group_user_amount: 100,
  orig_amount: 200,
  amount: null,
  cost_center_id: null,
  org_category_id: 117013,
};

export const expectedTxnParams4: Transaction = {
  ...txnData5,
  orig_currency: undefined,
  split_group_user_amount: 100,
  orig_amount: 200,
  amount: null,
  cost_center_id: 13795,
  org_category_id: 123032,
};

export const expectedTxnParams5: Transaction = {
  ...txnData5,
  source: 'MOBILE_SPLIT',
  orig_amount: null,
  amount: 0,
};

export const splitExpenseTxn1: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txPazncEIY9Q',
  org_user_id: 'ou5tyO64Eg0L',
  created_at: new Date('2023-06-15T23:39:29.934Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-05-05T18:30:00.000Z'),
  category: null,
  amount: 261805.478,
  user_amount: 174536.986,
  policy_amount: null,
  admin_amount: null,
  tax: null,
  tax_amount: null,
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE',
  billable: false,
  orig_amount: null,
  orig_currency: null,
  project_name: null,
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ou5tyO64Eg0L',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: null,
  cost_center_code: null,
  source_account_id: 'accdSPGRiSiZd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor: 'qq',
  vendor_id: 26523,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Bus',
  sub_category: 'Bus',
  fyle_category: 'Bus',
  org_category_code: null,
  org_category_id: 161531,
  expense_number: 'E/2023/06/T/23',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txPazncEIY9Q',
  split_group_user_amount: 174536.986,
  extracted_data: {
    amount: null,
    currency: 'INR',
    category: 'Others',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Bus',
};

export const splitExpenseTxn1_1: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txPazncEIY9Q',
  org_user_id: 'ou5tyO64Eg0L',
  created_at: new Date('2023-06-15T23:39:29.934Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-05-05T18:30:00.000Z'),
  category: null,
  amount: 174536.986,
  user_amount: 174536.986,
  policy_amount: null,
  admin_amount: null,
  tax: null,
  tax_amount: null,
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE',
  billable: false,
  orig_amount: null,
  orig_currency: null,
  project_name: null,
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ou5tyO64Eg0L',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: null,
  cost_center_code: null,
  source_account_id: 'accdSPGRiSiZd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor: 'qq',
  vendor_id: 26523,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Bus',
  sub_category: 'Bus',
  fyle_category: 'Bus',
  org_category_code: null,
  org_category_id: 161531,
  expense_number: 'E/2023/06/T/23',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txPazncEIY9Q',
  split_group_user_amount: 174536.986,
  extracted_data: {
    amount: null,
    currency: 'INR',
    category: 'Others',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Bus',
};

export const txnAmount1: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txPazncEIY9Q',
  org_user_id: 'ou5tyO64Eg0L',
  created_at: new Date('2023-06-15T23:39:29.934Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-05-05T18:30:00.000Z'),
  category: null,
  amount: 436342.464,
  user_amount: 174536.986,
  policy_amount: null,
  admin_amount: null,
  tax: null,
  tax_amount: null,
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE_DASHCAM_SINGLE',
  billable: false,
  orig_amount: null,
  orig_currency: null,
  project_name: null,
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ou5tyO64Eg0L',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: null,
  cost_center_code: null,
  cost_center_id: null,
  source_account_id: 'accdSPGRiSiZd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor: 'qq',
  vendor_id: 26523,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Bus',
  sub_category: 'Bus',
  fyle_category: 'Bus',
  org_category_code: null,
  org_category_id: 161531,
  expense_number: 'E/2023/06/T/23',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txPazncEIY9Q',
  split_group_user_amount: 174536.986,
  extracted_data: {
    amount: null,
    currency: 'INR',
    category: 'Others',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Bus',
};

export const splitExpenseTxn2: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE',
  id: 'txmsakgYZeCV',
  txn_dt: new Date('2023-06-15T18:30:00.000Z'),
  currency: 'INR',
  amount: 2000,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  locations: [],
  custom_properties: [],
  num_files: 0,
  org_user_id: 'ou5tyO64Eg0L',
  source_account_id: 'accdSPGRiSiZd',
  tax_amount: null,
  state: 'COMPLETE',
  org_category_id: 161539,
  fyle_category: 'Entertainment',
  admin_amount: 0,
  user_amount: 0,
};

export const splitExpenseTxn2_2: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE',
  state: 'COMPLETE',
  id: 'txmsakgYZeCV',
  txn_dt: new Date('2023-06-15T18:30:00.000Z'),
  currency: 'INR',
  amount: 2000,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  locations: [],
  custom_properties: [],
  num_files: 0,
  org_user_id: 'ou5tyO64Eg0L',
  source_account_id: 'accdSPGRiSiZd',
  tax_amount: null,
  org_category_id: 161531,
  fyle_category: 'Entertainment',
  admin_amount: 0,
  user_amount: 0,
};

export const splitExpenseTxn2_3: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE',
  id: 'txmsakgYZeCV',
  txn_dt: new Date('2023-06-15T18:30:00.000Z'),
  currency: null,
  amount: 2000,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  state: 'COMPLETE',
  locations: [],
  custom_properties: [],
  num_files: 0,
  org_user_id: 'ou5tyO64Eg0L',
  source_account_id: 'accdSPGRiSiZd',
  tax_amount: null,
  org_category_id: 161526,
  fyle_category: 'Entertainment',
  admin_amount: 0,
  user_amount: 0,
};

export const txnAmount2: Transaction = {
  skip_reimbursement: false,
  source: 'MOBILE_CAMERA',
  txn_dt: new Date('2023-06-15T18:30:00.000Z'),
  currency: 'INR',
  amount: 6000,
  orig_currency: null,
  orig_amount: null,
  policy_amount: null,
  locations: [],
  custom_properties: [],
  num_files: 0,
  org_user_id: 'ou5tyO64Eg0L',
  source_account_id: 'accdSPGRiSiZd',
  tax_amount: null,
  org_category_id: 161526,
  fyle_category: 'Entertainment',
  admin_amount: 0,
  user_amount: 0,
};

export const splitExpenseTxn3: Transaction[] = [
  {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'txQfKDtvIcZk',
    org_user_id: 'oudmNnyXjIgs',
    created_at: new Date('2023-05-09T03:45:39.382Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2023-05-08T18:30:00.000Z'),
    category: null,
    amount: 381,
    user_amount: 635,
    policy_amount: null,
    admin_amount: null,
    tax: null,
    tax_amount: 0,
    currency: 'INR',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: null,
    source: 'MOBILE',
    orig_amount: null,
    orig_currency: null,
    project_name: 'aa',
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'oudmNnyXjIgs',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: 'test',
    cost_center_code: null,
    source_account_id: 'acciPcZfp7j6o',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    vendor_id: null,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: '1',
    sub_category: 'Entertainment',
    fyle_category: 'Entertainment',
    org_category_code: null,
    org_category_id: 81820,
    expense_number: 'E/2023/05/T/3',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txQfKDtvIcZk',
    split_group_user_amount: 635,
    extracted_data: null,
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 174083,
        mandatory: false,
        name: 'userlist test',
        options: [],
        placeholder: 'userlist test',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
      {
        id: 210078,
        mandatory: false,
        name: 'tettest',
        options: [],
        placeholder: 'testtet',
        prefix: '',
        type: 'TEXT',
        value: null,
      },
      {
        id: 218778,
        mandatory: false,
        name: 'select type field',
        options: [
          {
            label: 'select-1',
            value: 'select-1',
          },
          {
            label: 'select-2',
            value: 'select-2',
          },
        ],
        placeholder: 'select custom field',
        prefix: '',
        type: 'SELECT',
        value: null,
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: '1 / Entertainment',
  },
  {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'txQfKDtvIcZk',
    org_user_id: 'oudmNnyXjIgs',
    created_at: new Date('2023-05-09T03:45:39.382Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2023-05-08T18:30:00.000Z'),
    category: null,
    amount: 254,
    user_amount: 635,
    policy_amount: null,
    admin_amount: null,
    tax: null,
    tax_amount: 0,
    currency: 'INR',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: null,
    source: 'MOBILE',
    orig_amount: null,
    orig_currency: null,
    project_name: 'aa',
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'oudmNnyXjIgs',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: 'test',
    cost_center_code: null,
    source_account_id: 'acciPcZfp7j6o',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    vendor_id: null,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: '1',
    sub_category: 'Entertainment',
    fyle_category: 'Entertainment',
    org_category_code: null,
    org_category_id: 81823,
    expense_number: 'E/2023/05/T/3',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txQfKDtvIcZk',
    split_group_user_amount: 635,
    extracted_data: null,
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 174083,
        mandatory: false,
        name: 'userlist test',
        options: [],
        placeholder: 'userlist test',
        prefix: '',
        type: 'USER_LIST',
        value: [],
      },
      {
        id: 210078,
        mandatory: false,
        name: 'tettest',
        options: [],
        placeholder: 'testtet',
        prefix: '',
        type: 'TEXT',
        value: null,
      },
      {
        id: 218778,
        mandatory: false,
        name: 'select type field',
        options: [
          {
            label: 'select-1',
            value: 'select-1',
          },
          {
            label: 'select-2',
            value: 'select-2',
          },
        ],
        placeholder: 'select custom field',
        prefix: '',
        type: 'SELECT',
        value: null,
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: '1 / Entertainment',
  },
];

export const amtTxn3: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txQfKDtvIcZk',
  org_user_id: 'oudmNnyXjIgs',
  created_at: new Date('2023-05-09T03:45:39.382Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-05-08T18:30:00.000Z'),
  category: null,
  amount: 635,
  user_amount: 635,
  policy_amount: null,
  admin_amount: null,
  tax: null,
  tax_amount: 0,
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE',
  orig_amount: null,
  orig_currency: null,
  project_id: 148345,
  project_name: 'aa',
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'oudmNnyXjIgs',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: 'test',
  cost_center_code: null,
  cost_center_id: 4735,
  source_account_id: 'acciPcZfp7j6o',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor_id: null,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: '1',
  sub_category: 'Entertainment',
  fyle_category: 'Entertainment',
  org_category_code: null,
  org_category_id: 115431,
  expense_number: 'E/2023/05/T/3',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txQfKDtvIcZk',
  split_group_user_amount: 635,
  extracted_data: null,
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  matchCCCId: undefined,
  locations: [],
  custom_properties: [
    {
      id: 174083,
      mandatory: false,
      name: 'userlist test',
      options: [],
      placeholder: 'userlist test',
      prefix: '',
      type: 'USER_LIST',
      value: [],
    },
    {
      id: 210078,
      mandatory: false,
      name: 'tettest',
      options: [],
      placeholder: 'testtet',
      prefix: '',
      type: 'TEXT',
      value: null,
    },
    {
      id: 218778,
      mandatory: false,
      name: 'select type field',
      options: [
        {
          label: 'select-1',
          value: 'select-1',
        },
        {
          label: 'select-2',
          value: 'select-2',
        },
      ],
      placeholder: 'select custom field',
      prefix: '',
      type: 'SELECT',
      value: null,
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: '1 / Entertainment',
};

export const editExpTxn = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'tx3qHxFNgRcZ',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-01-24T04:24:24.186Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-01-24T11:30:00.000Z'),
  category: null,
  amount: 344,
  user_amount: 344,
  policy_amount: null,
  admin_amount: null,
  tax: 52.47,
  tax_amount: 52.47,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 1,
  invoice_number: null,
  purpose: 'test_term',
  source: 'MOBILE_DASHCAM_SINGLE_OFFLINE',
  billable: null,
  orig_amount: null,
  orig_currency: null,
  project_id: 316443,
  project_name: 'Project 1 / asdfg',
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: '01test2',
  cost_center_code: null,
  cost_center_id: 13795,
  source_account_id: 'acc5APeygFjRd',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor: 'Australian Taxation Office',
  vendor_id: 28860,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Software',
  sub_category: 'Software',
  fyle_category: null,
  org_category_code: '117',
  org_category_id: 16577,
  expense_number: 'E/2023/01/T/99',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'tx3qHxFNgRcZ',
  split_group_user_amount: 344,
  extracted_data: {
    amount: null,
    currency: 'INR',
    category: 'Software',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: true,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  matchCCCId: undefined,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [
    {
      name: 'userlist',
      value: null,
    },
    {
      name: 'User List',
      value: null,
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Software',
};

export const editExpTxn2 = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txbO4Xaj4N53',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-05-30T02:18:27.646Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: null,
  category: null,
  amount: 500,
  user_amount: 780,
  policy_amount: null,
  admin_amount: null,
  tax: 64.4,
  tax_amount: null,
  currency: 'USD',
  report_id: 'rpGpzBpAxtSn',
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE',
  billable: null,
  project_name: null,
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: 'SMS1',
  cost_center_code: null,
  cost_center_id: 2411,
  tax_group_id: undefined,
  orig_amount: undefined,
  orig_currency: undefined,
  project_id: undefined,
  source_account_id: undefined,
  vendor: undefined,
  fyle_category: undefined,
  org_category_id: undefined,
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: true,
  vendor_id: 22658,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'ani test',
  sub_category: 'ani test',
  org_category_code: null,
  expense_number: 'E/2023/05/T/326',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txbO4Xaj4N53',
  split_group_user_amount: 780,
  extracted_data: {
    category: 'SYSTEM',
    currency: 'USD',
    amount: 100,
    date: new Date('2023-02-15T06:30:00.000Z'),
    invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    vendor_name: 'vendor',
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [optionsData15.options[0].value, optionsData33.options[0].value],
  custom_properties: [
    {
      id: 111,
      name: 'Test Number',
      value: 121,
      type: 'NUMBER',
    },
    {
      id: 150,
      name: 'checking',
      value: false,
      type: 'BOOLEAN',
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'ani test',
};

export const editExpTxn3 = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txbO4Xaj4N53',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-05-30T02:18:27.646Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: null,
  category: null,
  amount: 500,
  user_amount: 780,
  policy_amount: null,
  admin_amount: null,
  tax: 64.4,
  tax_amount: null,
  currency: 'USD',
  report_id: 'rpGpzBpAxtSn',
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE',
  billable: null,
  project_name: null,
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: 'SMS1',
  cost_center_code: null,
  cost_center_id: 2411,
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  tax_group_id: undefined,
  orig_amount: undefined,
  orig_currency: undefined,
  project_id: undefined,
  source_account_id: undefined,
  vendor: undefined,
  fyle_category: undefined,
  org_category_id: undefined,
  manual_flag: null,
  policy_flag: true,
  vendor_id: 22658,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'ani test',
  sub_category: 'ani test',
  org_category_code: null,
  expense_number: 'E/2023/05/T/326',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txbO4Xaj4N53',
  split_group_user_amount: 780,
  extracted_data: {
    category: 'SYSTEM',
    currency: 'USD',
    amount: 100,
    date: new Date('2023-02-15T06:30:00.000Z'),
    invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    vendor_name: 'vendor',
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [optionsData15.options[0].value, optionsData33.options[0].value],
  custom_properties: [
    {
      id: 111,
      name: 'Test Number',
      value: 121,
      type: 'NUMBER',
    },
    {
      id: 150,
      name: 'checking',
      value: false,
      type: 'BOOLEAN',
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'ani test',
};

export const editExpTxn4 = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txbO4Xaj4N53',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-05-30T02:18:27.646Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: null,
  category: null,
  amount: 500,
  user_amount: 780,
  policy_amount: null,
  admin_amount: null,
  tax: 64.4,
  tax_amount: null,
  currency: 'USD',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE',
  billable: null,
  project_name: null,
  tax_group_id: undefined,
  orig_amount: undefined,
  orig_currency: undefined,
  project_id: undefined,
  source_account_id: undefined,
  vendor: undefined,
  fyle_category: undefined,
  org_category_id: undefined,
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: 'SMS1',
  cost_center_code: null,
  cost_center_id: 2411,
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: true,
  vendor_id: 22658,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'ani test',
  sub_category: 'ani test',
  org_category_code: null,
  expense_number: 'E/2023/05/T/326',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txbO4Xaj4N53',
  split_group_user_amount: 780,
  extracted_data: {
    category: 'SYSTEM',
    currency: 'USD',
    amount: 100,
    date: new Date('2023-02-15T06:30:00.000Z'),
    invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    vendor_name: 'vendor',
  },
  transcribed_data: null,
  user_review_needed: true,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [optionsData15.options[0].value, optionsData33.options[0].value],
  custom_properties: [
    {
      id: 111,
      name: 'Test Number',
      value: 121,
      type: 'NUMBER',
    },
    {
      id: 150,
      name: 'checking',
      value: false,
      type: 'BOOLEAN',
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'ani test',
  tx_policy_amount: 0,
};

export const editExpTxn5 = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txbO4Xaj4N53',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-05-30T02:18:27.646Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: null,
  category: null,
  amount: 500,
  user_amount: 780,
  policy_amount: null,
  admin_amount: null,
  tax: 64.4,
  tax_amount: null,
  currency: 'USD',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 0,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE',
  billable: null,
  project_name: null,
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: 'SMS1',
  cost_center_code: null,
  cost_center_id: 2411,
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  tax_group_id: undefined,
  orig_amount: undefined,
  orig_currency: undefined,
  project_id: undefined,
  source_account_id: undefined,
  vendor: undefined,
  fyle_category: undefined,
  org_category_id: undefined,
  policy_flag: true,
  vendor_id: 22658,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'ani test',
  sub_category: 'ani test',
  org_category_code: null,
  expense_number: 'E/2023/05/T/326',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txbO4Xaj4N53',
  split_group_user_amount: 780,
  extracted_data: {
    category: 'SYSTEM',
    currency: 'USD',
    amount: 100,
    date: new Date('2023-02-15T06:30:00.000Z'),
    invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    vendor_name: 'vendor',
  },
  transcribed_data: null,
  user_review_needed: true,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [optionsData15.options[0].value, optionsData33.options[0].value],
  custom_properties: [
    {
      id: 111,
      name: 'Test Number',
      value: 121,
      type: 'NUMBER',
    },
    {
      id: 150,
      name: 'checking',
      value: false,
      type: 'BOOLEAN',
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'ani test',
  tx_policy_amount: 0,
};

export const personalCardTxn: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'tx3qHxFNgRcZ',
  org_user_id: 'ouX8dwsbLCLv',
  created_at: new Date('2023-01-24T04:24:24.186Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: null,
  category: null,
  amount: 100,
  user_amount: 100,
  policy_amount: null,
  admin_amount: null,
  tax: 52.47,
  tax_amount: null,
  currency: 'USD',
  report_id: null,
  reported_at: null,
  state: 'COMPLETE',
  num_files: 1,
  invoice_number: null,
  purpose: null,
  source: 'MOBILE',
  billable: null,
  project_name: 'Project 1 / asdfg',
  project_code: null,
  skip_reimbursement: false,
  creator_id: 'ouX8dwsbLCLv',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: 'SMS1',
  cost_center_code: null,
  cost_center_id: 2411,
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor_id: 28860,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'TRAVEL',
  sub_category: 'TAXI',
  org_category_code: '117',
  expense_number: 'E/2023/01/T/99',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'tx3qHxFNgRcZ',
  split_group_user_amount: 344,
  extracted_data: {
    amount: null,
    currency: 'INR',
    category: 'Software',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: true,
  mandatory_fields_present: true,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  tax_group_id: undefined,
  orig_amount: undefined,
  orig_currency: undefined,
  project_id: undefined,
  source_account_id: undefined,
  vendor: undefined,
  fyle_category: undefined,
  org_category_id: undefined,
  activity_policy_pending: null,
  activity_details: null,
  locations: [optionsData15.options[0].value],
  custom_properties: [
    {
      id: 111,
      name: 'Test Number',
      value: 121,
      type: 'NUMBER',
    },
    {
      id: 115,
      name: 'test date',
      value: new Date('2017-07-25T00:00:00.000Z'),
      type: 'DATE',
    },
    {
      id: 150,
      name: 'checking',
      value: false,
      type: 'BOOLEAN',
    },
    {
      id: 151,
      name: 'Select field',
      value: 'select-1',
      type: 'SELECT',
    },
  ],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Software',
};

export const modifiedTxnData4: Transaction = {
  ...txnData4,
  from_dt: new Date('2023-08-04'),
  to_dt: new Date('2023-08-07'),
  amount: 120,
  tax_amount: 23,
  project_id: undefined,
  billable: true,
  cost_center_id: undefined,
  org_category_id: 184692,
  custom_properties: [
    {
      name: 'test',
      value: '',
    },
    {
      name: 'category2',
      value: '',
    },
    {
      name: 'pub create hola 1',
      value: null,
    },
    {
      name: 'test 112',
      value: null,
    },
    {
      name: '2232323',
      value: null,
    },
    {
      name: 'select all 2',
      value: '2023-02-13T17:00:00.000Z',
    },
  ],
};

export const modifiedTxnData5: Transaction = {
  ...modifiedTxnData4,
  project_id: 384582,
};

export const modifiedTxnData6: Transaction = {
  ...modifiedTxnData4,
  cost_center_id: 384582,
  project_id: undefined,
};

export const modifiedTxnData7: Transaction = {
  ...modifiedTxnData4,
  cost_center_id: undefined,
  project_id: undefined,
};

export const txnData6: Transaction = {
  risk_state: null,
  is_duplicate_expense: null,
  duplicates: null,
  id: 'txUQZ7xKSbDw',
  org_user_id: 'ourw7Hi4mmpO',
  created_at: new Date('2023-01-21T13:55:38.496Z'),
  receipt_required: false,
  user_can_delete: true,
  txn_dt: new Date('2023-01-21T18:30:00.000Z'),
  category: null,
  amount: 2211.2650000000003,
  user_amount: 2211.2650000000003,
  policy_amount: null,
  admin_amount: null,
  tax: 337.31,
  tax_amount: 337.31,
  tax_group_id: 'tg3iWuqWhfzB',
  currency: 'INR',
  report_id: null,
  reported_at: null,
  state: 'DRAFT',
  num_files: 0,
  invoice_number: null,
  purpose: 'test_term',
  source: 'MOBILE_DASHCAM_SINGLE',
  billable: null,
  orig_amount: 5000,
  orig_currency: 'ARS',
  project_id: 168826,
  project_name: 'Abercrombie International Group',
  project_code: '67',
  skip_reimbursement: false,
  creator_id: 'ourw7Hi4mmpO',
  user_reason_for_duplicate_expenses: null,
  external_id: null,
  cost_center_name: 'A very long cost center name A very long cost center name A very long cost center name',
  cost_center_code: 'A very long cost center code A very long cost center code A very long cost center code',
  cost_center_id: 6725,
  source_account_id: 'acct0vTdfNQrT',
  transcription_state: null,
  verification_state: null,
  physical_bill: null,
  physical_bill_at: null,
  policy_state: null,
  manual_flag: null,
  policy_flag: null,
  vendor: 'Uber',
  vendor_id: null,
  platform_vendor: null,
  platform_vendor_id: null,
  org_category: 'Accm.Depr. Furniture & Fixtures',
  sub_category: 'Accm.Depr. Furniture & Fixtures',
  fyle_category: null,
  org_category_code: '15510',
  org_category_id: 129111,
  expense_number: 'E/2023/01/T/88',
  corporate_credit_card_expense_group_id: null,
  split_group_id: 'txUQZ7xKSbDw',
  split_group_user_amount: 2211.2650000000003,
  extracted_data: {
    amount: null,
    currency: 'INR',
    category: 'Others',
    date: null,
    vendor: null,
    invoice_dt: null,
  },
  transcribed_data: null,
  user_review_needed: null,
  mandatory_fields_present: false,
  distance: null,
  distance_unit: null,
  from_dt: null,
  to_dt: null,
  num_days: null,
  mileage_calculated_distance: null,
  mileage_calculated_amount: null,
  mileage_vehicle_type: null,
  mileage_rate: null,
  mileage_is_round_trip: null,
  hotel_is_breakfast_provided: null,
  flight_journey_travel_class: null,
  flight_return_travel_class: null,
  train_travel_class: null,
  bus_travel_class: null,
  taxi_travel_class: null,
  per_diem_rate_id: null,
  activity_policy_pending: null,
  activity_details: null,
  locations: [],
  custom_properties: [],
  is_implicit_merge_blocked: false,
  categoryDisplayName: 'Accm.Depr. Furniture & Fixtures',
  exchange_rate: 0,
  exchange_rate_diff_percentage: 0,
  payment_id: '',
  proposed_exchange_rate: 0,
  status_id: '',
  updated_at: undefined,
};
