import { UndoMerge } from '../models/undo-merge.model';
import { txnList } from './transaction.data';

export const UndoMergeData: UndoMerge = {
  user_created_expense: {
    created_at: new Date('2022-02-17T14:12:49.079Z'),
    updated_at: new Date('2022-06-12T11:37:06.592Z'),
    id: 'tx7NU3Dviv4K',
    source: 'CORPORATE_CARD',
    org_user_id: 'ouX8dwsbLCLv',
    creator_id: 'SYSTEM_CORPORATE_CARD',
    txn_dt: new Date('2008-12-27T10:00:00.000Z'),
    status_id: null,
    vendor: null,
    platform_vendor: null,
    category: null,
    amount: 1010,
    currency: 'INR',
    admin_amount: null,
    user_amount: 1010,
    orig_amount: null,
    orig_currency: null,
    tax: null,
    tax_amount: null,
    tax_group_id: null,
    report_id: null,
    reported_at: null,
    num_files: 0,
    invoice_number: null,
    purpose: 'description is mwyki0 (Card Transaction)',
    vendor_id: 26063,
    platform_vendor_id: null,
    project_id: null,
    billable: null,
    skip_reimbursement: false,
    state: 'DRAFT',
    external_id: null,
    cost_center_id: null,
    payment_id: 'pay5NNe4snm0F',
    source_account_id: 'accZ1IWjhjLv4',
    org_category_id: 16582,
    physical_bill: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    expense_number: 'E/2022/02/T/860',
    split_group_id: 'tx7NU3Dviv4K',
    split_group_user_amount: 1010,
    extracted_data: null,
    proposed_exchange_rate: null,
    exchange_rate: null,
    exchange_rate_diff_percentage: null,
    mandatory_fields_present: false,
    user_reason_for_duplicate_expenses: null,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    fyle_category: 'Unspecified',
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    custom_properties: null,
    physical_bill_at: null,
    policy_amount: null,
    locations: [],
  },
  auto_created_expense: {
    created_at: new Date('2023-01-23T15:38:05.557Z'),
    updated_at: new Date('2023-01-23T15:38:05.557Z'),
    id: 'txRgHytm4aa1',
    source: 'CORPORATE_CARD',
    org_user_id: 'ouX8dwsbLCLv',
    creator_id: 'SYSTEM_CORPORATE_CARD',
    txn_dt: new Date('2008-12-27T10:00:00.000Z'),
    status_id: null,
    vendor: null,
    platform_vendor: null,
    category: null,
    amount: 1010,
    currency: 'INR',
    admin_amount: null,
    user_amount: 1010,
    orig_amount: null,
    orig_currency: null,
    tax: null,
    tax_amount: null,
    tax_group_id: null,
    report_id: null,
    reported_at: null,
    num_files: 0,
    invoice_number: null,
    purpose: null,
    vendor_id: 26063,
    platform_vendor_id: null,
    project_id: null,
    billable: null,
    skip_reimbursement: false,
    state: 'DRAFT',
    external_id: null,
    cost_center_id: null,
    payment_id: null,
    source_account_id: 'accZ1IWjhjLv4',
    org_category_id: 16582,
    physical_bill: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    expense_number: 'E/2023/01/T/97',
    split_group_id: 'txRgHytm4aa1',
    split_group_user_amount: 1010,
    extracted_data: null,
    proposed_exchange_rate: null,
    exchange_rate: null,
    exchange_rate_diff_percentage: null,
    mandatory_fields_present: false,
    user_reason_for_duplicate_expenses: null,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    fyle_category: 'Unspecified',
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    custom_properties: null,
    physical_bill_at: null,
    policy_amount: null,
    locations: [],
  },
};

export const UndoMergeData2: UndoMerge = {
  user_created_expense: txnList[0],
  auto_created_expense: txnList[1],
};
