import { UnflattenedTransaction } from '../models/unflattened-transaction.model';
import { optionsData15, optionsData33 } from './merge-expenses-options-data.data';

export const unflattenedTxnData: UnflattenedTransaction = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'tx3qHxFNgRcZ',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-24T04:24:24.186Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2023-01-24T11:30:00.000Z'),
    category: null,
    amount: 344,
    user_amount: 344,
    policy_amount: null,
    admin_amount: null,
    tax: 52.47,
    tax_amount: 52.47,
    tax_group_id: 'tg3iWuqWhfzB',
    currency: 'INR',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 1,
    invoice_number: null,
    purpose: 'test_term',
    source: 'MOBILE_DASHCAM_SINGLE',
    billable: null,
    orig_amount: null,
    orig_currency: null,
    project_id: 316443,
    project_name: 'Project 1 / asdfg',
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: '01test2',
    cost_center_code: null,
    cost_center_id: 13795,
    source_account_id: 'acc5APeygFjRd',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    vendor: 'Australian Taxation Office',
    vendor_id: 28860,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'Software',
    sub_category: 'Software',
    fyle_category: null,
    org_category_code: '117',
    org_category_id: 16577,
    expense_number: 'E/2023/01/T/99',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'tx3qHxFNgRcZ',
    split_group_user_amount: 344,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: 'Software',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: true,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        name: 'userlist',
        value: null,
      },
      {
        name: 'User List',
        value: null,
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Software',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: 123,
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'deptpmQ0SsMO0S',
    department: '0000000',
    title: 'director',
    mobile: '123456',
    sub_department: null,
    joining_dt: new Date('2017-07-25T00:00:00.000+0000'),
  },
  tg: {
    name: 'cgst',
    percentage: 0.18,
  },
  rp: {
    purpose: null,
    approved_at: null,
    reimbursed_at: null,
    claim_number: null,
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
  source: {
    account_type: 'PERSONAL_ACCOUNT',
    account_id: 'acc5APeygFjRd',
  },
  external: {
    expense_id: null,
  },
  is: {
    test_call: null,
  },
};

export const unflattenedTxnDataWithSubCategory: UnflattenedTransaction = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'tx3qHxFNgRcZ',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-24T04:24:24.186Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2023-01-24T11:30:00.000Z'),
    category: null,
    amount: 344,
    user_amount: 344,
    policy_amount: null,
    admin_amount: null,
    tax: 52.47,
    tax_amount: 52.47,
    tax_group_id: 'tg3iWuqWhfzB',
    currency: 'INR',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 1,
    invoice_number: null,
    purpose: 'test_term',
    source: 'MOBILE_DASHCAM_SINGLE',
    billable: null,
    orig_amount: null,
    orig_currency: null,
    project_id: 316443,
    project_name: 'Project 1 / asdfg',
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: '01test2',
    cost_center_code: null,
    cost_center_id: 13795,
    source_account_id: 'acc5APeygFjRd',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    vendor: 'Australian Taxation Office',
    vendor_id: 28860,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'Software',
    sub_category: 'Subscriptions',
    fyle_category: null,
    org_category_code: '117',
    org_category_id: 16577,
    expense_number: 'E/2023/01/T/99',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'tx3qHxFNgRcZ',
    split_group_user_amount: 344,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: 'Software',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        name: 'userlist',
        value: null,
      },
      {
        name: 'User List',
        value: null,
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Software / Subscriptions',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: 123,
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'deptpmQ0SsMO0S',
    department: '0000000',
    title: 'director',
    mobile: '123456',
    sub_department: null,
    joining_dt: new Date('2017-07-25T00:00:00.000+0000'),
  },
  tg: {
    name: 'cgst',
    percentage: 0.18,
  },
  rp: {
    purpose: null,
    approved_at: null,
    reimbursed_at: null,
    claim_number: null,
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
  source: {
    account_type: 'PERSONAL_ACCOUNT',
    account_id: 'acc5APeygFjRd',
  },
  external: {
    expense_id: null,
  },
  is: {
    test_call: null,
  },
};

export const unflattenedTxnWithExtractedData: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    source: 'MOBILE',
    state: 'DRAFT',
    amount: undefined,
    currency: undefined,
    vendor: undefined,
    fyle_category: 'UNSPECIFIED',
    extracted_data: {
      amount: 100,
      currency: 'USD',
      date: new Date('2022-11-30T06:30:00.000Z'),
      category: 'TRAVEL',
      vendor: 'vendor',
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    },
  },
};

export const expectedUnflattendedTxnData1: UnflattenedTransaction = {
  tx: {
    risk_state: null,
    txn_dt: new Date('2023-01-24T11:30:00.000Z'),
    is_duplicate_expense: null,
    duplicates: null,
    id: 'tx3qHxFNgRcZ',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-24T04:24:24.186Z'),
    receipt_required: false,
    user_can_delete: true,
    category: null,
    amount: 100,
    user_amount: 344,
    policy_amount: null,
    admin_amount: null,
    tax: 52.47,
    tax_amount: 52.47,
    tax_group_id: 'tg3iWuqWhfzB',
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'DRAFT',
    num_files: 1,
    invoice_number: null,
    purpose: 'test_term',
    source: 'MOBILE',
    billable: null,
    orig_amount: null,
    orig_currency: null,
    project_id: 316443,
    project_name: 'Project 1 / asdfg',
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: '01test2',
    cost_center_code: null,
    cost_center_id: 13795,
    source_account_id: 'acc5APeygFjRd',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    vendor: 'vendor',
    vendor_id: 28860,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'Software',
    sub_category: 'Software',
    fyle_category: 'UNSPECIFIED',
    org_category_code: '117',
    org_category_id: 16566,
    expense_number: 'E/2023/01/T/99',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'tx3qHxFNgRcZ',
    split_group_user_amount: 344,
    extracted_data: {
      amount: 100,
      currency: 'USD',
      date: new Date('2022-11-30T06:30:00.000Z'),
      category: 'TRAVEL',
      vendor: 'vendor',
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    },
    transcribed_data: null,
    user_review_needed: true,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        name: 'userlist',
        value: null,
      },
      {
        name: 'User List',
        value: null,
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Software',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: 123,
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'deptpmQ0SsMO0S',
    department: '0000000',
    title: 'director',
    mobile: '123456',
    sub_department: null,
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  tg: {
    name: 'cgst',
    percentage: 0.18,
  },
  rp: {
    purpose: null,
    approved_at: null,
    reimbursed_at: null,
    claim_number: null,
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
  source: {
    account_type: 'PERSONAL_ACCOUNT',
    account_id: 'acc5APeygFjRd',
  },
  external: {
    expense_id: null,
  },
  is: {
    test_call: null,
  },
};

export const expectedUnflattendedTxnData2 = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'txbO4Xaj4N53',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-05-30T02:18:27.646Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: null,
    category: null,
    amount: 500,
    user_amount: 780,
    policy_amount: null,
    admin_amount: null,
    tax: 64.4,
    tax_amount: null,
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: null,
    source: 'MOBILE',
    billable: null,
    project_name: null,
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: 'SMS1',
    cost_center_code: null,
    cost_center_id: 2411,
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: true,
    vendor_id: 22658,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'ani test',
    sub_category: 'ani test',
    org_category_code: null,
    expense_number: 'E/2023/05/T/326',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txbO4Xaj4N53',
    split_group_user_amount: 780,
    extracted_data: {
      category: 'SYSTEM',
      currency: 'USD',
      amount: 100,
      date: new Date('2023-02-15T06:30:00.000Z'),
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
      vendor_name: 'vendor',
    },
    tax_group_id: undefined,
    orig_amount: undefined,
    orig_currency: undefined,
    project_id: undefined,
    source_account_id: undefined,
    vendor: undefined,
    fyle_category: undefined,
    org_category_id: undefined,
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [optionsData15.options[0].value, optionsData33.options[0].value],
    custom_properties: [
      { id: 111, name: 'Test Number', value: 121, type: 'NUMBER' },
      { id: 150, name: 'checking', value: false, type: 'BOOLEAN' },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'ani test',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'dept7HJ9C4wvtX',
    department: '0000000',
    title: 'director',
    mobile: '+919764989821',
    sub_department: 'arun',
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  dataUrls: [],
};

export const unflattenedTxnData2: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    amount: 100,
    user_amount: 100,
  },
};

export const expectedUnflattendedTxnData3 = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'tx3qHxFNgRcZ',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-24T04:24:24.186Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: null,
    category: null,
    amount: 100,
    user_amount: 100,
    policy_amount: null,
    admin_amount: null,
    tax: 52.47,
    tax_amount: null,
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 1,
    invoice_number: null,
    purpose: null,
    source: 'MOBILE',
    billable: null,
    project_name: 'Project 1 / asdfg',
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: 'SMS1',
    cost_center_code: null,
    cost_center_id: 2411,
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    vendor_id: 28860,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'TRAVEL',
    sub_category: 'TAXI',
    org_category_code: '117',
    expense_number: 'E/2023/01/T/99',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'tx3qHxFNgRcZ',
    split_group_user_amount: 344,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: 'Software',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: true,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    tax_group_id: undefined,
    orig_amount: undefined,
    orig_currency: undefined,
    project_id: undefined,
    source_account_id: undefined,
    vendor: undefined,
    fyle_category: undefined,
    org_category_id: undefined,
    activity_policy_pending: null,
    activity_details: null,
    locations: [optionsData15.options[0].value],
    custom_properties: [
      {
        id: 111,
        name: 'Test Number',
        value: 121,
        type: 'NUMBER',
      },
      {
        id: 115,
        name: 'test date',
        value: new Date('2017-07-25T00:00:00.000Z'),
        type: 'DATE',
      },
      {
        id: 150,
        name: 'checking',
        value: false,
        type: 'BOOLEAN',
      },
      {
        id: 151,
        name: 'Select field',
        value: 'select-1',
        type: 'SELECT',
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Software',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: 123,
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'deptpmQ0SsMO0S',
    department: '0000000',
    title: 'director',
    mobile: '123456',
    sub_department: null,
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  dataUrls: [],
};

export const expectedUnflattendedTxnData4 = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: null,
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-05-30T02:18:27.646Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: null,
    category: null,
    amount: 100,
    user_amount: 780,
    policy_amount: null,
    admin_amount: null,
    tax: 64.4,
    tax_amount: null,
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'DRAFT',
    num_files: 0,
    invoice_number: null,
    purpose: null,
    source: 'MOBILE',
    billable: null,
    project_name: null,
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: 'SMS1',
    cost_center_code: null,
    cost_center_id: 2411,
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: true,
    vendor_id: 22658,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'ani test',
    sub_category: 'ani test',
    org_category_code: null,
    expense_number: 'E/2023/05/T/326',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txbO4Xaj4N53',
    split_group_user_amount: 780,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: 'Food',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    tax_group_id: undefined,
    orig_amount: undefined,
    orig_currency: undefined,
    project_id: undefined,
    source_account_id: undefined,
    vendor: undefined,
    fyle_category: undefined,
    org_category_id: undefined,
    locations: [],
    custom_properties: [
      {
        id: 111,
        name: 'Test Number',
        value: 121,
        type: 'NUMBER',
      },
      {
        id: 115,
        name: 'test date',
        type: 'DATE',
        value: undefined,
      },
      {
        id: 150,
        name: 'checking',
        value: false,
        type: 'BOOLEAN',
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'ani test',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'dept7HJ9C4wvtX',
    department: '0000000',
    title: 'director',
    mobile: '+919764989821',
    sub_department: 'arun',
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  dataUrls: [],
};

export const expectedUnflattendedTxnData5 = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: null,
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-05-30T02:18:27.646Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: null,
    category: null,
    amount: 100,
    user_amount: 780,
    policy_amount: null,
    admin_amount: null,
    tax: 64.4,
    tax_amount: null,
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'DRAFT',
    num_files: 0,
    invoice_number: null,
    purpose: null,
    source: 'MOBILE',
    billable: null,
    project_name: null,
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: null,
    cost_center_code: null,
    cost_center_id: null,
    tax_group_id: undefined,
    orig_amount: undefined,
    orig_currency: undefined,
    project_id: undefined,
    source_account_id: undefined,
    vendor: undefined,
    fyle_category: undefined,
    org_category_id: undefined,
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: true,
    vendor_id: 22658,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'ani test',
    sub_category: 'ani test',
    org_category_code: null,
    expense_number: 'E/2023/05/T/326',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txbO4Xaj4N53',
    split_group_user_amount: 780,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: 'Food',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: null,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 111,
        name: 'Test Number',
        value: 121,
        type: 'NUMBER',
      },
      {
        id: 115,
        name: 'test date',
        type: 'DATE',
        value: undefined,
      },
      {
        id: 150,
        name: 'checking',
        value: false,
        type: 'BOOLEAN',
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'ani test',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'dept7HJ9C4wvtX',
    department: '0000000',
    title: 'director',
    mobile: '+919764989821',
    sub_department: 'arun',
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  dataUrls: [],
};

export const unflattenedTxnDataWithoutCategoryData: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    extracted_data: null,
    org_category_id: null,
    fyle_category: 'unspecified',
  },
};

export const expWithCriticalViolation: { etxn: UnflattenedTransaction; comment: string } = {
  etxn: {
    tx: {
      risk_state: null,
      is_duplicate_expense: null,
      duplicates: null,
      id: 'txbO4Xaj4N53',
      org_user_id: 'ouX8dwsbLCLv',
      created_at: new Date('2023-05-30T02:18:27.646Z'),
      receipt_required: false,
      user_can_delete: true,
      txn_dt: new Date('2023-05-30T01:00:00.000Z'),
      category: null,
      amount: 780,
      user_amount: 780,
      policy_amount: null,
      admin_amount: null,
      tax: 64.4,
      tax_amount: 64.4,
      tax_group_id: 'tgzhpXlC40LK',
      currency: 'INR',
      report_id: null,
      reported_at: null,
      state: 'COMPLETE',
      num_files: 1,
      invoice_number: null,
      purpose: 'test_term',
      source: 'WEBAPP',
      billable: null,
      orig_amount: null,
      orig_currency: null,
      project_id: null,
      project_name: null,
      project_code: null,
      skip_reimbursement: false,
      creator_id: 'ouX8dwsbLCLv',
      user_reason_for_duplicate_expenses: null,
      external_id: null,
      cost_center_name: null,
      cost_center_code: null,
      cost_center_id: null,
      source_account_id: 'accZ1IWjhjLv4',
      transcription_state: null,
      verification_state: null,
      physical_bill: null,
      physical_bill_at: null,
      policy_state: null,
      manual_flag: null,
      policy_flag: true,
      vendor: 'YEHUDAHALEVI16',
      vendor_id: 22658,
      platform_vendor: null,
      platform_vendor_id: null,
      org_category: 'ani test',
      sub_category: 'ani test',
      fyle_category: null,
      org_category_code: null,
      org_category_id: 212690,
      expense_number: 'E/2023/05/T/326',
      corporate_credit_card_expense_group_id: null,
      split_group_id: 'txbO4Xaj4N53',
      split_group_user_amount: 780,
      extracted_data: {
        category: 'SYSTEM',
        currency: 'USD',
        amount: 100,
        date: new Date('2023-02-15T06:30:00.000Z'),
        invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
        vendor_name: 'vendor',
      },
      transcribed_data: null,
      user_review_needed: null,
      mandatory_fields_present: true,
      distance: null,
      distance_unit: null,
      from_dt: null,
      to_dt: null,
      num_days: null,
      mileage_calculated_distance: null,
      mileage_calculated_amount: null,
      mileage_vehicle_type: null,
      mileage_rate: null,
      mileage_is_round_trip: null,
      hotel_is_breakfast_provided: false,
      flight_journey_travel_class: null,
      flight_return_travel_class: null,
      train_travel_class: null,
      bus_travel_class: null,
      taxi_travel_class: null,
      per_diem_rate_id: null,
      activity_policy_pending: null,
      activity_details: null,
      locations: [],
      custom_properties: [
        {
          name: 'userlist',
          value: [],
        },
        {
          name: 'test',
          value: '',
        },
        {
          name: 'User List',
          value: [],
        },
        {
          name: 'select all 2',
          value: null,
        },
        {
          name: 'test 112',
          value: null,
        },
        {
          name: 'category2',
          value: '',
        },
        {
          name: 'boolean',
          value: false,
        },
      ],
      is_implicit_merge_blocked: false,
      categoryDisplayName: 'ani test',
    },
    ou: {
      org_name: 'Staging Loaded',
      id: 'ouX8dwsbLCLv',
      org_id: 'orNVthTo2Zyo',
      user_id: 'usvKA4X8Ugcr',
      employee_id: '',
      location: 'Mumbai',
      level: '123',
      band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
      rank: 1121212121,
      business_unit:
        'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
      department_id: 'dept7HJ9C4wvtX',
      department: '0000000',
      title: 'director',
      mobile: '+919764989821',
      sub_department: 'arun',
      joining_dt: new Date('2017-07-25T00:00:00.000Z'),
    },
    tg: {
      name: 'Tax on Goods @8.75%',
      percentage: 0.09,
    },
    rp: {
      purpose: null,
      approved_at: null,
      reimbursed_at: null,
      claim_number: null,
    },
    us: {
      full_name: 'Abhishek Jain',
      email: 'ajain@fyle.in',
    },
    source: {
      account_type: 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT',
      account_id: 'accZ1IWjhjLv4',
    },
    external: {
      expense_id: null,
    },
    is: {
      test_call: null,
    },
    dataUrls: [],
  },
  comment: null,
};

export const unflattenedPaidExp: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    state: 'PAID',
    fyle_category: 'TRAVEL',
    org_category_id: 12345,
  },
};

export const unflattenedDraftExp: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    state: 'DRAFT',
    fyle_category: 'unspecified',
    org_category_id: 12345,
  },
};

export const unflattenedDraftExp2: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    state: 'DRAFT',
    extracted_data: null,
    fyle_category: 'unspecified',
    org_category_id: null,
  },
};

export const unflattenedPaidExp2: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    state: 'PAID',
    fyle_category: 'TRAVEL',
  },
};

export const expectedExpenseObservable: Partial<UnflattenedTransaction> = {
  tx: {
    skip_reimbursement: false,
    source: 'MOBILE',
    txn_dt: new Date('2023-01-17T06:34:32.50466Z'),
    currency: 'USD',
    amount: 100,
    orig_currency: null,
    orig_amount: null,
    policy_amount: null,
    org_category_id: undefined,
    fyle_category: undefined,
    locations: [],
    custom_properties: [],
    num_files: 1,
    org_user_id: 'ouX8dwsbLCLv',
    project_id: 3943,
    extracted_data: {
      amount: 100,
      currency: 'USD',
      category: 'SYSTEM',
      date: new Date('2023-02-15T06:30:00.000Z'),
      vendor: 'vendor',
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    },
    vendor: 'vendor',
  },
  dataUrls: [
    {
      url: 'data-url',
      type: 'image',
      thumbnail: 'data-url',
    },
  ],
};

export const expectedExpenseObservable2 = {
  tx: {
    skip_reimbursement: false,
    source: 'MOBILE',
    txn_dt: new Date('2019-06-19T01:00:00.000Z'),
    currency: 'USD',
    amount: null,
    orig_currency: null,
    orig_amount: null,
    policy_amount: null,
    locations: [],
    custom_properties: [],
    num_files: 0,
    org_user_id: 'ouX8dwsbLCLv',
    project_id: 3943,
  },
  dataUrls: [],
};

export const expectedExpenseObservable3: Partial<UnflattenedTransaction> = {
  tx: {
    skip_reimbursement: false,
    source: 'MOBILE',
    currency: 'USD',
    amount: 100,
    orig_currency: null,
    orig_amount: null,
    policy_amount: null,
    locations: [],
    custom_properties: [],
    num_files: 1,
    txn_dt: new Date('2023-01-24T11:30:00.000Z'),
    org_category_id: undefined,
    fyle_category: undefined,
    org_user_id: 'ouX8dwsbLCLv',
    project_id: 3943,
    extracted_data: {
      amount: 100,
      currency: 'USD',
      category: 'SYSTEM',
      date: new Date('2023-02-15T06:30:00.000Z'),
      vendor: 'vendor',
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    },
    vendor: 'vendor',
  },
  dataUrls: [
    {
      url: 'data-url',
      type: 'image',
      thumbnail: 'data-url',
    },
  ],
};

export const expectedExpenseObservable4: Partial<UnflattenedTransaction> = {
  tx: {
    source: 'MOBILE',
    currency: 'INR',
    amount: 8200,
    vendor: 'vendor',
    skip_reimbursement: false,
    txn_dt: new Date('2023-01-24T11:30:00.000Z'),
    purpose: undefined,
    org_category_id: undefined,
    fyle_category: undefined,
    locations: [],
    num_files: 1,
    org_user_id: 'ouX8dwsbLCLv',
    extracted_data: {
      amount: 100,
      currency: 'USD',
      category: 'SYSTEM',
      date: new Date('2023-02-15T06:30:00.000Z'),
      vendor: 'vendor',
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    },
    orig_amount: 100,
    orig_currency: 'USD',
  },
  dataUrls: [
    {
      url: 'data-url',
      type: 'image',
      thumbnail: 'data-url',
    },
  ],
};

export const expectedExpenseObservable5: Partial<UnflattenedTransaction> = {
  tx: {
    source: 'MOBILE',
    currency: 'USD',
    amount: 100,
    vendor: 'vendor',
    purpose: 'AMAZON.COM, SEATTLE, WA',
    skip_reimbursement: false,
    locations: [],
    hotel_is_breakfast_provided: false,
    num_files: 1,
    org_user_id: 'ouX8dwsbLCLv',
    txn_dt: new Date('2023-01-24T17:00:00.000Z'),
    org_category_id: undefined,
    fyle_category: undefined,
    extracted_data: {
      amount: 100,
      currency: 'USD',
      category: 'SYSTEM',
      date: new Date('2023-02-15T06:30:00.000Z'),
      vendor: 'vendor',
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    },
  },
  dataUrls: [
    {
      url: 'data-url',
      type: 'image',
      thumbnail: 'data-url',
    },
  ],
};

export const unflattenedTxnDataWithoutCategoryData2: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: null,
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    org_category_id: 12345,
    fyle_category: 'unspecified',
  },
};

export const unflattenedTransactionDataPersonalCard = {
  ...expectedUnflattendedTxnData3.tx,
  locations: null,
};

export const newUnflattenedTxn = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'tx053DOHz9pU',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-05-30T01:55:01.776Z'),
    receipt_required: true,
    user_can_delete: true,
    txn_dt: new Date('2023-05-30T01:00:00.000Z'),
    category: null,
    amount: 1234,
    user_amount: 1234,
    policy_amount: null,
    admin_amount: null,
    tax: 101.89,
    tax_amount: 101.89,
    matchCCCId: undefined,
    tax_group_id: 'tgzhpXlC40LK',
    currency: 'INR',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: 'test_term',
    source: 'WEBAPP',
    billable: null,
    orig_amount: null,
    orig_currency: null,
    project_id: null,
    project_name: null,
    project_code: null,
    skip_reimbursement: true,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: null,
    external_id: null,
    cost_center_name: null,
    cost_center_code: null,
    cost_center_id: null,
    source_account_id: 'acc5APeygFjRd',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: true,
    vendor: 'expensify@thatharmansingh.com - HoneComb Aus',
    vendor_id: 28824,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'Hotel',
    sub_category: 'Hotel',
    fyle_category: null,
    org_category_code: null,
    org_category_id: 16572,
    expense_number: 'E/2023/05/T/324',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'tx053DOHz9pU',
    split_group_user_amount: 1234,
    extracted_data: null,
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: null,
    distance_unit: null,
    from_dt: null,
    to_dt: null,
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: false,
    flight_journey_travel_class: null,
    flight_return_travel_class: null,
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        name: 'userlist',
        value: [],
      },
      {
        name: 'User List',
        value: [],
      },
      {
        name: 'test',
        value: '',
      },
      {
        name: 'category2',
        value: '',
      },
      {
        name: 'test 112',
        value: null,
      },
      {
        name: 'select all 2',
        value: null,
      },
      {
        name: 'boolean',
        value: false,
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Hotel',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'dept7HJ9C4wvtX',
    department: '0000000',
    title: 'director',
    mobile: null,
    sub_department: 'arun',
    joining_dt: new Date('2017-07-25T00:00:00.000+0000'),
  },
  tg: {
    name: 'Tax on Goods @8.75%',
    percentage: 0.09,
  },
  rp: {
    purpose: null,
    approved_at: null,
    reimbursed_at: null,
    claim_number: null,
  },
  us: {
    full_name: 'Abhishek Jain',
    email: 'ajain@fyle.in',
  },
  source: {
    account_type: 'PERSONAL_ACCOUNT',
    account_id: 'acc5APeygFjRd',
  },
  external: {
    expense_id: null,
  },
  is: {
    test_call: null,
  },
  dataUrls: [],
};

export const unflattenedTxnDataWithReportID = {
  ...expectedUnflattendedTxnData2,
  tx: {
    ...expectedUnflattendedTxnData2.tx,
    report_id: 'rpGpzBpAxtSn',
  },
  ou: {
    ...expectedUnflattendedTxnData2.ou,
    level: null,
  },
  us: undefined,
  source: {
    account_type: '',
    account_id: '',
  },
  tg: {
    name: '',
    percentage: 0,
  },
  rp: undefined,
  external: {
    expense_id: '',
  },
  is: {
    test_call: false,
  },
};

export const unflattenedTxnDataWithReportID2 = {
  ...expectedUnflattendedTxnData2,
  tx: {
    ...expectedUnflattendedTxnData2.tx,
    report_id: 'rpGpzBpAxtSn',
  },
  ou: {
    ...expectedUnflattendedTxnData2.ou,
    level: null,
  },
  us: undefined,
  source: {
    account_type: '',
    account_id: '',
  },
  tg: {
    name: '',
    percentage: 0,
  },
  rp: undefined,
  external: {
    expense_id: '',
  },
  is: {
    test_call: false,
  },
};

export const unflattenedTxnDataWithViolationUserReview = {
  ...expectedUnflattendedTxnData2,
  tx: {
    ...expectedUnflattendedTxnData2.tx,
    tx_policy_amount: 0,
    user_review_needed: true,
  },
  ou: {
    ...expectedUnflattendedTxnData2.ou,
    level: null,
  },
  us: undefined,
  source: {
    account_type: '',
    account_id: '',
  },
  tg: {
    name: '',
    percentage: 0,
  },
  rp: undefined,
  external: {
    expense_id: '',
  },
  is: {
    test_call: false,
  },
};

export const unflattenedExpenseWithCCCGroupId = {
  ...unflattenedTxnDataWithViolationUserReview,
  tx: {
    ...expectedUnflattendedTxnData2.tx,
    corporate_credit_card_expense_group_id: 'ccceWauzF1A3oS',
    report_id: null,
  },
};

export const unflattenedExpenseWithCCCGroupId2 = {
  ...unflattenedTxnDataWithViolationUserReview,
  tx: {
    ...expectedUnflattendedTxnData2.tx,
    corporate_credit_card_expense_group_id: 'ccceWauzF1A3oS',
    split_group_id: 'tx3nHShG60zq',
    report_id: null,
    policy_amount: -100,
  },
};

export const txnWithCCCGroupID = {
  ...unflattenedTxnData.tx,
  corporate_credit_card_expense_group_id: 'ccceWauzF1A3oS',
  report_id: null,
};

export const unflattenedExpWoProject = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    project_id: null,
  },
};

export const unflattenedExpWithReport = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    report_id: 'rprAfNrce73O',
  },
};

export const unflattenedExpWithCostCenter = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    cost_center_id: 2411,
  },
};

export const unflattenedExpWoCostCenter = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    cost_center_id: null,
  },
};

export const unflattenedExp2 = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    user_amount: 100,
    policy_amount: 0,
    currency: 'USD',
    state: 'DRAFT',
    id: null,
    project_id: null,
    cost_center_id: null,
  },
  dataUrls: [
    {
      url: 'data-url',
      type: 'image',
      thumbnail: 'data-url',
    },
  ],
};

export const unflattenedExpWithCCCExpn: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    corporate_credit_card_expense_group_id: 'cccet1B17R8gWZ',
    txn_dt: new Date('2021-07-29T06:30:00.000Z'),
    user_amount: 100,
    policy_amount: 0,
    currency: 'USD',
    state: 'DRAFT',
    id: null,
    project_id: null,
    cost_center_id: null,
  },
  dataUrls: [
    {
      url: 'data-url',
      type: 'image',
      thumbnail: 'data-url',
    },
  ],
};

export const trackCreateExpData: UnflattenedTransaction = {
  ...unflattenedExp2,
  tx: {
    ...unflattenedExp2.tx,
    org_category_id: 1234,
    project_id: 4567,
    cost_center_id: 8901,
    currency: 'USD',
    orig_currency: 'USD',
  },
};

export const trackCreateExpDataWoCurrency: UnflattenedTransaction = {
  ...unflattenedExp2,
  tx: {
    ...unflattenedExp2.tx,
    org_category_id: 1234,
    project_id: 4567,
    cost_center_id: 8901,
    currency: null,
    orig_currency: 'USD',
  },
};

export const trackAddExpenseWoCurrency = {
  ...expectedUnflattendedTxnData4,
  tx: {
    ...expectedUnflattendedTxnData4,
    currency: null,
    org_category: 'TAXI',
    amount: 120,
    project_id: 1234,
    org_category_id: 1234,
    orig_currency: 'USD',
    cost_center_id: 1234,
  },
  ou: {
    ...expectedUnflattendedTxnData4.ou,
    level: 0,
  },
  us: undefined,
  source: {
    account_type: '',
    account_id: '',
  },
  tg: {
    name: '',
    percentage: 0,
  },
  rp: undefined,
  external: {
    expense_id: '',
  },
  is: {
    test_call: false,
  },
  dataUrls: null,
};

export const newExpFromFg = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'txbO4Xaj4N53',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-05-30T02:18:27.646Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2019-06-19T06:30:00.000Z'),
    category: null,
    amount: 500,
    user_amount: 780,
    policy_amount: null,
    admin_amount: null,
    tax: 64.4,
    tax_amount: 120,
    tax_group_id: 'tgXEJA6YUoZ1',
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 0,
    invoice_number: null,
    purpose: 'purpose',
    source: 'MOBILE',
    billable: true,
    orig_amount: 100,
    orig_currency: 'USD',
    project_id: 1234,
    project_name: null,
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: 'reason',
    external_id: null,
    cost_center_name: 'SMS1',
    cost_center_code: null,
    cost_center_id: 2411,
    source_account_id: 'id',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: true,
    vendor: 'asd',
    vendor_id: 22658,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'ani test',
    sub_category: 'ani test',
    fyle_category: 'Groceries',
    org_category_code: null,
    org_category_id: 215481,
    expense_number: 'E/2023/05/T/326',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txbO4Xaj4N53',
    split_group_user_amount: 780,
    extracted_data: {
      category: 'SYSTEM',
      currency: 'USD',
      amount: 100,
      date: new Date('2023-02-15T06:30:00.000Z'),
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
      vendor_name: 'vendor',
    },
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: 100,
    distance_unit: 'KM',
    from_dt: new Date('2023-03-13T05:31:00.000Z'),
    to_dt: new Date('2023-01-26T17:00:00.000Z'),
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: true,
    flight_journey_travel_class: 'FIRST',
    flight_return_travel_class: 'ECONOMY',
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [
      {
        actual: 'null',
        city: 'Kalyan',
        country: 'India',
        display: 'Kalyan Station Road, Bhanunagar KalyanWest, Bhoiwada, Kalyan, Maharashtra, India',
        formatted_address: 'Kalyan Station Rd, Bhanunagar KalyanWest, Bhoiwada, Kalyan, Maharashtra 421301, India',
        latitude: 19.238037,
        longitude: 73.1296469,
        state: 'Maharashtra',
      },
      {
        actual: 'null',
        city: 'Bhiwandi',
        country: 'India',
        display: 'Bhiwandi Railway Station Road, Brahmanand Nagar, Kamatghar, Bhiwandi, Maharashtra, India',
        formatted_address:
          'Bhiwandi Railway Station Rd, Brahmanand Nagar, Kamatghar, Bhiwandi, Maharashtra 421302, India',
        latitude: 19.2687341,
        longitude: 73.0484305,
        state: 'Maharashtra',
      },
    ],
    custom_properties: [
      {
        id: 111,
        name: 'Test Number',
        value: 121,
        type: 'NUMBER',
      },
      {
        id: 150,
        name: 'checking',
        value: false,
        type: 'BOOLEAN',
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'ani test',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'dept7HJ9C4wvtX',
    department: '0000000',
    title: 'director',
    mobile: '+919764989821',
    sub_department: 'arun',
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  dataUrls: [],
};

export const newExpFromFg2 = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: 'tx3qHxFNgRcZ',
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-01-24T04:24:24.186Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2019-06-19T06:30:00.000Z'),
    category: null,
    amount: 100,
    user_amount: 100,
    policy_amount: null,
    admin_amount: null,
    tax: 52.47,
    tax_amount: 120,
    tax_group_id: 'tgXEJA6YUoZ1',
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'COMPLETE',
    num_files: 1,
    invoice_number: null,
    purpose: 'purpose',
    source: 'MOBILE',
    billable: true,
    orig_amount: 100,
    orig_currency: 'USD',
    project_id: 1234,
    project_name: 'Project 1 / asdfg',
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: 'reason',
    external_id: null,
    cost_center_name: 'SMS1',
    cost_center_code: null,
    cost_center_id: 2411,
    source_account_id: 'id',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: null,
    vendor: 'asd',
    vendor_id: 28860,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'TRAVEL',
    sub_category: 'TAXI',
    fyle_category: 'Groceries',
    org_category_code: '117',
    org_category_id: 215481,
    expense_number: 'E/2023/01/T/99',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'tx3qHxFNgRcZ',
    split_group_user_amount: 344,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: 'Software',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: true,
    mandatory_fields_present: true,
    distance: 100,
    distance_unit: 'KM',
    from_dt: new Date('2023-03-13T05:31:00.000Z'),
    to_dt: new Date('2023-01-26T17:00:00.000Z'),
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: true,
    flight_journey_travel_class: 'FIRST',
    flight_return_travel_class: 'ECONOMY',
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [
      {
        actual: 'null',
        city: 'Kalyan',
        country: 'India',
        display: 'Kalyan Station Road, Bhanunagar KalyanWest, Bhoiwada, Kalyan, Maharashtra, India',
        formatted_address: 'Kalyan Station Rd, Bhanunagar KalyanWest, Bhoiwada, Kalyan, Maharashtra 421301, India',
        latitude: 19.238037,
        longitude: 73.1296469,
        state: 'Maharashtra',
      },
    ],
    custom_properties: [
      {
        id: 111,
        name: 'Test Number',
        value: 121,
        type: 'NUMBER',
      },
      {
        id: 115,
        name: 'test date',
        value: new Date('2017-07-25T00:00:00.000Z'),
        type: 'DATE',
      },
      {
        id: 150,
        name: 'checking',
        value: false,
        type: 'BOOLEAN',
      },
      {
        id: 151,
        name: 'Select field',
        value: 'select-1',
        type: 'SELECT',
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'Software',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: 123,
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'deptpmQ0SsMO0S',
    department: '0000000',
    title: 'director',
    mobile: '123456',
    sub_department: null,
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  dataUrls: [],
};

export const newExpFromFg3 = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: null,
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-05-30T02:18:27.646Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2019-06-19T06:30:00.000Z'),
    category: null,
    amount: 100,
    user_amount: 780,
    policy_amount: null,
    admin_amount: null,
    tax: 64.4,
    tax_amount: 120,
    tax_group_id: 'tgXEJA6YUoZ1',
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'DRAFT',
    num_files: 0,
    invoice_number: null,
    purpose: 'purpose',
    source: 'MOBILE',
    billable: true,
    orig_amount: 100,
    orig_currency: 'USD',
    project_id: 1234,
    project_name: null,
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: 'reason',
    external_id: null,
    cost_center_name: 'SMS1',
    cost_center_code: null,
    cost_center_id: 2411,
    source_account_id: 'id',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: true,
    vendor: 'asd',
    vendor_id: 22658,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'ani test',
    sub_category: 'ani test',
    fyle_category: 'Groceries',
    org_category_code: null,
    org_category_id: 215481,
    expense_number: 'E/2023/05/T/326',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txbO4Xaj4N53',
    split_group_user_amount: 780,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: 'Food',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: 100,
    distance_unit: 'KM',
    from_dt: new Date('2023-03-13T05:31:00.000Z'),
    to_dt: new Date('2023-01-26T17:00:00.000Z'),
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: true,
    flight_journey_travel_class: 'FIRST',
    flight_return_travel_class: 'ECONOMY',
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 111,
        name: 'Test Number',
        value: 121,
        type: 'NUMBER',
      },
      {
        id: 115,
        name: 'test date',
        type: 'DATE',
        value: undefined,
      },
      {
        id: 150,
        name: 'checking',
        value: false,
        type: 'BOOLEAN',
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'ani test',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'dept7HJ9C4wvtX',
    department: '0000000',
    title: 'director',
    mobile: '+919764989821',
    sub_department: 'arun',
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  dataUrls: [],
};

export const newExpFromFg4 = {
  tx: {
    risk_state: null,
    is_duplicate_expense: null,
    duplicates: null,
    id: null,
    org_user_id: 'ouX8dwsbLCLv',
    created_at: new Date('2023-05-30T02:18:27.646Z'),
    receipt_required: false,
    user_can_delete: true,
    txn_dt: new Date('2019-06-19T06:30:00.000Z'),
    category: null,
    amount: 100,
    user_amount: 780,
    policy_amount: null,
    admin_amount: null,
    tax: 64.4,
    tax_amount: 120,
    tax_group_id: 'tgXEJA6YUoZ1',
    currency: 'USD',
    report_id: null,
    reported_at: null,
    state: 'DRAFT',
    num_files: 0,
    invoice_number: null,
    purpose: 'purpose',
    source: 'MOBILE',
    billable: true,
    orig_amount: 100,
    orig_currency: 'USD',
    project_id: 1234,
    project_name: null,
    project_code: null,
    skip_reimbursement: false,
    creator_id: 'ouX8dwsbLCLv',
    user_reason_for_duplicate_expenses: 'reason',
    external_id: null,
    cost_center_name: null,
    cost_center_code: null,
    cost_center_id: null,
    source_account_id: 'id',
    transcription_state: null,
    verification_state: null,
    physical_bill: null,
    physical_bill_at: null,
    policy_state: null,
    manual_flag: null,
    policy_flag: true,
    vendor: 'asd',
    vendor_id: 22658,
    platform_vendor: null,
    platform_vendor_id: null,
    org_category: 'ani test',
    sub_category: 'ani test',
    fyle_category: 'Groceries',
    org_category_code: null,
    org_category_id: 215481,
    expense_number: 'E/2023/05/T/326',
    corporate_credit_card_expense_group_id: null,
    split_group_id: 'txbO4Xaj4N53',
    split_group_user_amount: 780,
    extracted_data: {
      amount: null,
      currency: 'INR',
      category: 'Food',
      date: null,
      vendor: null,
      invoice_dt: null,
    },
    transcribed_data: null,
    user_review_needed: null,
    mandatory_fields_present: true,
    distance: 100,
    distance_unit: 'KM',
    from_dt: new Date('2023-03-13T05:31:00.000Z'),
    to_dt: new Date('2023-01-26T17:00:00.000Z'),
    num_days: null,
    mileage_calculated_distance: null,
    mileage_calculated_amount: null,
    mileage_vehicle_type: null,
    mileage_rate: null,
    mileage_is_round_trip: null,
    hotel_is_breakfast_provided: true,
    flight_journey_travel_class: 'FIRST',
    flight_return_travel_class: 'ECONOMY',
    train_travel_class: null,
    bus_travel_class: null,
    taxi_travel_class: null,
    per_diem_rate_id: null,
    activity_policy_pending: null,
    activity_details: null,
    locations: [],
    custom_properties: [
      {
        id: 111,
        name: 'Test Number',
        value: 121,
        type: 'NUMBER',
      },
      {
        id: 115,
        name: 'test date',
        type: 'DATE',
        value: undefined,
      },
      {
        id: 150,
        name: 'checking',
        value: false,
        type: 'BOOLEAN',
      },
    ],
    is_implicit_merge_blocked: false,
    categoryDisplayName: 'ani test',
  },
  ou: {
    org_name: 'Staging Loaded',
    id: 'ouX8dwsbLCLv',
    org_id: 'orNVthTo2Zyo',
    user_id: 'usvKA4X8Ugcr',
    employee_id: '',
    location: 'Mumbai',
    level: '123',
    band: 'Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name Very Long Level name',
    rank: 1121212121,
    business_unit:
      'A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed A very long Business Unit indeed',
    department_id: 'dept7HJ9C4wvtX',
    department: '0000000',
    title: 'director',
    mobile: '+919764989821',
    sub_department: 'arun',
    joining_dt: new Date('2017-07-25T00:00:00.000Z'),
  },
  dataUrls: [],
};

export const expWithSplitGroupID = {
  ...unflattenedTxnData,
  tx: null,
};

export const unflattenedTxnWithExtractedData2: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    source: null,
    state: 'DRAFT',
    amount: undefined,
    currency: undefined,
    vendor: undefined,
    fyle_category: null,
    extracted_data: {
      amount: 100,
      currency: 'USD',
      date: new Date('2022-11-30T06:30:00.000Z'),
      category: 'TRAVEL',
      vendor: 'vendor',
      invoice_dt: new Date('2023-02-24T12:03:57.680Z'),
    },
  },
};

export const unflattenedDraftExp3: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    state: 'COMPLETE',
    extracted_data: null,
    fyle_category: null,
    org_category_id: null,
  },
};

export const checkSplitExpData1: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    id: 'tx3qHxFNgRcZ',
    state: 'COMPLETE',
    extracted_data: null,
    fyle_category: null,
    org_category_id: null,
    split_group_id: 'tx3qHxFNgRcZ',
  },
};

export const checkSplitExpData2: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    id: 'tx3qHxFNgRcZ',
    state: 'COMPLETE',
    split_group_id: null,
  },
};

export const checkDebitCCCExpenseData1: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    id: 'tx3qHxFNgRcZ',
    state: 'COMPLETE',
    amount: 100,
    corporate_credit_card_expense_group_id: 'tx3qHxFNgRcZ',
  },
};

export const checkDebitCCCExpenseData2: UnflattenedTransaction = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData.tx,
    id: 'tx3qHxFNgRcZ',
    state: 'COMPLETE',
    amount: -1,
    corporate_credit_card_expense_group_id: 'tx3qHxFNgRcZ',
  },
};

export const setupFormExpenseWoCurrency = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData,
    amount: null,
    currency: 'USD',
    user_amount: 100,
    policy_amount: -10,
    locations: [],
    from_dt: new Date('2021-03-26T09:29:14.586Z'),
    to_dt: new Date('2022-01-07T11:53:53.588Z'),
    custom_properties: [
      {
        name: 'userlist',
        value: null,
      },
      {
        name: 'select all 2',
        value: null,
      },
    ],
  },
};

export const setupFormExpenseWoCurrency2 = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData,
    amount: null,
    currency: 'USD',
    user_amount: null,
    policy_amount: -10,
    locations: [],
    from_dt: new Date('2021-03-26T09:29:14.586Z'),
    to_dt: new Date('2022-01-07T11:53:53.588Z'),
    custom_properties: [
      {
        name: 'userlist',
        value: null,
      },
      {
        name: 'select all 2',
        value: null,
      },
    ],
  },
};

export const setupFormExpenseWoCurrency3 = {
  ...unflattenedTxnData,
  tx: {
    ...unflattenedTxnData,
    id: 'id1',
    amount: null,
    state: 'DRAFT',
    currency: 'INR',
    user_amount: null,
    policy_amount: -10,
    locations: [],
    project_id: null,
  },
};
