import { UniqueCardStats } from '../models/unique-cards-stats.model';

export const expectedUniqueCardStats: UniqueCardStats[] = [
  {
    cardNumber: '8698',
    cardName: 'DAMNA',
    totalDraftTxns: 964,
    totalDraftValue: 568437,
    totalCompleteTxns: 4,
    totalCompleteExpensesValue: 3494,
    totalTxnsCount: 968,
    totalAmountValue: 571931,
  },
  {
    cardNumber: '869',
    cardName: 'PEX BANK',
    totalDraftTxns: 107,
    totalDraftValue: 6598.172,
    totalCompleteTxns: 5,
    totalCompleteExpensesValue: 371.87,
    totalTxnsCount: 112,
    totalAmountValue: 6970.0419999999995,
  },
  {
    cardNumber: '6975',
    cardName: 'TEST-999',
    totalDraftTxns: 8,
    totalDraftValue: 2612.83,
    totalCompleteTxns: 0,
    totalCompleteExpensesValue: 0,
    totalTxnsCount: 8,
    totalAmountValue: 2612.83,
  },
  {
    cardNumber: 'Sample-Bank-xxx3420',
    cardName: null,
    totalDraftTxns: 0,
    totalDraftValue: 0,
    totalCompleteTxns: 1,
    totalCompleteExpensesValue: 5782.73,
    totalTxnsCount: 1,
    totalAmountValue: 5782.73,
  },
  {
    cardNumber: 'Sample-Bank-xxxxxx-99171',
    cardName: null,
    totalDraftTxns: 1,
    totalDraftValue: 2257.23,
    totalCompleteTxns: 0,
    totalCompleteExpensesValue: 0,
    totalTxnsCount: 1,
    totalAmountValue: 2257.23,
  },
];
