name: Android Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk-version: 25.1.8937393
          
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
        
      - name: Build web app
        run: |
          ionic build -c staging
          
      - name: Sync Capacitor
        run: |
          ionic capacitor sync android
          
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
          
      - name: Build Android AAB (if needed)
        run: |
          cd android
          ./gradlew bundleDebug
          
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-aab
          path: android/app/build/outputs/bundle/debug/app-debug.aab
          retention-days: 30
