name: End of Life and Outdated JS Scan

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-eol-scan:
    if: ${{ github.event.pull_request.draft == false }}
    uses: fylein/workflows/.github/workflows/eol-outdated-js-scan.yml@v1
    name: Run scanner
    with:
      npm-run-cmd: 'npm ci'
      suppression: 'suppression.xml'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_API_KEY }}