name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize, edited]

permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: fylein/fyle-mobile-app@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: 'gpt-4' # Optional: defaults to "gpt-4"
          exclude: '**/*.json, **/*.md' # Optional: exclude patterns separated by commas
