# This is a basic workflow that is manually triggered

name: Manual workflow - Appflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Build Android with Appflow
        run: touch ~/android.apk

      - name: Move android.apk to current directory
        run: mv ~/android.apk .

      - name: Upload apk to diawi Slack
        uses: rnkdsh/action-upload-diawi@v1.2.0
        id: diwaiAndroid
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: ${{ env.HOME }}/android.apk