name: Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths:
      - '**/package-lock.json'
      - '**/requirements.txt'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Vulnerability Scanner
        uses: fylein/vulnerability-scan-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          is_submodule: true 